### ISSUE TITLE
Cloud9 Integration

### ISSUE THREAD

**Issue by ispyinternet** [awslabs/aws-sam-cli#1018]
Your debugging examples use Visual Studio Code and my attempts to use the Cloud9 IDE debugger have been frustrating to say the least. Would be great to fire up the tests in debug mode then step through using the Cloud9 IDE like you do in Visual Studio example but I cannot get the integration to work. Im wondering if Cloud9 is still stuck on the node version? Are there any plans to better support Cloud9?

Does anyone in the sam-cli team have any link to the Cloud9 team to answer any of these concerns?

Thanks.

**Comment by TheSriram** [comment]
Check the version of sam on your cloud 9 instance, if its 0.2.x its the node version, and that could be the issue.

**Comment by jfuss** [comment]
@ispyinternet You can follow [Cloud9's docs](https://docs.aws.amazon.com/cloud9/latest/user-guide/lambda-functions.html?shortFooter=true#lambda-functions-debug) on testing Lambda Functions.

If you are seeing an "Unsupported Runtime" as an error, then the SAM CLI installed is old. First you should check the version. If the version is less than or equal to 0.2.11, then you will need to follow the instructions [here](https://docs.aws.amazon.com/cloud9/latest/user-guide/troubleshooting.html?shortFooter=true#troubleshooting-install-sam-local), the commands that start with `npm uninstall -g aws-sam-local`. This should resolve any integration issues.

Closing, but feel free to re-open, create a new issue, or reach out to our Slack community if something else comes up.
