### ISSUE TITLE
Greedy Proxy Path Does Not Work Locally

### ISSUE THREAD

**Issue by metaskills** [awslabs/aws-sam-cli#1037]
### Description

Can not use greedy proxy path variable in local SAM server 

### Steps to reproduce

Using something like this template.yaml.

```yaml
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        swagger: 2.0
        info: { title: !Ref 'AWS::StackName' }
        basePath: '/'
        schemes: [ 'https' ]
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}:live/invocations
                httpMethod: POST
                type: aws_proxy
          /{proxy+}:
            x-amazon-apigateway-any-method:
              parameters:
                - name: proxy
                  in: path
                  required: true
                  type: string
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}:live/invocations
                httpMethod: POST
                type: aws_proxy

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: ruby2.5
      MemorySize: 512
      Timeout: 10
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref MyApi
        All:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyApi
```

And then using `sam local start-api`

### Observed result

Any root `/` request works, but requesting a path like `/foo/bar` results in.

```
2019-03-03 10:59:10 127.0.0.1 - - [03/Mar/2019 10:59:10] "GET /foo/bar HTTP/1.1" 403 -
```

### Expected result

Building and deploying to AWS works. Can it work locally?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac/Darwin
2. `sam --version`: SAM CLI, version 0.11.0

**Comment by metaskills** [comment]
FWIW, I've been working around this by using `/app/{proxy+}`. Seem SAM needs some sort of anchor in the path to help it along.

**Comment by metaskills** [comment]
I also felt this was a little similar to https://github.com/awslabs/aws-sam-cli/issues/434 but I am not using any sort of builder, just raw SAM. Have not tested if this is specific to the Ruby runtime either.

**Comment by jfuss** [comment]
@metaskills Thanks for this issue. I think this is similar to #437, if not the same issue. If you agree, I would prefer to close this one and track with #437.

**Comment by metaskills** [comment]
Oh, I do think it might be. Will watch that one to see. Thanks! Closing this one now.

**Comment by prcongithub** [comment]
How can someone test this locally without support for /{proxy+}?
