### ISSUE TITLE
sam build for nodejs: support .npmrc

### ISSUE THREAD

**Issue by kroney** [awslabs/aws-sam-cli#1042]
### Describe your idea/feature/enhancement

I wish sam build for nodejs would also support .npmrc.
As we're using a private npm repo it would be great if sam build would copy the .npmrc file and use it during npm install

**Comment by jfuss** [comment]
@kroney Thanks for the issue. Have you tried using v0.12.0? This was released with the [`aws-lambda-builders` package](https://github.com/awslabs/aws-lambda-builders/releases/tag/v0.1.0) and was apart of the v0.12.0 release for SAM CLI.

**Comment by kroney** [comment]
@jfuss 	you're right. I still had a outdated version installed. Thanks 👍
