### ISSUE TITLE
Enable python3.7 debugging

### ISSUE THREAD

**Issue by billyshambrook** [awslabs/aws-sam-cli#1047]
### Description

Currently python3.7 debugging is blocked but debugging does work as it is documented for python functions here - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html

I would also propose to allow the user to pass in a custom `--bootstrap` argument via the `--debug-options` argument. This would allow the following workflow...

1. User creates a `debug/` folder.
2. Install ptvsd into that folder - `pip install ptvsd -t debug/.`.
3. Create a file called `debug_bootstrap` with the following contents:

```
#!/var/lang/bin/python3.7

import ptvsd

ptvsd.enable_attach(address=('0.0.0.0', 5890), redirect_output=True)
ptvsd.wait_for_attach()

import sys
sys.path.insert(0,'/var/runtime')

from bootstrap import main


if __name__ == '__main__':
    main()
```

4. `chmod +x debug/debug_bootstrap`
5. Run `sam local start-api -d 5890 --debugger-path debug/ --debug-args "--bootstrap /tmp/lambci_debug_files/debug_bootstrap"`

**Comment by jfuss** [comment]
@billyshambrook Thanks for the issue and getting it kicked off/providing a solution. We were in the process of doing the same and have a way that wouldn't require a customer to override through a `debug_bootstrap` (which matches with how we currently support debugging. It is out in PR now #1055.

Updating labels to reflect the current state.

**Comment by billyshambrook** [comment]
Perfect, thanks for the update @jfuss

**Comment by jfuss** [comment]
Support was adding in [v0.14.1](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.14.1).

Closing
