### ISSUE TITLE
Ability for sam package to apply tags to artifacts uploaded to S3

### ISSUE THREAD

**Issue by kelledro** [awslabs/aws-sam-cli#1070]
### Describe your idea/feature/enhancement

It would be nice if the deployment action would created tagged S3 objects. This would make managing the S3 objects easier. 

### Proposal

Given the S3 objects are not explicitly defined (they are just referenced by the CodeUri param) the tags applied could be the same as those defined for the AWS::Serverless::Function resource.

**Comment by jfuss** [comment]
@kelledro Thanks for creating this. Can you explain further on how you envision using this? Understanding the motivation and the outcome you are looking to take will help the team understand the use case. 

Marking this as a feature request and updating labels.

**Comment by kelledro** [comment]
At the moment I have an s3 bucket full of randomly named artefacts uploaded by sam package with no real way to know any more about them. I would like to be able to tag them with a version, maybe another tag with the name of the lambda etc etc.

SAM gives me the ability to add tags to the lambdas themselves (along with the default CFN and lambda:createdBy tags) so why not add those same tags to the artefacts in S3? The motivation is the same.

**Comment by bmgoau** [comment]
We would like this too. Same reasoning, all our resources and objects are tagged - artifacts should be too.

**Comment by jfuss** [comment]
@kelledro and @bmgoau That makes sense. I wonder if tagging with the function LogicalId is enough? 

> SAM gives me the ability to add tags to the lambdas themselves (along with the default CFN and lambda:createdBy tags) so why not add those same tags to the artifacts in S3?

Not sure I understand why you want the tags of the lambda you define also attached to the artifacts in S3. I can understand the need/want for some kind of auto tagging for the function name but to me the tags on the lambda function are for the function and not the artifacts.

You can use the `--metadata` flag to set metadata on all the artifacts that [package uploads](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html). Maybe this is enough to allow you to tag what you need but I still see value in adding some kind of 'auto tagging' mechanism.

**Comment by kelledro** [comment]
Ah I didn't know about `--metadata`, thanks!

> Not sure I understand why you want the tags of the lambda you define also attached to the artifacts in S3.
That was just a shortcut given that the S3 artefacts are not explicitly defined in the template so I imaged there would need to be some new construct to define the S3 tags. By just applying the lambda tags the template wouldn't have to change, but I understand others might want different tags between the lamdbas themselves and the s3 objects.

**Comment by sriram-mv** [comment]
yes `--metadata` gives you what you are looking for.

sam deploy also features `--tags`

**Comment by Dobby007** [comment]
@sriram-mv @jfuss I don't understand how --metadata can substitute tagging the uploaded artefacts. It can only serve to put metadata on the objects. Tags have completely different nature. Our organization is one step away from enforcing tagging the resources with certain tags using IAM policies. Also I heard a lot about the same policies in other organizations. I was going to test if our deployment flow works correctly with the new policy and found out that there is no capability to se set tags with `sam package` command! It seems like it is a blocker for us. We desperately need this.

**Comment by morezco** [comment]
This Is affecting our org as well, still today.
