### ISSUE TITLE
Catboost(Python) works with sam local, but errors in Lambda test

### ISSUE THREAD

**Issue by GaGaMan1101** [awslabs/aws-sam-cli#1093]
### Description

I am trying to deploy a catboost model in AWS Lambda.
I use sam to `build`, `local invoke lambda function`, `package`, `deploy`, all work. 
However, I had errors when I ran the test in Lambda console.

Note: as the dependencies of catboost has unzipped size more than 250MB. I kept zipped dependencies in S3, and downloaded to lambda `tmp` folder and then import. 

### Steps to reproduce

making `catboost` predictions in lambda function 

`catboost.predict`

### Observed result

`VERIFY failed: pctl failed: Operation not permitted
util/system/thread.cpp:363
CurrentThreadSetName(): requirement prctl(PR_SET_NAME, name, 0, 0, 0) == 0 failed
??+0 (0x7F0FC7530408)
??+0 (0x7F0FC7536886)
??+0 (0x7F1012151DE5)
clone+109 (0x7F1011569F1D)
`
### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: latest

**Comment by TheSriram** [comment]
Is catboost dependent on platform? if so do you want to try `sam build --use-container`, so thats its built to match the lambda execution environment?

**Comment by sriram-mv** [comment]
Seems like the failure messages seems to indicate C binding misses, Going to close the issue. Feel free to re-open if you are still facing this.
