### ISSUE TITLE
SAM Build support for Provided runtime

### ISSUE THREAD

**Issue by gkrizek** [awslabs/aws-sam-cli#1099]
### Describe your idea/feature/enhancement

I am trying to use [NodeSource's N|Solid Lambda Layer](https://nodesource.com/products/nsolid-aws-lambda) with SAM. This is a replacement for Node.js and therefore uses the `provided` runtime. Everything else with my function is identical to the Node.js runtime. I have a `package.json` that included dependencies for my application.

When running `sam build` I get the follow error:

```
$ sam build
2019-04-04 13:26:52 Found credentials in shared credentials file: ~/.aws/credentials
2019-04-04 13:26:52 Building resource 'Function'
Build Failed
Error: 'provided' runtime is not supported
```
I can't use SAM to build and deploy my Node.js functions when they use a provided runtime.

**I would like `sam build` to support the `provided` runtime.**

### Proposal

Obviously, the `provided` runtime is a little tricky for building because the runtime could be anything and there's no way to know from the `template.yaml` file.

My proposal would be to add an optional flag to the `sam build` command called `--builder`. With this flag you could tell `sam build` which builder to use regardless of runtime. This way we can still use the `provided` runtime, but still use `sam build` to package our Node.js applications.

**Comment by gkrizek** [comment]
I think we should perhaps only allow this flag when the runtime is `provided`. If we let someone build a Python function with `--builder node` that's just asking for problems.

**Comment by sanathkr** [comment]
@gkrizek This is a great usecase for `.samrc`(#975) - basically a config file that changes the default behavior for SAM CLI. I like the rc file over command line arguments because you can setup how SAM CLI behaves (in this case "sam build") one time, check into your repository, and be reused across your team without learning a new flag and typing it every time.

Thoughts?

**Comment by gkrizek** [comment]
@sanathkr Yeah I think this sounds like a good idea. I like the reusability of it. Is there any ETA on supporting a `.samrc`?

**Comment by sanathkr** [comment]
@gkrizek Not yet.

**Comment by gkrizek** [comment]
@sanathkr Since there's no date on getting a `.samrc` file implemented, do you think a CLI flag would be a viable option in the meantime? Then users would have the ability to either use the `.samrc` or the CLI flag once both exist.

**Comment by sanathkr** [comment]
@gkrizek You know what, there is a better solution to this: https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/lib/build/workflow_config.py#L107-L112

We have a mechanism to automatically select a workflow based on the manifest (ex: package.json) present. We already use this with Java to select between Gradle & Maven workflow. I think extending this for `provided` runtimes would be a good start. It adds a bit of "magic", but I think this will be a better UX and a compromise until we have .samrc.

**Comment by gkrizek** [comment]
@sanathkr Ok, I like that idea! I agree it seems like a good solution until we can get a .samrc in place. I'll try to come up with a PR soon. Although I'm pretty busy at the moment so if anyone else has more bandwidth feel free.

**Comment by mster** [comment]
Could it be as simple as adding the following to `selectors_by_runtime`?

```python
        "provided": ManifestWorkflowSelector([
            PYTHON_PIP_CONFIG,
            RUBY_BUNDLER_CONFIG,
            DOTNET_CLIPACKAGE_CONFIG,
            NODEJS_NPM_CONFIG,
        ])
```

**Comment by gkrizek** [comment]
I just did a quick test on a local build of the CLI and this seems to work as expected. Might be worth adding some additional logging to let the user know it's auto selected.

**Comment by mster** [comment]
Sweet! Thanks for checking it out @gkrizek ❤️

I’ll put some logging in there and throw up a PR tomorrow.

**Comment by dz902** [comment]
It seems this has been open for a while. Is there a possibility to at least allow `provided` and issue an warning instead of not allowing it at all? As I would really like to test other non-`provided` functions locally and deploy everything including `provided` functions using the same CloudFormation template to AWS.

**Comment by sriram-mv** [comment]
There is a PR in progress which adds support for building on provided runtimes. 
https://github.com/awslabs/aws-sam-cli/pull/1957
Corresponding builder on lambda builders: https://github.com/awslabs/aws-lambda-builders/pull/166

**Comment by sriram-mv** [comment]
This has now been released, closing.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html
