### ISSUE TITLE
Sample with API, Lampda and Dynamodb for Javascript

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [awslabs/aws-sam-cli#1102]
[Feature request]

A version written in Javascript would be much appreciated. 

https://github.com/aws-samples/aws-sam-java-rest
This Java sample inherits many Java habits don't relate to our Javascript development. 

Most helpful support I can find is this.
https://github.com/awslabs/aws-sam-cli/issues/219

Thanks for the consideration.

**Comment by jfuss** [comment]
The example you provided is not maintained by SAM CLI. While the languages are different, the process from the command line are the same. So you should be able to map this into the language you want.

Closing
