### ISSUE TITLE
Module Not Found When Requiring node-fetch, axios or request

### ISSUE THREAD

**Issue by krgutierrez** [awslabs/aws-sam-cli#1104]
### Description

**NOTE: I Use NodeJS 8.10**
Encounter this issue when requiring `axios` (also tried other same library such as `node-fetch` and `request`)

### Steps to reproduce

1. `npm install axios`
2. Add `require('axios')` to any handler
3. Run `sam local start-api --region ap-southeast-1 --profile {your_profile}`
4. Call the API where `require('axios')` is added.

### Observed result

Encountered `Module not found`

```
 { Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at resendChangePhoneNumberCode (/var/task/handlers/resend-change-phone-number-code/ResendChangePhoneNumberCode.handler.js:11:21)
    at /var/task/utils/HandlerUtils.js:12:30 code: 'MODULE_NOT_FOUND' }
```

### Expected result

I should be able to get the `axios`  library.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MAC OS
2. `sam --version`: 0.14.2

**Comment by krgutierrez** [comment]
I found a solution and put it on the question I asked on `Stackoverflow`
https://stackoverflow.com/questions/55558502/module-not-found-when-new-dependency-is-installed/55612124#55612124

**Comment by jfuss** [comment]
@krgutierrez Where are you installing `axios` into? Have you tried using `sam build`?

**Comment by TheSriram** [comment]
Going to close this. should be using `sam build` and specifying dependencies in `package.json`
