### ISSUE TITLE
Allow Python dependency management with Pipfile

### ISSUE THREAD

**Issue by rnhurt** [awslabs/aws-sam-cli#1109]
**Description:**
Pipfile and pipenv are considered to be the [current recommended standard way](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies) of managing project dependencies. Pipenv is the tool that manages your python virtual environment and dependencies according to the Pipfile.

**Expected behaviour:**
Dependencies declared in setup.py can be automatically declared in the Pipfile, reducing duplication as it currently exists.

setup.py and all requirements should declare as broad as possible ranges, so that the user can declare their own dependency versions.  Pipfile.lock can define what the exact expected versions are for reproducing builds (i.e. a dev environment or testing environment).

**Current behaviour:**
The use of `requirements.txt` forces an extra step of maintaining these files separately when working with modern Python applications.

**Comment by jfuss** [comment]
@rnhurt Got it. This is a duplicate of #817/https://github.com/awslabs/aws-lambda-builders/issues/74. Would you be willing to contribute a PIpenv/pipfile workflow?

**Comment by rnhurt** [comment]
Ah, I didn't know that there was an existing issue for this.  I checked this repo and didn't see anything so I created this ticket.  I'll look at the issue you indicated and close this ticket.  Thanx!

**Comment by jfuss** [comment]
@rnhurt You initially sent it to a different repo awslabs/serverless-appilication-model. I moved it to awslabs/aws-sam-cli, which is where build and other CLI commands live. The serverless-application-model is for the SAM Spec and code supporting the transformation from SAM to CloudFormation. That is why you didn't find it initially.
