### ISSUE TITLE
sam init -r nodejs TypeError: app.lambda_handler is not a function

### ISSUE THREAD

**Issue by nguyendviet** [awslabs/aws-sam-cli#1115]
### Description

The test function doesn't have the right Lambda function name

### Steps to reproduce

- Run either:
```
$ sam init --runtime nodejs6.10
// or
$ sam init --runtime nodejs8.10
```
- Follow the instruction inside `./sam-app/README.md`:
```
└── sam-app
    ├── README.md
    ├── hello_world
```
- Run:
```
$ cd hello_world
$ npm run test
```
- Or go to `./sam-app/hello_world/tests/unit/` then run:
```
$ mocha test_handler.js 


  Tests index
    1) verifies successful response


  0 passing (11ms)
  1 failing

  1) Tests index
       verifies successful response:
     TypeError: app.lambda_handler is not a function
      at Context.it (test_handler.js:11:34)
```

### Expected result

The test should pass.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: 
```
ProductName:	Mac OS X
ProductVersion:	10.14.4
```
2. `sam --version`: 
```
SAM CLI, version 0.6.0
```

### Attempts:

- I've tried to rename the function inside the `test_handler.js` from `lambda_handler` to `lambdaHandler` to mach the function name inside `/hello_world/app.js` and it solves the problem.
- However, when I check the examples from [aws-sam-cli](https://github.com/awslabs/aws-sam-cli) which are generated by Cookiecutter, the code in both test files look correct:
  ```
  const result = await app.lambdaHandler(event, context)
  ```
  - [Node 6 example test file](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs6/%7B%7Bcookiecutter.project_name%7D%7D/hello-world/tests/unit/test-handler.js)
  - [Node 8 example test file](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello-world/tests/unit/test-handler.js)
- For some reason, the command:
```
$ sam init --runtime nodejs<version>
```
does not pull the right code.

**Comment by jfuss** [comment]
@nguyendviet You are running a very out of date version of SAM CLI (current version is 0.14.2). 

Please upgrade the CLI. 

Tests are working on the latest as expected:

```
sam init --runtime nodejs --name sam-node
cd sam-node/hello-world
npm install # to install dev dependencies
npm run test
```

Closing as this is not an issue with latest release.
