### ISSUE TITLE
sam local update

### ISSUE THREAD

**Issue by AggarwalKunal** [awslabs/aws-sam-cli#1134]
sam --version
A newer version of the AWS SAM CLI is available!
Your version:   0.2.11
Latest version: 0.15.0
See https://github.com/awslabs/aws-sam-local for upgrade instructions

i am getting this link to upgrade the sam cli version but i am unable to find the instructions. When i try to install it with pip, i face difficulties. Please help!!

**Comment by AggarwalKunal** [comment]
@TheSriram https://github.com/awslabs/aws-sam-cli/releases please tell me how to update via npm. or how to update via these files.

**Comment by mikhama** [comment]
@AggarwalKunal you can install new version using brew for MacOS/Linux, or download MSI-package for Windows, or install it using pip. Instructions and links are available [here](https://aws.amazon.com/serverless/sam/).
However there are not version for npm. I think npm is not supported anymore.

**Comment by AggarwalKunal** [comment]
but when i tried to install it with pip, sam local start-api doesn't worked.

**Comment by mikhama** [comment]
You should add it into your `$PATH` variable. You could find it by following path:
`C:\Users\<Your_Username>\AppData\Roaming\Python\Python37\Scripts`

**Comment by AggarwalKunal** [comment]
currently i am working in ubuntu.

**Comment by mikhama** [comment]
Ok, try to find out where are placed scripts installed by pip. I don't have a computer with Linux installed, and can't do it. But I also have installed this version by pip, added it into `$PATH`, and it works for me.
Maybe it helps. Run in terminal, and command shows you where `sam` is placed:
`pip show aws-sam-cli`

**Comment by AggarwalKunal** [comment]
/home/force-laptop-13/.local/bin

**Comment by mikhama** [comment]
Have you `sam`-command in this directory? 
If answer is true, add it into your `$PATH` variable.
Maybe [this](https://docs.oracle.com/cd/E19062-01/sun.mgmt.ctr36/819-5418/gaznb/index.html) this topic will help you make it.

**Comment by AggarwalKunal** [comment]
i will see it and respond to you tomorrow.

**Comment by jfuss** [comment]
@AggarwalKunal It is kind of hidden in the Update section [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-additional.html).

You will need to uninstall the npm version.
```
npm uninstall -g aws-sam-local
```

You should then be able to follow the your [OS Installation instructions](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html)

**Comment by AggarwalKunal** [comment]
@jfuss yup, you are right but npm doesn't have the latest verion of aws-sam-cli and pip doesn't start aws-sam-cli properly. 
when we type : **sam local start-api**, it gives:
**Error:**

**Comment by jfuss** [comment]
@AggarwalKunal We don't publish to npm anymore (and haven't for about a year).

Looks like you are installing into Python2.7. If you instead install into Python3.6+, you should see what is going on (there is a bug with some of our output in Python2.7). It is probably something with your template, if I remember how this occurs.

**Comment by TheSriram** [comment]
Brew is the go to method on mac to install aws-sam-cli and MSI for windows. Unistall the npm based install of aws-sam-cli, its really old and is not going to be updated going forward.

**Comment by AggarwalKunal** [comment]
sam local start-api
Error: [InvalidResourceException('lambdasrc', 'property timeout not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('apartmentsrc', 'property timeout not defined for resource of type AWS::Serverless::Function')] ('apartmentsrc', 'property timeout not defined for resource of type AWS::Serverless::Function') ('lambdasrc', 'property timeout not defined for resource of type AWS::Serverless::Function')

**Comment by AggarwalKunal** [comment]
installed through pip3

**Comment by AggarwalKunal** [comment]
Thanks all.....

**Comment by PavleNeskovic** [comment]
`sudo -H pip install aws-sam-cli` to install sam globally using pip
