### ISSUE TITLE
Integrate capabilities with boto3 or create separate library

### ISSUE THREAD

**Issue by Marakai** [awslabs/aws-sam-cli#1135]
### Describe your idea/feature/enhancement

I would like to be able to call the SAM capabilities from directly within code, e.g. Python scripts, not least as I increasingly use tools like Troposphere to describe my infrastructure-as-code environments.

This  mean that I would be able to do:

Instead of:

`sam build --template mytemplate.yaml`

I could (brutally abbreviated to show concept):

```
from tempfile import NamedTemporaryFile
from troposphere import Template
from awssamcli import Build

t = Template()
sam_builder = Build(...)
t.add_resource(Function('MyLambda', ...)
with NamedTemporaryFile('w+t') as f:
    f.write(t.to_yaml())
    sam_builder.build(template=f.name)
```

And of course, extend this with `deploy`, `package`, etc

### Proposal

At this time the `aws-sam-cli` source already employs an internal library with most functionality not related to the CLI handling relegated to the code in the `lib` area.

Yet, after looking at the source, it's not as "encapsulated" that using that code directly would be as simple as it is with, say, `boto3`.

To minimise the need to any rewriting, my request would be to create separate wrappers:

- with `aws-sam-cli` installed, I can already do some things like `from samcli import commands`
- however it's not really an exposed (read: documented) API and I've simply been experimenting various bits hoping something might stick

**Comment by jfuss** [comment]
@Marakai You can use/integrate with [`aws-lambda-builders`](https://github.com/awslabs/aws-lambda-builders) library which is the brains behind `sam build`.

I do not think pip installing the `aws-sam-cli` is the right think to depend on. While that can 'work', it is a cli not a library. If there are part you would like to see in the builders library that is currently wrapped into the CLI, cut an issue to the aws-lambda-builders project. That project should be the level you want to interact with and is achievable. 

Closing as aws-lambda-builders is the library you will want to integrate with, not aws-sam-cli directly as a direct dependency in a requirements.txt.
