### ISSUE TITLE
aws-sam-cli 0.15.0 has requirement click~=6.7, but you'll have click 7.0 which is incompatible.

### ISSUE THREAD

**Issue by gangsd92** [awslabs/aws-sam-cli#1137]
### Description
 Error --------------------------------------------------
 
  aws-sam-cli 0.15.0 has requirement click~=6.7, but you'll have click 7.0 which is incompatible.
Exception:
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/pip-target-pp85trgo/lib/python/itsdangerous-1.1.0.dist-info' -> '/var/task/itsdangerous-1.1.0.dist-info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/var/lang/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 441, in run
    options.target_dir, target_temp_dir, options.upgrade
  File "/var/lang/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 498, in _handle_target_dir
    target_item_dir
  File "/var/lang/lib/python3.6/shutil.py", line 561, in move
    symlinks=True)
  File "/var/lang/lib/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/var/lang/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/task/itsdangerous-1.1.0.dist-info'

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.13.0
     Serverless Version:     1.41.0

Briefly describe the bug you are facing.

I'm Just trying to run a simple hello world with Serverless. when I gave 'sls deploy' command, the above mentioned error is thrown.

Provide steps to replicate.

Have files:
app.py
serverless.yml
package.json
package-lock.json
requirements.txt
handler.js

Please follow this link for detailed steps to replicate: https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/

### Expected result

App getting deployed in AWS and cloudformation stack getting populated.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Mojave v10.14.4
2. `sam --version`: SAM CLI, version 0.15.0

**Comment by jfuss** [comment]
@gangsd92 How have you installed SAM CLI? If you are using PIP, then another package you have installed is clashing with our dependencies (which is common and why we recommend brew as it gives you isolation). To get over this, you should be using [brew](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html).

**Comment by gangsd92** [comment]
@jfuss 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

- Is the error I get after trying to brew install aws-sam-cli
Should I install python using homebrew as well?

**Comment by jfuss** [comment]
@gangsd92 You should use homebrew instead of directly pip installing. The issue with install with pip, is you start running into system dependency clashing, outdated tools, etc. To give an isolated install so the cli is installed outside of your system python, we build installers and why we push customers to use these instead of pip. 

So you should uninstall aws-sam-cli from pip and use homebrew instead.

Closing as the issue was due to system python out of date and dependencies already installed conflict with SAM CLI's dependencies.
