### ISSUE TITLE
Check dependencies after/before installation

### ISSUE THREAD

**Issue by zafarella** [awslabs/aws-sam-cli#1153]
### Describe your idea/feature/enhancement
As sam requires aws eventually during it's package phase, it would save a lot of time if after installing or even before installing it it will check that the `aws` or others it depends on exists in the "PATH"

### Proposal
* add checking required dependencies before/after installation

**Comment by TheSriram** [comment]
How would you like for this to manifest? when running the first command? or specified as text right after install when installed through brew for instance, we can add caveats.

eg:

```
  def caveats
    "Something the user should know?"
  end
```

to https://github.com/aws/homebrew-tap `aws-sam-cli` Formula.

We could possibly add docker and aws-cli to that list. Thoughts?

**Comment by zafarella** [comment]
I think both options are good. May be after first command if it cannot find any executable it needs just report and quit?

I'm not aware about the details frankly, but if you put in brew formula, will it work on linux/windows?

**Comment by TheSriram** [comment]
brew is actually available across both linux and the Windows subsystem for linux.

https://docs.brew.sh/Homebrew-on-Linux

**Comment by jfuss** [comment]
This will only work for brew though right? How do we support this for MSI's or (dare I say) pip?

**Comment by TheSriram** [comment]
Yes it will only work for brew, came by this through some preliminary investigation.

**Comment by sriram-mv** [comment]
We no longer have a dependency on aws cli, Resolving this issue.
