### ISSUE TITLE
Use explicit memory settings for Java cookie cutters

### ISSUE THREAD

**Issue by mikebroberts** [awslabs/aws-sam-cli#1158]
Hi all - I just used "java" cookie cutter today and noticed that it had a very long cold start (14 seconds.) After a quick bit of investigation I realized it was using the default `MemorySize` of 128MB, which is barely sufficient for JVM Lambdas. I recommend setting this explicitly, e.g. to 512 or 1024 for the Java and Gradle cookie cutters.

**Comment by 53ningen** [comment]
This issue was probably resolved by #1340.
Released in v0.21.0.
https://github.com/awslabs/aws-sam-cli/releases

**Comment by c2tarun** [comment]
Resolving this issue as the PR is merged and I confirmed that on creating new sam cli project default memory allocated is 512 MB.
