### ISSUE TITLE
Dependency installation path

### ISSUE THREAD

**Issue by shduke** [awslabs/aws-sam-cli#1162]
### Describe your idea/feature/enhancement

For Python, SAM installs all the dependencies from the request.txt in the project root. It would be nice if we could chose the dependency path (e.g. .vendor/).

### Proposal

sam build -d, --dependency-dir DIRECTORY

**Comment by TheSriram** [comment]
you can pass the manifest path.

  -m, --manifest PATH        Path to a custom dependency manifest (ex:
                             package.json) to use instead of the default one

**Comment by shduke** [comment]
Specifying the manifest PATH only specifies where to read the dependency list from, it doesn't specify where those dependencies are placed once installed. The dependent modules are still placed in the project root regardless of the manifest path. It would be nice to place them in a specific folder (e.g. vendor/).

e.g. for python it would be nice if SAM had the ability to essentially do this when installing dependencies:
`pip install -r requirements.txt --target .vendor/`
