### ISSUE TITLE
Support --endpoint-url option

### ISSUE THREAD

**Issue by honglu** [awslabs/aws-sam-cli#1194]
### Describe your idea/feature/enhancement

I wish SAM CLI would support `--endpoint-url` just like [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/) does. 

Here is the error I got when I tried to use `--endpoint-url`:
```
sam publish -t .aws-sam/packaged-template.yml --region us-east-1 --endpoint-url https://serverlessrepo.us-east-1.amazonaws.com
Error: no such option: --endpoint-url
```

### Proposal

I think this option is probably not for every command under CLI but I think for the following command it makes sense:
```
sam package  # Customers can use --endpoint-url for customized S3 endpoints
sam deploy # Customers can use --endpoint-url for customized CloudFormation endpoints
sam publish # Customers can use --endpoint-url for customized Serverless repo endpoints
```

**Comment by TheSriram** [comment]
this is currently coupled to s3, cloudformation and serverless repo endpoints. doesn't region already allow this?

**Comment by sanathkr** [comment]
@honglu I understand why you want this, but I don't see how SAM CLI customers at large will want this. I am not inclined to supporting this as a CLI argument which adds cognitive load when a customer reads the help text to learn about the command.

**Comment by bezdjian** [comment]
Having this would have been also cool and awesome to be able to test lambda function locally with LocalStack (local AWS environment), where we can create and mock dynamo tables and S3 in local stack and test ´sam local invoke --env-vars --endpoint-url=http://localstack-url´ that would target the LocalStack. this would save so many lives 😢

**Comment by th3n3rd** [comment]
@bezdjian it would be nice indeed, and would remove the burden to use yet another library: https://github.com/localstack/aws-sam-cli-local
