### ISSUE TITLE
Error when validating template - property GatewayResponses not defined for resource of type AWS::Serverless::Api

### ISSUE THREAD

**Issue by danPudwellUK** [awslabs/aws-sam-cli#1198]
When running ```sam validate``` on example template at https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_gateway_responses/template.yaml

I get the following result:
```Error: [InvalidResourceException('MyApi', 'property GatewayResponses not defined for resource of type AWS::Serverless::Api')] ('MyApi', 'property GatewayResponses not defined for resource of type AWS::Serverless::Api')```

I would have expected this to validate.
Using aws-sam-cli v0.16.1
I'm not sure how this correlates to serverless-application-model which has latest 1.11.0?

Also when running ```sam build``` I get the following error:
```Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/samcli/lib/samlib/wrapper.py", line 67, in run_plugins 
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins 
  File "/usr/local/lib/python3.7/site-packages/samcli/lib/samlib/wrapper.py", line 134, in parse 
    raise InvalidDocumentException(document_errors) 
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('AdaptApiGateway', 'property GatewayResponses not defined for resource of type AWS::Serverless::Api')] ```

**Comment by keepersmith** [comment]
I am seeing this as well - it is preventing me from being able to use Cloud9/SAM API Gateway testing without having to comment-out the GatewayResponses block in template.yml everytime I want to test.

Details:
"sam validate" returns:
Error: [InvalidResourceException('PKRestApi', 'property GatewayResponses not defined for resource of type AWS::Serverless::Api')] ('PKRestApi', 'property GatewayResponses not defined for resource of type AWS::Serverless::Api')

template.yml:
...
Resources:
  PKRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
...

SAM CLI, version 0.17.0 (python3)

Thanks.

**Comment by chrisoverzero** [comment]
Because of how SAM translator runs plugins, the dependent version of `aws-sam-translator` hasn’t been updated to 1.11.0 yet – see [an open PR][] and [the project requirements][].

[an open PR]: https://github.com/awslabs/aws-sam-cli/pull/1155
[the project requirements]: https://github.com/awslabs/aws-sam-cli/blob/1fa05c561a31e8543ec38d7f21b77867b6394078/requirements/base.txt#L9

If you’ve installed the CLI through `pip`, then `aws-sam-translator` can be upgraded independently to 1.11.0. Off the top, I think that’s `pip install --upgrade aws-sam-translator`, but some installations have to run `pip3` explicitly.

I don’t use `brew`, so I’m not sure how to upgrade those installations.

**Comment by keepersmith** [comment]
Hi, thanks for the update. My pip/python are both 3.6 so I should be good there.

However, when I run "pip install --upgrade aws-sam-translator" it fails with:
ERROR: aws-sam-cli 0.17.0 has requirement aws-sam-translator==1.10.0, but you'll have aws-sam-translator 1.11.0 which is incompatible.

**Comment by alessandrobologna** [comment]
I managed to get it to work by adding `—force` to the `pip install --upgrade aws-sam-translator`. Not sure yet if it has broken something else…

**Comment by awood45** [comment]
We're actively working on the `aws-sam-translator` dependency, and by extension this issue.

**Comment by awood45** [comment]
This is going to be fixed with the next release, and other issues are open about the dependency upgrade. Closing this.
