### ISSUE TITLE
Invoking Local Lambda via AWS CLI and SDK

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#12]
The ability to invoke sam local Lambda functions via the AWS CLI and SDK, by simply setting the endpoint. Today, you have to call `sam local invoke` to actually Invoke a Lambda function. This means, you can't port your existing integration tests that run both against the local Lambda environment and cloud. 

SAM Local can provide a local HTTP endpoint that responds to Lambda Invoke API and invokes Lambda locally. You can simply point AWS CLI or SDK to this endpoint to run tests against it.

**Comment by rohitpg** [comment]
How to point AWS CLI or SDK to SAM LOCAL Lambda to run test?
Example: need aws sam local command equivalent to
aws lambda create-event-source-mapping \
    --region us-east-1 \
    --function-name publishNewBark \
    --event-source streamARN  \
    --batch-size 1 \
    --starting-position TRIM_HORIZON

**Comment by jfuss** [comment]
This was enabled through the `sam local start-lambda` command adding in [v0.5.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.5.0)

Closing
