### ISSUE TITLE
Linuxbrew messes up my python install on Archlinux

### ISSUE THREAD

**Issue by kaihendry** [awslabs/aws-sam-cli#1204]
```
[hendry@t480s ~]$ command -v python3
/home/linuxbrew/.linuxbrew/bin/python3
[hendry@t480s ~]$ brew uninstall python3
Error: Refusing to uninstall /home/linuxbrew/.linuxbrew/Cellar/python/3.7.3
because it is required by aws-sam-cli, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies python3
```

**Comment by sanathkr** [comment]
What is your `$PATH`? The whole Linuxbrew bin folder (`/home/linuxbrew/.linuxbrew/bin`) is probably in your $PATH, which is why this happens. 

Instead you could add simply your SAM CLI file to the path - `home/linuxbrew/.linuxbrew/bin/sam` or create an alias that points to that folder.

**Comment by pickfire** [comment]
Seems like I have some issue with sam cli on arch linux as well. I am using `python 3.7.3` with virtual environment with `pip 19.1.1`. `sam build` shows:

```
2019-06-10 14:42:24 Building resource 'SomeFunction'
2019-06-10 14:42:24 Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pip'

```

**Comment by awood45** [comment]
In both of these cases, can you provide your output for `echo $PATH`, taking care to remove anything sensitive that's not relevant if desired, I'm mainly interested in seeing what LinuxBrew is doing in your PATH relative to any Python installs you have.
