### ISSUE TITLE
Usage of Docker Tags for Runtime Versioning

### ISSUE THREAD

**Issue by metaskills** [awslabs/aws-sam-cli#1219]
This is a duplicate of the following issue I created on the lambci/docker-lambda repo. https://github.com/lambci/docker-lambda/issues/191

During the recent upgrade for the [execution environments](https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/) we noticed that would could not make a deterministic update because tags used in lambci/docker-lambda are for languages (https://hub.docker.com/r/lambci/lambda/tags) and not for versions of the execution environment. Not have version tags for major changes means it is hard for downstream users to migrate to the new runtime in a predictable way. It could also mean new containers could break build pipelines during the transition phase. 

I wanted to file this duplicate issue to share my experiences and see if there is some additional thinking here since SAM uses these containers. Thanks y'all!

**Comment by mhart** [comment]
docker-lambda now does this for large refactors, see https://github.com/lambci/docker-lambda/issues/191#issuecomment-557824167

**Comment by metaskills** [comment]
Cool, I'll close this issue now too.
