### ISSUE TITLE
Ignore hidden files when running sam build

### ISSUE THREAD

**Issue by zhangzhx** [awslabs/aws-sam-cli#1241]
### Describe your idea/feature/enhancement

When running `sam build` for python, sam copies the whole folder structure of the lambda base directory to the target build folder. I wish SAM CLI would ignore all the hidden files that is not needed for building the project, or at least provide a parameter to specify what folder/files should be ignored.

### Additional Details
N/A

**Comment by TheSriram** [comment]
Yeah each workflow in `aws-lambda-builders` has a series of files they excluded, but its locked into the workflow directly.

https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/python_pip/workflow.py#L21

I'll mark this issue as a feature request.

**Comment by sriram-mv** [comment]
This has been merged into lambda builders. Closing.

**Comment by solarmosaic-kflorence** [comment]
https://github.com/aws/aws-lambda-builders/issues/185
