### ISSUE TITLE
Upgrade to latest version of aws-sam-translator

### ISSUE THREAD

**Issue by beck3905** [awslabs/aws-sam-cli#1266]
I'm running into some compatibility issues in environments that use both aws-sam-cli and cfn-lint.  The latest version of cfn-lint requires `aws-sam-translator>=1.12.0` and aws-sam-cli requires `aws-sam-translator==1.10.0`.  Is there a reason the next version of aws-sam-cli can't upgrade the aws-sam-translator version?

**Comment by jfuss** [comment]
@beck3905 Thanks for the issue. You can find reasons why [here](https://github.com/awslabs/aws-sam-cli/pull/1155#issuecomment-487650840) which links out to a deeper explanation. 

But this is only an issue if you are installing SAM CLI through pip. Using our installers (or even an isolated instal in a venv), you wont even have this problem. Given that, the path is to not install everything into one global place. You will run into this issues in other cases, not just for these dependencies if you keep following the pip model.

Closing as the solution is not to use pip and use the installers to install SAM CLI.

**Comment by beck3905** [comment]
@jfuss I understand that there are changes required to the aws-sam-cli to support the newer version of aws-sam-translator.  Thank you for answering my question.  Are there plans to make those changes soon?

Also, it sounds like you are saying that installing the aws-sam-cli with pip is no longer supported.  However the documentation from AWS specifically describes using pip to install the aws-sam-cli.  https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html#serverless-sam-cli-install-linux-pip

In my case, I am installing aws-sam-cli and cfn-lint as dev dependencies into a ci/cd container.  That container does not have homebrew, but it does have pip, thus I am using pip to install both.

**Comment by jfuss** [comment]
@beck3905 We are working on addressing the documentation and the current recommendation is to use it as a last resort.

To use pip and avoid these issues, you should be using a venv. 
```
python3.7 -m venv samcli-venv
samcli-venv/bin/pip3 install aws-sam-cli
samcli-venv/bin/sam --version
```

You can do the same for AWS CLI. This way you never have to care about conflicts. You can then add that bin to the PATH so you don't have to provide the full path to the executable.

**Comment by beck3905** [comment]
@jfuss I am using pipenv which uses virtualenv under the hood so I am using a virtualenv, but it is attempting to install both aws-sam-cli and cfn-lint into the same virtualenv.

**Comment by jfuss** [comment]
@beck3905  Yes, Pipenv uses virtualenv under the hood but it only uses one. So you are still installing multiple things into one virtualenv. This means, at any point, an upgrade to something you install will conflict with anything else (today its SAM CLI and CFN Lint, tomorrow it could be AWS CLI and SAM CLI with boto3). This makes your build and environment very fragile. Pip is a great distribution for libraries but not CLIs. Because of this, you should be creating an venv for the CLI directly and using that outside of the Pipfile.
