### ISSUE TITLE
Pip install aws-sam-cli ERROR

### ISSUE THREAD

**Issue by VictorKunzler** [awslabs/aws-sam-cli#1268]
I'm trying to install AWS SAM CLI in my Linux Ubuntu 18.04 and I'm getting the error:

Building wheels for collected packages: regex
  Building wheel for regex (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-s6fYQC/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-JbeE6P --python-tag cp27:
  ERROR: BASE_DIR is /tmp/pip-install-s6fYQC/regex
  /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:472: UserWarning: Normalizing '2019.06.08' to '2019.6.8'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/regex
  copying regex_2/regex/__init__.py -> build/lib.linux-x86_64-2.7/regex
  copying regex_2/regex/regex.py -> build/lib.linux-x86_64-2.7/regex
  copying regex_2/regex/_regex_core.py -> build/lib.linux-x86_64-2.7/regex
  creating build/lib.linux-x86_64-2.7/regex/test
  copying regex_2/regex/test/__init__.py -> build/lib.linux-x86_64-2.7/regex/test
  copying regex_2/regex/test/test_regex.py -> build/lib.linux-x86_64-2.7/regex/test
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/regex_2
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-MW0004/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ERROR: Failed building wheel for regex

**Comment by awood45** [comment]
It looks like you may not have GCC installed. However, I would recommend that you use [Linuxbrew](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html#serverless-sam-cli-install-linux-homebrew) to install the AWS SAM CLI.

Our Python 2.7 support is on the path to deprecation, so installing this way will also get you set up using Python 3.

**Comment by VictorKunzler** [comment]
Hi @awood45 , thank you for the anwser, homebrew I got this error:

checking whether the C compiler works... no
configure: error: in `/tmp/python-20190712-12144-1augvtu/Python-3.7.4':
configure: error: C compiler cannot create executables

**Comment by awood45** [comment]
Have you installed GCC on your system?

**Comment by VictorKunzler** [comment]
I already installed GCC, and I'm getting the following error:
==> make
Last 15 lines from /home/victor/.cache/Homebrew/Logs/python/02.make:
2019-07-12 17:43:33 -0300

make

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make: line 25: exec: : not found

**Comment by nk2580** [comment]
im curious as to why we would need to use linuxbrew? the linux community has an established group of package managers which are standard in their distros. alternatively pip is also a standard way across distros for installing python based programs... why is the AWS CLI itself independent of linuxbrew but the SAM CLI is not?

**Comment by defel** [comment]
fyi: `pip install --user aws-sam-cli` works for me (this should be the official way to install `aws-sam-cli` on linux or at least be documented as an "expert-installation-method") 

Maybe it was confusing to use npm[1] some years ago so install sam. But now, forcing the user to use homebrew, which I only can install by curl-eval'ing a script, which curl-ruby-eval [2] another script is imho pretty yak-shaving. 

[1] https://www.npmjs.com/package/aws-sam-local
[2] https://github.com/Linuxbrew/install/blob/master/install.sh#L16

**Comment by nk2580** [comment]
@defel that was the old standard.. and fair enough.. pip is a neat and competent package manager for python.

This thread however leads me to believe that the SAM team don’t want us to use pip anymore and that’s where my confusion comes from... @awood45 can you confirm?

**Comment by nk2580** [comment]
anyone interested in responding?

**Comment by VictorKunzler** [comment]
Hey @nk2580, I used the linuxbrew because I was following the AWS SAM CLI tutorial.
I solved the problem after restart the computer some times.
Thanks for the help.

**Comment by defel** [comment]
so this issue can be closed? Works with linuxbrew, works with pip - everything fine?

**Comment by VictorKunzler** [comment]
Yes, sure.

**Comment by VictorKunzler** [comment]
Problem solved

**Comment by ArpitSrv** [comment]
Restart of computer after installation fixed the issue for me.
OS-Windows
Installation-MSI Installer for Windowsx64
