### ISSUE TITLE
[Question] Scripting SAM CLIs to build, package and deploy Lambda functions

### ISSUE THREAD

**Issue by simon10says** [awslabs/aws-sam-cli#1274]
Hi. Newbie here and hope someone can provide some guidance.

I uses `Visual Studio` SAM project to create multiple lambda functions. I've written a script that:
```
sam build
sam package
sam deploy
```
Everything works great. However:
1. `sam package` generates and upload to S3 {UUID} package zip files (one per function). Can I give it a more meaningful name instead of {UUID}?
2. Running my script will always generate and upload new package files even thought I've made no changes to my function. Is there a way/method where it will only `build` or `package` IFF there is changes to my function?

**Comment by hawkins** [comment]
Thanks to [this comment](https://github.com/awslabs/aws-sam-cli/issues/1173#issuecomment-518817038), I've found you can use the `--s3-prefix` to give the file a meaningful prefix at least, so now your various lambda functions can be sorted in the bucket

**Comment by sriram-mv** [comment]
sam deploy --guided now adds the stack name prefix automatically.

>> " Is there a way/method where it will only build or package IFF there is changes to my function"

This comes under incremental builds and packaging, for which we have separate issues already. 

Closing this issue.
