### ISSUE TITLE
sam local fails to execute when SAM CodeURI points to single file

### ISSUE THREAD

**Issue by tbennett0** [awslabs/aws-sam-cli#1298]
### Description
In my SAM template, I have a direct reference in CodeUri to the specific file with my code in it. When using sam package, it successfully uploads a ZIP with the single file of code. If I run `sam local invoke myFunction`, it attempts to mount that specific file as a volume in the container at /var/task:ro, which causes Docker to fail on container creation.

### Steps to reproduce
1. Create minimal template with AWS::Serverless::Function resource pointing to an individual file in the CodeUri.
2. Run sam local invoke YourFunction --event test.json

### Observed result
Mounting /path/to/individual/file.py as /var/task:ro,delegated inside runtime container
```
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/path/to/individual/file.py\\\" to rootfs \\\"/var/lib/docker/overlay2/67e20768118c419f3e48d35e793a4e725d8f9e040a2249389459aca31bf6ae2f/merged\\\" at \\\"/var/lib/docker/overlay2/67e20768118c419f3e48d35e793a4e725d8f9e040a2249389459aca31bf6ae2f/merged/var/task\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type")
```

### Expected result
Individual file to be pulled in and executed as in Lambda.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: macOS
2. `sam --version`: 0.18.0

**Comment by awood45** [comment]
This may be a documentation issue, because I don't think this is the intended use of CodeUri. What happens if you exclude CodeUri entirely and just point to the file path directly in the handler definition?

That said, the best practice pattern here would be to have your handler file(s) in a folder, and use that folder for CodeUri.

**Comment by tbennett0** [comment]
@awood45 yeah, I wondered that after reading a little more. Definitely makes sense, I can probably migrate that direction. I didn't know if this would be a supported way to use CodeUri.

It uploads the full local directory to S3, which works. I'm thinking of a use case where multiple smaller Lambda functions live in the same repository, so it would upload the full project for each function if I did that.

**Comment by awood45** [comment]
That's a fair shout, and that's what it will do in that case. You do have the option of having multiple folders for different functions, and that's absolutely a valid pattern. There's a feature request out to support multiple CodeUris to a single function as well to try and reduce duplication, but for now you'll want to split into multiple folders if needed. Layers are another option for shared code.

**Comment by awood45** [comment]
Closing as this seems to be answered - feel free to reopen if you have further questions or issues.

**Comment by bastidn98** [comment]
Hi, sorry appreciate this is old, but I wanted to ask if this is still the case. 
My use case sounds pretty similar to @tbennett0 where I want to have a project with multiple (python) scripts in a single `functions/` directory. But I don't want each function to have the code for every other function if I give them each `"CodeUri": "./tasks"`

**Comment by tbennett0** [comment]
@bastidn98 I believe it still works this way. You'd have to use folders per function to avoid every function having the full directory available when using sam build as far as I know.
