### ISSUE TITLE
Set SAM_DOCKER_VOLUME_BASEDIR without affecting working directory for decompression of jars/zips

### ISSUE THREAD

**Issue by Inkromind** [awslabs/aws-sam-cli#130]
To work with a remote docker, one has to set SAM_DOCKER_VOLUME_BASEDIR (or its equivalent commandline parameter) to a directory on the remote host containing all the files for the lambda functions.
This parameter is however also used to determine the "working directory".
As a result, when it wants to decompress a .jar or .zip specified by CodeUri, it will try to decompress the file in the remote volume basedir. If this directory is unreachable, then it is unable to decompress the file.

We are currently running sam-local in a docker container itself, and the SAM_DOCKER_VOLUME_BASEDIR points to a directory on the docker host, which is volume-mounted on the docker container in which sam-local is running. This way, sam-local can access the files that are passed to the lambda containers directly. When trying to decompress a .jar or .zip, it however tries to do that by using the path the file has in the host, rather than the local path.

Would there be a way to set SAM_DOCKER_VOLUME_BASEDIR without affecting the "working directory" for sam-local? This would at least help solve this problem in the cases where sam-local can access the files, but has to use a different path than SAM_DOCKER_VOLUME_BASEDIR. As it stands now, I don't see the decompression working in any case where you are working with a remote docker and set SAM_DOCKER_VOLUME_BASEDIR, even if sam-local can access it through a different uri.

Our current workaround is by unzipping everything ourselves rather than letting sam-local do it.

**Comment by sanathkr** [comment]
This is a feature gap. May be we should call it out in README. Here is the trouble:

SAM Local has to decompress code into a directory that is already mounted in remote Docker. Which means it will be writing temporary files, and potentially not clean up, into a directory that will contain legit files. This is our problem. With local Docker, SAM can just mount the `/tmp/foo` directory (in Mac for example) where the jar will be expanded.

Can you think of how we can solve it for remote Docker?

**Comment by Inkromind** [comment]
Doesn't SAM Local do the same (writing temp files to a directory possibly containing legit files and not clean them up) when using a local docker?

You could split the concept of "working directory" and "the directory to mount in the lambda containers" and allow configuring each separately. This way sam-local could still do its thing if it needs to use a different path to the directory than the remote docker uses to mount.
I however only see this as an edge case and as I said before and I don't think there are many cases where this will happen. I don't know if it adds much benefit over just saying decompression never works when using a remote docker and saying to manually do the decompression yourself beforehand.

**Comment by sanathkr** [comment]
Going to close this out because this didn't get much traction and we can't do much about it.
