### ISSUE TITLE
Windows installation fails thanks to an unknown Docker requirement

### ISSUE THREAD

**Issue by azarboon** [awslabs/aws-sam-cli#1300]
I'm trying to install SAM Cli on Windows 7 via pip. My python version is 2.7, 
have installed Docker 18.09.3 on my Windows. and I run this command:

`pip3 install aws-sam-cli --proxy our-proxy`

But installation fails and I get this error:

> 
>   Could not find a version that satisfies the requirement docker~=3.7.0 (from aw
> s-sam-cli) (from versions: 3.5.0, 4.0.1, 4.0.2)
> No matching distribution found for docker~=3.7.0 (from aws-sam-cli)
> You are using pip version 19.0.3, however version 19.1.1 is available.
> You should consider upgrading via the 'python -m pip install --upgrade pip' comm
> and.

Expected behavior is to install sam  without error.

**Comment by TheSriram** [comment]
Have you tried installing via the MSI? 

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html

**Comment by awood45** [comment]
The linked instructions are the correct way to install. This isn't actually a Docker requirement, it's the Docker library itself. Regardless, installing via Python 2.7 as well as via pip is not recommended and will soon be unsupported entirely. Closing for now, please reopen if you have issues installing via the MSIs.
