### ISSUE TITLE
Support additional parameters for Package command

### ISSUE THREAD

**Issue by cfbarbero** [awslabs/aws-sam-cli#1312]
### Support additional package params

I wish SAM CLI would support the `--kms-key-id` and `--s3-prefix `options on the `sam package` command.  We use the kms-key-id to encrypt our packages when pushing to s3.

### Proposal

1) Add 2 new parameters to the `sam package` command for `--kms-key-id` and `--s3-prefix`.  
2) Pass those arguments through to the underlying `aws cloudformation package` command

```
sam package --template-file /path_to_template/template.json --s3-bucket bucket-name --kms-key-id <some-key> --output-template-file packaged-template.json
```

**Comment by awood45** [comment]
We directly shell out to the AWS CLI for this command, so it's not supported there either. If you're able to get these working with `aws cloudformation package` but not `sam package`, please let me know the environments and versions as that would be an odd issue indeed.

That said, will look at this as this is definitely a good thing to support.

**Comment by cfbarbero** [comment]
You're right, it does work.  I guess I was misled because the documentation explicitly references the `--s3-bucket` param.  I wonder if it would be possible/helpful to extend the docs to state that all parameters of `aws cloudformation package` are supported.

Tested command:
```
sam package --s3-bucket artifact-store-123456789012 --template-file main.yml --kms-key-id     arn:aws:kms:us-east-1:123456789012:key/11111111-1111-1111-1111-111111111111 --s3-prefix test
```

**Comment by awood45** [comment]
Understood - we're actively working on the long term fix for this, which will include documentation updates. Going to go ahead and close this, feel free to reopen if you have further issues.
