### ISSUE TITLE
Fails to connect to proxy URL

### ISSUE THREAD

**Issue by azarboon** [awslabs/aws-sam-cli#1318]
I'm using SAM v0.16.1 on my Windows 7 workstation and behind our corporate proxy. Using `sam package` and `sam deploy`, often I get this error:

> Failed to connect to proxy URL: our-proxy-url

Few times the issue was with our proxy server, but it seems to me most of the time it's an issue with SAM. Because when I get this error, doing following activities solves the issues:
- run `sam init`
- run `sam validate`
- Running the command `sam package` in a new terminal within Visual Sudio Code (my default editor and terminal)
- Running the command `sam package`  in a new CMD terminal

Almost always, one of the above actions solves the issues. But the problem is that none of them offer a golden key, so I need to try each of the above one by one and see which one works. Often, I need to try all four of them to solve the issue. This is annoying. Is there anyway to fix the issue?

**Comment by awood45** [comment]
Is this an intermittent issue, or do you have a series of commands which seem to reliably reproduce this issue?

At a glance, this sounds like a networking issue on your machine. If there's a reliable reproduction mechanism, we could look more deeply into this.

**Comment by azarboon** [comment]
It's intermittent. I only use `sam package` and `sam deploy` commands. When this happens next time, I can log and send to you. But what and how should I log your required info?

**Comment by azarboon** [comment]
Update: just noticed that I encounter this issue also with `aws cloudformation package` and `aws cloudformation deploy`

**Comment by azarboon** [comment]
New update:  eventhough it fails to do 'cloudformation deploy' but I can do 'cloudformation package'

**Comment by sriram-mv** [comment]
@azarboon This does not seem to be from sam cli's operation. SAM CLI calls forth aws services depending on the commands that are being run. If you are seeing this with other CLIs as well, dont think this issue is exclusive to sam cli alone. Closing this issue, feel free to re-open if deemed necessary.
