### ISSUE TITLE
[Question] Is there a way to add a Mapping Template to an Integration Request for a Resource when running `sam local start-api`?

### ISSUE THREAD

**Issue by nservidio** [awslabs/aws-sam-cli#1353]
Hi, newbie here,

The README.m generated when running `sam init --runtime python3.7` indicates that when running:
```
sam local start-api
```
The following occurs:
> SAM CLI is used to emulate both Lambda and API Gateway locally...

Is there a way to add a `Mapping Template` to an `Integration Request` for a` Resource` in this emulated API Gateway?

**Comment by sanathkr** [comment]
Unfortunately we don't support mapping templates locally. This one is a bit tricky because Velocity, the engine used by mapping template, isn't available locally. We don't plan on supporting this for the time being.
