### ISSUE TITLE
YAML anchor unrolling 

### ISSUE THREAD

**Issue by shortjared** [awslabs/aws-sam-cli#1354]
### Describe your idea/feature/enhancement

This issue is to track/confirm that AWS CLI will behave the same as AWS CLI in terms of packaging resolving CloudFormation YAML anchors/aliases. https://github.com/aws/aws-cli/pull/3827

**Comment by sanathkr** [comment]
Oh thanks for the Issue. We have a copy of yamlhelper.py (surprise!) in SAM CLI that we now need to update.  "sam package/deploy" commands wrap AWS CLI commands, so they should continue to work, but other parts of the CLI might not. 

Would you be able to send a PR? It should just be some copy/pastas :)
