### ISSUE TITLE
Bumping requirement to support latest release of Flask

### ISSUE THREAD

**Issue by tcco** [awslabs/aws-sam-cli#1365]
### Describe your idea/feature/enhancement

Provide a clear description. Ex. I wish SAM CLI would [...]

I wish SAM CLI would support Flask>=1.1.0

### Proposal

Add details of how to add this to the product.

Update base.txt from the requirements folder.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

No updates to the SAM Spec

**Comment by TheSriram** [comment]
Thanks for the issue! is there a reason why you want sam cli to support a higher version of flask?

**Comment by TheSriram** [comment]
Closing this issue, feel free to re-open if you could provide more details on this.
