### ISSUE TITLE
Deprecating 32-bit MSI installer for Windows

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#1373]
## What is changing?
SAM CLI currently releases MSI installers for Windows in both 32-bit and 64-bit flavors. We are planning on deprecating the 32-bit flavor with plans to invest more into improving the 64-bit installer in future. 

If you are using a 64-bit hardware you should not be impacted. You can continue to use the 64-bit installer. Most laptops, desktops and cloud machines use 64-bit hardware because it offers more security, supports larger more than 4GB of RAM, and is even required to run [Docker](https://docs.docker.com/docker-for-windows/install/).

## Am I impacted?
Following instructions from [Microsoft's Support page](https://support.microsoft.com/en-us/help/827218/how-to-determine-whether-a-computer-is-running-a-32-bit-version-or-64) to determine if you are running a 32-bit or 64-bit operating system. 

If you are running a 64-bit operating system, you will not be impacted. 

If you are running a 32-bit operating system and do not have a path to migrating to a 64-bit OS, let us know here.

**Comment by TheSriram** [comment]
https://github.com/awslabs/aws-sam-cli/releases/tag/v0.22.0 has only the 64 bit installer. Closing this issue.
