### ISSUE TITLE
Break point is not hitting When Debugging Golang code using SAM CLI 

### ISSUE THREAD

**Issue by KarthickEmis** [awslabs/aws-sam-cli#1379]
I just created a sample project in golang using sam cli in vs code ...
Followed the below steps to build and run in my windows machine

set GOARCH=amd64
set GOOS=linux
go build -o ./dlv github.com/go-delve/delve/cmd/dlv
go get -u github.com/aws/aws-lambda-go/...
set GOARCH=amd64
set GOOS=linux
go build -gcflags="-N -l" -o  hello-world/main ./hello-world
sam local start-api -d 5989 --debugger-path . --debug-args="-delveAPI=2"

( i tried -delveAPI=1 also , but not working)

Attached my template.yaml file.
[template.txt](https://github.com/awslabs/aws-sam-cli/files/3549238/template.txt)

When i try to run the below command , 
sam local start-api -d 5989 --debugger-path . --debug-args="-delveAPI=2" , i  can see upto the below lines in terminal 

2019-08-28 10:42:16 Mounting C:\go-work\src\sam-app1\sam-app\hello-world as /var/task:ro,delegated inside runtime container
Could not create config directory: mkdir .config: read-only file system.API server listening at: [::]:5989
2019-08-28T05:12:17Z info layer=debugger launching process with args: [/var/task/main], 

once i select restart in debugger option , i am getting output in browser ... But i am not hitting break point in vs code. 

2019-08-28T05:12:57Z debug layer=debugger continuing
?[32mSTART RequestId: 959e2982-4823-1ac4-38a2-db2fb097b6d0 Version: $LATEST?[0m
?[32mEND RequestId: 959e2982-4823-1ac4-38a2-db2fb097b6d0?[0m
?[32mREPORT RequestId: 959e2982-4823-1ac4-38a2-db2fb097b6d0     Duration: 1178.29 ms    Billed Duration: 1200 ms        Memory Size: 128 MB     Max Memory Used: 30 MB  ?[0m
2019-08-28 10:42:59 No Content-Type given. Defaulting to 'application/json'.
2019-08-28 10:42:59 127.0.0.1 - - [28/Aug/2019 10:42:59] "GET /hello HTTP/1.1" 200 -
2019-08-28 10:42:59 127.0.0.1 - - [28/Aug/2019 10:42:59] "GET /favicon.ico HTTP/1.1" 403 -

VsCode: 1.37.1
aws-cli - 1.16.26
aws sam cli 0.19.0
Docker For Windows: 19.03.1

**Comment by TheSriram** [comment]
Closingthis issue. This issue is referenced in #1310
