### ISSUE TITLE
sam build -b . deletes directory

### ISSUE THREAD

**Issue by joxtoyod** [awslabs/aws-sam-cli#1394]
Thought it might necessary to have some check/confirmation before proceeding when specifying the build path.

if you invoke the command `sam build -b .` by accident it will clear the entire directory including .git folder

**Comment by TheSriram** [comment]
This is related to https://github.com/awslabs/aws-sam-cli/issues/1157

**Comment by jfuss** [comment]
Closing as this is a duplicate of #1157
