### ISSUE TITLE
Upgrading from 0.19 to 0.21.0 Breaks Working Project

### ISSUE THREAD

**Issue by ktersius** [awslabs/aws-sam-cli#1402]
### Description

We have a working template that runs fine using version 0.19 but when we upgrade to 0.21 doing the exact same thing results in an error.

```
	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token { in JSON at position 1","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token { in JSON at position 1","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:36:30)","    at Module._compile (internal/modules/cjs/loader.js:776:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
```

### Steps to reproduce

For our setup:

1. Upgrade to 0.21. start sam cli.
2. Start sam local: sam local start-api --env-vars local.env.json --region ap-southeast-2 --template ./template.yaml
3. Invoke a lambda.

### Observed result

When you downgrade to 0.19 everything works as expected.

### Expected result

After the upgrade it should still function as before. Unless there are some breaking changes I missed?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu 18 lts
2. `sam --version`: 0.19 & 0.21

```
Found one Lambda function with name 'RestEntry'
Invoking rest-api.handler (nodejs10.x)
Environment variables overrides data is in CloudFormation parameter file format
Loading AWS credentials from session with profile 'None'
2019-09-12 14:07:28 Found credentials in shared credentials file: ~/.aws/credentials
Resolving code path. Cwd=/home/tersius/src/lambda-main, CodeUri=dist/
Resolved absolute path to code is /home/tersius/src/lambda-main/dist
Code /home/tersius/src/lambda-main/dist is not a zip/jar file
Skipping building an image since no layers were defined

Fetching lambci/lambda:nodejs10.x Docker container image......
Mounting /home/tersius/src/lambda-main/dist as /var/task:ro,delegated inside runtime container
Starting a timer for 300 seconds for function 'RestEntry'
2019-09-12T02:07:32.737Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token { in JSON at position 1","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token { in JSON at position 1","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:36:30)","    at Module._compile (internal/modules/cjs/loader.js:776:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 0.00 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 59 MB	
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Unexpected token { in JSON at position 1"
}
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: 
2019-09-12 14:07:33 127.0.0.1 - - [12/Sep/2019 14:07:33] "GET /api/nodemaster/list HTTP/1.1" 502 -

```

**Comment by jfuss** [comment]
@ktersius Can you provided a template to allow us to repro? It hard to tell what the issue is here without more information.

At first glance, this seems like it could be the same as #1386 but hard to tell without a template and repro-ing.

**Comment by ktersius** [comment]
@jfuss Sure here it is. https://gist.github.com/ktersius/bef929d958e81b337ebef3c59d067fa7#file-sam-template

**Comment by jfuss** [comment]
@ktersius I took the template and replaced all the `CodeUri` and `Handler` properties to be the directories of our `sam init --runtime nodejs10.x`. I was unable to repro though. So this could be something in your `--env-vars` file or the function code itself. The weird thing is that is works in 0.19. 0.21 has some refactoring done on start-api to allow for vanilla Api Gateway CloudFormation support and resolving intrinsics but with the current information, I can't pinpoint what is going on.

If you can share code and you env-vars files so that we could repro this completely? Otherwise it's hard to say way it works in 0.19 and not 0.21. If you can't share the these things in detail, can you provide a working example instead.

**Comment by ktersius** [comment]
@jfuss I've had some time to figure this out. It seems since 0.21 now has support for the Sub function we are actually getting a string back in the below environmental variable. But the parameter store resolution is not being done locally so we were trying to interpret this string as JSON which broke our app.

With version 0.19 Sub would just return a falsy empty value.

CONFIG_OVERRIDES: !Sub '{{resolve:ssm:/ps-lambdas/${Stage}/CONFIG_OVERRIDES:${ConfigOverridesVersion}}}'
