### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - {shap==0.30.1(wheel)}

### ISSUE THREAD

**Issue by AbhinavMudgal** [awslabs/aws-sam-cli#1422]
HI ,
SAM BUILD 
is giving this error 
for library shap in requirements.txt.
Please help me build this .

**Comment by TheSriram** [comment]
Have you tried running with `sam build --use-container`. Its probable that particular dependency has C bindings.

Update: just tried `sam build --use-container` , specifying that dependency and it worked.

**Comment by AbhinavMudgal** [comment]
Thank you

**Comment by Rubyj** [comment]
@AbhinavMudgal I have a dependency which fails to build. It has C bindings and whl. I am unable to build with `--use-container` any thoughts?

**Comment by aaronlelevier** [comment]
I tried this, but it also failed. I got:

```
Build Failed
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
Error: PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/requirements.txt'
```

**Comment by deanrabinowitz4** [comment]
> @AbhinavMudgal I have a dependency which fails to build. It has C bindings and whl. I am unable to build with `--use-container` any thoughts?

I also have dependencies with C bindings that fail when building with `--use-container`. Some:
psycopg2
pyorc

Did you figure out any workarounds?

I've seen the suggestions in [this issue](https://github.com/awslabs/aws-sam-cli/issues/1577) to "manually build it and vendor the dependency directly or place it in a layer that you can use." When I created a layer and added it as a property under my function (and removed the package from my requirements.txt) I was able to build, but the package was not included in the resulting build.

**Comment by Rubyj** [comment]
Try updating wheel

**Comment by deanrabinowitz4** [comment]
@Rubyj no luck.
