### ISSUE TITLE
Error: no such option: --profile

### ISSUE THREAD

**Issue by emayssat** [awslabs/aws-sam-cli#1435]
### Description

--profile option does not seem to be supported

### Steps to reproduce

sam --debug --profile 2842-emayssat@vmware.com --region us-east-1 local invoke function HelloWorldFunction --event /home/vagrant/cct/myCloud/aws/bin/sam/apps/hello-sam/events/event.json
Usage: sam [OPTIONS] COMMAND [ARGS]...
Try "sam --help" for help.

Error: no such option: --profile

### Expected result

No error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu xenial
2. `sam --version`: SAM CLI, version 0.22.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@emayssat `--profile` is not an option on the `sam` command. You need to place this option after `sam local invoke`

**Comment by jfuss** [comment]
Closing as there has been no response.
