### ISSUE TITLE
while running sam build I am getting error on Java 8 hello world project example

### ISSUE THREAD

**Issue by abhinav-jain09** [awslabs/aws-sam-cli#1445]
### Description

Briefly describe the bug you are facing.

### Steps to reproduce

sam init --java then run sam build 
### Observed result

Please provide command output with `--debug` flag set.

### Expected result

sam build should work as expected 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:Mac 
2. `sam --version`: 0.22.0

`Add --debug flag to command you are running`

```amskel:sam-app abhinav$ sam build
 Template file not found at /Users/abhinav/Documents/ns-docs/sam-java/sam-app/HelloWorldFunction/template.yml
```

**Comment by jfuss** [comment]
You are running the `sam build` command within a folder that does not have a template. The `template.yaml` file is within the `sam-app` dir.

Closing
