### ISSUE TITLE
Error after sam cli 1 update Error: [InvalidResourceException('ServerlessApi', 'property Fn::Transform not defined for resource of type AWS::Serverless::Api')] ('ServerlessApi', 'property Fn::Transform not defined for resource of type AWS::Serverless::Api')

### ISSUE THREAD

**Issue by dgoodworth** [awslabs/aws-sam-cli#1449]
It's not clear to me whether my issue is related to #1198 and #1330. They are similar, but not exact.

### Description

After update to aws cli on 0/7/2019, previously working sam templates no longer work (in Cloud9 environment). 
Receiving error when attempting to test/run:
InvalidResourceException on ServerlessApi RE: property Fn::Transform 

### Steps to reproduce

In Cloud9, build nodejs-based project. 
Use template.yaml that includes the following :
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Timeout: 180

Parameters:
  ENV:
    Type: String
    Default: dev
  SUFFIX:
    Type: String
    Default: ""

Resources:

  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref "ENV"
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location: auth-include.yaml # intrinsic functions do not work here
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: api-swagger.yaml

### Observed result

No command line execution - is via Cloud9 Run -> Local Run:
Error: [InvalidResourceException('ServerlessApi', 'property Fn::Transform not defined for resource of type AWS::Serverless::Api')] ('ServerlessApi', 'property Fn::Transform not defined for resource of type AWS::Serverless::Api')

### Expected result

Run would initiate Lambda and run code.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  Linux/4.14.133-88.112.amzn1.x86_64
2. `sam --version`: SAM CLI, version 0.8.0
aws --version:
aws-cli/1.16.212 Python/2.7.16 Linux/4.14.133-88.112.amzn1.x86_64 botocore/1.12.202

**Comment by TheSriram** [comment]
your sam cli version is old. could you upgrade to the latest and try testing this again?

**Comment by sriram-mv** [comment]
Closing issue, Please update to the latest and retry.

**Comment by omijh** [comment]
Not an issue with `sam deploy` but still raises an error with `sam validate` on `sam --version 1.53.0`
```
(base) ➜  aws git:(master) ✗ sam --version
SAM CLI, version 1.53.0
(base) ➜  aws git:(master) ✗ sam validate
2022-07-06 13:20:35 Loading policies from IAM...
2022-07-06 13:20:37 Finished loading policies from IAM.
2022-07-06 13:20:38 Requesting to create CFN template arn:aws:serverlessrepo:xxx:xxx:applications/aws-lambda-powertools-python-layer/1.7.0 in serverless application repo...
2022-07-06 13:20:39 Requested to create CFN template arn:aws:serverlessrepo:xxx:xxx:applications/aws-lambda-powertools-python-layer/1.7.0 in serverless application repo.
Template provided at 'xxx/aws/template.yaml' was invalid SAM Template.
Error: [InvalidResourceException('StateMachineCWSchedule', 'property Fn::Transform not defined for resource of type Schedule')] ('StateMachineCWSchedule', 'property Fn::Transform not defined for resource of type Schedule')
```
> Note: xxx is just redacted info
