### ISSUE TITLE
appsync locally test and deploy 

### ISSUE THREAD

**Issue by alejandrocorrea** [awslabs/aws-sam-cli#1459]
I do a scanning process in AppSync, and I need to test different data sources, with a high level of complexity, but amplify limits the range of action, since we are not interested in testing from the client, only the work for which AppSync has been created.
and, sometimes, you only need a space where you can with multiple simulated data sources, tested new things, without the need to do it directly in the cloud, to perform more precise tests, in exploration processes and definition of new processes. useful if Sam allows you to do this locally, and if it already exists, could you tell me how you could do it?

**Comment by TheSriram** [comment]
Can you elaborate a bit more on this usecase? Do you want appsync locally?

**Comment by jfuss** [comment]
@alejandrocorrea We do not have Appsync support today. We already have an open request for this: #551 

Closing as a duplicate
