### ISSUE TITLE
Expose multiple ports through --debug-port when start lambda in debug mode

### ISSUE THREAD

**Issue by sdubov** [awslabs/aws-sam-cli#1463]
### Describe your idea/feature/enhancement
I would like to have multiple debug ports to be exposed on start lambda in debug mode.
JetBrains Rider IDE debugger requires two ports to be exposed to work properly (the process set up two sockets). We would like to have an option to start dotnet core docker container with multiple ports available.

### Proposal
It would be great to be able to specify a multiple coma-separated ports in `--debug-port` option, e.g. `--debug-port 5600, 5601`.

Add details of how to add this to the product.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
No.

### Additional Details
None.

**Comment by TheSriram** [comment]
Hey! @sdubov . Opening multiple ports makes sense :+1: and as long as its done with no breaking changes. Could you submit a proposal with design based on [design tempalte](https://github.com/awslabs/aws-sam-cli/blob/develop/designs/_template.md)

**Comment by sdubov** [comment]
Hi, @TheSriram. Thank you for checking. I'll do a PR tomorrow if you don't mind (have a working prototype already). No breaking changes here.

**Comment by sriram-mv** [comment]
Closing issue, since the underlying PR is merged.
