### ISSUE TITLE
sam invoke not working for java8. Getting class not found exception!

### ISSUE THREAD

**Issue by debabratapatra** [awslabs/aws-sam-cli#1466]
I am getting Class not found exception while running sam invoke. 

I ran below commands.

`sam init --runtime java8`
`cd sam-app`
`sam build`
`sam local invoke "HelloWorldFunction" -e test.json`

I got below error.

![image](https://user-images.githubusercontent.com/5602062/66904443-b7380680-f021-11e9-99ae-3840fbfba7cd.png)

I am using window 7 OS.  Please let me know if I am missing something.

Thanks in advance!

**Comment by jfuss** [comment]
See #1436. This is a docker problem.

**Comment by debabratapatra** [comment]
Thanks.

**Comment by shearn89** [comment]
Huh - looks like removing the `-t template.yaml` argument changed the error and it looks like it's running okay (or at least failing elsewhere).

**Comment by macaranduba** [comment]
Had this problem with maven and only when running remotely on AWS and thanks to https://youtu.be/Q14uFOshVa8?t=165 all it took to work was to run `mvn clean package` before sam build and change the CodeUril of the sam template to 
`CodeUri: HelloWorldFunction/target/HelloWorld-1.0.jar`
Still, does not fill right that we have to do this extra steps that could be done by generic sam cli calls.
