### ISSUE TITLE
Sam local invoke not finding @ modules from lambda layer from SAR

### ISSUE THREAD

**Issue by gallor** [awslabs/aws-sam-cli#1489]
### Description

Slightly related to #1187 but for NodeJs. The issue is not that `local invoke` won't run but that the lambda invoked can't find any modules that are namespaced with an `@` symbol within the modules. If I deploy this to AWS the lambda works fine and finds all the modules included in the layer.
Important point to make, my layer deployed to SAR is a separate template/repo than the consuming stack. Don't know if that makes a difference but every example I've found so far to use layers always includes the creation inside the consuming stack.

### Steps to reproduce
The layer template.yaml
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda layer to house all shared code with backend apps

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'serverless-shared-node-modules-dev'
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs8.10
        - nodejs10.x
      RetentionPolicy: Retain

Metadata:
  AWS::ServerlessRepo::Application:
    Name: serverless-shared-node-modules-dev
    Description: >
      Lambda layer to house all Node-based shared code with backend/serverless apps
    Author: Grant
    SemanticVersion: 1.0.0
    ReadmeUrl: README.md
```
My folder structure for this layer
package.json (contains script to publish the layer)
README.md
template.yaml
nodejs
    -- node_modules
    -- package.json (contains `@hapi/joi` and `uuid` as dependencies)

A sample of the consuming layer's template (it's quite large)
```
Globals:
  Function
  RunTime: nodejs8.10
  Layers:
    - !GetAtt NodeModulesLayer.Outputs.LayerVersion

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: 'arn:aws:serverlessrepo:us-east-1:<accountId>:applications/serverless-shared-node-modules-dev'
        SemanticVersion: 1.0.0
  
    TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      CodeUri: ./
```

Within this test.js file:
```
const Joi = require('@hapi/joi');
const uuidv4 = require('uuid/v4');

exports.handler = () => {
  console.log('This is great');
}
```
Publish the layer to SAR.

Run the TestFunction with sam local invoke:
`sam local invoke -e test-event.json TestFunction` or `sam local invoke -e test-event.json TestFunction -d 5858`

I didn't include the test-event.json since it doesn't matter for this bug, considering it never gets to the handler.
 
### Observed result
I get the following output:
```
 sam local invoke -e test-event.json TestFunction
2019-10-29 16:29:52 Found credentials in shared credentials file: ~/.aws/credentials
2019-10-29 16:29:52 {'ResponseMetadata': {'RequestId': '<id>', 'HTTPStatusCode': 201, 'HTTPHeaders': {'date': 'Tue, 29 Oct 2019 21:29:53 GMT', 'content-type': 'application/json', 'content-length': '1657', 'connection': 'keep-alive', 'x-amzn-requestid': '<id>', 'x-amz-apigw-id': '<id>', 'x-amzn-trace-id': '<id>'}, 'RetryAttempts': 0}, 'ApplicationId': 'arn:aws:serverlessrepo:us-east-1:<accountId>:applications/serverless-shared-node-modules-dev', 'CreationTime': '2019-10-29T21:29:53.316Z', 'ExpirationTime': '2019-10-30T03:29:53.316Z', 'SemanticVersion': '1.0.0', 'Status': 'PREPARING', 'TemplateId': '<templateId>', 'TemplateUrl': '<templateUrl>'}
Invoking back-channel/index.dataHandler (nodejs8.10)
2019-10-29 16:29:53 Found credentials in shared credentials file: ~/.aws/credentials

Fetching lambci/lambda:nodejs8.10 Docker container image......
Mounting <project path> as /var/task:ro,delegated inside runtime container
START RequestId: ca1fffae-7d4b-1687-b8c3-5f3de9ef1053 Version: $LATEST
Unable to import module 'test': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/test.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
END RequestId: c67c6e8d-1994-1858-535d-d3bb0405eef7
REPORT RequestId: c67c6e8d-1994-1858-535d-d3bb0405eef7  Duration: 5386.11 ms    Billed Duration: 5400 ms        Memory Size: 384 MB     Max Memory Used: 36 MB

{"errorMessage":"Cannot find module '@hapi/joi'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)","Object.<anonymous> (/var/task/test.js:1:75)","Module._compile (module.js:652:30)","Object.Module._extensions..js (module.js:663:10)","Module.load (module.js:565:32)","tryModuleLoad (module.js:505:12)","Function.Module._load (module.js:497:3)"]}
```

If you comment out the `@hapi/joi` and only import `uuid` for instance the handler invokes fine:

### Expected result
All modules should be found, including namespaced modules (`@` packages).

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

- OS: Mac 10.14.6
- shell: bash v 5.0.11
- SAM cli v 0.23.0

**Comment by sanathkr** [comment]
I don't think we support referencing the Layer this way. For local invoke, we only support pulling down a cloud layer (specified with ARN) or a local layer referred by !Ref or !GetAtt of AWS::Lambda::LayerVersion resource.

To support your usecase, SAM CLI needs to first deploy the `Serverless::Application` resource to the cloud, identify the layer version ARN, and pull it down. On `sam local invoke`, we try to not deploy a resource in order to invoke locally.

Does this make sense?

**Comment by gallor** [comment]
Hi @sanathkr.
Whoops. I see my error and why I was confused by your answer. The original template was not supposed to have a !Sub for the layer for the LayerName (that was a copy paste error on my part related to my linked issue not supporting !Sub). Just assume that is a static pointer to the actual layer named already deployed to SAR. 

But to your point though, why can't !Sub just do a string substitution locally and then look if that package is deployed? Why is deploying a necessity? Just check if it's there and if not throw an error? !Sub would be REALLY helpful since directly referencing does not allow for environment parameterizing for multiple env deployments. I actually created a separate ticket for that but some reason it was moved out of aws-sam-cli (have no idea why): https://github.com/awslabs/aws-serverlessrepo-python/issues/32

The point of this ticket though is that invoking locally blows up if you include a namespaced node package, including popular packages like `@hapi`, `@babel` etc.  Sorry for the red herring with the template error. Thanks

**Comment by jfuss** [comment]
@gallor 

> Whoops. I see my error and why I was confused by your answer. The original template was not supposed to have a !Sub for the layer for the LayerName (that was a copy paste error on my part related to my linked issue not supporting !Sub). Just assume that is a static pointer to the actual layer named already deployed to SAR.

If it is a static Arn, they SAM CLI will pull this down for you if you provide credentials to the command (and the region where the layer exists).

> But to your point though, why can't !Sub just do a string substitution locally and then look if that package is deployed? Why is deploying a necessity? 

Your layer is within a SAR app. So unless that app is deployed the layer does not exist for us to pull down.

> I actually created a separate ticket for that but some reason it was moved out of aws-sam-cli (have no idea why): awslabs/aws-serverlessrepo-python#32

SAR does not accept the template because a property is invalid: "Invalid type for parameter Name, value: OrderedDict([('Fn::Sub', 'serverless-shared-node-modules-${DeploymentEnvironment}-ga892')]), type: <class 'collections.OrderedDict'>, valid types: <class 'str'>". This was transferred to that repo because that is the SAR python library we use and it should be catching these errors and providing a better explanation of the issue.

**Comment by gallor** [comment]
@jfuss Thanks for the clarification on the ticket being moved to that repo. Makes more sense. 

But back to the point to the this original ticket, `@` modules can't be found when invoking locally. This breaks any ability to test locally with layers as the trend in npm is start namespacing the modules. Would this be the right repo for this ticket or would the `serverlessrepo-python` also be more appropriate?

**Comment by jfuss** [comment]
@gallor 

> Would this be the right repo for this ticket or would the serverlessrepo-python also be more appropriate?

Yes this is the right repo.

> But back to the point to the this original ticket, @ modules can't be found when invoking locally. This breaks any ability to test locally with layers as the trend in npm is start namespacing the modules. 

I am confused now on what this issue still is. I think we have described how to make this work and why. Is there something more I can clarify? Have you tried the suggestions from above?

**Comment by gallor** [comment]
@jfuss Ha, now I'm confused :-) Sorry about that. 

I think I see my original error beside the typo of leaving the `!Sub` in the lambda template. The ApplicationId has a <accountId> in there. I didn't want to create an issue with my actual accountId. Should have just made up a number. My bad. 
So say my layer arn is `ApplicationId: 'arn:aws:serverlessrepo:us-east-1:123456789:applications/serverless-shared-node-modules-dev'`

Here's the main issue to try and clarify: I created a layer and have deployed it to the SAR. This layer only holds shared npm modules (ie. aws-sdk, lodash). I can invoke locally and it finds and fetches the layer. If I try to require an npm package from that layer that has a `@` at the beginning of the npm name (see the test.js file example above) the sam invoke local blows up saying it can't find the module. If I remove all requires to packages that have an `@` symbol, it executes fine. 

So this issue is not about pulling down the layer, or finding it or publishing it. It's that `@` packages can't be found within the layer when invoking locally. Sorry for the confusion on that and getting off topic. I hope this was able to clarify, and if not let me know.

**Comment by jfuss** [comment]
@gallor 

> So say my layer arn is ApplicationId: 'arn:aws:serverlessrepo:us-east-1:123456789:applications/serverless-shared-node-modules-dev'

That is not a layer are, that is for a SAR application, but sounds like you have it being downloaded so probably a copy paste error.

> I can invoke locally and it finds and fetches the layer. If I try to require an npm package from that layer that has a @ at the beginning of the npm name (see the test.js file example above) the sam invoke local blows up saying it can't find the module. If I remove all requires to packages that have an @ symbol, it executes fine.

Since the layer is getting downloaded, this sounds like an issue with your layer. Your layer needs to be in a specific structure or it will not get picked up by default: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path. You can also follow https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-layers.html to be able to log into the docker image that is created with your layer. You can then inspect the image.

**Comment by gallor** [comment]
Ok.... first off, thanks for everyone's patience with me. First time working with layers so I apologize if I'm just not thinking through things correctly. 

So I'm now more confused because what I'm getting is contrary to the docs you linked to. 
> That is not a layer are, that is for a SAR application, but sounds like you have it being downloaded so probably a copy paste error.
Correct, that's not the layer ARN, that's the ApplicationId using the Application Location Object the AWS::Serverless::Application fetches. I'm then referencing that within my globals section to resolve the ARN (see above template for more):
```
Globals
  Function:
    Layers:
      - !GetAtt NodeModulesLayer.Outputs.LayerVersion
```
> Your layer needs to be in a specific structure or it will not get picked up by default:
You got it. The layer follows that structure outlined per the doc linked. (see original post for the outline)

I then tried to follow the instructions in the second link you provided to inspect the layer and got stuck. Nothing is loaded nor cached as a docker image, nor is it inspectable. All my images printed by `docker image ls` only references `lambci/lambda` repository. I have no reference to a 'samcli/lambda' repository nor is there anything inside my ~/.aws-cli/layers-pkg (the default docker cache location. There's not even the `layers-pkg` folder). I'm wondering if this is because I'm not using a layer created within the same template but an external SAR.

The kicker is I know I'm getting my layer because I deleted all of my local node_modules, ran the following code as the sam local invoke lambda:
```
// const joi = require('@hapi/joi');
// console.log('got joi', joi);
const uuidv4 = require('uuid/v4');
console.log('got uuid', uuidv4);

exports.handler = () => {
  console.log('This is great');
}
```
And both consoles logged properly. Uncomment the top 2 lines, blows up and says can't find it. Deploy and view cloudwatch logs, both modules log being found properly.

I also tried logging into the most recent lambci/lambda images and couldn't find anything related to my lambda code... Any ideas on what I'm missing? Thanks.

**Comment by jfuss** [comment]
@gallor Ok let's back up a bit. 

```
Globals
  Function:
    Layers:
      - !GetAtt NodeModulesLayer.Outputs.LayerVersion
```

This will not work locally. We do not have a way (locally) to get a Layer from another stack or the `AWS::Serverless::Application` resource. You need to provide the Layer Arn statically or compose it with `!Sub` in a manner that we can compose the arn.

One way to do this is to deploy the resource to an put the Arn directly in the template or pass it into the template by a Paramater. You could also move the Layer Resource into the same stack and !Ref that Layer resource (assuming the Layer resource points to the code locally).

By your latest comment, It sounds like the layer was never getting downloaded, probably because we could resolve the !GetAtt.

Does this help?

**Comment by gallor** [comment]
@jfuss 
>One way to do this is to deploy the resource to an put the Arn directly in the template or pass it into the template by a Paramater. 

Isn't that what I'm doing here? Wouldn't this be able to get the ARN to enable the GetAtt resolve? If this is not supported how am I able to get my SAR layer and resolving the npm modules within it?
```
Globals
  Function:
    Layers:
      - !GetAtt NodeModulesLayer.Outputs.LayerVersion
Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::Application
    Properties:
       Location:
         ApplicationId: arn:aws:serverlessrepo:us-east-1:111111111111:applications/serverless-shared-node-modules-dev
         SemanticVersion: 1.0.0
```
(As a side note, using !Ref doesn't work for the `ApplicationId` when trying to resolve a parameter locally. When I tried a different function the error logging said only !Ref and !FindInMap were supported, but it still fails when using !Ref. Only a statically typed ARN works)

>You could also move the Layer Resource into the same stack and !Ref that Layer resource (assuming the Layer resource points to the code locally).

Meaning instead of deploying the layer to the SAR as a separate repo? If so that defeats the whole purpose of doing the layer for us as we're trying to deploy a single helper library that multiple stacks can pull from (and also reduce the amount of data we have to upload/deploy each time we test out something). Thanks again for all the help and continued clarifications.

**Comment by jfuss** [comment]
@gallor Technically, yes that is what you are doing that but again that will not work locally. We do not have a way to lookup that stack/SAR app and therefore cannot get the layer nested within that application. Which brings us back to the solutions I proposed to allow this to work locally.

**Comment by gallor** [comment]
@jfuss Ahhh. I gotcha. Thanks for the clarification 👍. Sorry for the confusion on my part then. 

Is it just a happy accident then that somehow the layer is getting fetched and I'm able to use modules contained in that layer?

**Comment by jfuss** [comment]
@gallor 
| Is it just a happy accident then that somehow the layer is getting fetched and I'm able to use modules contained in that layer?

If you are talking about when run on Lambda Service, then that is completely different than locally. What indicates this was fetched during invoke locally?

**Comment by gallor** [comment]
So, my comment was regarding locally, and what made me think that the SAR was being fetched locally was a log line in the `ResponseMetada` that referenced the SAR's applicationId. Within my test lambda I was requiring `uuid` or `lodash`, which resolved fine. But when I tried to import any other module that is supposed to be in the SAR it would say they couldn't be found. I'm wondering if somehow the Docker container used to run it locally has some helper modules and that's what my test was picking up, not the actual SAR. Anyway, thanks @jfuss for the help. Really appreciate it.

**Comment by sanathkr** [comment]
Awesome. @gallor glad you got this figured out. I am going to close this for now because we don't have any specific next steps

**Comment by CJohnsonLehi** [comment]
I encountered this same problem, but with a python lambda function. I was encountering the exact same problem. 
So I spun up the docker image and connected via a bash terminal.
What I found was that the lambda zip file was indeed copied to the /opt directory, but that it was NOT unzipped.
Hence the failure.
