### ISSUE TITLE
pathParameter in in the resource string?

### ISSUE THREAD

**Issue by CodeVelo** [awslabs/aws-sam-cli#149]
I think I'm seeing a discrepancy between the request object using sam and the API Gateway. 

On my local machine I have a Java class that implements RequestStreamHandler. When I write out the inputStream I receive this:

`"httpMethod":"GET","resource":"/programs/1","pathParameters":{"program_id":"1"}`

However, when looking at the same request on the API Gateway I see this:

`endpoint request body after transformations: {"resource":"/programs/{program_id}","path":"/programs/1","httpMethod":"GET","pathParameters":{"program_id":"1"}`

Should the resource string contain the value of the pathParameter or the name of the pathParameter?

**Comment by CodeVelo** [comment]
I tested this out using node.js as well. It looks like the same issue happens with that runtime.

[api-gateway.txt](https://github.com/awslabs/aws-sam-local/files/1342512/api-gateway.txt)
[sam.txt](https://github.com/awslabs/aws-sam-local/files/1342513/sam.txt)

**Comment by resios** [comment]
I'm not sure what the right behavior is, but the missing name of the pathParameter can be explained by the lack of Swagger support in the CLI.

**Comment by lucasortigoso** [comment]
Same problem here! I need the parameter name but the value is returned. API Gateway works well with parameter name.

Path and Resource are equals on SAM local. Take a look:
![image](https://user-images.githubusercontent.com/14048944/31312934-6430f5d8-aba8-11e7-9d30-d08ec4a8af37.png)

**Comment by xkguq007** [comment]
Same problem here!! any proceed?

**Comment by sanathkr** [comment]
Can you try the latest release - https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0? I believe this is fixed. Feel free to re-open Issue if not.
