### ISSUE TITLE
Slack Invite Link Expired

### ISSUE THREAD

**Issue by r0zar** [awslabs/aws-sam-cli#1497]
### Description

I wasn't able to join the SAM slack channel.

### Steps to reproduce

Click the link at the bottom of the readme.

### Observed result

Expired link

### Expected result

Welcome to Slack.

**Comment by 53ningen** [comment]
I found similar issue on [serverless-application-repository](https://github.com/awslabs/serverless-application-model/pull/1177/files) and I make a pull request for fix this

**Comment by awood45** [comment]
Merged the PR fix, thanks @53ningen

**Comment by PrakashGoulla** [comment]
@awood45 Looks like the invite has expired again. Can you please check?
