### ISSUE TITLE
Unable to perform sam build OSX 10.14.6 && RHEL 7.7

### ISSUE THREAD

**Issue by anash28** [awslabs/aws-sam-cli#1513]
### Description

I am trying to convert Python 2.7 Lambda to using a Python 3.x runtime within MacOSX and RHEL 7 Linux environments and ran into several issues as follows: 

### Steps to reproduce
sam build --template template.yaml --user-container 
Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt

### Expected result
Sample hello-world docker container running to demo `sam invoke` to team members  
Upon successful completion of invoke demo, we planned to use our actual newly converted Python 3.7 Lambda code. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOSX 10.14.7 && RHEL 7.7
2. `sam --version`: 
SAM CLI, version 0.31.0
3. `aws --version`:
aws-cli/1.16.247 Python/3.7.3 Darwin/18.7.0 botocore/1.12.237
4. `pip --version`
pip 19.2.3 from /Users/<username>/.local/lib/python3.7/site-packages/pip (python 3.7)
5. `pip3 --version`
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by sanathkr** [comment]
Few questions:
- Do you have requirements.txt in the root of your Lambda function?
- Is Docker file sharing working fine? ie. Can you run ` docker run -i -v `pwd`:/tmp/foo alpine ls /tmp/foo`? It should give you a `ls` of files in the current working directory

**Comment by include** [comment]
Hi,

I have a similar problem.

### Steps to reproduce:

    brew update && brew install python@3.8
    echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc
    source ~/.zshrc

    python3.8 -m venv .python3.8
    echo 'source .python3.8/bin/activate' >> .env
    source .env
    pip install --upgrade pip
    pip install -r aws-sam-cli

    mkdir /tmp/foo ; cd /tmp/foo
    sam init --name sam-app --runtime python3.8 --app-template hello-world
    sam build --use-container

```
Starting Build inside a container
Building resource 'RegisterFunction'

Fetching lambci/lambda:build-python3.8 Docker container image.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Mounting /temp/foo/sam-app/hello-world as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - [Errno 1] Operation not permitted: '/tmp/samcli/source/requirements.txt'
```

### Additional environment details

```
sam --version
SAM CLI, version 0.40.0
aws --version
aws-cli/1.17.0 Python/3.8.1 Darwin/19.2.0 botocore/1.14.0
pip --version
pip 19.3.1 from /tmp/foo/.python3.8/lib/python3.8/site-packages/pip (python 3.8)

**Comment by anash28** [comment]
@sanathkr Sorry for the delayed response. I have upgrades `samcli` since posting this inquiry. Give me sometime to retest with the requirements.txt file inclusion within my Lambda(s)

**Comment by sriram-mv** [comment]
@anash28 How did the testing go? I'm going to close this issue, but feel free to re-open it if you are still facing these problems.
