### ISSUE TITLE
sam build can't resolve dependencies

### ISSUE THREAD

**Issue by elliottye** [awslabs/aws-sam-cli#1522]
Hi,

I was trying to deploy a SAM app but stopped at `sam build` with these two dependencies being unable to be resolved: `jieba` and `regex`. Here's the error emitted from commandline:

```Building resource 'HelloWorldFunction'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - {regex==2019.11.1(sdist), jieba==0.39(sdist)}
```

Should I build them with `--use-container` option?

**Comment by jfuss** [comment]
@elliottye 

> Should I build them with --use-container option?

That would be the first thing to try.

Anytime we cannot build a dependency locally, using `--use-container` will be the way forward. This is especially true for dependencies that are written in C (which regex is not sure about jieba). 

Closing as the question has been answered.
