### ISSUE TITLE
SAM CLI now collects telemetry, this should be OPT IN not OPT OUT

### ISSUE THREAD

**Issue by stojanovic** [awslabs/aws-sam-cli#1525]
**Description:**
SAM CLI now collects telemetry, which is ok, but it should be OPT IN, not OPT OUT.

**Steps to reproduce the issue:**
1. Update SAM CLI to the latest version (I have SAM CLI version 0.31.0).
2. Run any SAM command, i.e., `sam local`.
3. See the yellow message at the beginning of the SAM CLI command response.

**Observed result:**
```
SAM CLI now collects telemetry to better understand customer needs.

You can OPT OUT and disable telemetry collection by setting the
environment variable SAM_CLI_TELEMETRY=0 in your shell.
Thanks for your help!

Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
```

**Expected result:**
Telemetry should be OPT IN, not OPT OUT.

**Comment by keetonian** [comment]
Transferred to the correct repository.

**Comment by jfuss** [comment]
Thank you for the input on the opt-out vs. opt in experience. 
The AWS SAM CLI collects telemetry, such as generic usage metrics and errors. The AWS SAM CLI does not collect personal information, such as usernames or email addresses. It also does not extract sensitive project-level information. 
Telemetry is additional information that helps us to better understand our customers’ needs, diagnose issues, and deliver features that improve the customer experience. 
Happy to connect on a call if you have further questions. 

For details of the types of telemetry collected, see [Types of Information Collected](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html#serverless-sam-telemtry-data-collected).

**Comment by jghaines** [comment]
Has this approach between checked against the EU GDPR and the Australian Privacy Act?

**Comment by yasuoiwakura** [comment]
It is absolutely scandalous and hilarious I need to set Operating-System Level System Variables for ALL Shells (cmd, PS, git bash, wsl bash) just to opt out from Spyware!

This is btw. how the Microsoft Era slowly but steadily ended itself.
