### ISSUE TITLE
sam init --runtime python3.8 returns invalid choice: python3.8

### ISSUE THREAD

**Issue by andriihorpenko** [awslabs/aws-sam-cli#1548]
### Description

I can't create a new project with python3.8 as a runtime. If I change the existing project from python3.7 to python3.8 SAM complains that this runtime is not supported.

### Steps to reproduce

Install latest SAM CLI (0.31.1) and try initializing a project with sam init --runtime python3.8

### Observed result

Error: Invalid value for "-r" / "--runtime": invalid choice: python3.8. (choose from nodejs8.10, ruby2.5, dotnetcore2.0, dotnetcore1.0, go1.x, nodejs6.10, java8, python2.7, python3.7, dotnetcore2.1, python3.6, nodejs10.x)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 0.31.1

**Comment by jfuss** [comment]
All new runtimes (including Python3.8) are being introduced in #1549

**Comment by jfuss** [comment]
This was just released with [v0.32.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.32.0).

Closing.
