### ISSUE TITLE
Can't reference environment variables in a file if access outside handler

### ISSUE THREAD

**Issue by joxtoyod** [awslabs/aws-sam-cli#1553]
I wanted to override the variables in my template.yaml 
`env.json`
```
 {
    "MyLambdaFunction": {
        "DB_HOST": "localhost",
        "USERNAME" : "user",
        "PASSWORD": "Password",
        "DB_NAME": "testdb" 
    }
}
       
```
`app.py`
```
host  = os.environ['DB_HOST']
user =  os.environ['USERNAME']
pass =  os.environ['PASSWORD']
db_name =  os.environ['DB_NAME']

def lambda_handler(event, context):
       .....

```
I invoke it the method
```
sam local invoke MyLambdaFunction --event event.json --env-vars env.json
```

and I got a KeyError:
```
{"errorType":"KeyError","errorMessage":"'DB_HOST'"}
```

However, if I add those variables on template.yaml itself it works just fine. 
This also works if I access the variables inside the handler.

```
# can be invoked with --env-vars env.json
def lambda_handler(event, context):
  host  = os.environ['DB_HOST']
  user =  os.environ['USERNAME']
  pass =  os.environ['PASSWORD']
  db_name =  os.environ['DB_NAME']
       .....
```

is this an intended behavior? How can I override the variables?

**Comment by jfuss** [comment]
@joxtoyod Env Vars must be defined in the template.yaml's function configuration, otherwise there is nothing to override.

**Comment by joxtoyod** [comment]
thanks @jfuss ..  the workaround on my end is to add the variables as an empty string on my template.yaml file
