### ISSUE TITLE
Include support to Nodejs12.x on CLI build

### ISSUE THREAD

**Issue by possebom** [awslabs/aws-sam-cli#1564]
### Describe your idea/feature/enhancement

On 18th November 2019, AWS published they are now supporting Node.js 12.x runtime in AWS Lambda. However, AWS SAM CLI does support this runtime for building purposes.

Tested on AWS SAM CLI version:
`
⇒  sam --version
SAM CLI, version 0.31.1
` 

At this moment, the supported runtimes are:

- Python 2.7, 3.6, 3.7 using PIP

- Nodejs 10.x, 8.10, 6.10 using NPM

- Ruby 2.5 using Bundler

- Java 8 using Gradle

- Dotnetcore2.0 and 2.1 using Dotnet CLI (without --use-container flag)

### Proposal

Include the support to Node.js 12.x on the build command.

### Additional Details
Support Node.js 12.x Release Post: https://aws.amazon.com/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda/

**Comment by giles-jason** [comment]
I ran into similar issues today when attempting to test upgrading functions locally and the `start-api` and `invoke` commands fail for similar reasons. Also tested on version 0.31.1. I get the following error message:
```
ValueError: Unsupported Lambda runtime nodejs12.x
```

**Comment by jfuss** [comment]
It is in flight. Hang in there guys :) #1549

**Comment by jfuss** [comment]
Hot off the press. [v0.32.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.32.0) with Nodejs12.x support.

Closing

**Comment by 40x** [comment]
I am on version 0.38.0 and it does not show support for version 12. Am I looking at the wrong place?

![image](https://user-images.githubusercontent.com/10065828/71425828-2146da80-2667-11ea-99f7-4ac600260d1f.png)

**Comment by jfuss** [comment]
@40x Thanks for bringing this up. Looks like we forgot to update the help text but Node12 is supported and released.
