### ISSUE TITLE
Issue accessing S3 bucket from lambda when invoked through SAM LOCAL

### ISSUE THREAD

**Issue by kumarjak** [awslabs/aws-sam-cli#157]
We are using SAM LOCAL to invoke a lamdba which does read/write to S3 bucket. We are able to invoke the lambda but i am getting a timeout error when trying to access S3 bucket. As per the below error details, it looks like the HTTP endpoint is latching on to the port 443

Error Details: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to <bucketName>.s3.amazonaws.com:443 failed: connect timed out org.apache.http.conn.ConnectTimeoutException:

**Comment by PaulMaddox** [comment]
Hi @kumarjak. 

Have you customised the Docker network configuration at all? By default, docker containers should have access to the internet (and hence the AWS APIs) from your machine. 

It might be worth manually executing a shell in one of the Lambda runtime containers, so you can test/debug connectivity.

```bash
$ docker run -v $(pwd):/var/task -i -t --rm --entrypoint /bin/bash lambci/lambda:java8`
bash-4.2$ 
```

From there you can try using something like `curl -v ` to test connectivity.

Actually, on re-reading the above, it seems it's trying to connect to `.s3.amazonaws.com` which is an invalid hostname. It should be prefixed with a region, for example, `eu-west-1.s3.amazonaws.com`. Are you sure you're setting a region correctly in your code?

**Comment by royal409** [comment]
I verifed the hostname and it is prefixed with the region. I am running the docker container in windows machine. When i try to ping google.com from cmd, i am getting request timed out. I believe the docker container doesn't have access to internet.

**Comment by sanathkr** [comment]
Looks like a Docker configuration problem.
