### ISSUE TITLE
Unable to upload artifact ./target/referenced by CodeUri parameter of .... resource

### ISSUE THREAD

**Issue by ashishsoni** [awslabs/aws-sam-cli#1578]
When i have a local Jar url in the SAM Template YAML Code Build in the AWS fails with below error but it work when i test in local .

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/platform-api-1.0.jar
      Handler: com.nielsen.attr.platform.admin.handler.HelloWorldHandler::handleRequest
      Runtime: java8
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /client/{id}
            Method: get
            RestApiId:
              Ref: PlatformApi

ExportFailedError: Unable to upload artifact ./target/platform-api-1.0.jar referenced by CodeUri parameter of GetHelloWorld resource.
Parameter CodeUri of resource GetHelloWorld refers to a file or folder that does not exist /codebuild/output/src096336395/src/target/platform-api-1.0.jar

**Comment by c2tarun** [comment]
Hi @thanuj11  Your issue seem to be different than original issue. I create a new issue [1591](https://github.com/awslabs/aws-sam-cli/issues/1591) for this problem. I am closing this issue and will track your problem in the new one.

**Comment by rahulpopat** [comment]
> @jlhood Thanks a lot .. it is working both ways after removing those commands

Hi Ashish, can yo uplease tell me how did you fix this. I am stugging with same error for quite some time now and unable to fix it. I have similar buildspec file and sam template.yaml like yours. and getting same error. Appreciate your help.

**Comment by margadi** [comment]
The service role used for the AWS codebuild might not have permission to push artifacts to S3. Please choose the role and attach "Amazons3fullaccess" to them. That would work!!!
