### ISSUE TITLE
Failed to upload artifact on sam deploy.

### ISSUE THREAD

**Issue by c2tarun** [awslabs/aws-sam-cli#1591]
I am facing the same issue

sam build --use-container (is successful & working)
sam local invoke (works fine as expected)

But when I run sam package **sam package --template-file .\template.yaml --s3-bucket <bucket_name>**
it return the error below
**Error: Unable to upload artifact ./hello_world referenced by CodeUri parameter of HelloWorldFunction resource.**

My template.yaml file looks like this
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./hello_world
      Handler: app.lambda_handler
      Runtime: python3.6
      Layers:
        - !Ref MyLambdaLayer
I am giving the right local path to the CodeUri, but still it returns the error mentioned above.

Any comments or ideas to solve this issue.

_Originally posted by @thanuj11 in https://github.com/awslabs/aws-sam-cli/issues/1578#issuecomment-555130496_

**Comment by c2tarun** [comment]
Hi @thanuj11,

You might be overwriting the template file. Can you please modify your command to following:

### Package
`sam package --s3-bucket <bucket_name> --output-template-file packaged.yaml`
This will package your artifacts and upload them to your s3 bucket. Plus it'll also create a new `package.yaml` file with s3 bucket link.

### Deploy
`sam deploy --template-file packaged.yaml --stack-name <your stack name> --capabilities CAPABILITY_IAM`

Thanks
Tarun

**Comment by jfuss** [comment]
Similar to #1569 

Passing `--template-file` to the package command will force the cli to use that Template. To use the pre-built one from `sam build`, remove the `--template-file` option.

Closing as this is working as expected.

**Comment by andrewjhanlon-dmg** [comment]
Try this guys:
https://stackoverflow.com/a/74805210/18216765
