### ISSUE TITLE
Mount points are incorrectly written to console.

### ISSUE THREAD

**Issue by jarruda** [awslabs/aws-sam-cli#160]
When using `local start-api`, there's something in the template that will cause it to display the wrong functions to mount for the endpoints.  It will display the same mount point (randomly chosen, it seems) for all paths.

e.g.
```
Mounting index.deactivateBaz (nodejs6.10) at http://127.0.0.1:3000/foo/bar [GET]
Mounting index.deactivateBaz (nodejs6.10) at http://127.0.0.1:3000/foo/bar/{barId}/baz [POST]
Mounting index.deactivateBaz (nodejs6.10) at http://127.0.0.1:3000/foo/baz [GET]
Mounting index.deactivateBaz (nodejs6.10) at http://127.0.0.1:3000/foo/fizz [POST]
Mounting index.deactivateBaz (nodejs6.10) at http://127.0.0.1:3000/foo/baz/{bazId} [DELETE]
Mounting static files from public at /
```

I'm using an inline swagger definition in my template.  In the above example each method has a unique method.

**Comment by lucasortigoso** [comment]
The same occurs with java 8
![image](https://user-images.githubusercontent.com/14048944/31312950-1aa9f710-aba9-11e7-9750-c15ebd533b1d.png)

**Comment by sanathkr** [comment]
Can you try the latest release - https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0? I believe this is fixed. Feel free to re-open Issue if not.
