### ISSUE TITLE
Homebrew installation of SAM CLI succeeds, but will not run

### ISSUE THREAD

**Issue by if-jeremy** [awslabs/aws-sam-cli#1629]
### Description

Installed aws-sam-cli via Homebrew on MacOS Catalina.  Installation was successful, but the software will not execute, giving a ModuleNotFoundError for samcli

### Steps to reproduce

brew install aws-sam-cli
sam --version

### Observed result

$ sam --version
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/sam", line 7, in <module>
    from samcli.cli.main import cli
ModuleNotFoundError: No module named 'samcli'

Please provide command output with `--debug` flag set.

Same

### Expected result

SAM version output

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  MacOS Catalina
2. `sam --version`:  See above

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@if-jeremy It is resolving to a python interpreter that is not brew. Is `/usr/local/bin` in your path?

**Comment by if-jeremy** [comment]
It was, but it ended up there was another version of Python also in the path.  Once I removed that from the path, it began working.  Thanks for the pointer!
