### ISSUE TITLE
Global context is not preserved locally

### ISSUE THREAD

**Issue by cecotw** [awslabs/aws-sam-cli#1638]
### Description

Not sure if this is a bug, or a feature request, but global variables are reset when running sam local start-api on each subsequent invocation.

### Steps to reproduce

Declare a global variable.
Modify variable.
Run `sam local start-api`
Run multiple invocations and notice that the global variable always gets reset.

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

I would expect global variable context to be preserved.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOs
2. `sam --version`: 0.30.0

`Add --debug flag to command you are running`

**Comment by sanathkr** [comment]
This is not a bug, it's by design. Local invoke tears down the container and starts a new container. It mimics Lambda "cold starts" on every invoke.

#239 is a feature request to keep containers warm and thereby preserving global variables. Track the Issue for updates.
