### ISSUE TITLE
no_fail_on_empty_changeset in samconfig

### ISSUE THREAD

**Issue by plantusd** [awslabs/aws-sam-cli#1657]
Can I use  "no_fail_on_empty_changeset"  option in samconfig.toml somehow instead of inline flag? I couldn't achieve this with 
`no_fail_on_empty_changeset=true`
Thanks!

**Comment by jfuss** [comment]
@plantusd What version of SAM CLI are you running? My understanding is that should work.

**Comment by plantusd** [comment]
aws-sam-cli 0.37.0

![image](https://user-images.githubusercontent.com/44056339/70655179-78f54700-1c60-11ea-8e68-567b303780c6.png)

![image](https://user-images.githubusercontent.com/44056339/70655244-91fdf800-1c60-11ea-86ab-8e19e1f8274b.png)

**Comment by jfuss** [comment]
@plantusd I have a small hunch. Can you try doing `fail_on_empty_changeset=false` instead of `fail_on_empty_changeset=true`?

**Comment by plantusd** [comment]
thanks, it worked 
also quick question wanted to clarify, an option to specify which env to use in samconfig.toml ( e.g. `sam build --env dev`) is not implemented yet? Thanks a lot!

**Comment by plantusd** [comment]
noticed, if some option was declared twice in samconfig.toml, other options are ignored
for example
![image](https://user-images.githubusercontent.com/44056339/70663175-74388f00-1c70-11ea-9f60-4115c5ae880c.png)
path to the manifest is ignored, sam looks it up by the default path ("/project_name/requirements.txt")

**Comment by sriram-mv** [comment]
Closing this issue as original query has been answered.

Will create a new issue for the last comment.
