### ISSUE TITLE
Make sam deploy output more user-friendly

### ISSUE THREAD

**Issue by stojanovic** [awslabs/aws-sam-cli#1659]
### Describe your idea/feature/enhancement

The new `sam deploy` command is fantastic, but the output can be slightly more UX-friendly.
For example, the output is nicely formatted, but when I try the copy the URL, which is in the multiple lines, I get the URL with spaces.

Here's the screenshot of the action:
<img width="1014" alt="Screenshot_2019-12-11_at_14_38_04" src="https://user-images.githubusercontent.com/613478/70629087-a83c9180-1c29-11ea-8adc-f301644b1235.png">

Expected result of the copy action:
```bash
https://abcdefghij.execute-api.eu-central-1.amazonaws.com
```

Actual result:
```bash
https://abcdefghij.execute-api.eu-
                                                      central-1.amazonaws.com
```
or this, if the paste destination doesn't support new lines:
```bash
https://abcdefghij.execute-api.eu-                                                      central-1.amazonaws.com
```

It's even more confusing if I try to copy something with the long key. For example, if I try to copy the Arn from the previous screenshot, I'll get the "Arn" string in the middle of my actual Arn.

### Proposal

Not sure what's the best solution to this, but it would be much more useful if I can copy the output.

**Comment by TheSriram** [comment]
Thanks for the feedback! this is definitely on our mind to fix.

**Comment by rts-rob** [comment]
I would like to see this with a --output=json or similar flag to allow processing the output with jmespath or jq.

If appropriate I can file a separate issue for this, but to me they're related.
