### ISSUE TITLE
sam command doesn't work on Mac Catalina

### ISSUE THREAD

**Issue by Toady00** [awslabs/aws-sam-cli#1665]
### Description

Using a brand new work mac with catalina preinstalled, tried installing sam cli. Brew tap and install works as expected but trying to run the `sam` command results in a bash error. (Default shell for Catalina is zsh but I've followed apple's article to revert back to bash for the time being).

Similar to #1629 but not quite the same.

### Steps to reproduce

```
~ $ brew tap aws/tap
==> Tapping aws/tap
Cloning into '/usr/local/Homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Tapped 1 formula (41 files, 48.8KB).
~ $ brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.37.0//aws-sam-cli-0.37.0.sierra.bottle.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/92205085/f33f2d80-169a-11ea-80c0-5fe6a085
######################################################################## 100.0%
==> Pouring aws-sam-cli-0.37.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/aws-sam-cli/0.37.0: 3,980 files, 62.6MB
~ $ sam --version
-bash: aws-sam-local: command not found
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS Catalina
2. `sam --version`: 0.37.0 I'm guessing from the brew output

I went digging a little. The `sam` command is on my path, symlinked to the brew installed bin directory, which is symlinked to the libexec directory. That file explicitly uses a python interpreter that is packaged with the brew install. I've used that interpreter to get the version to verify that the interpreter is indeed working properly. I'm not a python developer and I'm not sure what the `load_entry_point` is doing or how that works so I stopped digging there.

```
~ $ which sam
/usr/local/bin/sam
~ $ readlink $(!!)
readlink $(which sam)
../Cellar/aws-sam-cli/0.37.0/bin/sam
~ $ ls -l /usr/local/Cellar/aws-sam-cli/0.37.0/bin/
total 0
lrwxr-xr-x  1 brandon  staff  18 Dec  4 15:43 sam -> ../libexec/bin/sam
~ $ ls -l /usr/local/Cellar/aws-sam-cli/0.37.0/libexec/bin/sam
-rwxr-xr-x  1 brandon  staff  431 Dec 15 00:32 /usr/local/Cellar/aws-sam-cli/0.37.0/libexec/bin/sam
~ $ cat !$
cat /usr/local/Cellar/aws-sam-cli/0.37.0/libexec/bin/sam
#!/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/bin/python3.7
# EASY-INSTALL-ENTRY-SCRIPT: 'aws-sam-cli==0.37.0','console_scripts','sam'
__requires__ = 'aws-sam-cli==0.37.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('aws-sam-cli==0.37.0', 'console_scripts', 'sam')()
    )
~ $ /usr/local/Cellar/aws-sam-cli/0.37.0/libexec/bin/python3.7 --version
```

**Comment by TheSriram** [comment]
The error 
```
-bash: aws-sam-local: command not found
``` 

is interesting, do you have the old sam cli that was published to npm also installed by any chance on your path?

Could you also try installing via pip to make sure this is an issue with the installation process with homebrew?

**Comment by Toady00** [comment]
No I don't have it installed any other way. This is a brand new Mac, I'm just now getting setup. What's the pip package name? aws-sam-cli? I can try later tonight and update.

**Comment by include** [comment]
Hi @Toady00 try this way (works for me)


    brew update && brew install python@3.8
    echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc
    source ~/.zshrc

    python3.8 -m venv .python3.8
    echo 'source .python3.8/bin/activate' >> .env
    source .env
    pip install --upgrade pip
    pip install aws-sam-cli awscli

    sam init --name sam-app --runtime python3.8 --app-template hello-world
    cd sam-app
    sam build

**Comment by sriram-mv** [comment]
Going to close the issue, feel free to re-open if you are still facing this issue.

**Comment by sahilgupta88** [comment]
@include 

> Hi @Toady00 try this way (works for me)
> 
> ```
> brew update && brew install python@3.8
> echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc
> source ~/.zshrc
> 
> python3.8 -m venv .python3.8
> echo 'source .python3.8/bin/activate' >> .env
> source .env
> pip install --upgrade pip
> pip install aws-sam-cli awscli
> 
> sam init --name sam-app --runtime python3.8 --app-template hello-world
> cd sam-app
> sam build
> ```
> 
> Cheers,
> F

Thanks @include your solution works for me on bash.
