### ISSUE TITLE
Document `sam build` steps

### ISSUE THREAD

**Issue by abiro** [awslabs/aws-sam-cli#1676]
Hi,

It would great if there was documentation on the steps taken by `sam build`. My concrete use case is that I'd like to know how it finds and installs packages for Python Lambda functions so I can figure out the best way to structure my project. More specifically, does it just do a `pip install -r` and copies the source files or does it build my package with `setuptools`? 

Thanks!

(Edited with more info.)

**Comment by jfuss** [comment]
@abiro The design for python builder lives here: https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/python_pip/DESIGN.md

The TLDR is; we check for requirements.txt in your CodeUri directory of the function, then call the language + dependency manager builder (in your case python_pip workflow), then move this artifacts into a known location (.aws-sam in your project directory).

**Comment by abiro** [comment]
Thanks, I think I have a better understanding of the build process now. Summarizing for posterity:

`sam build` performs the following steps to build a Python Lambda function:

1. Find the base directory of the function. By default this is the same directory as the location of the `template.yml` file, but it is customizable with the `sam build --base-dir` flag.
2. Find the requirements file. By default `sam` looks for a `requirements.txt` file in the base directory, but this is customizable with the `sam build --manifest` flag.
3. Recursively copy all non-hidden directories and files from the base directory to the bundle directory.
4. Get wheels for all dependencies listed in `requirements.txt` with `pip` and unpack them into the bundle directory.

**Comment by slotrans** [comment]
Why is only `manylinux1` considered compatible? The version of python in the lambci/lambda:build-python3.7 container reports (via `pip debug`) compatibility with `manylinux2010` and `manylinux2014` as well...

**Comment by slotrans** [comment]
Following up on the above: I manually built a python 3.7 lambda zip using manylinux2010 wheels and it executes correctly. This _suggests_ (though does not prove) that incorporating support for newer manylinux specs into SAM would be safe and effective. Not sure the right way to actually do it in the code, as "--platform manylinux1_x86_64" is currently hardcoded into the `pip install` command (see https://github.com/awslabs/aws-lambda-builders/blob/24f0aca6ed41ec2b08333655adbd1433f14cdc9e/aws_lambda_builders/workflows/python_pip/packager.py line 624-625).

The motivation for doing this would be that currently, if you are building a function and need to incorporate a dependency that's not available or buildable for `manylinux1` (e.g. snowflake-connector-python), you then have to _abandon `sam build` entirely_, which is not a great user experience.

**Comment by jfuss** [comment]
@slotrans See https://github.com/awslabs/aws-sam-cli/issues/2014#issuecomment-645508588

**Comment by sriram-mv** [comment]
Closing as support for manylinux2010 wheels will be in the next release as its part of aws lamba builders 1.0.0
