### ISSUE TITLE
"Error: No such image: lambci/lambda:nodejs6.10" === "no space left on device"

### ISSUE THREAD

**Issue by joshuadfranklin** [awslabs/aws-sam-cli#169]
Hi,

I suddenly got `Error: No such image: lambci/lambda:nodejs6.10` from sam and couldn't figure out why. Turns out I had a minimal EC2 instance with a small root volume and didn't notice I ran out of space. Another program gave me the "no space left on device" message.

I'd love a better error from sam on this. Also would love something like a --verbose option to see what sam is up to when something goes wrong.

```
sam local invoke -e event.json  
2017/10/15 11:19:20 Successfully parsed template.yaml
2017/10/15 11:19:20 Connected to Docker 1.32
2017/10/15 11:19:20 Runtime image missing, will pull....
2017/10/15 11:19:20 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
5aed7bd8313c: Extracting [==================================================>]  324.2MB/324.2MB
d60049111ce7: Download complete 
df2c17ad5e5e: Download complete 
93956b6301bb: Download complete 
2017/10/15 11:20:08 Invoking index.handler (nodejs6.10)
2017/10/15 11:20:08 Could not invoke function: Error: No such image: lambci/lambda:nodejs6.10
```

**Comment by sanathkr** [comment]
Can you try the latest release - https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0? Verbose option is available with `--debug`
