### ISSUE TITLE
SAM Lambda Python Functions are not being deployed with Requirements.txt Modules

### ISSUE THREAD

**Issue by nelsynelz** [awslabs/aws-sam-cli#1690]
**Description**
When deploying my template which contains Lambda functions, the modules specified on my requirements.txt file are not being deployed. Locally however, in the .aws-sam directory, if I navigate into the functions themselves that are built there, I see the modules within those folders. 

The issue seems to be either in the packaging or deploy stage but I'm not sure which. 

**Additional Info**
SAM Version: 0.38.0

On my Linux machine I have no issues, however the issue just started happening when using SAM on MacOS Catalina.

This is prohibiting me from working entirely. I cannot deploy any code changes as none of my Lambdas are working without their required modules.

**Comment by jfuss** [comment]
@nelsynelz How are you running `sam package`?

**Comment by jfuss** [comment]
If I had to guess, this is what you are running into: https://github.com/awslabs/aws-sam-cli/issues/1569#issuecomment-557196630

**Comment by nelsynelz** [comment]
@jfuss 

I was running it like this: 
```
sam package --template-file template.yml --output-template-file package.yml --s3-bucket <MY_BUCKET>
```
But I read the template-file line could cause issues so I'm testing now with just this: 
```
sam package --template-file template.yml package.yml --s3-bucket <MY_BUCKET>
```

**Comment by nelsynelz** [comment]
Looks like the issue you linked is along similar lines, I'll update shortly whether that fixes my issue or not.

Do you know of a way to force deploy a stack? My issue now is that I deployed the stack and it removed all of my module dependencies. Now when I want to re-deploy it says no changes are detected. Not sure of the best way around this.

**Comment by nelsynelz** [comment]
Fixed it.

For anyone looking in the future, you need to remove the "--template-file" portion from the sam package command. 

```
sam package --output-template-file package.yml --s3-bucket <MY_BUCKET>
```

**Comment by sulfasTor** [comment]
What is working for me is using the template inside the build folder:

`sam package --template-file .aws-sam/build/template.yml --output-template-file package.yml --s3-bucket <MY_BUCKET>`

**Comment by jfuss** [comment]
@sulfasTor ‘sam package’ will pick up the ‘.aws-sam/build/template.yml’ automatically. No need to pass the ‘—template-file’ at all.
