### ISSUE TITLE
bootstrap in china regions fail on creating s3 bucket

### ISSUE THREAD

**Issue by huangzbaws** [awslabs/aws-sam-cli#1696]
**Description:**

sam deploy bootstrap fail in china regions: cn-north-1, cn-northwest-1
Cloudformation stack aws-sam-cli-managed-default fail on creating S3 bucket, because of wrong ARN "arn:aws:s3:::", it should be "arn:aws-cn:s3:::" in China regions.

**Steps to reproduce the issue:**
1. First time to sam deploy
2. Check the cloudformation stack aws-sam-cli-managed-default created by sam, the template has wrong ARN "arn:aws:s3:::", it should be "arn:aws-cn:s3:::" in China regions.
3. Check the bootstrap.py, in line 147

**Observed result:**
sam deploy fail. 
**Expected result:**
sam deploy success in china regions: cn-north-1, cn-northwest-1

**Comment by tuo** [comment]
yeah, @jfuss , it is a quite big problem here in China. I saw you have merged into dev branch. Any idea on what time it would be released for next version ?

**Comment by jfuss** [comment]
@tuo We do not communicate releases ahead of time. Though, if you take a look at our release history, you can see we typically release every two weeks 😉

**Comment by tuo** [comment]
@jfuss thanks mate. totally understood.  I will keep an eye on it :)

**Comment by jfuss** [comment]
Was released in [v0.42.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.42.0).

Closing
