### ISSUE TITLE
Error `Invalid value for "--parameter-overrides"` is occured by `sam local invoke` with `--parameter-overrides`

### ISSUE THREAD

**Issue by goldeneggg** [awslabs/aws-sam-cli#1703]
### Description
The following three commands give the same error `Error: Invalid value for "--parameter-overrides":  TestFunction is not in valid format.`.

- `sam local invoke --parameter-overrides ParameterKey=Hoge,ParameterValue=Huga TestFunction`   (__parameter-overrides are not quoted__)
- `sam local invoke --parameter-overrides 'ParameterKey=Hoge,ParameterValue=Huga' TestFunction`   (__parameter-overrides are single-quoted__)
- `sam local invoke --parameter-overrides "ParameterKey=Hoge,ParameterValue=Huga" TestFunction`   (__parameter-overrides are double-quoted__)

However, the following command with the order of options changed __does NOT give errors.__

- `sam local invoke TestFunction --parameter-overrides ParameterKey=Hoge,ParameterValue=Huga`   (__the function name is written immediately after the command `sam local invoke`__)

Is it correct to write the function name immediately after the command `sam local invoke`?

### Steps to reproduce

1. Prepare sam template that contains `Parameters` section with `Hoge` Parameter and `Resources` section with `TestFunction` AWS::Serverless::Function.
1. Run `sam local invoke --parameter-overrides ParameterKey=Hoge,ParameterValue=Huga TestFunction`

### Observed result

```
Usage: sam local invoke [OPTIONS] [FUNCTION_IDENTIFIER]
Try "sam local invoke --help" for help.

Error: Invalid value for "--parameter-overrides":  TestFunction is not in valid format. It must look something like 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'
```

### Expected result

Some errors does not occur.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OS X 10.14.6
2. `sam --version`: SAM CLI, version 0.39.0

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Thanks for the Report! This looks to be because of the way parameter overrides option is processed. Its a multivalue option and can process multiple parameters, but putting the function name at the very end makes it seem as if its a part of the parameter overrides, which is why flipping it around with the function name before the parameter overrides option seems to work as expected.

**Comment by sriram-mv** [comment]
To answer original question.

```
sam local invoke TestFunction --parameter-overrides ParameterKey=Hoge,ParameterValue=Huga (the function name is written immediately after the command sam local invoke)
```
is the correct way to invoke without interfering with how the cli internals processes options vs parameters.
