### ISSUE TITLE
Local development with MFA not working

### ISSUE THREAD

**Issue by SteffenBurger** [awslabs/aws-sam-cli#1734]
**Description:**
Testing a serverless function locally should not require MFA

**Steps to reproduce the issue:**
1. setup a `.aws/config` with MFA
2. `sam build`
2. `sam local invoke`

**Observed result:**

Invoking app.lambdaHandler (nodejs10.x)
Enter MFA code for arn:aws:iam::XXXXXX:mfa/my-name: 
...
"Hello from Lambda!"

**Expected result:**
1. for local development there should be no MFA required, this is just annoying

**Comment by jfuss** [comment]
@SteffenBurger We mount default credentials into the container by default. This is so you can interact with cloud resources and the behavior is by design. If you do not want this, you can move your default profile to a different profile name, or not use mfa on the default profile.

It is unlikely this behavior will change because customers are already relying on the current behavior of reading the default profile.

**Comment by SteffenBurger** [comment]
@jfuss thank you for the quick reply.

If it is a design decision that the containers interact with cloud resources - so be it.

However, if this is the case I may have misunderstood the local development capability of AWS SAM.

Since the command `sam local invoke` require cloud resources to work, I personally think the term `local` is misleading. 

The truth is that only a container is running locally, I assume the code of the function, and some additional stuff I do not know is running the the cloud.

However, if I continue this thought I am wondering if not a "remote debug" feature would provide the same advantages for me. But in this case there is nothing local and everything is running in my target platform AWS. So there would be no confusion like, "what is running locally" and "what is running remotely".

But my general intention was to provide some user experience (which is slightly reduced due to the repeatedly and unexpected MFA prompt)

PS: Unfortunately, the AWS Account of my company is enforcing MFA. Therefore I am not able to simply change the profile 😔
