### ISSUE TITLE
property Domain not defined for resource of type AWS::Serverless::Api

### ISSUE THREAD

**Issue by voathnak** [awslabs/aws-sam-cli#1738]
Hello
I tried to use domain in AWS::Serverless::Api, I can deploy successfully but i when validating the template I got an error

`Error: [InvalidResourceException('RestApi', 'property Domain not defined for resource of type AWS::Serverless::Api')]`

**Comment by timoschilling** [comment]
Duplicate of #1723

**Comment by voathnak** [comment]
ahh, thank you @timoschilling

**Comment by sriram-mv** [comment]
Closing as its a duplicate.
