### ISSUE TITLE
SAM Deploy: Tag Parameters are not correctly passed to CloudFormation

### ISSUE THREAD

**Issue by consemk-cg** [awslabs/aws-sam-cli#1739]
### Description

When passing the Resource Tags to SAM Deploy command cli, the tags keys are truncated when the key cotains a hyphon. The resources deployed using SAM Deploy does not have the first part of the tag key. For instance, if the resource tag has a key such "application-id", The deployed resource's tag key has "id" only, and "application" is omitted. 

### Steps to reproduce

 Example - When trying to deploy a resouce with SAM CLI=0.39 using the command below, passing the resource tag with the key `exp-date`, like the following: 
sam deploy \
   --template-file $TEMPLATE \
      --region $AWS_REGION \
      --capabilities CAPABILITY_NAMED_IAM \
      --stack-name $stackName \
      --force-upload \
      --tags "exp-date=99-00-9999" \
      --parameter-overrides \
        Stage=$API_STAGE_NAME \

### Observed result
 It will create all resources in AWS with tag key `date` only rather than `exp-date`
Please provide command output with `--debug` flag set.

### Expected result

The expected result should have all the provisioned resources tagged with the key `exp-date`. 
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`: 0.39

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
https://github.com/awslabs/aws-sam-cli/pull/1727 aims to address this issue.
