### ISSUE TITLE
Node module installation not being added to node_module folder of lambda zip file

### ISSUE THREAD

**Issue by parveensaini** [awslabs/aws-sam-cli#1741]
**Description:**
I have added a couple of dependencies for my project. One of the dependencies is chrome-aws-lambda which downloads headless chrome binary. 

On running build process, the folder is installed correctly in my local environment but SAM CLI doesn't add it to node_module folder while packaging artifacts for lambda.

Due to missing artifact folder, code running on lambda has no way to get the binary.

**Steps to reproduce the issue:**
1. Add chrome-aws-lambda dependency in node lambda project.
2. Install the artifact and then run SAM package.
3.

**Observed result:**
chrome-aws-lambda is present in local node_module folder but missing in zip file

**Expected result:**
chrome-aws-lambda folder to be present in zip file.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac, Amazon linux

**Comment by parveensaini** [comment]
bash-4.1$ sam build

  SAMToolkit 1.0 - Serverless Applications for Happy Developers

  Usage:
    sam package                 - archives package runtime closure and uploads to S3
    sam deploy [args]           - creates or updates the SAM environment based on build/sam/template.yml
    sam clean                   - deletes the currently deployed stack
    sam validate                - uploads and validates the stack template
    sam exec <command>          - executes arbitrary commands within the current SAM environment
    sam test [env] -- [command] - runs integration tests within a SAM environment (supports ToD workers)
    sam help [command]          - prints global or subcommand help
    sam help config             - describe configuration options

Invalid subcommand: build

Command failed.
Please see the logs above.

**Comment by jfuss** [comment]
@parveensaini Please reach out to us internally. I don't think you are using SAM CLI.
