### ISSUE TITLE
Adding --region parameter as the region this Lambda function resides in

### ISSUE THREAD

**Issue by zhangzhx** [awslabs/aws-sam-cli#175]
The current way for providing the region of the Lambda function is using bash env var like
`AWS_REGION=us-west-1 sam local invoke ...`.

This is implicit and not a regular bash command. Can you add a parameter `--region us-west-1` to explicitly override the region environment variable?

**Comment by purefan** [comment]
This is the repository for AWS SAM Local, when you invoke a function you are executing code that resides in your computer, not in an aws environment, that is to say: there are no regions. 

Can you please describe what you're trying to do?

**Comment by bradleyjames** [comment]
There are regions when interacting with other AWS resources from a lambda.  I've ran into this issue as well.

**Comment by zhangzhx** [comment]
@purefan I want to mock the Lambda environment in a specific region as much as possible with SAM Local. In the AWS Lambda runtime environment, you don't have to specify the region in the Credentials Provider chain, so that you can access AWS resources in the same region to the Lambda function. I want SAM Local to have a specific region configured as the environment variable same to the standard AWS Lambda.

**Comment by purefan** [comment]
Although I still fail to see the need for defining the region you can also use the env vars file if you prefer: `sam local start-api --env-vars path_to.json`

The way I imaging going about it is by defining the region from a configuration file, and when using the sdk I would specify the region based on the value in the config file, for example `AWS.config.update({region: my_config_object.region});` [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html)

**Comment by bradleyjames** [comment]
The reason I'm fine with `--region` is it replicates the AWS CLI method of configuring the region.  I think `--env-vars` works but it's the least favorable.  The core concern that I believe @zhangzhx has, and I do as well, is sam local doesn't replicate the runtime environment.  Each developer has to trip over it and determine how best to handle it on their own.

My preference would be for sam local to:
* read the region of the profile from ~/.aws/credentials if `AWS_PROFILE` is specified
* read from a sam local specific default region (something like .samlocalrc) local to my project
* use --region if specified
* default 'us-east-1'

> The way I imaging going about it is by defining the region from a configuration file, and when using the sdk I would specify the region based on the value in the config file, for example AWS.config.update({region: my_config_object.region});

Defining the region in a config file doesn't address determining the current region by inspecting `AWS_REGION` which is how most write their lambdas today.

**Comment by PaulMaddox** [comment]
+1. I agree that `--region` is the AWS standard way of doing this, and while the region can be specified in other ways, most people will try `--region` first.

Marking this as a feature request that we should implement.

**Comment by SanderKnape** [comment]
A +1 from me as well. I also tried to use --region first before I added the region to the Lambda function.

**Comment by rustyautopsy** [comment]
+1. I first tried using `AWS_DEFAULT_REGION` as a bash env var. I found this post and @zhangzhx comment which solved my issue. 

`--region` for the win.

Also where in the docs is it mentioned that one should use `AWS_REGION` specifically?

**Comment by dementiev** [comment]
+1 for region parameter, i receive 'region 'us-east-1' is wrong; expecting 'eu-central-1' '

**Comment by domZippilli** [comment]
+1

**Comment by red8888** [comment]
+1

**Comment by red8888** [comment]
Another use case i have is a lambda im deploying to multiple regions. So I can reset the env var before I call  sam deploy but thats not great.

Should just not use sam at all and just use: 
aws cloudformation package
aws cloudformation deploy

Those commands have a region switch, and they are the same as the sam ones right?

**Comment by hb-adw** [comment]
Another way to change region is to add a variable "region" in your file ".aws/credentials" with your profile. Then you could add --profile <profile_name> as parameter

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)

**Comment by jfuss** [comment]
@ndelvalle Documented as in? If you run the `--help` on the sam local [start-lambda|invoke|start-api], you will see `--region` as an option. 

`sam deploy` should already have this option.
