### ISSUE TITLE
sam cli fails on arm64

### ISSUE THREAD

**Issue by 6iix** [awslabs/aws-sam-cli#1759]
### Description

I am using a arm64 machine. I have installed docker, aws cli and followed the instructions for installing aws-sam-cli (verified everything is working properly). However local invoke fails and returns this message:  
`standard_init_linux.go:211: exec user process caused "exec format error"`

it appears docker works correctly, I was able to successfully run `docker run hello-world`

### Steps to reproduce
install everything needed for aws sam cli, try invoking locally. 

### Observed result
```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local invoke command is called
Collected default values for parameters: {'EnvironmentTagName': 'dev', 'StackTagName': 'stackery-quickstart'}
2 resources found in the template
Found Serverless function with name='test' and CodeUri='test'
Found one Lambda function with name 'test'
Invoking index.handler (nodejs12.x)
No environment variables found for function 'test'
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
Resolving code path. Cwd=/mnt/c/Users/username/projects/stackery-quickstart/.aws-sam/build, CodeUri=test
Resolved absolute path to code is /mnt/c/Users/username/projects/stackery-quickstart/.aws-sam/build/test
Code /mnt/c/Users/username/projects/stackery-quickstart/.aws-sam/build/test is not a zip/jar file
Skipping building an image since no layers were defined

Fetching lambci/lambda:nodejs12.x Docker container image......
Mounting /mnt/c/Users/username/projects/stackery-quickstart/.aws-sam/build/test as /var/task:ro,delegated inside runtime container
Starting a timer for 30 seconds for function 'test'
standard_init_linux.go:211: exec user process caused "exec format error"
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 2968, 'exitReason': 'success', 'exitCode': 0, 'requestId': '1281c514-43c6-4c43-9713-06cf4b95e96e', 'installationId': '813e2f45-8827-479f-ab58-a88cf3bc7f7b', 'sessionId': '7b117b79-945f-450d-9508-eec70989800e', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.40.0'}}]}
Telemetry response: 200
```
### Expected result
the function should be executed and log the event file being dropped in
Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 10 (wsl2)(ubuntu 18.04 arm64)
2. `sam --version`:0.40.0
3. `docker version`: 19.03.5, build 633a0ea

**Comment by timoschilling** [comment]
Sam uses https://hub.docker.com/r/lambci/lambda which is only available as linux/amd64.

**Comment by 6iix** [comment]
@timoschilling thank you, i thought that is what it was but wanted to be sure. I'll open a ticket with them and see if they can help.

**Comment by mhart** [comment]
Circling back here – Lambda itself runs on x86-64 (and all the Lambda software is x86-64) – so it's not really an issue with the docker containers, it's Lambda itself.

**Comment by 6iix** [comment]
@mhart thank you for explaining. I really appreciate it.
