### ISSUE TITLE
Lambda Trigger - Feature Request

### ISSUE THREAD

**Issue by Prinolan009** [awslabs/aws-sam-cli#1761]
Hi

Could it be possible to add in SAM commands which is able to actively add in a Lambda trigger upon creation of the Lambda function.

For example, the AWS CLI command - you can add a trigger to Lambda using aws lambda add-permission \
    --function-name HourlyLambdaFunction \
    --statement-id 276xxxxxx\
    --action "lambda:InvokeFunction" \
    --principal sns.amazonaws.com \
    --source-arn arn:aws:sns:eu-west-1:276xxxxxx:HourlyLambdaFunction

Is there an equivalent AWS SAM command for Lambda?

Thank you

**Comment by awood45** [comment]
Is this for an existing SNS queue, or for creating and then subscribing to a queue? The [event source](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventsource.html) property on the `AWS::Serverless::Function` type can link your function to that SNS queue for you.

We don't intend to add hooks to modify functions outside of the capability SAM provides at this time, but SAM does have a solution for the problem you seem to be having.

Closing as this is answered, but if you have additional questions or if I've misunderstood what you're trying to do, feel free to reopen.
