### ISSUE TITLE
sam publish duplicate semantic version issue

### ISSUE THREAD

**Issue by honglu** [awslabs/aws-sam-cli#1764]
### Description

When using sam publish command to publish a new version of a SAR app, if I forget to update the semantic version in the template metadata, it succeeds leading the user to think they published a new version.

### Steps to reproduce
We use this script when publishing to SAR:
https://github.com/awslabs/aws-athena-query-federation/blob/master/tools/publish.sh

It has the exact commands that get run. The steps to reproduce are:

1. use the script to publish an initial semantic version to SAR
2. deploy an instance of that app
3. make a code change to the app but forget to change the semantic version
4. publish the code change using the script
5. attempt to deply an update to the previous app instance.

You'll find that step #4 doesn't throw and error but that after step 5 which also won't error, the deployed app will still be running the code from step 1.

### Expected result

Step #4 should somehow throw an error or helpful information to indicate a new version is not published so that we can stop before running step 5.

**Comment by jfuss** [comment]
Possible issue with our dependency not handling this correctly? https://github.com/awslabs/aws-serverlessrepo-python

**Comment by sriram-mv** [comment]
I'm closing this issue here, and will follow up with our dependency.
