### ISSUE TITLE
Code: InternalServerError, Message: Unknown request

### ISSUE THREAD

**Issue by plantusd** [awslabs/aws-sam-cli#1791]
### Description

I'm getting `{"headers":{},"multiValueHeaders":{},"statusCode":500,"body":"{\"Code\":\"InternalServerError\",\"Message\":\"Unknown request.\"}`

### Steps to reproduce

sam local invoke --no-event --debug

### Observed result

Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 4697, 'exitReason':
'success', 'exitCode': 0, 'requestId': 'ebbeca29-14f4-4ba8-bd95-aeb8c4e12b94', 'installationId': '072d408a-950f-4a21-bb6b-cea85e65da65', 'sessionId': '51fac846-dedc-4387-9225-efaf1a4890
e2', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.41.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

{"headers":{},"multiValueHeaders":{},"statusCode":500,"body":"{\"Code\":\"InternalServerError\",\"Message\":\"Unknown request.\"}"}

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 0.41.0

**Comment by plantusd** [comment]
Could it be related to samconfig.toml somehow?
oddly there wasn't local_invoke section, but I didn't change anything, except removing samconfig.toml and it worked

**Comment by plantusd** [comment]
I think I got it, in samconfig.toml was build section with custom build_dir, so as I understand, when I run sam local invoke - it used .aws-sam/build instead, but I'm not sure

**Comment by sriram-mv** [comment]
@plantusd Thats interesting. What did your samconfig.toml look like?

**Comment by plantusd** [comment]
`version = 0.1

[default.local_start_api.paramaters]
 port=5400
 template_file="template.yaml"
 env_vars="env.json"
 debug=true

[default]
[default.validate]
[default.validate.parameters]
 template-file='template.yaml'
 debug=false

[default.build]
[default.build.parameters]
 build_dir='target'
 base_dir='.'
 manifest='requirements.txt'
 use_container=false
 template_file='template.yaml'
 skip_pull_image=true
 debug=false

[default.deploy]
[default.deploy.parameters]
 template_file='target/template.yaml'
 stack_name="StatisticService"
 s3_bucket="statistics"
 force_upload=true
 fail_on_empty_changeset=false
 capabilities="CAPABILITY_IAM"
 debug=true`

**Comment by sriram-mv** [comment]
Ah I see. 

Your understanding is right.

When a project gets built using `sam build`, all other commands that need to deal with built artifacts start referencing to `.aws-sam/build/template.yaml` unless a `--template-file` option is specified.

When local start api command gets a `--template-file` option specified it is expecting to find a template where the codeuri contains built artifacts. If the supplied template file does not fulfill those characteristics, it errors out.

**Comment by plantusd** [comment]
Thanks!
