### ISSUE TITLE
SAM build --parameter-overrides fails if specified before the identifier

### ISSUE THREAD

**Issue by abrooksv** [awslabs/aws-sam-cli#1799]
### Description

Briefly describe the bug you are facing.

### Steps to reproduce

```
/usr/local/bin/sam build --template IdeaProjects/untitled31/template.yaml --build-dir IdeaProjects/untitled31/HelloWorldFunction/.aws-sam/build --parameter-overrides LLAYER=MyLambda:Arn HelloWorldFunction
Usage: sam build [OPTIONS] [FUNCTION_IDENTIFIER]
Try "sam build --help" for help.

Error: Invalid value for "--parameter-overrides":  HelloWorldFunction is not in valid format. It must look something like 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'
```

### Expected result
Build is ran

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: osx
2. `sam --version`: 0.41.0

`Add --debug flag to command you are running`

**Comment by abrooksv** [comment]
FYI: Local invoke does handle this correctly.

**Comment by sriram-mv** [comment]
@abrooksv : of what format do you specify it with local invoke?

`--parameter-overrides` 

Is it 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'

**Comment by abrooksv** [comment]
Same parameter format as for the build:
```
/usr/local/bin/sam local invoke --template IdeaProjects/untitled31/HelloWorldFunction/.aws-sam/build/template.yaml --event "/private/var/folders/q5/cfv4k63519vcllnnpwz5zsj0wnjvck/T/[Local] HelloWorldFunction-event1.json" HelloWorldFunction --parameter-overrides LLAYER=MyLambda:Arn
Invoking helloworld.App::handleRequest (java8)
```

**Comment by sriram-mv** [comment]
Function identifier first and then options would be the way to go. Does that work consistently for you?

**Comment by abrooksv** [comment]
Ya, I can make that work. Should we move ALL options after the identifier?

**Comment by sriram-mv** [comment]
Yeah, that pattern would ensure that parameter overrides dont run into the pattern where it thinks the identifier is also a parameter override.
