### ISSUE TITLE
Profile argument not taken into account when calling package do_cli from python interpreter

### ISSUE THREAD

**Issue by Zangror** [awslabs/aws-sam-cli#1801]
### Description

I'm using the do_cli method from the samcli.commands.package.command.py in a python interpreter to package a Serverless Function. 

I provide the profile argument but it doesn't seems taken into account because I have ```An error occurred (AccessDenied) when calling the PutObject operation: Access Denied```.

### Steps to reproduce

1. Create a main.py and a requirements.txt (or whatever depending on the programming language)
2. Create a template.yaml
3. Have a profile not linked to the default profile 
4. Run deploy.py in a python interpreter

#### main.py
```python
def handler(event, context):
    print("Hello World")
```
#### requirements.txt
```
boto3
```
#### template.yaml
```yaml
Resources:
  Function:
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
```
#### deploy.py
```python
import os
import tempfile
from samcli.commands.build.command import do_cli as build_do_cli
from samcli.commands.package.command import do_cli as package_cli

template_path = "template.yaml"
base_dir = ""  # Todo: define here where you created the main.py and the requirements.txt
s3_bucket_name = ""  # Todo: define here your bucket
region_name = "" # Todo: define here the region
profile_name = "" # Todo: define here the profile nale

with tempfile.TemporaryDirectory() as tmp_dir_name:
    sam_build_dir = os.path.join(tmp_dir_name, "SAM_BUILD")
    sam_build_path = os.path.join(sam_build_dir, "template.yaml")
    sam_package_path = os.path.join(tmp_dir_name, "SAM_PACKAGE_TEMPLATE.yaml")

    build_do_cli(
        function_identifier="Function",
        template=template_path,
        base_dir=base_dir,
        build_dir=sam_build_dir,
        clean=True,
        use_container=True,
        manifest_path=None,
        docker_network=None,
        skip_pull_image=False,
        parameter_overrides=None,
        mode=None,
    )
    package_cli(
        template_file=sam_build_path,
        s3_bucket=s3_bucket_name,
        s3_prefix="lambdas",
        kms_key_id=None,
        output_template_file=sam_package_path,
        use_json=False,
        force_upload=False,
        metadata=None,
        region=region_name,
        profile=profile_name,
    )

```

### Observed result

I received the following error:
```An error occurred (AccessDenied) when calling the PutObject operation: Access Denied```

### Expected result

Package should work out of the box without passing from the cli.

### Observations

Issue seems relative to [this line](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/package/package_context.py#L83). If profile is specified, the boto3 Session object should be created before creating the s3 client.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOs Catalina 10.15.3
2. `sam --version`: SAM CLI, version 0.41.0

**Comment by jfuss** [comment]
@Zangror Are you using the CLI as a library?

**Comment by Zangror** [comment]
Yes I am.

**Comment by jfuss** [comment]
The CLI is not built in a way to do this. So it is completely not supported. We heavily rely on click and Click's Context model to setup things like profiles and regions.

Closing as this is not a supported usage.
