### ISSUE TITLE
sam build issue

### ISSUE THREAD

**Issue by gkuppuswamy** [awslabs/aws-sam-cli#1811]
Following versions installed on Mac OS.
Python -  3.7.3
pip - 20.0.2
sam cli - 0.42.0

Included "aws-xray-sdk" in the requirements.txt and ran the sam build command. Iam getting following error
"Building resource 'HelloWorldFunction'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - {wrapt==1.12.0(sdist), future==0.18.2(sdist)}"

**Comment by sriram-mv** [comment]
I was able to build successfully, do you have `wheel` installed?

does sam build --use-container work?

**Comment by sriram-mv** [comment]
Feel free to re-open this if you are still facing this issue.

**Comment by gkuppuswamy** [comment]
Sam build —use-container works.

But the Sam build is not working.

Yes I do have wheel package installed.

**Comment by jfuss** [comment]
This is expected. We cannot build packages that require c bindings on Mac and have them compatible with Lambda (wrapt has .c code: https://github.com/GrahamDumpleton/wrapt/tree/develop/src/wrapt). So you will need to use `sam build --use-container` to build your functions correctly.
