### ISSUE TITLE
Version 0.43 of sam cli does not conform to the regular working of sam templates

### ISSUE THREAD

**Issue by ritwiksingh** [awslabs/aws-sam-cli#1819]
### Description

On using the aws-sam-cli version 0.43, SAM creates new packages for code uri and updates lambda functions even if there is no change in the code.
In the previous version being used, 0.41, SAM would only update a function if their was a change in the code or property of the particular lambda function.
 
### Steps to reproduce

We are building and deploying sam template through code build.

`# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

environment_variables:
  plaintext:
    LAMBDA_SERVICE_TO_BUILD: |
       lambdaFunction01
       lambdaFunction02
       lambdaFunction03
       
phases:
  install:
    runtime-versions:
      nodejs: 10 
    commands:
      - pip install aws-sam-cli
      - export BUCKET=<bucket name>
  build:
    commands:
      - echo Build started on `date`
      - |
        for lambda in $LAMBDA_SERVICE_TO_BUILD; do
          echo "Building lambda service $lambda"
          cd $CODEBUILD_SRC_DIR/$lambda
          npm install --silent --no-progress
          npm test
          rm -rf node_modules
          cd /
        done
      - |
      - cd  $CODEBUILD_SRC_DIR
      - npm install --silent --no-progress -g serverless
  post_build:
    commands:
      - ls
      - sam package --template-file template-v2.yml --s3-bucket $BUCKET  --output-template-file outputtemplate.yml
      - sam deploy --template-file outputtemplate.yml --stack-name my-sam-application --capabilities CAPABILITY_IAM
artifacts:
  type: zip
  files:
    - template-v2.yml
    - outputtemplate.yml
`
### Observed result
With no change to any of the deployed lambdas on sam cli version 0.43

[Container] 2020/02/24 14:56:16 Running command sam package --template-file template-v2.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
250 |  
251 | SAM CLI now collects telemetry to better understand customer needs.
252 |  
253 | You can OPT OUT and disable telemetry collection by setting the
254 | environment variable SAM_CLI_TELEMETRY=0 in your shell.
255 | Thanks for your help!
256 |  
257 | Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
258 |  
259 |  
260 | Uploading to lambdapackage/69bf834224c0af83af583550d6b79f91  15605 / 15605.0  (100.00%)
261 |  
262 | Uploading to lambdapackage/42399b3872a8a24a578b30a4df887e2c  15608 / 15608.0  (100.00%)
263 |  
264 | Uploading to lambdapackage/7084dd59c02e26e0ea65ab1711059cf2  15709 / 15709.0  (100.00%)
265 |  
266 | Uploading to lambdapackage/8cd27ec36cd96f6293ae6e391600870e  16141 / 16141.0  (100.00%)
267 | Successfully packaged artifacts and wrote output template to file outputtemplate.yml.

### Expected result
With no change to any of the deployed lambdas on sam cli version 0.41

[Container] 2020/02/24 15:35:28 Running command sam package --template-file template-v2.yml --s3-bucket $BUCKET --s3-prefix lambdapackage --output-template-file outputtemplate.yml
235 |  
236 | SAM CLI now collects telemetry to better understand customer needs.
237 |  
238 | You can OPT OUT and disable telemetry collection by setting the
239 | environment variable SAM_CLI_TELEMETRY=0 in your shell.
240 | Thanks for your help!
241 |  
242 | Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
243 |  
244 |  
245 | Successfully packaged artifacts and wrote output template to file outputtemplate.yml.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: amazon-linux
2. `sam --version`: 0.43

**Comment by jfuss** [comment]
@ritwiksingh We updated how we do the hashing of files in https://github.com/awslabs/aws-sam-cli/pull/1789 as there are cases where we were uploading artifacts that didn't change. So this is expected as a first run in some cases but you shouldn't see this happen after that.

Closing this as this is expected but only on the first run. Please re-open if that is not the case and we can investigate further.
