### ISSUE TITLE
Unable to connect docker to Python Remote debugging with Pycharm/jetbrains

### ISSUE THREAD

**Issue by GarimaBathla** [awslabs/aws-sam-cli#1847]
### Description
With SAM when running lambda/api combination with command `sam local start-api -d 8989` using PyCharm IDE, unable to connect to the remote debugger. 

somehow the docker is not able to connect on port -d 8989 and I cannot make out what configuration in docker needs to change. There is no documentation on this anywhere. 

Only link is here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html

and this only talks about using ptvsd which is not what JetBrains supports.

### Problem

Using JetBrains IDE Python remote debugging can be done using the 2 lines added to handler like below.
import pydevd_pycharm
pydevd_pycharm.settrace('localhost', port=8989, stdoutToServer=True, stderrToServer=True)
 
```
handler:
import pydevd_pycharm
pydevd_pycharm.settrace('localhost', port=8989, stdoutToServer=True, stderrToServer=True)

def handler(event, context):
    print(event)
    print(context)
    return {"pingT": "pongT!"}
```

These 2 lines are able to connect to remote debugger that is waiting to listen on port 8989. 

This solution works out of the box for Serverless-offline. 

But when sam is used and it starts docker container with command ```same local start-api -d 8989```  below error is seen

```
{
  'errorType': 'ConnectionRefusedError',
  'errorMessage': '[Errno 111] Connection refused',
  'stackTrace': [
    '  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module\n    return load_source(name, filename, file)\n',
    '  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source\n    module = _load(spec)\n',
    '  File "<frozen importlib._bootstrap>", line 696, in _load\n',
    '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\n',
    '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\n',
    '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n',
    '  File "/var/task/app/test.py", line 2, in <module>\n    pydevd_pycharm.settrace(\'localhost\', port=8989, stdoutToServer=True, stderrToServer=True)\n',
    '  File "/var/task/pydevd.py", line 1631, in settrace\n    stop_at_frame,\n',
    '  File "/var/task/pydevd.py", line 1678, in _locked_settrace\n    debugger.connect(host, port)  # Note: connect can raise error.\n',
    '  File "/var/task/pydevd.py", line 607, in connect\n    s = start_client(host, port)\n',
    '  File "/var/task/_pydevd_bundle/pydevd_comm.py", line 449, in start_client\n    s.connect((host, port))\n'
  }
```
### Steps to reproduce

1. Create a sample SAM application with a basic /get endpoint with 2 lines listed above in the handler.  
2. sam build 
3. connect remote debugger configuration - it should try to connect to localhost:8989
4. sam local start-api -d 8989
5. try to hit the endpoint  
6. Error, connection refused. 

### Observed result
Exception seen above. 
### Expected result
Should be able to debug with IntelliJ python remote debugging.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. `OS`: Mac OS Mojave 10.14.5
2. `runtime`: Python 3.7
3. `sam --version`: 0.43.0
4. `IDE`:  Intellij 2019.3.3
5. `docker`: Mac OS community edition

**Comment by jfuss** [comment]
@GarimaBathla This is because within the docker container, it cannot attach to your localhost. You can follow instructions here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html#serverless-sam-cli-using-debugging-python-ptvsd to get it setup correctly.

Closing

**Comment by GarimaBathla** [comment]
@jfuss that is not quite right. I cannot use ptvsd, that is for vscode only.

I am refering here to pycharm IDE. With Pycharm I edited the line to use 0.0.0.0 and I still see the same error

import pydevd_pycharm
pydevd_pycharm.settrace('0.0.0.0', port=8989, stdoutToServer=True, stderrToServer=True)


'errorType': 'ConnectionRefusedError', 'errorMessage': '[Errno 111] Connection refused'

**Comment by GarimaBathla** [comment]
Please reopen this issue, it has not been resolved.

**Comment by jfuss** [comment]
@GarimaBathla Are you including pydevd in your function code? 

This is an issue with your setup not the CLI, but will re-open.

**Comment by jfuss** [comment]
@GarimaBathla We only have docs for VSCode and not sure what it will take for PyCharm. Your best bet is to use the [AWS Toolkit for PyCharm](https://aws.amazon.com/pycharm/), as debugging is directly integrated, though they only support the `sam local invoke` equivalent today. So you would be mocking out your events instead of interacting with the API in this situation.

Closing, as our docs are only VSCode and the path forward is to use AWS Toolkit for debugging and mocking out events.
