### ISSUE TITLE
sam build --use-container stuck at mounting

### ISSUE THREAD

**Issue by CristianKrieger** [awslabs/aws-sam-cli#1863]
# Description

SAM CLI suddenly stopped working. If I run `sam build --use-container` the process gets stuck at `Mounting /app as /tmp/samcli/source:ro,delegated inside runtime container`. I have tried several things: restarting the terminal, my computer, docker; I have done a clean install of docker and the SAM CLI and the problem persists.

### Observed result

This is what happens when I leave the `--debug` flag set:
`sam build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='AuthFunction' and CodeUri='/app'
Building resource 'AuthFunction'

Fetching lambci/lambda:build-python3.8 Docker container image......
Mounting /app as /tmp/samcli/source:ro,delegated inside runtime container`
Sadly, the process never ends, I have left my computer for hours waiting for a result. Nothing happens.

### Expected result

The process should finish or at least show an error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Catalina v10.15.3
2. `sam --version`: 0.43.0

**Comment by CristianKrieger** [comment]
After a lot of debugging, the problem was the CodeUri='/app'. I had a typo, by using 'app/' instead it works.

**Comment by berniedurfee-renaissance** [comment]
@CristianKrieger thank you!
