### ISSUE TITLE
Environment Variables From Secret Manager Not Correctly Replaced When Running Locally

### ISSUE THREAD

**Issue by AMcManigal** [awslabs/aws-sam-cli#1878]
### Description

Hi Team. Consider the following template fragment.

    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
          CodeUri: SomePath
          Handler: package.Handler::handleRequest
          Runtime: java11
          MemorySize: 512
          Environment:
            Variables:
              value: "{{resolve:secretsmanager:name1:SecretString:property}}"
          Layers:
            - Ref: SharedLayer

If I run this locally in IntelliJ using the AWS Toolkit Plugin the environment variables are not replaced and the code fails. However, if I deploy the code the Lambda configuration has the correct values.

### Steps to reproduce

Replication Steps:
- Create a function that tries to pull a secret from the Secret Manager as shown above using a SAM template.
- Run the function **locally** using the default configuration created by the AWS Toolkit.
- If you check the environment variable in the running code it should be the Cloud Formation syntax instead of the secret value.
- Deploy the stack and check the value in the deployed function. It should have been correctly substituted.

### Observed result

The Cloud Formation syntax remains intact rather than being replaced with the Secret Manager value.

### Expected result

I would expect the Cloud Formation values to be replaced with the Secret Manager values even when running locally.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

AWS CLI: aws-cli/1.18.1 Python/2.7.17 Darwin/18.7.0 botocore/1.15.1
SAM: SAM CLI, version 0.45.0
IntelliJ IDEA: 2019.3.4 (Ultimate Edition) Build #IU-193.6911.18, built on March 17, 2020
AWS Toolkit Plugin for IntelliJ: 1.11-193
Java: java 11.0.4 2019-07-16 LTS
MacOS Mojave: 10.14.6
Docker Desktop Community Edition: 2.2.0.4 

No special events or flags should be necessary to reproduce this.

**Comment by jfuss** [comment]
@AMcManigal Thanks for the issue. This is very similar to https://github.com/awslabs/aws-sam-cli/issues/1069 and basically we do not read and understand the syntax for SSM in the templates. Instead, the way to do this is override the values of the Environment Variables though the `--env-var` parameter. 

Background context: Things like this require us to re-implement parts of CloudFormation, instead we have given some ways around thing depending on where it is defined. You can use `--parameter-overrides` to override any parameters in your template that use SSM and `--env-vars` if you have then defined in Environment Variables.

We will track support in #1069 but it is currently not any work we have directly planned to do.

Closing.

**Comment by devpresleycobb** [comment]
I came up with a work around for this. @jfuss What do you think? https://stackoverflow.com/questions/68138883/resolve-secretsmanager-when-invoking-sam-template-locally/68518207#68518207
