### ISSUE TITLE
Can I init a new function in exist folder not new folder with name(sam-app)

### ISSUE THREAD

**Issue by theowenyoung** [awslabs/aws-sam-cli#1905]
### Describe your idea/feature/enhancement

Provide a clear description. Ex. I wish SAM CLI would [...]

I want to init a function in exist folder, not create a new `sam-app` folder.

**Comment by sriram-mv** [comment]
Im not sure if we want to support this as this may cause damage to existing folder.

**Comment by awood45** [comment]
Indeed, there are other features we have in mind that would help to add to existing projects, but if you really need an existing folder to have the contents of a sam init, would recommend you create a temporary folder, copy the contents, and delete it.
