### ISSUE TITLE
Local golang function no response

### ISSUE THREAD

**Issue by blackout1208** [awslabs/aws-sam-cli#1913]
### Description
On requesting locally a golang function response is hanged and on console got a message saying that my code is not a zip/jar file. After that, the execution is stuck on fetching a docker container image. 

PS: Am I not supposed to be able to see a new container when I run `docker ps -a` while I'm running a function through aws-sam?

### Steps to reproduce

1. sam init
2. Choice: 1
3. Choice: 4 
4. make deps
5. make build
6. sam local start-api --debug
7. postman request -> GET - http://127.0.0.1:3000/hello

### Observed result

![image](https://user-images.githubusercontent.com/12602104/78511779-81d5cf80-779f-11ea-8be8-23bb0f649202.png)

### Expected result

Expected a status 200

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac Catalina 10.15.3
2. `sam --version`:  0.47.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@blackout1208 How do you know it is stuck? Did you let the download of the image finish? By the looks of it, you killed the command while we were downloading the image, which can take some time due to the size of the image.

**Comment by blackout1208** [comment]
@jfuss I killed the execution because I wanted to take a screenshot to publish here. On one of the executions before I left it run for over than 5 minutes.

To whom may come here to look for the same situation, the way I found to fix my issue was by adding the flag `--skip-pull-image` or by downloading docker image - `docker pull lambci/lambda:go1.x` - before starting the api.

**Comment by jfuss** [comment]
@blackout1208 We do a `docker pull` in the CLI through the dockerpy library. My guess is either there was an underlying issue with docker or the pull needed to take that long on your machine.

Note: using `--skip-pull-image` constantly means that you may be running a very out of date version of the image.
