### ISSUE TITLE
How to use secure parameters in AWS SAM?

### ISSUE THREAD

**Issue by singhs020** [awslabs/aws-sam-cli#1919]
Hi Team,

We pass secure credentials via environment variables to our app, but SAM deploy and lambda console prints out the value. Is there a recommended way to pass on the secured values to lambda function using AWS SAM?

**Comment by c2tarun** [comment]
Hello @singhs020,

Environment variables are not the most secure way to store credentials. I would recommend using [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/) to store your credentials and pass credentials name via environment variables.
Then your lambda can simply use the name passed and fetch credentials from secrets manager.

Some helpful resources:
1. https://docs.aws.amazon.com/secretsmanager/latest/userguide/tutorials_basic.html
2. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html

Please let me know if you have more questions.

Thanks
Tarun

**Comment by singhs020** [comment]
Thank you @c2tarun . I will look into it.

**Comment by dfuentes77** [comment]
Related but I have apigateway config along with lambda that my sam-cli deploys and there are secrets that I'd rather not commit to the toml but have the `sam-cli deploy` read from secrets manager for some values.  Is there any way of doing this?
