### ISSUE TITLE
Using aws-serverless-express

### ISSUE THREAD

**Issue by yarax** [awslabs/aws-sam-cli#192]
Hi,
I'm using `aws-serverless-express` for Lambda. 
It up and runs node.js server (creating socket in the Docker container file system) proxying API Gateway request to it. 
That works fine and I'm able to see logs out from this created server route.
But I cannot perform any async operations inside of this route, because `aws-serverless-express`  immediately gets `Error: socket hang up`
The Lambda timeout is set up to 20s
Inside of AWS environment everything works fine.

**Comment by StefanSmith** [comment]
+1 Any updates on this?

**Comment by villasv** [comment]
Won't work out of the box right now, AFAIK.
Following https://github.com/awslabs/aws-serverless-express/issues/137

**Comment by sanathkr** [comment]
This should be fixed as of v0.3.0. Feel free to re-open if it still doesn't work
