### ISSUE TITLE
sam deploy improperly handles whitespace in tags

### ISSUE THREAD

**Issue by zsabin** [awslabs/aws-sam-cli#1925]
### Description
`sam deploy` fails to correctly handle whitespace in tag keys and values when passed using the `--tags` flag. AWS Cloudformation docs specify that whitespace is valid for both keys and values: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html.

### Steps to reproduce

sam deploy
    --debug
    --profile <>
    --template-file <>
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
    --parameter-overrides <>
    --stack-name <>
    --tags "key name=foo bar"

### Observed result
The command above will tag resources as `name=foo`

### Expected result
Should tag resources as `key name=foo bar`

The same tags specified using the `aws cloudformation deploy` command will produce the expected result.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS
2. `sam --version`:
`SAM CLI, version 0.47.0`

**Comment by justengland** [comment]
I also so the same issue with a dash

**Comment by sriram-mv** [comment]
https://github.com/awslabs/aws-sam-cli/pull/1968 this should have fixed this, closing this issue, re-open if you are still seeing this.

**Comment by ceberz** [comment]
I believe I'm seeing this behavior again with SAM version 1.52.

From my Makefile:

```Makefile
sam deploy \
  --template-file ./FOO.yml \
  --region us-west-2 \
  --stack-name FOO \
  --s3-prefix FOO \
  --s3-bucket FOO \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
  	Foo=bar \
    	Baz="bot" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --tags \
    	"some:tag=foo-and-then-bar" \
    	"some:other:tag=foo and then bar"
```

When the stack is created, the _some:tag_ tag has the correct value of _foo-and-then-bar_, but _some:other:tag_ ends up with only the value _foo_. 

This seems to happen regardless of whether the values are passed with quotes around the entire "key=value" or simply around "value".

```Makefile
  --tags \
    	"some:tag=foo-and-then-bar" \
    	"some:other:tag=foo and then bar"
```

...or:

```Makefile
  --tags \
    	some:tag="foo-and-then-bar" \
    	some:other:tag="foo and then bar"
```
