### ISSUE TITLE
VS Code debugging not working as per documentation

### ISSUE THREAD

**Issue by rupe120** [awslabs/aws-sam-cli#1926]
### Description

The setup described in the following documentation does not seem to work. 

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html

### Steps to reproduce

I setup the following repository to demonstrate

https://github.com/rupe120/aws-sam-python-debugging-test

As shown in the readme, I perform the following:

```
sam build --use-container
sam local invoke -d 5890
```

I set the breakpoint in the code within `.aws-sam/build` and when I start the debugger the breakpoint is ignored.

I tried to submit a question to Stackoverflow but this all seems to be in line with the documentation and no one has so far repsoned that this setup is incorrect.

https://stackoverflow.com/questions/61294133/aws-sam-vscode-ptvsd-debugging-not-using-breakpoints

### Observed result

The code executes without pausing at the breakpoint

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local invoke command is called
Collected default values for parameters: {'OwnerTag': 'jrusso', 'ProjectTag': 'Sandbox'}
4 resources found in the template
Found Serverless function with name='Function1' and CodeUri='Function1'
Invoking app.lambda_handler (python3.8)
No environment variables found for function 'Function1'
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
Resolving code path. Cwd=C:\Temp\aws\sam-debug-test\.aws-sam\build, CodeUri=Function1
Resolved absolute path to code is C:\Temp\aws\sam-debug-test\.aws-sam\build\Function1
Code C:\Temp\aws\sam-debug-test\.aws-sam\build\Function1 is not a zip/jar file
SharedLayer1 is a local Layer in the template
Resolving code path. Cwd=C:\Temp\aws\sam-debug-test\.aws-sam\build, CodeUri=..\..\shared_layer1
Building image...
Requested to skip pulling images ...

Mounting C:\Temp\aws\sam-debug-test\.aws-sam\build\Function1 as /var/task:ro,delegated inside runtime container
Setting up SIGTERM interrupt handler
START RequestId: 3a6600aa-d448-11c6-1bfd-d540c30b8aa3 Version: $LATEST
App 3 shared helper: global stuff
END RequestId: 3a6600aa-d448-11c6-1bfd-d540c30b8aa3
REPORT RequestId: 3a6600aa-d448-11c6-1bfd-d540c30b8aa3  Init Duration: 9515.91 ms       Duration: 14.20 ms      Billed
Duration: 100 ms        Memory Size: 128 MB     Max Memory Used: 41 MB

null
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 11429, 'exitReason': 'success', 'exitCode': 0, 'requestId': 'c34706ec-0bae-46e7-bb6f-2c002ec9f1c2', 'installationId': '4589c86c-7c3b-4188-86f1-13ee7d6298fa', 'sessionId': 'd0263246-baed-4585-8736-841018b3fb48', 'executionEnvironment': 'CLI', 'pyversion': '3.8.2', 'samcliVersion': '0.47.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result

The debugger pauses at the breakpoint

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Pro 1909
2. `sam --version`: SAM CLI, version 0.47.0

**Comment by jfuss** [comment]
@rupe120 My initially recommendation is to just us the [AWS Toolkit for VSCode](https://aws.amazon.com/visualstudiocode/) as it handles everything you need (building and debugging).

Your debug config is incorrect, specifically your `localRoot`. From the docs: "localRoot: This path is to be mounted in the Docker container, and needs to have both the application and dependencies at the root level.". When you use `sam build`, the function code we mount is within `.aws-sam/build/<logicalId>` not `.aws-sam/build`. So VSCode won't be able to find the source correctly and therefore debugging will not work.

Two options:
1. You can keep with building and maintain a launch config for each function.
2. Just use AWS Toolkit for VSCode and let that do the leg work for you. 

My recommendation is the second, as AWS Toolkit will use SAM CLI under the hood and provide a better IDE experience than you manually maintaining all the correct configs.

**Comment by rupe120** [comment]
Thank you! I am able to debug an app that I create from the Command Palette "AWS: Create new SAM Application", though I don't receive the CodeLens links on my `lambda_handler` method in my referenced repository and I don't see what is different. 

I'm able to successfully `sam build` and run a `sam local invoke` on the project, so I know the configuration works.

Any thoughts?

**Comment by rupe120** [comment]
Additionally the CodeLens stops working after I try to add the layer folder structure to the newly created SAM application, where it was working initially. I didn't even get so far as to add the definition to the `template.yaml` yet. I added a `shared_layer1/python` folder path, a basic `my_helper.py` in that folder, and a `.env` file along side the `template.yaml` file to include the layer logic.  Somewhere in those steps CodeLens stopped working, and even when I remove those things it does not come back. 

I'm using the following versions:
AWS Toolkit 1.8.0
VS Code 1.44.2
SAM cli 0.47.0

**Comment by rupe120** [comment]
Apparently there are many other issues as well 

https://github.com/aws/aws-toolkit-vscode/issues/746

I'm going to close this since it seems this is a Toolkit bug and not a SAM bug

**Comment by tobiasfeil** [comment]
This works (without the Toolkit as well) when removing the `build` at the end of the `"localRoot"`, as opposed to the docs [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html). Please fix as soon as possible. I found this by following the steps [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html), which provide the right path for `localRoot`.
