### ISSUE TITLE
Homebrew does not have aws-sam-cli

### ISSUE THREAD

**Issue by challapradyumna** [awslabs/aws-sam-cli#1927]
### Description

Homebrew does not have aws-sam-cli formula

### Steps to reproduce

run `brew install aws-sam-cli

### Observed result

Error: No available formula with the name "aws-sam-cli"

### Expected result

Install aws-sam-cli on macOS

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Catalina 10.15.4
2. Homebrew Version:  2.2.13

**Comment by webkhung** [comment]
@challapradyumna I have the same issue.  Is this resolved?

**Comment by challapradyumna** [comment]
first add the brew tap
`brew tap aws/tap`

**Comment by spuds51** [comment]
Have same issue (after running brew tap aws/tap), output ..

$ brew upgrade aws-sam-cli                                                                                                                                                                 
Error: aws/tap/aws-sam-cli not installed

**Comment by Roy-VZ** [comment]
@spuds51 - I had the same issue
after that I just wrote **brew install aws-sam-cli** although I though it was already installed and it worked.
