### ISSUE TITLE
sam deploy --parameter-overrides doesn't receive underbar contained key

### ISSUE THREAD

**Issue by hangingman** [awslabs/aws-sam-cli#1937]
### Description

sam-cli doesn't receive environment key containing underbar while we can set such keys on AWS Lambda.

### Steps to reproduce

```
// Prepare a template.yml containing 'AWS::Serverless::Function' as Type

$ sam deploy --parameter-overrides "TEST_=a"

Then I got following error messages.

Usage: sam deploy [OPTIONS]
Try 'sam deploy --help' for help.

Error: Invalid value for '--parameter-overrides':  TEST_=a is not in valid format. It must look something like 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'
```

### Observed result

Please provide command output with `--debug` flag set.

```
$ sam deploy --debug --parameter-overrides "TEST_=a"
Usage: sam deploy [OPTIONS]
Try 'sam deploy --help' for help.

Error: Invalid value for '--parameter-overrides':  TEST_=a is not in valid format. It must look something like 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'
```

### Expected result

We should able to set under bar contained string as an environment variable. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`:
```
$ sam --version
SAM CLI, version 0.47.0
```

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@hangingman `--parameter-overrides` is to allow you to override the Parameter section in the template. CloudFormation does not allow `_` in the key only alphanumeric values: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-requirements

Closing as this is a requirement made by CloudFormation itself.
