### ISSUE TITLE
sam validate fails when adding UsagePlan to Auth object in AWS::Serverless::Api resource

### ISSUE THREAD

**Issue by piersf** [awslabs/aws-sam-cli#1944]
### Description

`sam validate` fails when adding `UsagePlan` to `Auth` object in `AWS::Serverless::Api` resource. However, `sam deploy` does not have any issues in deploying.

Error:
```Error: [InvalidResourceException('AccountManagementApi', "Invalid value for 'Auth' property")] ('AccountManagementApi', "Invalid value for 'Auth' property")```

### Steps to reproduce

Running `sam validate` for the below resource will reproduce the error:

```
AccountManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${environment}-${ApiName}"
      StageName: !Ref ApiStageName
      Auth:
        UsagePlan:
          UsagePlanName: !Sub "${environment}-${ApiName}-api-usage-plan"
          CreateUsagePlan: PER_API
```

### Observed result
Error:
```Error: [InvalidResourceException('AccountManagementApi', "Invalid value for 'Auth' property")] ('AccountManagementApi', "Invalid value for 'Auth' property")```

### Expected result

Validation should succeed as this is a supported configuration.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: `RedHat 7`
2. `sam --version`: `SAM CLI, version 0.41.0`
3. Python version: `Python 3.7.4`

`Add --debug flag to command you are running`: Adding `--debug` flag does not output anymore info other than the above error.

**Comment by jfuss** [comment]
@piersf Did you try using a newer version of SAM CLI? If you are seeing this error but is deployable, the version of the spec (which is tied to the version of the cli) is outdated.

**Comment by piersf** [comment]
@jfuss thank you for the quick response. Upgrading to the latest version of SAM CLI fixed the issue.

For anyone else that might run into the same issue, upgrading to at least version `0.47.0` fixes the issues described above.

Closing this issue.
