### ISSUE TITLE
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### ISSUE THREAD

**Issue by lisandrolan** [awslabs/aws-sam-cli#1949]
### Description

Every time I try to run any of the SAM commands, I get the error 
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### Steps to reproduce

Im running the following command

sam package --template ./0.AWSCF/templateCognito.yaml --output-template-file cloudformation.yaml --s3-bucket sqsosam --region us-east-1 && sam deploy --template-file cloudformation.yaml --stack-name sqsoCognitoSAM --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --region us-east-1 

### Observed result

Error: Unable to upload artifact ../CognitoPostConfirmation/ referenced by CodeUri parameter of CognitoPostConfirmationFunction resource.   
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### Expected result
The correct result

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:0.47.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@lisandrolan `sam package` needs credentials that allow uploading of zips to S3. If your credentials being used do not have that access, then you will see this error. 

Make sure you are running with credentials that allow `PutObject` to S3.

**Comment by lisandrolan** [comment]
Hi,
The related user has AdministratorAccess policy.

**Comment by jfuss** [comment]
@lisandrolan Then your bucket is not configured to allow that user access. This is not an issue with the CLI and is an issue with your S3 bucket or user/role you are using to upload.

**Comment by lisandrolan** [comment]
The problem was the name of the bucket.
Thanks.

**Comment by Unkas82** [comment]
>The problem was the name of the bucket
What precisely was wrong with the name of the bucket? :thinking_face:

**Comment by TDaglis** [comment]
> > The problem was the name of the bucket
> 
> What precisely was wrong with the name of the bucket?

@Unkas82 even if the credentials used for the sam command have administrator access, there can be cases where you get permission denied. Some examples are:
- The bucket has a resource policy that denies uploads
- The bucket does not exist
- The bucket is owned by a different AWS account and has no cross-sharing policies that allow PutObject to your account

So if you provide a bucket name in `--s3-bucket` that is either not yours, doesn't exist, has a typo, etc., you will get a Permission Denied error.
