### ISSUE TITLE
SAM CLI returns null if no output results instead of empty string or success message

### ISSUE THREAD

**Issue by maveius** [awslabs/aws-sam-cli#1950]
### Description
After call `sam invoke MyFunction --template my/path/to/template.yaml --event "/sqs.json"`
Output returns null if no message or errors

### Steps to reproduce
Execute `sam invoke MyFunction --template my/path/to/template.yaml --event "/sqs.json"`

### Observed result
Output returns null if no message or errors when no debug flag.

with `--debug` flag:
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 44176, 'exitReason': 'success', 'exitCode': 0, 'requestId': 'a6e41842-7ca2-4bc6-9adb-a3404a365d83', 'installationId': '2facdfe6-3a4b-4380-976d-e218d0b7beb2', 'sessionId': '75429bac-fed6-48bf-ac06-121ad8893d3e', 'executionEnvironment': 'CLI', 'pyversion': '3.7.7', 'samcliVersion': '0.47.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

### Expected result
When no message, errors and exceptions then should return empty content instead of `null`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux_x64_5.6.7-1-MANJARO
2. `sam --version`: SAM CLI, version 0.47.0

**Comment by sriram-mv** [comment]
sam local invoke attempts to best mimic the actual lambda experience, running a function which does not return anything on lambda, also returns null, so the fidelity here is maintained.
