### ISSUE TITLE
`sam deploy --guided` doesn't seem to respect additional CLI args

### ISSUE THREAD

**Issue by afoeder** [awslabs/aws-sam-cli#1955]
### Steps to reproduce

Both invoke
a) `sam deploy --guided --capabilities CAPABILITY_AUTO_EXPAND`
b) `sam deploy                 --capabilities CAPABILITY_AUTO_EXPAND`

### Observed result

a) Deployment process is invoked with `capabilities = "CAPABILITY_IAM"`
b) Deployment process is invoked with `capabilities = "CAPABILITY_AUTO_EXPAND"`

### Expected result

Should be `CAPABILITY_AUTO_EXPAND` also in case a). 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: `SAM CLI, version 0.48.0`

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Guided is currently a walkthrough process and you cant explicitly set those arguments that will be asked as questions during the walkthough process. However, this is a good request and I definitely see the value add. Marking it as a request.

**Comment by wayne-folkes** [comment]
It would be helpful if the guided mode gave you an option to pick the type of capability you needed. In that wizard because it will just use `CAPABILITY_IAM` by default.

**Comment by jfuss** [comment]
Reopening since the PR is merged but not released.

**Comment by mndeveci** [comment]
Patched in [0.53.0 release](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.53.0), closing
