### ISSUE TITLE
sam deploy hangs with SAM CLI version higher than 0.41.0

### ISSUE THREAD

**Issue by piersf** [awslabs/aws-sam-cli#1960]
### Description

We have noticed a strange behavior when upgrading SAM CLI to any version higher than `0.41.0`.
The `sam deploy` command hangs for a long time without doing/outputting anything.

Even at this point, we have a `sam deploy` process on a VM still running after 2 days. We haven't killed the process in order to be able to troubleshoot.

This happens(for us) with every version higher than `0.41.0`. With versions prior to `0.41.0`, we don't see this behavior.

We are running SAM CLI inside a Python virtual environment. At first, we thought this could be the version of Python inside the virtual environment(`3.7.4`). So we created a virtual environment with Python `3.7.7`. But the problem still remained and this did not make a difference.

The command we are running is:

```
/path/to/virtualenv/bin/python3.7 /path/to/virtualenv/bin/sam deploy --region REGION --profile PROFILE --template-file /path/to/packaged/template.yaml --stack-name STACK_NAME --s3-bucket S3_BUCKET_NAME --s3-prefix S3_BUCKET_PREFIX --capabilities CAPABILITY_NAMED_IAM --tags Name=value --parameter-overrides Parameter1=value1 Parameter2=value2 Parameter3=value3 ParameterN=valueN --no-fail-on-empty-changeset
```

Looking at the CloudFormation console while the `sam deploy` command is hanging, there's no stack update happening whatsoever.

We tried to add the `--debug` flag, but no additional output is being shown.

I want to point out that with versions prior to `0.41.0` the deployment works just fine. We don't experience the same behavior.

Is there something wrong with our command above? Are we missing some kind of flag that is required with versions higher than `0.41.0`?

Has anyone else experienced something similar? As a result of this, we're unable to go any higher than version `0.41.0`.

### Steps to reproduce

Upgrade to SAM CLI version > `0.41.0` and run `sam deploy`

### Observed result

`sam deploy` with SAM CLI version higher than `0.41.0` hangs

### Expected result

`sam deploy` with SAM CLI version higher than `0.41.0` should not hang

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: `Redhat 7, Debian`
2. `sam --version`: `0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0`
3. Python version: `3.7.4, 3.7.7`

Thank you in advance!

**Comment by c2tarun** [comment]
A similar issue was reported [here](https://github.com/awslabs/aws-sam-cli/issues/1845) which is causing sam-cli to hang if long tag value (30+ characters) is passed. However, the sam command you shared do not have long tag value. Can you please confirm if the tag value you are seeing issue with is long or short?

**Comment by piersf** [comment]
@c2tarun thank you for your reply.

Yes, the tag value I shared above was just an example as I didn't want to share the real values. But I can confirm that I have tags that are longer than 30 characters.

Any idea when a fix could be ready? I guess a lot of people could be stuck on version `0.41.0` because of this.

**Comment by c2tarun** [comment]
We just released v0.49.0. Sorry for the delay, you should be able to upgrade now.

**Comment by piersf** [comment]
Superb! Thank you very much!

**Comment by simoroma** [comment]
I noticed that my `sam deploy` is hanging even if the Cloudformation shows `UPDATE_COMPLETE`.

`SAM CLI, version 1.79.0`
