### ISSUE TITLE
Function Handler in Subdirectory

### ISSUE THREAD

**Issue by destinybonavita** [awslabs/aws-sam-cli#1962]
### Description

I'm trying to use the SAM Local CLI to create my cloud-formation stack and I'm having issues having my function handlers in subdirectories. Executing `sam local start-api`  runs fine, but when I execute the api it can't detect any node modules or other files in the parent directory. 

### Steps to reproduce

1. Use `sam local init` to create NodeJS stack
Use the below to reproduce creating the project
```
Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1

Which runtime would you like to use?
        1 - nodejs12.x
        2 - python3.8
        3 - ruby2.7
        4 - go1.x
        5 - java11
        6 - dotnetcore3.1
        7 - nodejs10.x
        8 - python3.7
        9 - python3.6
        10 - python2.7
        11 - ruby2.5
        12 - java8
        13 - dotnetcore2.1
        14 - dotnetcore2.0
        15 - dotnetcore1.0
Runtime: 1

Project name [sam-app]: 

Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git

-----------------------
Generating application:
-----------------------
Name: sam-app
Runtime: nodejs12.x
Dependency Manager: npm
Application Template: hello-world
Output Directory: .

Next steps can be found in the README file at ./sam-app/README.md
```
2. Under `sam-app/hello-world` create a folder called `example`
3. Move `sam-app/hello-world/app.js` into `sam-app/hello-world/example/app.js`
4. Update `sam-app/template.yaml` to reflect for the change
5. Create file `sam-app/hello-world/temp.js` with the below contents:
```javascript
exports.ping = () => { return "Worked!" }
```
6. Add the below to the top of `sam-app/hello-world/example/app.js`
```javascript
console.log(require('../temp.js').ping())
```
7. Execute `sam local start-api` 
8. Call `/hello` in a browser or Postman

### Observed result

`sam-app/hello-world/temp.js` will fail to be found.

### Expected result

`sam-app/hello-world/temp.js` is found successfully and writes "Worked!" to the console.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.15.4 (19E287)
2. `sam --version`: SAM CLI, version 0.48.0

**Comment by timoschilling** [comment]
It must be `console.log(require('./temp.js').ping())`

**Comment by destinybonavita** [comment]
Since the file is in the parent directory, it would have to be `require('../temp.js')`

**Comment by timoschilling** [comment]
Following your description it's in the same directory.
> 3. `sam-app/hello-world/app.js`

> 5. `sam-app/hello-world/temp.js`

**Comment by destinybonavita** [comment]
My mistake I apologize. I had just updated the example

**Comment by timoschilling** [comment]
A Lambda can't load code from outside the directory.

If you want to make code sharing, you maybe can resolve your issue by using layers.

**Comment by michaelj-smith** [comment]
Another option for NodeJS is to webpack your lambdas into a "dist" directory, then you can pack each lambda in separate subdirectories and have shareable code between the lambdas in the same stack.

I understand this isn't what the OP is asking for, but I'll include the snippets to make this possible:

In the SAM template, define CodeUri on your functions like such:

```
  resLambdaHealthGet: # Name each lambda logical id something unique to this template
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      FunctionName: !Sub "${paramEnvironment}${paramFeatureBranch}_${paramServiceName}_healthGet" # Use the handler filename at the end
      CodeUri: dist/healthGet  # Use the filename of your handler, e.g. "healthGet.ts", but without the file extension
```

In your webpack config, create separate packages for each handler:

```
const path = require("path");
const fs = require("fs");

class ConfigBase {
  constructor() {
    this.target = "node";

    // Read in all of the files in the Handlers directory.
    // These are the entrypoints and we will create a webpack bundle for each one.
    let handlersDir = "./src/_lambda-handlers"; // Change this if you want to put handlers in a different location
    const files = fs.readdirSync(handlersDir);

    const entries = {};
    files.forEach(function(filename) {
      // Each file in the _lambda-handlers directory is an "entry" point
      // Except for the .spec files
      if (!filename.match(/\.spec\.[jt]s/i)) {
        entries[filename.split(".")[0]] = `${handlersDir}/${filename}`;
      }
    });

    this.entry = entries;

    this.output = {
      libraryTarget: "commonjs2",
      path: path.resolve(__dirname, "../dist"),
      filename: "[name]/handler.js"
    };

    this.resolve = {
      extensions: [".js", ".json"]
    };

    this.module = {
      rules: []
    };
  }
}

module.exports = ConfigBase;
```

**Comment by destinybonavita** [comment]
I was hoping to be able to segregate specific APIs into their own folder for organization purposes. Example:

root/
       src/
             api/
                   api1.js
                   api2.js
            root.js

**Comment by destinyb-realityi** [comment]
I was hoping to be able to segregate specific APIs into their own folder for organization purposes. Example:

root/
       src/
             api/
                   api1.js
                   api2.js
            root.js

**Comment by michaelj-smith** [comment]
You can do whatever structure you want, if you're using the webpack approach. You'll need to adjust the webpack config to match your structure. When you deploy, each lambda needs to be a single .zip file with all the code in it.

**Comment by c2tarun** [comment]
I am closing this issue. Please re-open if you have more questions.
