### ISSUE TITLE
Getting Error: Object cannot be parsed into a string. Raw object: {Fn::FindInMap=[RegionMap, {Ref=AWS::Region}, bucketname]} when trying to publish template

### ISSUE THREAD

**Issue by SumoSourabh** [awslabs/aws-sam-cli#1975]
### Description
When trying to publish SAM app using a CF template, getting issue as Object cannot be parsed into a string. Raw object: {Fn::FindInMap=[RegionMap, {Ref=AWS::Region}, bucketname]} .

I am using serverless function resource with bucket as combination of findinmap as below
  SumoLogicHelperFunction:
    Type: 'AWS::Serverless::Function'
    Condition: do_not_use_parent_stack
    Properties:
      FunctionName: !Join
        - ""
        - - !Sub "sumo-lambda-${Section2aAccountAlias}-"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split ["/", !Ref "AWS::StackId"]
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - bucketname
        Key: "sumologic-aws-observability/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelper.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn

### Steps to reproduce

Use the above Resource and try to publish the sam app.

### Observed result

Please provide command output with `--debug` flag set.

Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Publish Failed
Failed to publish application to serverlessrepo
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serverlessrepo/publish.py", line 45, in publish_application
    response = sar_client.create_application(**request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateApplication operation: Object cannot be parsed into a string. Raw object: {Fn::FindInMap=[RegionMap, {Ref=AWS::Region}, bucketname]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/samcli/commands/publish/command.py", line 77, in do_cli
    publish_output = publish_application(template_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serverlessrepo/publish.py", line 50, in publish_application
    raise _wrap_client_error(e)
serverlessrepo.exceptions.ServerlessRepoClientError: Object cannot be parsed into a string. Raw object: {Fn::FindInMap=[RegionMap, {Ref=AWS::Region}, bucketname]}
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam publish', 'duration': 2930, 'exitReason': 'ServerlessRepoClientError', 'exitCode': 1, 'requestId': 'e5cfe0b9-d3e6-4594-907d-e8764cda5973', 'installationId': '8590c35b-73ba-4143-ab38-1cd91776b337', 'sessionId': '44464003-11bb-43cc-9902-ed891eb97a40', 'executionEnvironment': 'CLI', 'pyversion': '3.7.1', 'samcliVersion': '0.48.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Object cannot be parsed into a string. Raw object: {Fn::FindInMap=[RegionMap, {Ref=AWS::Region}, bucketname]}
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-

### Expected result

App should be published.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Mojave
2. `sam --version`: SAM CLI, version 0.48.0

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Do cfn lint or sam validate, indicate that there are no errors with the template?

**Comment by jfuss** [comment]
@SumoSourabh SAR expects the `CodeUri.Bucket` to be a string. Mappings (or any other intrinsic functions) are only evaluated by AWS CloudFormation deploy (create-stack or update-stack). SAR can't evaluate them when the app is published and therefore must restrict this field.

In order to publish the app to SAR, you will need to remove the FindInMap to an S3 Uri. The easiest way to do this would be to: 
1. Point CodeUri to the local directory the code lives in.
2. Run `sam package -o packaged.yaml` with that updated template.
3. Run `sam publish -t package.yaml` to publish to SAR.

Closing as this is a constraint on the Serverless Application Repo service itself.
