### ISSUE TITLE
0.49.0 brew issue

### ISSUE THREAD

**Issue by mrichman** [awslabs/aws-sam-cli#1987]
While upgrading 0.48.0 to 0.49.0, an error in the URL gives a 404, which forces brew to build from source:

```
==> Upgrading 1 outdated package:
aws/tap/aws-sam-cli 0.48.0 -> 0.49.0
==> Upgrading aws/tap/aws-sam-cli 0.48.0 -> 0.49.0
==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.48.0//aws-sam-cli-0.49.0.sierra.bottle.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/awslabs/aws-sam-cli/releases/download/v0.48.0//aws-sam-cli-0.49.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://api.github.com/repos/awslabs/aws-sam-cli/tarball/v0.49.0
==> Downloading from https://codeload.github.com/awslabs/aws-sam-cli/legacy.tar.gz/v0.49.0
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/aws-sam-cli--homebrew-virtualenv-20200514-57734-1ap59xn/target --install-scripts=/private/tmp/aws-sam-cli--homebrew-virtualenv-20200514-57734-1ap59xn/target
==> python3 -s /private/tmp/aws-sam-cli--homebrew-virtualenv-20200514-57734-1ap59xn/target/bin/virtualenv -p python3 /usr/local/Cellar/aws-sam-cli/0.49.0/libexec
==> /usr/local/Cellar/aws-sam-cli/0.49.0/libexec/bin/pip install pip==19.2.3
==> /usr/local/Cellar/aws-sam-cli/0.49.0/libexec/bin/pip install -v --ignore-installed /private/tmp/aws-sam-cli-20200514-57734-zvwuv8/awslabs-aws-sam-cli-2f46818
==> /usr/local/Cellar/aws-sam-cli/0.49.0/libexec/bin/pip uninstall -y aws-sam-cli
==> /usr/local/Cellar/aws-sam-cli/0.49.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/aws-sam-cli-20200514-57734-zvwuv8/awslabs-aws-sam-cli-2f46818
🍺  /usr/local/Cellar/aws-sam-cli/0.49.0: 6,223 files, 81.1MB, built in 1 minute 39 seconds
Removing: /usr/local/Cellar/aws-sam-cli/0.48.0... (4,719 files, 70MB)
Removing: /Users/mark/Library/Caches/Homebrew/aws-sam-cli--0.48.0.sierra.bottle.tar.gz... (11.6MB)
```

**Comment by dougbergh** [comment]
Same happens when installing aws-cli for the first time:

`% brew --version
Homebrew 2.2.16
Homebrew/homebrew-core (git revision 0fe2e33; last commit 2020-05-15)
Homebrew/homebrew-cask (git revision 3367f; last commit 2020-05-15)
dougbergh@192 wave % brew tap aws/tap
Updating Homebrew...
dougbergh@192 wave % brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.48.0//aws-sam-cli-0.49.0.sierra.bottle.tar.gz
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/awslabs/aws-sam-cli/releases/download/v0.48.0//aws-sam-cli-0.49.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/gdbm not present or broken
Please reinstall gdbm. Sorry :(
`
...and, adding insult to injury, the build from source fails...

**Comment by dlaudams** [comment]
The version in the path (v0.48.0) does not match the version in the filename (v0.49.0):

>     ==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.48.0//aws-sam-cli-0.49.0.sierra.bottle.tar.gz

**Comment by dlaudams** [comment]
There seems to be an issue with the installer: https://github.com/aws/homebrew-tap/issues/84

As a work-around you can force the install of the previous version (0.48.0):

```
cd /usr/local/Homebrew/Library/Taps/aws/homebrew-tap
git reset --hard 9ddfdddbe1fed52940f9561ed04618682d5b24b2
HOMEBREW_NO_AUTO_UPDATE=1 brew install aws-sam-cli
```

**Comment by c2tarun** [comment]
Hi @dlaudams and @mrichman ,

Thanks for reporting this issue, we were in middle of our release when we ran into another issue. I have fixed brew tap for now, it defaults to install version `0.48.0`. Will update brew again once release 49 is successful.

Thanks
Tarun

**Comment by aashutoshbane** [comment]
`Admin@Admin:~$ brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /home/ashutosh/.cache/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> Downloading https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1
==> Downloading from https://codeload.github.com/aws/aws-sam-cli/legacy.tar.gz/v1.3.1
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1
Admin@Admin:~$ 
`

**Comment by svenzon** [comment]
I'm currently trying to install aws-sam-cli, but I keep this error. This is on MacOS Catalina.

```
❯ brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://homebrew.bintray.com/bottles/python%403.7-3.7.9.catalina.bottle.tar.gz
Already downloaded: /Users/anderssvensson/Library/Caches/Homebrew/downloads/fa2b5c403c691e0df2ff7150396f5906c6a82e74b21b68784523b7164452ace7--python@3.7-3.7.9.catalina.bottle.tar.gz
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.sierra.bottle.tar.gz
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://homebrew.bintray.com/bottles/python%403.7-3.7.9.catalina.bottle.tar.gz
Already downloaded: /Users/anderssvensson/Library/Caches/Homebrew/downloads/fa2b5c403c691e0df2ff7150396f5906c6a82e74b21b68784523b7164452ace7--python@3.7-3.7.9.catalina.bottle.tar.gz
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /Users/anderssvensson/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> Downloading https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1
==> Downloading from https://codeload.github.com/aws/aws-sam-cli/legacy.tar.gz/v1.3.1
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1
```

**Comment by bonovoxly** [comment]
Hit this as well.

**Comment by linghuiluo** [comment]
me too

**Comment by khoyee** [comment]
This issue is now closed.
I think we should follow this one instead:
https://github.com/aws/aws-sam-cli/issues/2247
