### ISSUE TITLE
sam build is stuck in Mounting ....

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [awslabs/aws-sam-cli#1994]
### Description

E:\zxf\software\aws-sam-cli\bin\sam.cmd build function --template E:\zxf\git-project\aws-lambda-developer-guide\sample-apps\java-events\template-mvn.yml --build-dir E:\zxf\git-project\aws-lambda-developer-guide\sample-apps\java-events\.aws-sam\build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='function' and CodeUri='target/java-events-1.0-SNAPSHOT.jar'
Building resource 'function'
Looking for a supported build workflow in following directories: ['E:\\zxf\\git-project\\aws-lambda-developer-guide\\sample-apps\\java-events\\target\\java-events-1.0-SNAPSHOT.jar', 'E:\\zxf\\git-project\\aws-lambda-developer-guide\\sample-apps\\java-events']
Cannot convert host path 'E:\zxf\git-project\aws-lambda-developer-guide\sample-apps\java-events' to its equivalent path within the container. Host path is not mounted within the container

Fetching lambci/lambda:build-java8 Docker container image......
Mounting E:\zxf\git-project\aws-lambda-developer-guide\sample-apps\java-events\target\java-events-1.0-SNAPSHOT.jar as /tmp/samcli/source:ro,delegated inside runtime container

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 10
2. `sam --version`: 0.48.0
3. `docker --version`: 19.03.8

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
Is your E drive shared in your docker setttings?

**Comment by zxf-thingsmatrix** [comment]
![image](https://user-images.githubusercontent.com/65008815/82274218-128ef600-996f-11ea-9c02-332443d111ea.png)
Seems like this...

**Comment by zxf-thingsmatrix** [comment]
> 
> 
> Is your E drive shared in your docker setttings?

![image](https://user-images.githubusercontent.com/65008815/82274329-68fc3480-996f-11ea-9be3-fca7f4bb3b9d.png)
Seems like this...

**Comment by sriram-mv** [comment]
I have seen that sometimes even though docker states it has shared the entire drive, the user directory within that drive is the one that was actually shared.

**Comment by sriram-mv** [comment]
Closing this issue, feel free to re-open it, if you are still facing the issues.

**Comment by RajeswariRamadossTR** [comment]
Hi 

We have been facing this issue in our team where the build freezes on the "Mounting" phase of a lambda for almost 45 minutes before it proceeds to the next step. We have tried with three SAM versions and we see this behavior in all three versions. It is intermittent and happens sometimes on java lambda and sometimes on python lambdas. We have to kill the session and restart the build when it happens. Please see the build logs below.  Thanks!

**Parameters used for sam build** 
--use-container --debug --skip-pull-image

**PC Configuration and versions**
SAM CLI, version - 1.15.0,  1.17.0, 1.18.0
aws cli - aws-cli/2.1.17
Windows PC - Windows 10 Enterprise 
OS build - 10.0.19041, RAM -32 GB, 
Docker Engine -20.10.2 with WSL2

**Build Logs**
2021-03-10 14:09:11,217 | Mounting C:\....\lambdas\java\xslt_conversion as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'JavaGradleWorkflow' to support capabilities 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Running workflow 'JavaGradleWorkflow'
Running JavaGradleWorkflow:GradleBuild
JavaGradleWorkflow:GradleBuild succeeded
Running JavaGradleWorkflow:CopyArtifacts
JavaGradleWorkflow:CopyArtifacts succeeded
2021-03-10 14:14:04,974 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
2021-03-10 14:14:04,975 | Build inside container was successful. Copying artifacts from container to host
2021-03-10 14:14:05,281 | Copying from container: /tmp/samcli/artifacts/. -> C:\....\templates\automated-normalization-template\.aws-sam\build\RunXSLTFunction
2021-03-10 14:14:08,717 | Build inside container succeeded
2021-03-10 14:14:08,720 | Building codeuri: ../lambdas/job/convert_html_to_xhtml/ runtime: python3.8 metadata: {} functions: ['ConvertHTMLtoXHTML']
2021-03-10 14:14:08,720 | Building to following folder C:\....\templates\automated-normalization-template\.aws-sam\build\ConvertHTMLtoXHTML
2021-03-10 14:14:08,734 | Requested to skip pulling images ...

2021-03-10 14:14:34,084 | Mounting C:\....\lambdas\job\replace_unicode_characters as /tmp/samcli/source:ro,delegated inside runtime container
