### ISSUE TITLE
Incorrect inline help in "sam local generate-event" command

### ISSUE THREAD

**Issue by FrcMoya** [awslabs/aws-sam-cli#1999]
### Describe your idea/feature/enhancement

Using the CLI I had some problems with the inline help of the command "sam local generate-event". I was trying to pipe the event generated by that command with "sam local invoke" and it failed. The part of the inline help that it is incorrect is this:

`{...} After you generate a sample event, you can use it to test your Lambda function locally
  $ sam local generate-event s3 [put/delete] --bucket <bucket> --key <key> | sam local invoke <function logical id> {...}`

In the web documentation here (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-generate-event.html) the help is correct:

`After you generate a sample event, you can use it to test your Lambda function locally
sam local generate-event s3 [put/delete] --bucket <bucket> --key <key> | sam local invoke -e - <function logical id>`
### Proposal

Replace the incorrect help by the correct one.

**Comment by sriram-mv** [comment]
Thanks for submitting this! Looks to be a quick fix, would be glad to take in a PR for this :)

**Comment by FrcMoya** [comment]
Fixed with PR #2007
