### ISSUE TITLE
11:51	Error running '[Local] xxx': SAM build command failed

### ISSUE THREAD

**Issue by uday-docsynk** [awslabs/aws-sam-cli#2001]
### Description

Sam build command keeps failing every now and then  I keep restarting my docker to ensure it doesnt fail. 

### Observed result

11:41	Error running '[Local] xxx': SAM build command failed

11:51	Error running '[Local] xxx': SAM build command failed

11:51	Error running '[Local] xxx': SAM build command failed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 10
2. `sam --version`: 0.50

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Is this a docker mounting issue? are you running on a container?

**Comment by jfuss** [comment]
Closing due to no response.

**Comment by Hiskrtapps** [comment]
I have the same problem (and all my colleagues have too).
Maybe it is connected to this: https://github.com/aws/aws-toolkit-jetbrains/issues/1473#issuecomment-601320805
Can we reopen the issue?
