### ISSUE TITLE
When using swagger definition don't inject integrations

### ISSUE THREAD

**Issue by janza** [awslabs/aws-sam-cli#201]
Serverless application model [doesn't inject integrations](https://github.com/awslabs/serverless-application-model/issues/5#issuecomment-262039699) when using a swagger definition for `AWS::Serverless::Api`. 

aws-sam-local seems to do exactly that making it confusing when doing local development and later finding out that something is wrong.

**Comment by SAPessi** [comment]
This should be fixed in #222. To make sure, could you share your SAM template?

**Comment by sanathkr** [comment]
This is available in v0..3.0. Closing the issue
