### ISSUE TITLE
Save save_to_config to samconfig.toml

### ISSUE THREAD

**Issue by f-w** [awslabs/aws-sam-cli#2015]
### Describe your idea/feature/enhancement

I wish SAM CLI would save *save_to_config* to *samconfig.toml* so that the answer to *Save arguments to samconfig.toml* can be defaulted to the saved one rather than hard-coded *True* in guided deploy.

Reason is that *samconfig.toml* is usually version controlled, containing only common shareable configs. Per-invocation variations shouldn't be saved in it. This is achievable had *save_to_config* been set to _false_ in *samconfig.toml* and sam defaults to it.

### Proposal

I think this can be easily implemented by modifying [guided_context.py](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/deploy/guided_context.py) and possibly [guided_config.py](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/deploy/guided_config.py)

**Comment by c2tarun** [comment]
@f-w Can you please explain what do you mean by `Per-invocation variations shouldn't be saved in it`?

I tried invoking `sam deploy --stack-name test2` while my samconfig.toml have stack name as `test1`. Sam deploy did deploy with new stack name bug samconfig.toml was not updated for that invocation.

**Comment by f-w** [comment]
@c2tarun, if instead I run `sam deploy -g` and specify `test2` at prompt, then `test2` will be written to `samconfig.toml` overwriting the version controlled default one. This is what I want to avoid.

**Comment by c2tarun** [comment]
@f-w Can you please explain me your use case in more detail? `sam deploy -g` is expected to be used only when you don't have a guided config. Once you have a config, you can simply override parameters of config by passing them via CLI.

**Comment by f-w** [comment]
@c2tarun, I perceive `sam deploy -g` as the "default" way to run `sam deploy` as it is documented in [getting started tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html) as well as other places for newbies. There is no place saying only use it when you don't have a guided config. In fact it work when `samconfig.toml` exists. Intuitively I expect `samconfig.toml` provides default value for guided deploy.

**Comment by c2tarun** [comment]
Thanks @f-w for providing that feedback, we will work on fixing our documentation to remove this confusion. I'll try to explain a bit here though.

As you already know `sam deploy --guided` generates `samconfig.toml` file. Our intention with `guided deploy` is for developers to use it first time to setup that config. Once that config is setup one should deploy simply by using `sam deploy` command.

For situation where you have to change certain parameters already mentioned in `samconfig` we can simply override them by passing as CLI option.

**Generate config in new project**:
`sam deploy --guided` this will create a config file and trigger a deploy at the end.

**Deploying that project after updates**:
`sam deploy` - for simply deploying new changes and updating the stack,
or `sam deploy --stack-name new-stack-name` - to deploy with different stack name
or `sam deploy --region us-east-1` - to deploy to us-east-1.

I am marking this ticket as resolved as we are tracking documentation issue internally. Please feel free to re-open the ticket if you have more questions.

Thanks
Tarun
