### ISSUE TITLE
Unknown CloudFormation resource type: AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by TannerIsBender** [awslabs/aws-sam-cli#2017]
### Description

I saw this article and tried to create an AWS SAM Step function/State machine, but SAM cannot find the AWS::Serverless::StateMachine resource type. SAM is working for me besides this resource type. I was able to deploy some Lambda functions within a SAM template using sam build and sam deploy. This resource type is just giving me problems.

### Steps to reproduce
I followed this
https://aws.amazon.com/blogs/compute/simplifying-application-orchestration-with-aws-step-functions-and-aws-sam/

I have SAM CLI 0.52.0.
64 bit OS - Windows 10 Enterprise version 1809 

https://gyazo.com/2997af69c8527198e346f20256ae4a1d

![image](https://user-images.githubusercontent.com/10541121/83440523-ed33ca80-a3f9-11ea-9f7a-8d87333efddf.png)

**Comment by jfuss** [comment]
@TannerIsBender SAM CLI doesn't do anything in the IDE's directly, so this isn't an issue with SAM CLI. What tool is doing your linting on your IDE? I would reach out to whatever tool you are using for that, as a place to start.

**Comment by TannerIsBender** [comment]
Thanks for the reply @jfuss ! I am using IntelliJ, I think I found the issue because of your comment. I had the AWS CloudFormation plugin installed.
https://plugins.jetbrains.com/plugin/7371-aws-cloudformation/

Disabling this removed the redline. However, I did try to sam build/deploy before I disabled this plugin and everything still worked.
