### ISSUE TITLE
sam deploy incorrectly displays parameter override when value has a space in it

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [awslabs/aws-sam-cli#2018]
sam version is 0.52.0
Cannot send parameter with whitespace in value

>  sam deploy --template-file sam_output.yaml --stack-name test --parameter-overrides "PARAM__KEY=PARAM VALUE"

but in log I see

> Parameter overrides        : {''PARAM__KEY': 'PARAM'}

Looks like it was not fixed for https://github.com/awslabs/aws-sam-cli/issues/1652

**Comment by Aleksandr-Filichkin** [comment]
Hi @sriram-mv, no. it doesn't help

**Comment by karahanozturk** [comment]
I had similar issue passing an xml file as parameter for SSO and it gets truncated after the first space.
AWS Support also managed to replicate the issue and confirmed it's a bug.
v0.53.0 doesn't work either. Temporary workaround is to downgrade to v0.32.0

**Comment by karahanozturk** [comment]
Can you label this as a bug? This needs more attention

**Comment by awood45** [comment]
Treating as a bug and investigating.

**Comment by awood45** [comment]
I can confirm this bug does not exist, at least for the given example, when using `sam deploy --guided` - consider the following `samconfig.toml`:

```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "issue2018"
s3_bucket = "REDACTED"
s3_prefix = "issue2018"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TestParam=\"hello test\""
```

This works in `0.53.0`.

**Comment by awood45** [comment]
This doesn't preclude the issue in the original issue post, but it's at least a workaround. Looking at the original issue as well.

**Comment by awood45** [comment]
```bash
$ sam deploy --parameter-overrides "TestParam='hello test'"

        Deploying with following values
        ===============================
        Stack name                 : issue2018
        Region                     : us-east-1
        Confirm changeset          : False
        Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-1fme5yordvskg
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {'TestParam': "'hello"}
```

So this issue is confirmed by me as well, will try to see what the difference in behavior is. I can also note that double-quotes seem to behave differently and are another workaround:

```bash
$ sam deploy --parameter-overrides "TestParam=\"hello test\""

        Deploying with following values
        ===============================
        Stack name                 : issue2018
        Region                     : us-east-1
        Confirm changeset          : False
        Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-1fme5yordvskg
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {'TestParam': 'hello test'}
```

**Comment by luchees** [comment]
I'm still experiencing this issue. I've tried several combinations mentionned in the issues but none of them worked for me
"Key1=rate(1 hours)" "Key2=someValue"
"Key1='rate(1 hours)'" "Key2=someValue"
"Key1='rate(1\ hours)'" "Key2=someValue"
"Key1='rate(1\ hours)'" "Key2=someValue"
"Key1=\"rate(1 hours)\"" "Key2=someValue"

**Comment by wchengru** [comment]
Hi @Aleksandr-Filichkin @luchees ,
I have created a pr to support single quoting parameter overrides.
You can use single quotes to wrap string with spaces after this pr is released.

```
$samdev deploy --parameter-overrides "TestParam='hello test'"
	Deploying with following values
	===============================
	Stack name                 : sam-app
	Region                     : us-east-1
	Confirm changeset          : False
	Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-6wsl7tf21dut
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {'TestParam': 'hello test'}
```

```
$ samdev deploy --parameter-overrides "Key1='rate(1 hours)' Key2=someValue"

	Deploying with following values
	===============================
	Stack name                 : sam-app
	Region                     : us-east-1
	Confirm changeset          : False
	Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-6wsl7tf21dut
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {'Key1': 'rate(1 hours)', 'Key2': 'someValue'}
```

**Comment by wchengru** [comment]
PR is released.

**Comment by PalituxD** [comment]
I resolved this scenario using options below: 

`
"scripts": {
    "invoke": "sam ... --parameter-overrides \"$(jq -j 'to_entries[] | \"\\(.key)='\\\\\\\"'\\(.value)'\\\\\\\"''\\ '\"' params.json)\""
  }
`

Or

`
sam ... --parameter-overrides "$(jq -j 'to_entries[] | "\(.key)='\\\"'\(.value)'\\\"''\ '"' params.json)"
`
