### ISSUE TITLE
Split out event generation to separate Go package

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/aws-sam-cli#202]
As suggested by @mweagle [1], it would be nice to split out the Lambda event generation in `event.go` into a separate Go package so it can be used within other applications as a library.

[1] https://twitter.com/mweagle/status/935345253451644928

**Comment by mweagle** [comment]
Thanks for considering this and I'm happy to help PR/review/etc.

**Comment by sanathkr** [comment]
This is already available as a separate Python module in this repo. I haven't seen a lot of interest in this feature. So closing it for now. Feel free to re-open if you are interested in working on this :)
