### ISSUE TITLE
Include latest runtimes on sam-cli 0.52.0

### ISSUE THREAD

**Issue by hardtail29** [awslabs/aws-sam-cli#2025]
This is in followup to "Include support to Nodejs12.x on CLI build #1564"

### running sam init the runtimes included do not include Nodejs12.x.
Which runtime would you like to use?
	1 - nodejs12.x
	2 - python3.8
	3 - ruby2.7
	4 - go1.x
	5 - java11
	6 - dotnetcore3.1
	7 - nodejs10.x
	8 - python3.7
	9 - python3.6
	10 - python2.7
	11 - ruby2.5
	12 - java8
	13 - dotnetcore2.1

Specifically, nodejs12.x is missing.

This is on sam-cli 0.52.0 OS X.  

This was reported to have been fixed in 0.40.0 but as you can see nodejs12.x is missing.

**Comment by johangu** [comment]
`nodejs12.x` is the first one in the list.

> Which runtime would you like to use?
**_1 - nodejs12.x_**
2 - python3.8
3 - ruby2.7

**Comment by jfuss** [comment]
Closing. Please see https://github.com/awslabs/aws-sam-cli/issues/2025#issuecomment-640467076 above.
