### ISSUE TITLE
Region shows as "None" after stack deploys using manual parameters

### ISSUE THREAD

**Issue by jbesw** [awslabs/aws-sam-cli#2028]
### Description

Briefly describe the bug you are facing.

In the Cloud9 IDE, if you deploy using "sam deploy" with manual parameters, and do not supply a region in the command line, it uses the correct region but the output message shows "None". 

Partially described in issue https://github.com/awslabs/aws-sam-cli/issues/1704.

### Steps to reproduce

1. Open Cloud9.
2. Deploy a stack with manual parameters, e.g.:
sam deploy --template-file packaged.yaml --stack-name ride-times --capabilities CAPABILITY_IAM
3. See output message ("Successfully created/updated stack - ride-times in None").

The stack deploys implicitly to the correct region (where the Cloud9 instance is located) but the output message is misleading/wrong.

### Observed result

Please provide command output with `--debug` flag set.

jbeswick@amazon.com:~/environment/theme-park-backend/1-app-deploy/ride-controller (master) $ sam deploy --template-file packaged.yaml --stack-name ride-times --capabilities CAPABILITY_IAM

        Deploying with following values
        ===============================
        Stack name                 : ride-times
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {}

Initiating deployment

### Expected result

It should display the region code where the stack was deployed.

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Cloud9
2. `sam --version`: SAM CLI, version 0.38.0

`Add --debug flag to command you are running`

**Comment by timoschilling** [comment]
maybe related https://github.com/awslabs/aws-sam-cli/issues/1704

**Comment by prenx4x** [comment]
This issue is fixed and merged.
