### ISSUE TITLE
Contribution improvement, add support for GitPod.io

### ISSUE THREAD

**Issue by matdumsa** [awslabs/aws-sam-cli#2030]
### Describe your idea/feature/enhancement

I wish contributing code to SAM CLI would be easier. I once found a one liner to fix and had a hard-time getting the correct set-up required to build it on my local machine and eventually gave up.

The awk-cdk project is now promoting the use of GitPod, a online IDE leveraging containers to make it easy for first time contributors to get started and contribute something to the project. With 1-click, anyone with a GitHub account can launch the project in a pre-configured environment.

### Proposal

1. Add configuration for GitPod
1. Modify the DEVELOPMENT_GUIDE to add a button to launch GitPod

**Comment by awood45** [comment]
Added this via PR, closing!
