### ISSUE TITLE
Building when using a container appears to log information to standard error

### ISSUE THREAD

**Issue by tks816** [awslabs/aws-sam-cli#2036]
When using `sam build --use-container -t template.yaml` in a pipeline, it was failing due to my setting to force the task to fail on stdErr. After researching the logs, I found that all the stdErr messaging was just logged info from prior in the build and every part of the build was successful.

I was able to reproduce this locally as well by directing stdErr to a file:
`sam build --use-container --skip-pull-image -t template.yaml 2> errors.txt` in which I get the following text:

```
Starting Build inside a container
Building resource 'Application'
Requested to skip pulling images ...

Mounting /filepath/src as /tmp/samcli/source:ro,delegated inside runtime container
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
```

The stdout for this was:
```
Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
```

Is this intended?

**Comment by jfuss** [comment]
Yes this is intended. Instead of relying out stderr, you should check the status of the last call.

Closing.
