### ISSUE TITLE
start-api emits max-age header making development difficult

### ISSUE THREAD

**Issue by matdumsa** [awslabs/aws-sam-cli#2037]
### Description

Static files served with start-api through Flask are served with a cache header that makes developing challenging. The default in flask is 43200 seconds. 

### Steps to reproduce

imagine you are switching between several different project, each with a similar structure. You start a project by typing

```
sam local start-api -p 3000 -t template.yaml -s packages/website/build
```

Switching project and opening localhost:3000/index.html always serves an old page rather than the one of the server we are running because of that header. 

### Observed result

```
Cache-Control: public, max-age=43200
```

### Expected result

```
Cache-Control: public, max-age=0
```

Having cached results adds another concept to developer, we receive many reports in our application of "wrong page displayed" even though we explain our dev they must refresh when they start the server. We would like to get rid of this concept all together.

**Comment by sriram-mv** [comment]
https://github.com/awslabs/aws-sam-cli/pull/2038 is merged, closing this issue.
