### ISSUE TITLE
Cannot install aws-sam-local on windows

### ISSUE THREAD

**Issue by sh-rao** [awslabs/aws-sam-cli#204]
Environment:
---------------
node v6.10.0
npm  v5.5.1 (i have tried with npm@3 and npm@4 but with no luck)
OS Windows 7 Enterprise (SP1) x64 bit

This is what the log tells me:

70 verbose stack Exit status 1
70 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at EventEmitter.emit (events.js:191:7)
70 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at ChildProcess.emit (events.js:191:7)
70 verbose stack     at maybeClose (internal/child_process.js:877:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
71 verbose pkgid aws-sam-local@0.2.2

**Comment by burninggoatgames** [comment]
Have you tried downloading the binary?

**Comment by sanathkr** [comment]
> v0.3.0 introduced different installation mechanism. Closing this
