### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - {psycopg2==2.8.5(sdist)}

### ISSUE THREAD

**Issue by bbastia** [awslabs/aws-sam-cli#2043]
### Description
Unable to build project

### Steps to reproduce

sam init runtime python3.7

in requirements.txt 
psycopg2

sam build --debug
### Observed result
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
No Parameters detected in the template
Building function 'HelloWorldFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /Users/biswajit/Desktop/Playground/Test/hello_world/requirements.txt --dest /var/folders/6c/mv2bg0p554nf88mw5dp7kcsc0000gp/T/tmpb0a3rg25
Full dependency closure: {psycopg2==2.8.5(sdist)}
initial compatible: set()
initial incompatible: {psycopg2==2.8.5(sdist)}
Downloading missing wheels: {psycopg2==2.8.5(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/6c/mv2bg0p554nf88mw5dp7kcsc0000gp/T/tmpb0a3rg25 psycopg2==2.8.5
compatible wheels after second download pass: set()
Build missing wheels from sdists (C compiling True): {psycopg2==2.8.5(sdist)}
calling pip wheel --no-deps --wheel-dir /var/folders/6c/mv2bg0p554nf88mw5dp7kcsc0000gp/T/tmpb0a3rg25 /var/folders/6c/mv2bg0p554nf88mw5dp7kcsc0000gp/T/tmpb0a3rg25/psycopg2-2.8.5.tar.gz
compatible after building wheels (no C compiling): set()
Build missing wheels from sdists (C compiling False): {psycopg2==2.8.5(sdist)}
calling pip wheel --no-deps --wheel-dir /var/folders/6c/mv2bg0p554nf88mw5dp7kcsc0000gp/T/tmpb0a3rg25 /var/folders/6c/mv2bg0p554nf88mw5dp7kcsc0000gp/T/tmpb0a3rg25/psycopg2-2.8.5.tar.gz
compatible after building wheels (C compiling): set()
Final compatible: set()
Final incompatible: set()
Final missing wheels: {psycopg2==2.8.5(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.52.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/usr/local/Cellar/aws-sam-cli/0.52.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/Cellar/aws-sam-cli/0.52.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {psycopg2==2.8.5(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.52.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/0.52.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {psycopg2==2.8.5(sdist)}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 10941, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'requestId': '95841b50-c96a-47b3-8705-3c94e33decb3', 'installationId': '74b17ca5-bb1d-4d31-8ba4-af23be476339', 'sessionId': '42cb046f-11de-4448-8059-2f9b3405cdbe', 'executionEnvironment': 'CLI', 'pyversion': '3.7.7', 'samcliVersion': '0.52.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {psycopg2==2.8.5(sdist)}

Please provide command output with `--debug` flag set.

### Expected result

should build sucessfull

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS
2. `sam --version`: SAM CLI, version 0.52.0

**Comment by rriicckk** [comment]
In your requirements.txt file change psycopg2 to aws-psycopg2 

https://github.com/AbhimanyuHK/aws-psycopg2

**Comment by awood45** [comment]
Indeed, this seems like an issue with the requirements document rather than build itself. Closing, feel free to reopen if you're seeing errors after revising the requirements document.

**Comment by smrutiranjantripathy** [comment]
This issue has been fixed in sam  1.26
