### ISSUE TITLE
sam deploy --guided errors with "S3 Bucket does not exist"

### ISSUE THREAD

**Issue by jbesw** [awslabs/aws-sam-cli#2045]
### Description

Using `sam deploy --guided`, the process fails with "Error: S3 Bucket does not exist." 

### Steps to reproduce

1. A developer deployed [this stack](https://github.com/aws-samples/ask-around-me/blob/master/backend/realtime.yaml) using `sam deploy --guided --template-file realtime.yaml`.
2. Output:
Deploying with following values
===============================
        Stack name                 : askAroundMe-realtime
        Region                     : us-east-1
        Confirm changeset          : False
        Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-kll3li4nzc9r
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {}

Initiating deployment
=====================
Error: 
S3 Bucket does not exist.

Provide steps to replicate.

The developer has also renamed the template to template.yaml to avoid the template parameter, with the same result. Then tried after deleting the toml file with the same result.

### Observed result

sam deploy –guided
Deploying with following values
===============================
        Stack name                 : askAroundMe-realtime
        Region                     : us-east-1
        Confirm changeset          : False
        Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-kll3li4nzc9r
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {}

Initiating deployment
=====================
Error: 
S3 Bucket does not exist.

### Expected result

The sam deployment should create a deployment bucket and complete.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:

`Add --debug flag to command you are running`

**Comment by divmgl** [comment]
Were you able to figure this out? This is happening to me because I deleted the S3 bucket that SAM created on AWS when I first ran `guided`, but now it's not recreating that bucket. I'm wondering if there is a way to reset SAM, but removing `.aws-sam` and `~/.aws-sam` did not work.

**Comment by jbesw** [comment]
> Were you able to figure this out? This is happening to me because I deleted the S3 bucket that SAM created on AWS when I first ran `sam deploy --guided`, but now it's not recreating that bucket. I'm wondering if there is a way to reset SAM, but deleting the `.aws-sam` and `~/.aws-sam` directories did not work.

If this is caused by deleting the S3 bucket, I would suggest just recreating the bucket as a workaround. I'm still interested to know where S3 keeps a reference to the bucket after the configuration, build folder and toml files are deleted.

**Comment by sagarpatke** [comment]
In addition to the bucket, your sam deployment also creates two cloudformation stacks. One for keeping track of SAM CLI resources, and the other to track the deployment. Try deleting these as well.

**Comment by sriram-mv** [comment]
SAM looks up a cloudformation stack with the name `https://github.com/awslabs/aws-sam-cli/blob/7ba1b444a926a9771e86d5fd023510f6f07c0ea0/samcli/lib/bootstrap/bootstrap.py#L21` first, and then looks for bucket within the output of that stack.

**Comment by awood45** [comment]
The `sam deploy --guided` process looks for a CloudFormation stack, rather than the bucket, to decide whether or not to create a new bucket (S3 API doesn't give us a good way to search by tags, for example, and since S3 bucket names need to be globally unique this is the approach we need to take). If you're going to delete the S3 bucket, you'll also need to delete the associated stack.

You can, of course, always provide your own S3 bucket via `samconfig.toml` or as a parameter to deployments.

Given that this was filed on another developer's behalf, I think the question would be what the contents of the `aws-sam-cli-managed-default` template are, and if there is a bucket present there and this error persists, please reopen this issue. Otherwise, delete the stack and re-run.

**Comment by amarquezp** [comment]
> In addition to the bucket, a sam deployment also creates two cloudformation stacks. One for keeping track of SAM CLI resources, and the other to track the app's resources. Try deleting these as well.

this worked for me, thanks

**Comment by Nxtra** [comment]
> The `sam deploy --guided` process looks for a CloudFormation stack, rather than the bucket, to decide whether or not to create a new bucket (S3 API doesn't give us a good way to search by tags, for example, and since S3 bucket names need to be globally unique this is the approach we need to take). If you're going to delete the S3 bucket, you'll also need to delete the associated stack.
> 
> You can, of course, always provide your own S3 bucket via `samconfig.toml` or as a parameter to deployments.
> 
> Given that this was filed on another developer's behalf, I think the question would be what the contents of the `aws-sam-cli-managed-default` template are, and if there is a bucket present there and this error persists, please reopen this issue. Otherwise, delete the stack and re-run.

Okay I see. This is what happened to me:

- I previously deployed resources using `sam`
- I cleaned up my s3 buckets in my account and removed the bucket managed by the cloudformation stack of sam
- The cloudformation stack still existed. However, the bucket that was in the stack was deleted
- When using `sam deploy --guided` it told me it had found the necessary resources for deployment. Meaning, it found the stack
- However I couldn't deploy the stack. It gave me an unrelated error message, for example: Unable to upload artifact hello_world/ referenced by CodeUri parameter of HelloWorldFunction resource.
- I deleted the sam deployment stack that originally contained the bucket
- I ran `sam deploy --guided`. This recreated the sam deployment bucket and deploy worked.

**Comment by nquayson** [comment]
> You can, of course, always provide your own S3 bucket via `samconfig.toml` or as a parameter to deployments.

Can someone expand on this? In my case, runing `sam deploy --guided`, sam appears to disregard a custom bucket already defined in `samconfig.toml`. 

Also running `sam deploy` when param `s3_bucket` is defined in `samconfig.toml` recreates
Error: S3 Bucket does not exist. 
It doesn't look too different from [this issue](https://github.com/aws/aws-sam-cli/issues/1701)

**Comment by luiscorujo** [comment]
Deleting the aws-sam-cli-managed-default stack on cloudformation console fixed this for me

**Comment by SecOpsWarrior** [comment]
I am having this same issue because of deleting the original stack and s3 bucket. I looked in cloudformation console, but it says "no stacks to display" as I've deleted everything...any ideas? I don't see the aws-sam-cli-managed-default stack anywhere; am I looking in the wrong place?

**Comment by alramalho** [comment]
Deleting the aws-sam-cli-managed-default is not working for me. This should be reflected immediately, right?

**Comment by Geoide** [comment]
> > In addition to the bucket, a sam deployment also creates two cloudformation stacks. One for keeping track of SAM CLI resources, and the other to track the app's resources. Try deleting these as well.
> 
> This worked for me. Thanks a lot. Go to `CloundFormation` Service -> delete `aws-sam-cli-managed-default` stack

This worked for me too. Thanks.

**Comment by ZakharovAleksey** [comment]
Yep! Thanks a lot. 
Command: `sam delete` made the job.

**Comment by MosesWangira** [comment]
I did the following and everything worked out

`aws cloudformation delete-stack --stack-name **your-stack-name** `
If the above fails, go to aws Console locate your s3 bucket and empty it then re-run the command above

delete `.aws-sam` directory

In CloudFormation on your AWS console make sure `aws-sam-cli-managed-default` is also cleared

Try `sam build` and `sam deploy --guided` - it should deploy your code

**Comment by MosesWangira** [comment]
I did the following and everything worked out

`aws cloudformation delete-stack --stack-name your-stack-name`
If the above fails, go to aws Console locate your s3 bucket and empty it then re-run the command above

delete `.aws-sam` directory

In CloudFormation on your AWS console make sure `aws-sam-cli-managed-default` is also cleared

Try `sam build` and `sam deploy --guided` - it should deploy your code
