### ISSUE TITLE
Is there a way to force the lamba response to not return a response that needs body etc?

### ISSUE THREAD

**Issue by gibtang** [awslabs/aws-sam-cli#2057]
### Describe your idea/feature/enhancement

I am running my Lambda created using Golang and I have a custom response that does not return body etc. If I am running my custom JSON object that does not have the 'body', then it shows an error "Lambda returned empty body!" because of the SAM CLI code checking for the presence of the 'body'.

### Proposal

Add in a flag --use-custom-response so that it will bypass the check of the presence of the 'body' object in the JSON response

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by jfuss** [comment]
@gibtang `sam local start-api` only support the proxy integration of AWS API Gateway and the response must be in this format: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format

That is why the check is there. Are you using the proxy intergration or some other one?

If you want to test the response, you can use `sam local invoke` or `sam local start-lambda` instead.

**Comment by gibtang** [comment]
Ok, understood. Thanks @jfuss
