### ISSUE TITLE
Latest aws-sam-cli boto dependencies are incompatible with latest awscli

### ISSUE THREAD

**Issue by getjack** [awslabs/aws-sam-cli#2063]
# Description

I'd like to keep my software up to date so i run `pip install awscli aws-sam-cli --upgrade --user` every morning. Recently i get errors regarding boto3 and botocore dependencies. Even though those are separate products i'd like them to be compatible to a certain degree but i don't know how. I am not able to use the latest awscli without breaking the aws-sam-cli. A potential workaround would be to create a venv somwhere on my disk.

### Steps to reproduce

Run `pip install awscli aws-sam-cli --upgrade --user`.

### Observed result

Depending on the order either awscli or aws-sam-cli will create a dependency warning for boto3 or botocore.

### Expected result

No dependency issues but this is sort of a wish then a real expectation.

**Comment by jfuss** [comment]
@getjack Installing software into the same python location runs the risk of this happening. This is one reason we do not recommend using pip. If you really want to use pip (and not one of our installers), then you need to install them into different location (venv's) on your system.

Closing as there is no action for us to take here.

**Comment by getjack** [comment]
@jfuss I was not aware that there are installers so thank you for the answer. I'll have a look if that solves the "problem" for me :)
