### ISSUE TITLE
Please provide SAM installation method on Linux other than Homebrew 

### ISSUE THREAD

**Issue by plantusd** [awslabs/aws-sam-cli#2090]
### Describe your idea/feature/enhancement

I understand the installation solution for Mac OS, just can't rationalize pulling relatively big package management system on Ubuntu, just to install aws-sam-cli. 

Is there any updates on this?

**Comment by sriram-mv** [comment]
Closing this issue as its already documented ask: https://github.com/awslabs/aws-sam-cli/issues/1424
