### ISSUE TITLE
Installation of Python via linuxbrew conflicts with linux mint blueberry

### ISSUE THREAD

**Issue by jackcholt** [awslabs/aws-sam-cli#2094]
### Description

Using Linux Mint 20, the bluetooth setting widget (Blueberry) uses the Python3.7 that is installed by default.  Installing AWS SAM CLI via linuxbrew overrides the default install of Python3.  This causes the Blueberry widget to fail to load.  If you run "blueberry" at the command line, you receive the Python error message "ModuleNotFoundError: No module named 'gi'".

I tried "brew uninstall python3" to try to clean it up, and though that allowed blueberry to find the gi module and run successfully, it breaks AWS SAM CLI.  I now get

> /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

When trying to run sam local invoke

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: linux mint 20

**Comment by awood45** [comment]
We'll add this as a +1 to the request for alternative Linux installation options. In the meantime, you can install using `pip` or `pipx`, though we strongly recommend you use a virtualenv when doing so. For example:

```
python3.7 -m venv /usr/local/opt/sam-cli
/usr/local/opt/sam-cli/bin/pip3 install aws-sam-cli
```

Closing this, feel free to reopen if the alternative approach here doesn't work for you.
