### ISSUE TITLE
BUG: --guided flag on deploy fails to recognise inline and samconfig.toml parameters.

### ISSUE THREAD

**Issue by pedrosola** [awslabs/aws-sam-cli#2096]
**Description:**
When using the `--guided` flag at deployment, SAM fails to consider the parameters specified both at the command line or at the `samconfig.toml` file.

**Steps to reproduce the issue:**
1. Create a sample SAM template, with one or more parameters.
2. Manually create a `samconfig.toml` file, or let SAM create it by running `sam deploy --guided` without deploying it.
3. Run `sam deploy --guided`

**Observed result:**
SAM fails to recognise the parameter specified on the samconfig.toml file, leaving the parameter input blank. When trying to specify the parameter using the `--parameter-overrides` option the same behaviour is produced.

`SAM CLI, version 0.53.0`

**Comment by c2tarun** [comment]
Hi @pedrosola ,
Can you please share a sample of the way you are passing parameter_overrides in samconfig.toml? I tried following approach and it worked for me.

`parameter_overrides = "Key1=\"Value1\" Key2=\"Value2\""`

Thanks
Tarun

**Comment by sriram-mv** [comment]
As @c2tarun mentions, this should work, please try the suggested approach and re-open if neccesary.
