### ISSUE TITLE
Installation immediately broken on macOS 10.15.5

### ISSUE THREAD

**Issue by dschu-lab** [awslabs/aws-sam-cli#2099]
### Description

Hi! I'd really like to get started with AWS SAM, but I'm unable to get the cli to work on my machine.

### Steps to reproduce

```
 ~ ⚡️   brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.53.0//aws-sam-cli-0.53.0.sierra.bottle.tar.gz
Already downloaded: /Users/julian/Library/Caches/Homebrew/downloads/967af9dae702ac5e4f24aa221eaa4e925f7afa86e68636f95d30ce9a27051a7f--aws-sam-cli-0.53.0.sierra.bottle.tar.gz
==> Pouring aws-sam-cli-0.53.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/aws-sam-cli/0.53.0: 4,062 files, 66.0MB


~ ⚡️   sam --version
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7
  Reason: image not found


~ ⚡️   python --version
Python 3.8.3

~ ⚡️   aws --version
aws-cli/2.0.29 Python/3.8.3 Darwin/19.5.0 botocore/2.0.0dev33

```

### Observed result

Installation is broken immediately

### Expected result

Get something like `SAM CLI, version 0.52.0`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.15.5
2. `sam --version`: Nothing

**Comment by Poisoned** [comment]
@dschu-lab Had the same problem today after doing `brew upgrade` which upgraded my Python to v3.8.3_1. I think AWS SAM still refers internally to Python 3.7, what helped me was `brew link python 3.7.8`.

I hope this helps.

**Comment by ns408** [comment]
I can confirm the above.

```shell
~ % /usr/local/Cellar/aws-sam-cli/0.53.0/bin/sam

dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7
  Reason: image not found
[1]    15931 abort      /usr/local/Cellar/aws-sam-cli/0.53.0/bin/sam
```

```shell
~ % /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7

dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7
  Reason: image not found
[1]    15736 abort      /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7
```

**Comment by ns408** [comment]
This worked for me. I have both python@3.7 and python@3.8 installed using brew on my system.

```shell
brew unlink python
brew reinstall python@3.7
brew link python python@3.7
```

**Comment by dschu-lab** [comment]
> @dschu-lab Had the same problem today after doing `brew upgrade` which upgraded my Python to v3.8.3_1. I think AWS SAM still refers internally to Python 3.7, what helped me was `brew switch python 3.7.8`.
> 
> I hope this helps.

Thank you! This was the fix I was looking for! Horray! 🥳

**Comment by Poisoned** [comment]
And if it happens again because python 3.7 is no longer available then there is a workaround:
https://github.com/aws/homebrew-tap/issues/93

`brew install --build-from-source aws-sam-cli`
