### ISSUE TITLE
Homebrew install/upgrade on MacOS breaks sam-cli

### ISSUE THREAD

**Issue by cmccoypdx** [awslabs/aws-sam-cli#2101]
### Description

On an upgrade or new installation of `aws-sam-cli` via homebrew, `sam --version` (and any other sam commands) fails with the error 

`dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7
  Reason: image not found`

This seems to have something to do with homebrew upgrading Python3 to version 3.8 on any upgrade or install, while sam-cli is looking for specifically version 3.7.

In my case, this happened from trying to upgrade my sam-cli version via `brew upgrade aws-sam-cli`, but the same issue seems to occur on a new installation via homebrew. 

### Steps to reproduce

Install (or upgrade) `aws-sam-cli` via homebrew, as per the instructions at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html. Run `sam --version`, or any other sam-cli command.

### Observed result

`dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/aws-sam-cli/0.53.0/libexec/bin/python3.7
  Reason: image not found`

### Expected result

`sam --version` displays sam-cli version, sam-cli commands work.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Mojave 10.14.6
2. `sam --version`: 0.53.0
3. homebrew version: 2.4.4-36-gd1f6296

**Comment by kgc00** [comment]
is there anyway to use a previous version of aws-sam-cli until this is fixed? it seems like only the latest version is available via homebrew

**Comment by jfuss** [comment]
There is a workaround provided here: https://github.com/aws/homebrew-tap/issues/93

Specifically: brew install --build-from-source aws-sam-cli. This will not use the bottle. This will however take much longer to install.

**Comment by cmccoypdx** [comment]
Thanks for the workaround, I'm back in business.

**Comment by sreerammeka** [comment]
Is this fixed, still facing the same issue with Python 3.8 via Homebrew on MacOS after following the instructions at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html and after 1 year this issue has been closed.

`laptop@terminal ~ % brew install aws-sam-cli

Warning: No available formula with the name "python@3.8" (dependency of aws/tap/aws-sam-cli).
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.`
