### ISSUE TITLE
WSL 2 with Docker

### ISSUE THREAD

**Issue by hyphen1370** [awslabs/aws-sam-cli#2106]
Hello, 

I tried to install AWS SAM CLI to Ubuntu 20.04 as WSL 2 machine. It failed with following error: 

error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

The environment is docker desktop installed with WSL 2 integration turned on and enable to access docker via WSL 2 machine. The OS is Windows 10 2004

When I tested the installation without installing the docker desktop, the installation process went through. Is that anyone has this issue or knowing the issue or conflict with docker desktop? 

Thanks

**Comment by CoshUS** [comment]
I wasn't able to replicate this issue. Can you describe the steps you have taken in detail?

**Comment by CoshUS** [comment]
Closed. Feel free to reopen if there is more information on the issue.
