### ISSUE TITLE
Unable to install on AWS Cloud9

### ISSUE THREAD

**Issue by johnjelinek** [awslabs/aws-sam-cli#212]
```
Installation Started

Package c9.ide.lambda 3
-----------------------
Installing SAM Local
|
> aws-sam-local@0.2.2 preuninstall /root/.c9/node/lib/node_modules/aws-sam-local
> go-npm uninstall

npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.4.6","npm":"2.15.5"})
-
> aws-sam-local@0.2.2 postinstall /root/.c9/node/lib/node_modules/aws-sam-local
> go-npm install

Downloading from URL: https://github.com/awslabs/aws-sam-local/releases/download/v0.2.2/sam_0.2.2_linux_amd64.tar.gz
aws-sam-local@0.2.2 /root/.c9/node/lib/node_modules/aws-sam-local
└── go-npm@0.1.8 (mkdirp@0.5.1, tar@2.2.1, request@2.83.0)
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "explore" "-g" "aws-sam-local@0.2.2" "--" "ln -sfv $(pwd)/bin/* /usr/bin/"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5

npm ERR! It doesn't look like aws-sam-local@0.2.2 is installed.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.c9/empty/npm-debug.log

Failed npm-g. Exit code 1
```

**Comment by heitorlessa** [comment]
John, SAM Local is installed by default on AWS Cloud9 — Have you checked
prior to re-installing?

Tho it’d be great to see what’s inside npm-debug.log to understand what
happened here

**Comment by johnjelinek** [comment]
it turns out that Cloud9 fails to initially install when you provide a root SSH user when creating your environment.

**Comment by foufrix** [comment]
Hello @johnjelinek , how did you solved that problem ? I have other user on my server but impossible to connect with them, only root is working, but have the same problem as you described with SSH remote connection.

Thanks in advance

**Comment by sanathkr** [comment]
Cloud9 comes bundled with SAM CLI. You don't have to do anything extra now :)

**Comment by singledigit** [comment]
It comes bundled with 0.2.11. Any chance of updating to 3.0?

**Comment by samcodrington** [comment]
C9 comes bundled with the npm installation of SAM, but newer versions of SAM need to be installed using pip, will this be fixed in future?

**Comment by judahb** [comment]
+1 Can anyone respond to this as a simply upgrade path is a requirement for development
