### ISSUE TITLE
Brew issue - 1.0.0

### ISSUE THREAD

**Issue by tecklund** [awslabs/aws-sam-cli#2120]
### Description

Failure to install aws-sam-cli

### Steps to reproduce

```
brew tap aws/tap 
brew install aws-sam-cli 
```

### Observed result

```
curl: (22) The requested URL returned error: 404 Not Found
 
Error: Failed to download resource "aws-sam-cli"
 
Download failed: https://github.com/awslabs/aws-sam-cli/releases/download/v0.53.0//aws-sam-cli-1.0.0.x86_64_linux.bottle.tar.gz
 
```

### Expected result

aws-sam-cli to install

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. It looks like the version numbers in the url do not align - 0.53.0 and 1.0.0

**Comment by sriram-mv** [comment]
Thanks for the report! This has been updated and should work now.
