### ISSUE TITLE
Add support for single binary releases

### ISSUE THREAD

**Issue by marcosnils** [awslabs/aws-sam-cli#2123]
### Describe your idea/feature/enhancement

There are other python projects like [docker compose](https://github.com/docker/compose/releases) which already support single binary releases. The idea is to bring the same experience to SAM so it's easier to install and update for everyone. 

I particularly am a Linux user and I wouldn't like to install brew to manage SAM.

### Proposal

Add the same release pipeline that  [docker compose](https://github.com/docker/compose/releases) has. It's proven to be a super mature products with millions of users. 

### Additional Details

Not too many things to do here. I can offer help to implement these pipelines if necessary.

**Comment by awood45** [comment]
Adding as a +1 of #1424
