### ISSUE TITLE
Update build images to 1.0.0

### ISSUE THREAD

**Issue by therealjeffg** [awslabs/aws-sam-cli#2134]
### Description

The build images are still at 0.53, see:

https://github.com/awslabs/aws-sam-cli/issues/2014#issuecomment-663650587

### Steps to reproduce

```
docker pull amazon/aws-sam-cli-build-image-python3.7:latest
docker run -it --rm amazon/aws-sam-cli-build-image-python3.7:latest
sam --version # returns "SAM CLI, version 0.53.0"
```

**Comment by awood45** [comment]
This is in progress now.

**Comment by awood45** [comment]
All build images have been updated to use AWS SAM CLI 1.0.0.
