### ISSUE TITLE
local generate-event sns produces invalid json if message contains special characters

### ISSUE THREAD

**Issue by mariusgrigaitis** [awslabs/aws-sam-cli#214]
`$ aws-sam-local local generate-event sns --message "test\""`

Produces output (invalid JSON)
```
...
        "Message": "test"",
...
```

Expected output
```
...
        "Message": "test\"",
...
```

I expect it to "escape" special characters. It causes problem if I want to generate a message which contains JSON.

Tested on 0.2.2, develop ef5127a0

**Comment by zach5410** [comment]
Can we get this merged?  I am having issues with this currently.

**Comment by zach5410** [comment]
Can we get PR #216 merged?  I am having issues with this right now.

**Comment by sanathkr** [comment]
v0.3.0 fixes this
