### ISSUE TITLE
Parameter to specify which `samconfig.toml` to use

### ISSUE THREAD

**Issue by milesgranger** [awslabs/aws-sam-cli#2152]
### Describe your idea/feature/enhancement

To my understanding, `sam deploy` does not presently accept a `--sam-config` type parameter to specify which config to use. 

This seems beneficial in cases where one has dev/test/production specific config files for `sam`

### Proposal

Add the possibility to do something like `sam deploy --config samconfig-prod.toml`

**Comment by milesgranger** [comment]
I'd be happy to submit a PR if this seems reasonable and if I could get a short pointer on where to start. :+1:

**Comment by ronaldour** [comment]
#1615 Is related to this one :)
