### ISSUE TITLE
Error when Proxy Intergration header value is a boolean

### ISSUE THREAD

**Issue by sfeldkamp** [awslabs/aws-sam-cli#221]
When the Proxy Integration response header value is boolean an error occurs.
```
// Example of a Proxy Integration response
exports.handler = (event, context, callback) => {
    callback(null, {
        statusCode: 200,
        headers: { "x-custom-header" : true },
        body: "hello world"
    });
}
```
> Function returned an invalid response (must include one of: body, headers or statusCode in the response object): json: cannot unmarshal bool into Go value of type string

If the value is instead a string, no error occurs.
`        headers: { "x-custom-header" : "true" },`

**Comment by aaronjameslang** [comment]
Error also appears as
```
Function returned an invalid response (must include one of: body, headers or statusCode in the response object): json: cannot unmarshal number into Go value of type string
```
given header `'Access-Control-Max-Age': 0`

**Comment by sanathkr** [comment]
Can you try latest version v0.3.0? This should be fixed. Feel free to re-open if it is not
