### ISSUE TITLE
Utilizing the "Globals" section of SAM is not respected

### ISSUE THREAD

**Issue by spockNinja** [awslabs/aws-sam-cli#226]
I am utilizing the `Globals` section of SAM. This is a great feature to help reduce copy-pasting in all of the Functions. However, sam-local does not appear to be respecting the runtime supplied in this section.

The Globals section of template.yml
```
Globals:
  Function:
    runtime: python3.6
```

And when I run `sam local start-api`, I receive errors like this for all of my endpoints:
```
2017/12/09 15:29:01 Ignoring FunctionName (functionPath) due to unsupported runtime ()
ERROR: None of the Serverless functions in your SAM template were able to be mounted. See above for errors.
```

I would be happy to make a pull request if this is a feature that would be welcomed, and if I could get some initial guidance on the internals of sam-local to know where this would fit best.

Based on a quick search of the source, I _think_ we would have to look for `Globals` and pass the runtime into `https://github.com/awslabs/aws-sam-local/blob/develop/start.go#L78` when building the Functions.

**Comment by spockNinja** [comment]
In the meantime, the simple workaround is to copy the `runtime` setting into each of your functions. I just have that change stashed in git for now and don't commit it.

**Comment by metaskills** [comment]
Same issue for me, glad it is a reported issue.

**Comment by stevehouel** [comment]
+1

**Comment by kienpham2000** [comment]
I'm having similar as well: 
```
$ sam local invoke MyLambda -e ./test/fixtures/test.json
2018/01/16 11:25:08 Successfully parsed template.yml
ERROR: json: cannot unmarshal number into Go value of type string
2018/01/16 11:25:08 Connected to Docker 1.35
2018/01/16 11:25:08 Could not initiate  runtime: unsupported runtime
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Putting the `Runtime: nodejs6.10` back into the lambda function definition works fine. 

```
$ sam local invoke MyLambda -e ./test/fixtures/test.json
2018/01/16 11:29:29 Successfully parsed template.yml
ERROR: json: cannot unmarshal number into Go value of type string
2018/01/16 11:29:29 Connected to Docker 1.35
2018/01/16 11:29:29 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
....
```

**Comment by cwonrails** [comment]
Exact same issue @kienpham2000 posted re: `Runtime: nodejs6.10` in the `Globals` section.

**Comment by dimahavrylevych** [comment]
+1 to unsupported runtime issue

**Comment by lfdesousa** [comment]
+1 to unsupported runtime issue

**Comment by vasylk** [comment]
+1

**Comment by nzoschke** [comment]
I also needed to copy the `Handler` property back from Globals to each function

**Comment by pacey** [comment]
Look forward to this being resolved. I'm not a go developer but would be happy to help where I can.

**Comment by mittyo** [comment]
+1 to Globals and nodejs6.10 || would be great to get nodejs 8...

**Comment by GuidoNebiolo** [comment]
+1 to Globals

**Comment by pikovets** [comment]
+1 to Globals

**Comment by IainAdams** [comment]
+1 to Globals

**Comment by harrypunk** [comment]
+1 to Globals.
Have to copy properties to child functions.
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 6
Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.greet
      Runtime: nodejs8.10 #have to duplicate this to invoke locally
```

**Comment by vendablefall** [comment]
+1 to Globals

**Comment by jfuss** [comment]
Globals are supported as of [v0.3.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0)

Closing
