### ISSUE TITLE
give an ability to create a container network link to existed container

### ISSUE THREAD

**Issue by dreampuf** [awslabs/aws-sam-cli#238]
For now, there is one way to customize container's networking. 
https://github.com/awslabs/aws-sam-local/blob/bd1672469e85bf533ee10849773ee7c92a854411/runtime.go#L322

For the general cases, we'd like to utilize more existed services those in containers. An example is we have a lambda function scripts, which includes some RDS (PostgreSQL) access. For fully functional testing. I set up a pg container for it. But now the `sam local invoke` doesn't support containers network link. So I have to use a trick way to approach that by hardcode the container's IP address in DB DSN.

Would you mind to expose a link interface to end user?

**Comment by jvanbrunschot-coolblue** [comment]
Doesn't this just work with `--docker-network ` ? 

Just tested it (with node) and it seems to work by calling `sam local invoke` with the --docker-network flag.

also DNS resolution works

**Comment by dreampuf** [comment]
Hi @jvanbrunschot-coolblue 

It's no problem about the link the sam container to existing one. But I want it to be more friendly. It's true I can use `--docker-network` connect to customized docker network bridge. But finding the container IP is kind of tricky. Here is what I'm doing now.

```bash
    export DB_CONTAINER_IP="$(docker inspect -f "{{.NetworkSettings.Networks.bridge.IPAddress}}" $(docker ps --filter "name=CONTAINER_NAME" --format "{{.ID}}"))"
    sam local invoke "LAMBDA_FUNCTION_NAME" --parameter-values "ParameterKey=DatabaseDNS,ParameterValue=postgresql://DB_USER@${DB_CONTAINER_IP}/DB_NAME?connect_timeout=10&application_name=APPLICATION_NAME"
```

What I wanted is a standard way to access the external container, like `docker run --link HOST:CONTAINER_ID`.

**Comment by sanathkr** [comment]
Closing this and tracking it as part of a larger issue to access DBs running in a separate container - #219
