### ISSUE TITLE
Build From Source Fails.

### ISSUE THREAD

**Issue by pernambucano** [awslabs/aws-sam-cli#249]
I am having the same problem as [awslabs/aws-sam-local#225](https://github.com/awslabs/aws-sam-local/issues/225), and I know it has been resolved in [#223](https://github.com/SAPessi/aws-sam-local/commit/c8a71f681fc6dca0ffd3c0ba58377e56ae875f01). However those commits are not in a new release yet. Because of that I tried to build form the develop branch source code, and found this response:

`$ go get github.com/awslabs/aws-sam-local `
`$ go build github.com/awslabs/aws-sam-local/vendor/github.com/awslabs/goformation/cloudformation: C:\Go\pkg\tool\windows_amd64\compile.exe: fork/exec C:\Go\pkg\tool\windows_amd64\compile.exe: The filename or extension is too long.`

Go version : go version go1.9.2 windows/amd64
npm version : 3.10.10

**Comment by stephenliberty** [comment]
Getting this issue as well. To add some detail:

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Stephen\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

It doesn't matter if I move the GOPATH to something shorter or anything like that - it keeps failing on the same step. I've tried go 1.9 and 1.8, and tried using a different command shell with no difference.

Hope that helps. (And hope this is related, and not me just rambling off into space with people giving my message weird looks :) )

**Comment by tebruno99** [comment]
This is actually a go compiler root cause from: https://github.com/golang/go/issues/18468

To fix this we would have to have the AWS team shorten the paths and change the module names until there is a fix for the go compiler on windows.

**Comment by sanathkr** [comment]
Not relevant anymore. v0.3.0 rewrote the CLI in Python
