### ISSUE TITLE
cannot invoke sam local outside c:\users 

### ISSUE THREAD

**Issue by imshambhu** [awslabs/aws-sam-cli#251]
Hi , 
 I am able to execute the sam local invoke command successfully when my projects files are under c:\users . However  when I change my project directory to other than  c:\users e.g d:\workdir1 , sam local invoke  command does not work . It errors out as listed below. 

I tried using the mounting solution mentioned at this link . http://support.divio.com/local-development/docker/how-to-use-a-directory-outside-cusers-with-docker-toolbox-on-windows

**Even after  mounting my shared folder , sam local invoke does not work outside c:\users** 

**Please not that I am on windows 7 64 bit and I am using docker toolbox**

$ sam local invoke  "sks1" -e event.json
2018/01/07 09:43:47 Successfully parsed template.yaml
←[34mINFO←[0m[0001] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
2018/01/07 09:43:47 Connected to Docker 1.35
←[34mINFO←[0m[0001] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
2018/01/07 09:43:47 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:e34f92bc0df0cf4a8ba560c6c7bf201183d5f6773ddf44440a97295486906744
Status: Image is up to date for lambci/lambda:nodejs6.10
2018/01/07 09:43:51 Invoking index.handler (nodejs6.10)
2018/01/07 09:43:52 WARNING: No AWS credentials found. Missing credentials may lead to slow startup times as detailed in
l/issues/134
2018/01/07 09:43:52 Mounting /d/workdir1/sam-local1 as /var/task:ro inside runtime container
←[32mSTART RequestId: 7a5aa8d7-e643-17f7-5e86-5dfeedad0d2d Version: $LATEST←[0m
←[31mUnable to import module 'index': Error←[0m
←[31m    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)←[0m
←[32mEND RequestId: 7a5aa8d7-e643-17f7-5e86-5dfeedad0d2d←[0m
←[32mREPORT RequestId: 7a5aa8d7-e643-17f7-5e86-5dfeedad0d2d     Duration: 7.33 ms       Billed Duration: 0 ms   Memory S
←[0m

{"errorMessage":"Cannot find module '/var/task/index'","errorType":"Error","stackTrace":["Function.Module._load (module.
97:17)","require (internal/module.js:20:19)"]}

**Comment by sanathkr** [comment]
This should work when you setup the Docker container file sharing settings properly.
