### ISSUE TITLE
Code parameter of AWS::Lambda::Function ignored

### ISSUE THREAD

**Issue by jjonek** [awslabs/aws-sam-cli#252]
The `Code` parameter of `AWS::Lambda::Function` resource is ignored in the conversion, although it could be handled exactly the same as the `CodeUri` of `AWS::Serverless::Function` resource. Given that the behavior of `aws cloudformation package` is the same on both parameters I'd expect  *aws-sam-local* to handle this too.

Currently the `Code` parameter is ignored and set to `nil` here: https://github.com/awslabs/aws-sam-local/blob/develop/convert.go#L36

references

* package command https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html
* AWS::Serverless::Function https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
* AWS::Lambda::Function Code parameter https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-code

**Comment by sanathkr** [comment]
This should work as of v0.3.0
