### ISSUE TITLE
TypeError: Cannot read property 'product' of null

### ISSUE THREAD

**Issue by cjokinen** [awslabs/aws-sam-cli#254]
There is an issue with your sample on this line...

let id = event.pathParameters.product || false;

it generates the title error when using 
http://localhost:3000/products

I did a console.log to see what was going on and this is what I found on the event
```javascript
{
  "httpMethod": "GET",
  "body": "",
  "resource": "/products",
  "requestContext": {
    "resourcePath": "/products",
    "httpMethod": "GET",
    "stage": "prod",
    "identity": {
      "sourceIp": "127.0.0.1:58158"
    }
  },
  "queryStringParameters": {},
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en-US,en;q=0.5",
    "Cache-Control": "max-age=0",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
  },
  "pathParameters": null,
  "stageVariables": null,
  "path": "/products"
}
```

as you can see stageVariables is eqal to null...so event.pathParameters.product will not work.

I changed that line to this 
let id = (event.pathParameters !== null ? event.pathParameters.product : false);
and so far it works, I have not tested the other paths yet.

**Comment by sanathkr** [comment]
This should work as of v0.3.0
