### ISSUE TITLE
Unsupported runtime for Java Lambda functions

### ISSUE THREAD

**Issue by josecalles** [awslabs/aws-sam-cli#261]
docker version: `1.35`
sam version: `0.2.4`
java jdk version: `1.8.0_152`

I have defined a couple of simple Lambda functions that work properly when imported through the Lambda console. In my template, I have specified the runtime as `java8` and the CodeUri points to the correct jar. When running `sam local start-api`, I'm told that none of my functions were mounted due to an unsupported runtime. While looking through the open issues, I found that defining globals might cause this, so I've removed the global function definitions and set the runtime and codeUri to each individual function, but the issue still persists. 

Edit: 
When invoking one of the functions using `sam local invoke "UserFunction" `
I get the following: 
`Could not initiate  runtime: unsupported runtime`
note: there is two spaces between 'initiate' and 'runtime' where it should show 'java8'

**Comment by PaulMaddox** [comment]
Could you paste your whole SAM template here?

**Comment by flakeparadigm** [comment]
I'm running into the same error message. Changing the contents of the "Handler" section of the yaml file doesn't seem to affect this.

Log:
```
> sam local invoke "MyLambdaFunction"
2018/02/20 11:34:31 Successfully parsed template.yaml
2018/02/20 11:34:31 Connected to Docker 1.35
2018/02/20 11:34:31 Could not initiate  runtime: unsupported runtime
> sam --version
sam version 0.2.6
> docker --version
Docker version 17.12.0-ce, build c97c6d6
```

template.yaml:
```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    CodeUri: ./code
    Runtime: nodejs6.10
    Handler: app.handler
    Timeout: 5
```

**Comment by EgidioCaprino** [comment]
I'm having a similar error:
```
ValueError: Unsupported Lambda runtime {u'Ref': u'Runtime'}
```

In the template I'm defining the runtime with a reference
```
Runtime: !Ref Runtime
```

I guess `!Ref` is not supported yet.

**Comment by sanathkr** [comment]
Yes, Ref of a property for Runtime is not yet supported.
