### ISSUE TITLE
sam rollback functionality

### ISSUE THREAD

**Issue by danielwhatmuff** [awslabs/aws-sam-cli#269]
- A way to rollback a sam managed function to a previously deployed version
- Look at previous lambda version tag and then update the AutoPublishAlias to use it
- An example of this type of functionality - https://github.com/Miserlou/Zappa#rollback

**Comment by charsleysa** [comment]
@danielwhatmuff I think you submitted this issue in the wrong repo.
I think you are looking for https://github.com/awslabs/serverless-application-model

**Comment by ktal90** [comment]
This would be very useful, and I think @charsleysa is right. This belongs in the SAM repo. I made an issue reflecting this request there: https://github.com/awslabs/serverless-application-model/issues/321
