### ISSUE TITLE
Inconsistent representation of "no parameters" across parameter types

### ISSUE THREAD

**Issue by toobrien** [awslabs/aws-sam-cli#277]
If a request has no path parameters, "PathParameters" will end up nil: https://github.com/awslabs/aws-sam-local/blob/develop/event.go#L76

However, if a request has no headers or query string parameters, "Headers" and "QueryStringParams" will end up as empty objects: https://github.com/awslabs/aws-sam-local/blob/develop/event.go#L60-L72

I noticed this inconsistency while testing one of our documented examples. See line 5 in the "products.js" snippet:

```javascript
let id = event.pathParameters.product || false;
```

  https://docs.aws.amazon.com/lambda/latest/dg/test-sam-local.html#sam-cli-simple-app

On my Amazon Linux build, pathParameters is "{}", but on Windows 10 it's "null". Either we should change the example or represent an empty set of path parameters with an empty object.

**Comment by sanathkr** [comment]
I don't know why this difference between Windows & Linux. It is probably showing up in some marshaling/unmarshalling to Docker. We should definitely change SAM Local to output a consistent result - ideally equal to what APIGW behavior is.

**Comment by jfuss** [comment]
This was corrected in the [0.3.0 release](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0). We now match Api Gateway's behavior (for the event), which is if pathParameters is not present we default to `null`. Closing since this has been addressed.
