### ISSUE TITLE
Support for http_proxy type in x-amazon-apigateway-integration

### ISSUE THREAD

**Issue by sgarcez** [awslabs/aws-sam-cli#291]
Our OpenApi spec contains the following path:
```
...
          /{proxy+}:
            get:
              parameters:
              - name: "proxy"
                in: "path"
              x-amazon-apigateway-integration:
                type: "http_proxy"
                uri: "https://127.0.0.1:8000/{proxy}"
                httpMethod: "GET"
               passthroughBehavior: "when_no_match"
...
```

**Expected behaviour:**
Requests are routed to `https://127.0.0.1:8000/*` when no other routes are matched.

**Observed behaviour:**
```
$ sam local start-api

2018/02/02 14:00:32 Connected to Docker 1.35
2018/02/02 14:00:33 Could not extract Lambda function ARN: Could not find match in
2018/02/02 14:00:33 Could not extract Lambda function ARN: Could not find match in https://127.0.0.1:8000/{proxy}
2018/02/02 14:00:33 Fetching lambci/lambda:go1.x image for go1.x runtime...
go1.x: Pulling from lambci/lambda
Digest: sha256:d77adf847c45dcb5fae3cd93283447fad3f3d51ead024aed0c866a407a206e7c
Status: Image is up to date for lambci/lambda:go1.x

Mounting handler (go1.x) at http://127.0.0.1:3000/a-non-proxied-endpoint [GET]
WARNING: Could not find function for [GET] to /{proxy+} resource

You can now browse to the above endpoints [...]
```

It would appear that the `type` property of [x-amazon-apigateway-integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html) is always treated like an `aws_proxy`.

 Looking at the source code, the [ApiGatewayIntegration type](https://github.com/awslabs/aws-sam-local/blob/739c48e3467109f7cec5b38b6bd407183e89e6a2/router/integration.go#L8)'s `GetFunctionArn()` method completely ignores the `Type` field, and simply attempts to construct a Function Arn from `Uri`, which fails with the `"Could not find match in"` error.

I don't know what would be the best way to add support for this, I guess it could be done fully in Go or another solution would be to provide a 'proxier' handler / docker image that mimics the proxying behaviour in AWSGateway and [gets mounted](https://github.com/awslabs/aws-sam-local/blob/c4d34f2eb23c375274c374489cf723b0da5b87c3/router/api.go#L75) like any other endpoint.

**Comment by sanathkr** [comment]
Unfortunately SAM CLI doesn't have mechanism to support other integration types. SAM CLI's API layer works only with Lambda backed APIs and not others. Is this something you will interested in contributing?

**Comment by jfuss** [comment]
This issue hasn't got much traction, so closing. 

Feel free to reopen.

**Comment by jqdurham** [comment]
This was also an unforeseen gotcha for our team.  The documentation calls the REST API running via `sam local start-api` API Gateway, but it is only a subset of functionality.  Documentation and tutorials are focused primarily on Lambda examples and the similarity between SAM templates and CF templates make researching the capabilities difficult.

If APIGW is part of the serverless stack, then I think it make sense to extend SAM's understanding of APIGW configuration and/or implementation of APIGW features more robust.  This is one of those enhancements that would make local development more efficient.
