### ISSUE TITLE
AWS::Serverless::API StageName ignored, Event defaults to "prod"

### ISSUE THREAD

**Issue by christianklotz** [awslabs/aws-sam-cli#292]
As we were trying to distinguish the API stage from which a Lambda function got called I noticed that `aws-local` _always_ defaults to `prod` and ignores the `StageName` specified in the SAM template.

### Steps to reproduce behaviour

Follow the [SAM documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi) and set `StageName` of the API resource to `dev`.

> **StageName `string`:** Required The name of the stage, which API Gateway uses as the first path segment in the invoke Uniform Resource Identifier (URI).

```yaml
Resources:
  MyAPI:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: dev
```

### Expected result
The event should contain a stage value of `dev`.

### Actual result
The event is set to `prod`.

From what I can see the value is set to `prod` in the following line:

https://github.com/awslabs/aws-sam-local/blob/f80c385e0d50a8de028d6cfde5cfa96c1d74d910/event.go#L92

This poses two questions:
- How could stage be passed from the API to the runtime? As it stands, each Lambda function is initialised with a runtime which doesn't know anything about the API stage – and shouldn't since the same function could potentially be used by multiple APIs with different stage values. This suggests the request context itself could be initialised with a stage value derived from the API configuration. Currently the flow for a new event involves the following stages, showing there's no context passed in from the API to the invocation of the Lambda function:
[`start()`](https://github.com/awslabs/aws-sam-local/blob/c4d34f2eb23c375274c374489cf723b0da5b87c3/start.go#L110) → [`Runtime.InvokeHTTP(string)`](https://github.com/awslabs/aws-sam-local/blob/1cfd626a52946c38722ce1718c87b44975d53cee/runtime.go#L510) → [`NewEvent(http.Request)`](https://github.com/awslabs/aws-sam-local/blob/f80c385e0d50a8de028d6cfde5cfa96c1d74d910/event.go#L92)
- Would it be better to use a different default value than `prod` if `StageName` hasn't been set, something like `local` perhaps? Or, given that the documentation states that the attribute is _required_ it would be better to throw an error instead?

**Comment by keetonian** [comment]
Looking into this. The problem still exists in the python version: [link](https://github.com/awslabs/aws-sam-cli/blob/546d271210c1aff657a60044647533abd7f87cd4/samcli/local/apigw/local_apigw_service.py#L272)

**Comment by jfuss** [comment]
Release in [v0.21.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.21.0).

Closing
