### ISSUE TITLE
[Feature Request] Cognito sync event

### ISSUE THREAD

**Issue by alez007** [awslabs/aws-sam-cli#296]
Hi,

It would be great if we could have a cognito sync generate event feature in Sam local. 

Thanks

**Comment by jfuss** [comment]
[It's coming](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/local/lib/generated_sample_events/events/cognito/CognitoSyncTrigger.json)

Marking this as waiting for release.

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)
