### ISSUE TITLE
Unable to import module 'index': Error on Amazon Linux EC2 instance

### ISSUE THREAD

**Issue by psogani** [awslabs/aws-sam-cli#300]
Hi i am seeing the aforementioned error error while running the command "sam local invoke "HelloWorld" -e input/events.json " from the directory where my index.js and template.yml are located on an amazon linux EC2 instance.
```
[uvb125@ip-10-205-233-250 uvb125_serverless_test]$ dzdo sam local invoke "HelloWorld" -e input/events.json 
2018/02/09 11:34:20 Successfully parsed template.yml
2018/02/09 11:34:20 Connected to Docker 1.32
2018/02/09 11:34:20 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:b72789e8a544e658a76d71a0abbb2fa8b4122cc882bcd27097037bd28f657c9b
Status: Image is up to date for lambci/lambda:nodejs6.10
2018/02/09 11:34:21 Invoking index.handler (nodejs6.10)
2018/02/09 11:34:21 WARNING: No AWS credentials found. Missing credentials may lead to slow startup times as detailed in https://github.com/awslabs/aws-sam-local/issues/134
2018/02/09 11:34:21 Mounting /tmp/uvb125_serverless_test as /var/task:ro inside runtime container
START RequestId: 2ea3aae5-1457-1fc5-2725-22c799036905 Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 2ea3aae5-1457-1fc5-2725-22c799036905
REPORT RequestId: 2ea3aae5-1457-1fc5-2725-22c799036905	Duration: 7.87 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 28 MB	

{"errorMessage":"Cannot find module '/var/task/index'","errorType":"Error","stackTrace":["Function.Module._load (module.js:417:25)","Module.require (module.js:497:17)","require (internal/module.js:20:19)"]}
```
I would greatly appreciate any help towards resolving this. Thanks in advance!

**Comment by chauhansachinkr** [comment]
You can now browse to the above endpoints to invoke your functions.
You do not need to restart/reload SAM CLI while working on your functions,
changes will be reflected instantly/automatically. You only need to restart
SAM CLI if you update your AWS SAM template.

2018/02/26 18:54:01 Invoking index.handler (nodejs6.10)
2018/02/26 18:54:01 Mounting /Users/xxxxprojects/xxx/ms/ms as /var/task:ro inside runtime container
START RequestId: e447c35e-e7b6-1aed-76e9-137b087d5448 Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
END RequestId: e447c35e-e7b6-1aed-76e9-137b087d5448
REPORT RequestId: e447c35e-e7b6-1aed-76e9-137b087d5448  Duration: 14.13 ms      Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 28 MB
2018/02/26 18:54:02 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): %!s(<nil>)

**Comment by jfuss** [comment]
@psogani Does your app have dependencies? If so, do you have the dependencies installed in the same folder as your index.js or are they included in your zip file?

By looking at the error, `Function.Module._load (module.js:417:25)","Module.require (module.js:497:17)","require (internal/module.js:20:19)`, is seems like you do and they are not reachable in the container. You will need to install them into the folder or place them in a zip file.

**Comment by jfuss** [comment]
Closing since there was no response.

**Comment by davidrissato** [comment]
I think I know what they were talking about, but I'm not sure if you are willing to reopen the issue.

The problem is `sam` cli works in a different way for python and nodejs.

Lets say your `template.yaml` file contains these 2 definitions:

```
Resources:
  HelloWorldPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world_python/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  HelloWorldNodeFunction:
    Type: AWS::Lambda::Function
    Properties:
      CodeUri: hello_world_node/
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 25
      Events:
        HelloWorld2:
          Type: Api
          Properties:
            Path: /hello2
            Method: get
```

`HelloWorldPythonFunction` will find `app.py` inside `hello_world_python` subfolder, but that doesn't happen for node.js. It is trying to load `index.js` from the same folder where `template.yaml` is located, instead of loading that from `hello_world_node` subfolder. This is the reason why node says 'unable to load index`.

I tried to change Handler to `Handler: ./hello_world_node/index.handler` and then it passes, however it breaks in a later step with this message: `Bad handler ./hello_world2/index.handler`.

It seems there is an issue with `sam` cli when using direct folders. I guess it can be easily solved by just executing a `cd hello_world_node` before running node.js, but this change need to be done to `sam.

**Comment by jfuss** [comment]
@davidrissato Not sure I understand what you are saying. What you have in the template is correct (and is how our init examples are even setup). Running `sam local invoke HelloWorldNodeFunction` does not work?
