### ISSUE TITLE
Environment variables read from shell can't include `=`

### ISSUE THREAD

**Issue by twhitbeck** [awslabs/aws-sam-cli#303]
The way environment variables are being read using `os.Environ` precludes specifying an environment variable with an `=` in it.

This is because `os.Environ` returns an array of strings in the format `KEY=value`, and with a value like `foo=bar` you end up with `KEY=foo=bar` which when split by `=` yields `['KEY', 'foo', 'bar']` and thus the environment variable that ends up getting set in the container is `KEY=foo`.

Maybe should switch to using `os.Getenv` for each Variable in the template file.

**Comment by jfuss** [comment]
I believe this was referring to the go implementation. This should no longer be a concern in 0.3.0 since it is written in python.

Closing
