### ISSUE TITLE
AWS Lambda read/write on closed pipe error　(Py3.6)

### ISSUE THREAD

**Issue by mgsteinkamp** [awslabs/aws-sam-cli#310]
### Env: 
-Windows7
-Python 3.6,
-SAM Local 0.2.6
-Docker Toolbox 18.01.0
-DynamoDBLocal

### Expected behavior: 
-Response data from Lambda function successfully delivered as HTTP Response

### Actual behavior: 
-Actual function completes and returns. 
-sam-local console displays function Report
-sam-local hangs until function timeout and returns HTTP Repsonse: Internal server error

### Detail:
I have a very simple function (py3.6) that I'm running on `sam-local` via `start-api` that I'm testing with a shell script full of `curl` posts:

    lambda_handler(event, context):
      try:
        json_body = event["body"]
        if not validate_json(json_body):
          raise Exception("Bad JSON")
        post_to_dynamo_db_local(json_body)
      except Exception as err:
        return {
            'statusCode': 999,
            'headers': {"x-custom-header": "my custom header value"},
            'body': "\nException! " + str(err)
        }
      return {
        'statusCode': 200,
        'headers': {"x-custom-header": "my custom header value"},
        'body': "hello world"
      }

The test works fine in the correct use-case about 95% of the time, but fails (inconsistently) when `validate_json` raises an `Exception` despite being caught,  or when `post_to_dynamo_db_local` shorts and returns early (object already in DB, return).  
＊I say correct use-case works about 95% of the time, because sometimes I touch stuff and it fails, but me touching stuff is likely the cause. Unconfirmed though!

The function appears to return properly, according to the `sam-local` console:

    START RequestId: 8c7cf7ce-2926-4ce4-ba3c-0fac95a810b0 Version: $LATEST
    END RequestId: 8c7cf7ce-2926-4ce4-ba3c-0fac95a810b0
    REPORT RequestId: 8c7cf7ce-2926-4ce4-ba3c-0fac95a810b0 Duration: 162 ms 
    Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 24 MB

But the `curl` doesn't receive a response until the request times out:
    
      { "message": "Internal server error" }

and around the same time the `sam-local` console responds:

      Error invoking python 3.6 runtime: io: read/write on closed pipe

Any ideas? The function run-time also seems abnormally high for such a simple task, and I don't think memory should be an issue here...

ADDITION: A couple things that help:

 - Sleeping between curls (tried up to 10 seconds, but still errors occasionally
 - Not caching references to tables (so they should be collected fairly quickly)

**Comment by mgsteinkamp** [comment]
Maybe related to #301 ? Inserting a sleep of ~10 seconds

**Comment by faustofjunqueira** [comment]
+1

**Comment by jseakle** [comment]
Very similar issue here.

**Comment by mgsteinkamp** [comment]
@jseakle @faustofjunqueira 
If you have additional info, please feel free to add it! (Different environment/version, different way to produce the problem, etc)

**Comment by salekseev** [comment]
Same exact issue for me:

**Comment by mgsteinkamp** [comment]
@salekseev 

Your issue doesn't seem to be the same--your function isn't returning the normal report. It appears you're just timing out. 
Try increasing your timeout parameter in your template.yaml

**Comment by jfuss** [comment]
Given we rewrote the CLI in python, can you test this with the new version?

**Comment by jfuss** [comment]
No response, closing. 

Feel free to reopen if the issue is still happening.

**Comment by hafizurcse** [comment]
Still having the issue even the timeout is 20 seconds. 

```
2019/04/12 20:40:47 Error invoking nodejs8.10 runtime: io: read/write on closed pipe
2019/04/12 20:40:49 Error reading I/O from runtime container: io: read/write on closed pipe
2019/04/12 20:40:51 Function index.handler timed out after 20 seconds
```

My SAM CLI version is 0.2.11

**Comment by jfuss** [comment]
@hafizurcse You are using a SUPER old version of SAM CLI. Current version is 0.14.2. You should be upgrading. I haven't seen this with python version (v0.3.0 and greater).

**Comment by Ghilteras** [comment]
@jfuss can we increase the timeout? I'm still hitting this a lot of times with 0.17.0
