### ISSUE TITLE
Use multiples lambda

### ISSUE THREAD

**Issue by jagu-sayan** [awslabs/aws-sam-cli#322]
I try to use multiples lambda with same code with diffenrent handlers.

But aws sam local use randomly one of both handlers I have defined.

I just follow instructions in this tutorial : https://www.apollographql.com/docs/apollo-server/servers/lambda.html and rename `graphql.graphqlHandler` to `graphql.handler` and `graphql.graphiqlHandler` to `graphql.explorer`

Sometimes I get :
![image](https://user-images.githubusercontent.com/1262860/37148379-94e1db5e-22ca-11e8-88d0-41948e675026.png)
or
![image](https://user-images.githubusercontent.com/1262860/37148410-a7fcc424-22ca-11e8-8fa8-edf4e03adaeb.png)

**Comment by michaelj-smith** [comment]
@jagu-sayan I have seen this output also when running `sam local start-api`, but I believe this is a bug in the console output of the command, and not the execution of the lambda functions. That is, even though the output shows that "Mounting main.explorerHandler" is on every endpoint, when I actually execute the endpoints I find that the various different handlers were correctly mounted.

Your situation may be different than mine, but it warrants making sure whether the actual execution of the endpoints is broken.

**Comment by jagu-sayan** [comment]
This issue is fixed in release [v0.3.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0)
