### ISSUE TITLE
swagger nodejs server

### ISSUE THREAD

**Issue by harshavarun25** [awslabs/aws-sam-cli#328]
I am trying to pass my application authentication credentials through postman(POST) inside the header but I am not able to parse them on my server side. I usually parse the headers with req.header function. Swagger middleware manipulates the whole request format. any idea where I will be able to parse the header function.

**Comment by jfuss** [comment]
Headers are read from the request and put into the event that is invoked with your Lambda. [Relevant code](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/apigw/service.py#L370)

Closing since we pass the headers from the request to the local lambda.
