### ISSUE TITLE
Is here assuming all responses are using  "Content-Type: application/json"?

### ISSUE THREAD

**Issue by allinwonder** [awslabs/aws-sam-cli#329]
https://github.com/awslabs/aws-sam-local/blob/629e6277c88b6a41edcc38f5f7227ad29888b78d/runtime.go#L544

I am hitting an issue that `sam-local` response contains multiple contradicted "Content-Type" header.  Please see the following `curl` command debugging output. In my API, the only Content-Type defined is `text/plain` format, but using the sam-local test, its response message contains an extra "Content-Type" header `application/json`. Could you please confirm is this line injecting the header, if so, can this assumption be removed and honor the response header returned by  Lambda functions?

Please see the following out console output.

```
$> curl -v -H "Accept: text/plain" http://127.0.0.1:3000/resources/greeting
* Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /resources/greeting HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.54.0
> Accept: text/plain
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Type: text/plain
< Date: Mon, 19 Mar 2018 07:21:00 GMT
< Content-Length: 5
<
* Connection #0 to host 127.0.0.1 left intact
Hello
```

**Comment by jimedelstein** [comment]
@allinwonder downgrading sam-local to v0.2.5 worked for me

**Comment by ronaldwidha** [comment]
confirmed.

`$ curl -v --header 'Accept:text/html' 'http://localhost:8080/'`

yields

```
...
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Type: text/html
< Date: Thu, 12 Apr 2018 13:40:56 GMT
...
```

**Comment by allinwonder** [comment]
hm, yeah. looks like not only me hitting this issue. Can this be changed to honor the response header from the app?

**Comment by endymion** [comment]
Issues 325 and 361 are about this same bug.

**Comment by endymion** [comment]
I described a workaround that I found in #361.  You might want to try it.

**Comment by jfuss** [comment]
This should be fixed in our newest release: https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0

Please feel free to reopen if the issue persists.
