### ISSUE TITLE
Discrepancies between local and AWS Lambda Function

### ISSUE THREAD

**Issue by zuesmajor** [awslabs/aws-sam-cli#331]
<img width="818" alt="screen shot 2018-03-20 at 1 54 43 pm" src="https://user-images.githubusercontent.com/6497357/37682256-45d2e474-2c46-11e8-996b-e696b6c91d42.png">

I currently am using the dotnetcore2.0 runtime on my local machine and it works fine even though on AWS we are using dotnetcore1.0 BUT when I change the AWS lambda function runtime to dotnetcore2.0 and re-run the lambda it doesn't work (most likely because the code is not compatible with dotnetcore2.0) 

I would expect the dotnetcore2.0 SAM local lambda test not being able to execute the code if the remote AWS lambda function can't execute.

**Comment by jfuss** [comment]
The docker container we use is not identical to the one run by the service. 

This is an issue with the docker container not with SAM CLI. I would encourage you to file an issue [here](https://github.com/lambci/docker-lambda/issues).

Closing as this is not an issue with SAM CLI.
