### ISSUE TITLE
error in json format return

### ISSUE THREAD

**Issue by moedeveloper** [awslabs/aws-sam-cli#337]
When i run sam local start-api -t template.yml i get the following error as return

2018/03/23 23:59:56 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): json: cannot unmarshal string into Go value of type struct { StatusCode json.Number "json:\"statusCode\""; Headers map[string]string "json:\"headers\""; Body json.Number "json:\"body\""; IsBase64Encoded bool "json:\"isBase64Encoded\"" }

 this is how my yaml file looks like 

> Transform: 'AWS::Serverless-2016-10-31'
> Resources:
>     GetHelloWorld:
>         Type: AWS::Serverless::Function
>         Properties:
>             Handler: main
>             Runtime: go1.x
>             CodeUri: ./
>             Events:
>               GetResource:
>                 Type: Api
>                 Properties:
>                   Path: /sam
>                   Method: get

**Comment by michaelj-smith** [comment]
That error message is sometimes a red herring. It could either be telling you exactly what's going on (i.e. your `./main` handler file is not returning the correct format needed) or it could be that your function is throwing an unhandled error in your handler code, which would cause the handler to not return the correct format needed. I recommend adding logging statements or attaching a debugger to identify what's going on in your `main` handler.

**Comment by jfuss** [comment]
This has been answered by @michaelj-smith and has had no additional response. Closing
