### ISSUE TITLE
Inconsistent queryStringParameters representation 

### ISSUE THREAD

**Issue by n3ziniuka5** [awslabs/aws-sam-cli#338]
When using the proxy integration with sam-local, if you call a method without any query string parameters, you get this as part of your input:
```
"queryStringParameters": {}
```

However, In production this is represented as:
```
"queryStringParameters": null
```

**Comment by n3ziniuka5** [comment]
Same inconsistency with `body` parameter. In sam local empty body is represented as an empty string, while in production it is `null`.

**Comment by jfuss** [comment]
This inconsistency was corrected in the [0.3.0 release](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0). Closing since this has been addressed.

**Comment by rqtx** [comment]
I was debugging my API with sam local and notice that the queryStringParameters  was just getting the last char of the parameters passed on URL.

`?param=value`

queryStringParameters with sam local:
`"queryStringParameters": {"param":"e"}`

queryStringParameters on Production:
`"queryStringParameters": {"param":"value"}`
