### ISSUE TITLE
Debug mode not starting in SAM Local 

### ISSUE THREAD

**Issue by vilaspmahajan** [awslabs/aws-sam-cli#347]
i am trying to "sam local invoke "HelloWorld" -e event.json"

sam local invoke "HelloWorld" -e event.json
2018/04/04 19:29:51 Successfully parsed template.yaml
←[34mINFO←[0m[0001] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
2018/04/04 19:29:51 Connected to Docker 1.37
←[34mINFO←[0m[0001] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
2018/04/04 19:29:51 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:56205b1ec69e0fa6c32e9658d94ef6f3f5ec08b2d60876deefcbbd72fc8cb12f
Status: Image is up to date for lambci/lambda:nodejs6.10
2018/04/04 19:29:53 Invoking index.handler (nodejs6.10)
2018/04/04 19:29:53 Mounting /c/Users/{UserName}/Desktop/Hello-word as /var/task:ro inside runtime container

**Comment by jfuss** [comment]
@vilaspmahajan You are not executing the right command if you want to be in Debug mode. You need to be passing a debug port and any debug args you need.

```
  -d, --debug-port TEXT           When specified, Lambda function container
                                  will start in debug mode and will expose
                                  this port on localhost.
  --debug-args TEXT               Additional arguments to be passed to the
                                  debugger
```

Closing as no issue
