### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "argument list too long"

### ISSUE THREAD

**Issue by mikeluz** [awslabs/aws-sam-cli#350]
Hi, I'm getting the subject error when I try to send base64 encoded data read from files of sizes larger than ~100kb. Specified MemorySize in my template.yaml is 512; wondering why I'm getting this error. The lambda is in java and I'm running it locally using Sam -- it's being hit by a local express proxy that is being hit by a fetch. Any help appreciated!

**Comment by hobotroid** [comment]
Did you ever solve this issue? I'm stuck on this exact thing.

**Comment by sanathkr** [comment]
This is coming from the Docker container directly. SAM CLI is currently using a mechanism that does not support large payloads. I believe we have another issue open to fix this

**Comment by callado4** [comment]
What was the other issue where this was going to be fixed in? I have the latest version of SAM CLI (SAM CLI, version 0.3.0) and I'm getting this issue now.

**Comment by sanathkr** [comment]
It is #188

**Comment by sromano88-svc** [comment]
Unfortunately not yet available even in v1.3.2.
Based on that it is a local environment issue, we can try with small files of about 95 kB (See great explanation here - https://github.com/aws/aws-sam-cli/issues/188#issuecomment-538370921).

Note: I am using sam local mainly for tests so I can do it with small files.
