### ISSUE TITLE
Mocking a Cloudfront Lamda@Edge event using start-api

### ISSUE THREAD

**Issue by hmgibson23** [awslabs/aws-sam-cli#352]
This is really a question.

Is it possible to mock a Lambda@Edge event when running the lamdba through an api.

So my lambda expects something like:
```
{ "Records": [
    {
      "cf": {
        "config": {
            ...
        },
        "request": {
          "headers": {
              ...
          },
          "origin": {
              ...
          }
        },
        "response": {
          "status": "200",
          "statusDescription": "OK",
          "headers": {
              ...
          }}}}]}
```

I can pass along a mock event if calling the lamda directly: ```sam local <lambda> -e event.json``` but if I make the request through the api, a GET (or whatever) event is passed and the lamdba fails and returns null (as I've told it to), but this breaks the start-api. So, basically, can I mock the cf event when it's running as an api?

**Comment by jfuss** [comment]
The CLI requires the functions behind an Api Gateway to be returning a Proxy response. `null` is not a valid response for the Proxy and therefore will fail, as it is expected too. 

Currently, your options would be:
1. Continue to use `sam local invoke` and pass in the Edge Event.
1. Modify your Lambda to return a proxy response that is expected.
