### ISSUE TITLE
Docs incorrect

### ISSUE THREAD

**Issue by charsleysa** [awslabs/aws-sam-cli#359]
The docs which cover additional debug arguments talk about setting an environment variable called `DEBUGGER_ARGUMENTS`. https://github.com/awslabs/aws-sam-local#passing-additional-runtime-debug-arguments

Though this does not work and in the source code it looks like it's referring to `DEBUGGER_ARGS`. https://github.com/awslabs/aws-sam-local/blob/develop/runtime.go#L439

**Comment by jfuss** [comment]
@charsleysa Good catch. Would you be willing up update and send a PR?

**Comment by charsleysa** [comment]
Closed by #399 
cc @jfuss
