### ISSUE TITLE
Clojure support

### ISSUE THREAD

**Issue by jplaza** [awslabs/aws-sam-cli#365]
We have successfully deployed Clojure based projects uberjars to production, but SAM local seems to load the JAR differently that the actual AWS Lambda platform.
I'm guessing it has something to do with how dependencies are loaded. This works when uploading to Lambda but doesn't work on SAM local:

```clojure
(ns awslambda.test
  (:require [cheshire.core :as json]
            [lambada.core :refer [deflambdafn]]
            [clojure.java.io :as io]))

(deflambdafn awslambda.test.CreateCommand
  [in out ctx]
  (json/generate-stream {:statusCode "200"
                         :body "Hello SAM Local!"}
                        (io/writer out)))
```

```stacktrace
java.lang.UnsupportedOperationException: handleRequest (awslambda.test/G__11099handleRequest not defined?)
	at awslambda.test.CreateCommand.handleRequest(Unknown Source)
```

I also found out that using `deftype` to implement the `com.amazonaws.services.lambda.runtime.RequestStreamHandler` interface works but I need to require used `ns` again, which is obviously too hacky.

```clojure
(ns awslambda.test
  (:require [cheshire.core :as json]))

(deftype CreateCommandHandler []
  RequestStreamHandler
  (^void handleRequest [this ^InputStream in ^OutputStream out ^Context ctx]
    (require '[cheshire.core :as json])
    (let [resp (json/generate-string {:statusCode "200"
                                      :body "Hello SAM, from deftype!"})]
      (.log (.getLogger ctx) resp)
      (spit out resp))))
```

**Comment by jfuss** [comment]
SAM CLI only supports official Lambda Runtimes. While you can deploy Closure using the Runtime Java8, SAM CLI does not guarantee support these use-cases.
