### ISSUE TITLE
Install sam local without npm?

### ISSUE THREAD

**Issue by red8888** [awslabs/aws-sam-cli#366]
How can I install sam local without npm?

**Comment by andreabedini** [comment]
it's a single static binary, so pretty much

```
curl -L https://github.com/awslabs/aws-sam-local/releases/download/v0.2.11/sam_0.2.11_darwin_amd64.tar.gz | tar xz -C /usr/local/bin sam
```

or similar, releases can be found [here](https://github.com/awslabs/aws-sam-local/releases)

**Comment by jfuss** [comment]
Now you don't need NPM at all :)

See our current release notes for details: https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0

Closing as we moved away from npm and to pip

**Comment by andreabedini** [comment]
😱 this is terrible.
