### ISSUE TITLE
Use in CI?

### ISSUE THREAD

**Issue by ianwremmel** [awslabs/aws-sam-cli#378]
Is it possible to use `sam local start-api` in commodity CI environments and, if not, can such support be added? I spent about a day trying to get it working on Circle CI 2.0 and while I *think* I got the service running, it looks like my test code can't actually reach the sam-hosted endpoints.

**Comment by sanathkr** [comment]
It should just work in a CI environment as long as your environment can run a Docker container. If you ran into specific issues, feel free to open the Issue with your problems. We will be happy to dive deep.
