### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListPolicies operation

### ISSUE THREAD

**Issue by luistm** [awslabs/aws-sam-cli#394]
After upgrading to 0.3.0 I have the following error: 

`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListPolicies operation: User: arn:aws:iam::9999999999:user/user.name is not authorized to perform: iam:ListPolicies on resource: policy path /`

I'm using the latest version of MacOS.

Anyone having the same issue ?

**Comment by sanathkr** [comment]
You need to set AWS Credentials for ‘Sam validate’ command to work. You can set them using the AWS CLI

**Comment by luistm** [comment]
The role was missing the access to iam:ListPolicies. 

Thanks

**Comment by chkp-dhouari** [comment]
The role was missing the access to iam:ListPolicies.
How do to add that..i am trying to my codebuild service role
