### ISSUE TITLE
[Feature Request] Support --profile in `sam validate`

### ISSUE THREAD

**Issue by jfuss** [awslabs/aws-sam-cli#396]
**Description:**

Currently `sam validate` requires AWS Credentials to be configured. A typically way this is done on the aws cli is passing in a --profile option into the command. We support this behavior for sam local commands (invoke and start-api).

**Steps to reproduce the issue:**
1. `sam validate --profile <name>

**Observed result:**

```
Error: no such option: --profile
```

**Expected result:**

This should run validate with the creds from the profile that is configured.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Output of `sam --version`**:

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by sbol-coolblue** [comment]
AWS team: thanks for the contributors/good-first-issue label! Much appreciated :) Not sure if my PR is up to standards, but I'll be happy to receive feedback on it.

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)
