### ISSUE TITLE
validate should catch circular resource dependencies

### ISSUE THREAD

**Issue by kay-is** [awslabs/aws-sam-cli#406]
**Description:**
I got a template validated by sam-local, but it failed to deploy because of circular dependencies.

**Steps to reproduce the issue:**
1. Defined a state machine that had a task with a Lambda function as resource
2. Passed the state machines ARN into the Lambda functions environment variables
3. Ran `sam validate` 
4. Ran `sam package...`
5. Ran `sam deploy...`

**Observed result:**

Get an error from CloudFormation.

**Expected result:**

Get an error from sam-locals validate command

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac

**Output of `sam --version`**: 0.2.11

**Comment by kay-is** [comment]
Oh, it had probably to do with the fact, that I defined the state-machine ARN environment variable in globals.

**Comment by sanathkr** [comment]
This is definitely a nice to have feature. But this will require us to re-implement large parts of the behavior of the CloudFormation service. This is out of the scope for SAM CLI for now, but we can revisit later if things change.
