### ISSUE TITLE
sam local not recognized as a valid command

### ISSUE THREAD

**Issue by grogithub** [awslabs/aws-sam-cli#410]
I am following this doc 
https://docs.aws.amazon.com/lambda/latest/dg/test-sam-cli.html

I could successfully install sam and could also output sam --version to confirm
But sam local command fails 
I have docker running in my system tray as displayed
can anyone help please?

**Comment by jfuss** [comment]
@grogithub Please add the following details. It's very difficult understand the problem.

* What versions does `sam --version` output?
* Any debug logs?
* What command did you run that was not recognized?

**Comment by grogithub** [comment]
Thanks jfuss. Here is the version info I current have and please note with 0.2.11 it does have sam local recognized, but in the higher 0.3.0 version there is no support for the local clause

Your version:   0.2.11
Latest version: 0.3.0

**Comment by grogithub** [comment]
Your version:   0.2.11
Latest version: 0.3.0
I am on version 0.2.11 and now the command sam local runs perfect 
While on the higher 0.3.0 level, it fails since the support for local clause does not exist

**Comment by yzhao1216** [comment]
Hey @jfuss after I , pip install --user aws-sam-cli, when I try to sam --version, it says:
