### ISSUE TITLE
Bind for 0.0.0.0:80 failed: port is already allocated

### ISSUE THREAD

**Issue by neuberfran** [awslabs/aws-sam-cli#412]
Hi,
When I tried this: https://cuprak.info/2017/10/09/debugging-aws-lambda-with-netbeans/#comments

I have this issue:
![39204944-abbdba62-47cf-11e8-9dfc-c508852f0288](https://user-images.githubusercontent.com/38701397/39974472-7d0e4fd0-56ff-11e8-9302-4305b5c9edd7.png)

Never work. I need run sam local start-api (without -d 5858) to see correct template in my brower (http://localhost:3000/products)...
![39851240-342effdc-53ec-11e8-83e9-984086d64694](https://user-images.githubusercontent.com/38701397/39974541-e117afc6-56ff-11e8-85f1-be6e27e413ea.png)

If I run with -d 5858:
![39851250-38f293f8-53ec-11e8-83b5-88d4e18d7769](https://user-images.githubusercontent.com/38701397/39974547-eb691b0e-56ff-11e8-8d3b-80385625de3b.png)

I have more screens to help us to solve and a question: what about docker-proxy:?????

https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/39

![9jdzh](https://user-images.githubusercontent.com/38701397/39974559-001f6fee-5700-11e8-9293-2500b8958231.jpg)

![39851265-49bd6032-53ec-11e8-8f68-f8897028d49f](https://user-images.githubusercontent.com/38701397/39974564-0b057ee4-5700-11e8-9a85-629a1a7a888c.png)

![39851350-b876b7b2-53ec-11e8-9fb3-3420f2738dcd](https://user-images.githubusercontent.com/38701397/39974565-0de8e380-5700-11e8-9946-ca00f1bdd5ac.png)

https://stackoverflow.com/questions/50050904/bind-for-0-0-0-080-failed-port-is-already-allocated-issue-in-aws-sam-local-pro

**Comment by sanathkr** [comment]
Hey thanks for bringing this up. I think similar to the StackOverflow post says, can you try `docker ps` to make sure there are no running Docker containers. Also, don't use port 80 because in most systems that is protected by default. Use Port 8080 instead or something greater than 1024. 

Closing this for now because this is not an bug. But feel free to re-open

**Comment by neuberfran** [comment]
I want to reopen because the solutions proposed by you have not resolved. Understand that when I do not use the -d option (any port number here) the command works but I can not debug
