### ISSUE TITLE
API Gateway returns Server header

### ISSUE THREAD

**Issue by brentpabst** [awslabs/aws-sam-cli#424]
**Description:**

With the rewrite to Python from Go the utility now inserts a server header in all responses: Server →Werkzeug/0.14.1 Python/2.7.10.  The prior utility returned no header.  For testing purposes this header should not be returned, especially if security tests require the server header to not be returned.

**Steps to reproduce the issue:**
1. Create an API handler
2. Use sam local start-api function
3. Issue request to new api

**Observed result:**
HTTP Server header exists: Server →Werkzeug/0.14.1 Python/2.7.10

**Expected result:**
HTTP Server header does not exist or reflects the AWS Lambda server header settings instead

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
OSX

**Output of `sam --version`**:
SAM CLI, version 0.3.0

**Optional Debug logs**:
N/A

**Comment by mingkun2020** [comment]
@brentpabst , Thanks for reporting this issue and sorry for delayed response. We use Flask to generate an http server for `sam local start-api`. When Flask generates the response, it auto fills the server header. Flask does not offer a way to remove/or not add the server header to the response. As a workaround you can test this in the cloud and that works as expected. I am closing this issue for now, please re-open if you have more questions or concerns.
