### ISSUE TITLE
Examples link in Readme broken

### ISSUE THREAD

**Issue by oharaandrew314** [awslabs/aws-sam-cli#430]
In the [Examples Section](https://github.com/awslabs/aws-sam-cli#examples) of the Readme, there's a link to a `samples` folder, which is broken.

Where should we send users to instead?

**Comment by oharaandrew314** [comment]
Good catch, I've created a PR to remove the broken link.

**Comment by TheSriram** [comment]
Closing this issue, as PR is merged.
