### ISSUE TITLE
Unable to capture the environment variables from either json file or template file in 0.3.0

### ISSUE THREAD

**Issue by dotekien** [awslabs/aws-sam-cli#440]
**Description:**
Unable to capture the environment variables from either json file or template file
Both:
sam local start-api --env-vars env.json
or 
template.yaml
      Environment:
        Variables:
          STAGE: local

**Steps to reproduce the issue:**
1. Using release 0.3.0
2.
3.

**Observed result:**

**Expected result:**

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Output of `sam --version`**:

**Optional Debug logs**:

env.go has not in 0.3.0

`Add --debug flag to command you are running`

**Comment by mims92** [comment]
Json file doesn't work for me.

But I solved my issue regarding no Environment variables passed to the container:
It was due to a wrong indentation in the template.yaml file.

Stupid mistake :)
