### ISSUE TITLE
sam --version doesn't work

### ISSUE THREAD

**Issue by yzhao1216** [awslabs/aws-sam-cli#448]
**Description:**
I am using python 2.7 in Windows
I did pip install --user aws-sam-cli, and then I do pip list, I can see aws-sam-cli has version 0.3.0. 
However, when I do sam --version in cmd, I got: 
_'sam' is not recognized as an internal or external command,
operable program or batch file._
I think it is environment variable path issue, but I don't know which path to put there. 
**Steps to reproduce the issue:**
1.
2.
3.

**Observed result:**

**Expected result:**

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Output of `sam --version`**:

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by sanathkr** [comment]
You should be setting the PATH in your machine to the installation of SAM CLI.

**Comment by cristiean** [comment]
sanathkr, could you please shed some light on how to set the PATH to the installation of SAM CLI? the sentence "in Windows systems the command py -m site --user-site typically print %APPDATA%\Roaming\Python<VERSION>\site-packages, so you'll need to remove the last \site-packages folder and replace it with the \Scripts one." is not really helpful to me. 

I tried adding the path in my environment variables. Didn't work

I tried running these commands in my Windows Command Prompt. Didn't work
`# Find your Python User Base path (where Python --user will install packages/scripts)
$ USER_BASE_PATH=$(python -m site --user-base)

# Update your preferred shell configuration
## Standard bash --> ~/.bash_profile
## ZSH           --> ~/.zshrc
$ export PATH=$PATH:$USER_BASE_PATH/bin` 

Am I doing something wrong?

**Comment by markthegrea** [comment]
If I may be so bold, where is SAM CLI installed at?

I seem to already have the python/scripts folder in my path.

**Comment by dpmott** [comment]
For me, it's at /c/Program\ Files/Amazon/AWSSAMCLI/bin/sam.cmd (or c:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd, if you're using that filespec)

(I do have the file that @markthegrea mentions, but executing it yields "failed to create process".  I installed sam via instructions and the windows installer at: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html)

I'm currently having the issue that Git Bash doesn't seem to natively know how to find executables with a ".cmd" file extension, even if they are in the path. :/

**Comment by forgivegod** [comment]
> I'm currently having the issue that Git Bash doesn't seem to natively know how to find executables with a ".cmd" file extension, even if they are in the path. :/

create an alias, 

$ alias sam='sam.cmd'

**Comment by dacgray** [comment]
Note, in a script you can do:

```
sam deploy || sam.cmd deploy
```

**Comment by arryan231** [comment]
> For me, it's at /c/Program\ Files/Amazon/AWSSAMCLI/bin/sam.cmd (or c:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd, if you're using that filespec)
> 
> (I do have the file that @markthegrea mentions, but executing it yields "failed to create process". I installed sam via instructions and the windows installer at: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html)
> 
> I'm currently having the issue that Git Bash doesn't seem to natively know how to find executables with a ".cmd" file extension, even if they are in the path. :/

were you able to solve this problem

**Comment by subwaymatch** [comment]
@arryan231 For me, adding an alias to `~/.bashrc`  with a full path to the `.cmd` file worked. This was one of the solutions suggested in a [StackOverflow thread](https://stackoverflow.com/questions/62986561/git-bash-will-not-resolve-sam-command).

Open `.bashrc`.
```bash
vim ~/.bashrc
```
![image](https://user-images.githubusercontent.com/1064036/189913135-974ee24b-44f8-468d-a141-e95c737dc8cc.png)

Add the line below to the `.bashrc` file.
```
alias sam="/c/Program\ Files/Amazon/AWSSAMCLI/bin/sam.cmd"
```
![image](https://user-images.githubusercontent.com/1064036/189913034-f5749313-4f4f-4f1d-b996-da6b9da8c535.png)

Reload `.bashrc` settings.
```bash
source ~/.bashrc
```
![image](https://user-images.githubusercontent.com/1064036/189913227-7dcee69c-666e-4c1f-9ca5-2296484cd34e.png)

Try running `sam --version`.
![image](https://user-images.githubusercontent.com/1064036/189913316-cd09554f-52ea-48a7-a630-360cd806fcbb.png)

**Comment by Akotox** [comment]
> Note, in a script you can use:
> 
> ```
> sam deploy || sam.cmd deploy
> ```

cdk synth && sam.cmd in my case this worked
