### ISSUE TITLE
The way to run two lambdas, one of which is waiting call from another. 

### ISSUE THREAD

**Issue by alex-semenyuk** [awslabs/aws-sam-cli#458]
Is there way to run two lambdas, one of which is waiting call from another or plan an enhancement? It would be very helpful for debugging purposes.

**Comment by jfuss** [comment]
@alex-semenyuk It is not clear to me what you are asking. Are you asking if one local lambda can call another or something else?

**Comment by alex-semenyuk** [comment]
@jfuss Yes, one call another with AWSLambdaClient and would like to have ability to debug them.

**Comment by TheSriram** [comment]
sam local start-lambda should be what you are looking for.

**Comment by jfuss** [comment]
@alex-semenyuk As @TheSriram stated, you can achieve this through `sam local start-lambda` and configuring the endpoint of the client to be the `host:port` of the service that the command starts. You may need to use `host.docker.internal` for docker to talk to you machine.

Closing as this is support and we will use #510 to track the adding documentation for this.
