### ISSUE TITLE
Cant upgrade to 0.3.0 on macOS

### ISSUE THREAD

**Issue by jarrettj** [awslabs/aws-sam-cli#465]
Hi,

Good day.

I've tried removing sam in my host macOS machine and no luck.

I run uninstall npm uninstall -g aws-sam-local

macOS output:
```
$ sudo npm uninstall -g aws-sam-local
> aws-sam-local@0.2.11 preuninstall /Users/thejj/.nvm/versions/node/v9.11.1/lib/node_modules/aws-sam-local
> go-npm uninstall
removed 72 packages in 1.858s
```

**Observed result:**
Even though it is uninstalled, I can still run sam.
macOS output:
```
$ sam -v
A newer version of the AWS SAM CLI is available!
Your version:   0.2.11
Latest version: 0.3.0
See https://github.com/awslabs/aws-sam-local for upgrade instructions
sam version 0.2.11
```

I then try to install it with:
pip install --user aws-sam-cli and pip install --user --upgrade aws-sam-cli
macOS output:
```
$ sudo pip install --user --upgrade aws-sam-cli
Requirement already up-to-date: aws-sam-cli in /Users/thejj/Library/Python/2.7/lib/python/site-packages (0.3.0)

$ sudo pip install --user aws-sam-cli
Requirement already satisfied: aws-sam-cli in /Users/thejj/Library/Python/2.7/lib/python/site-packages (0.3.0)

$ sam -v
A newer version of the AWS SAM CLI is available!
Your version:   0.2.11
Latest version: 0.3.0
See https://github.com/awslabs/aws-sam-local for upgrade instructions
```

**Expected result:**
Expected sam to upgrade. Expected sam to completely uninstall. 

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
macOs

**Output of `sam --version`**:
A newer version of the AWS SAM CLI is available!
Your version:   0.2.11
Latest version: 0.3.0
See https://github.com/awslabs/aws-sam-local for upgrade instructions

Is there something macOS specific that I am missing maybe? Thanks.

Regards.
JJ

**Comment by jfuss** [comment]
@jarrettj Do you remember how you installed SAM CLI originally? Seems like SAM CLI never fully uninstalled. 

I don't know much about npm but would assume you can still do `which sam` and then forcefully delete it. 

Closing as this is an npm issue and not SAM CLI.

**Comment by heitorlessa** [comment]
Seen this in a custom installation with sudo, if that’s the case...

Remove the old go binary: sudo rm $(which sam)

Install the new Sam CLI: pip install aws-sam-cli —user

Adjust your path to add Python User Scripts (instructions in the
troubleshooting section)

Open up a new terminal
