### ISSUE TITLE
sam init --runtime python3.6 does not create a Makefile

### ISSUE THREAD

**Issue by jlhood** [awslabs/aws-sam-cli#467]
**Description:**

`sam init --runtime python3.6` sets up a basic python serverless app, but does not include a Makefile to make it easy to build and run unit tests out of the box.

**Steps to reproduce the issue:**
1. `sam init --runtime python3.6` --name my-app
1. `cd my-app`
1. `make`

**Observed result:**

```
make: *** No targets specified and no makefile found.  Stop.
```

**Expected result:**

Builds serverless app and runs tests. Should include some kind of basic targets for build and test.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac

**Output of `sam --version`**:

```
SAM CLI, version 0.3.0
```

**Comment by jfuss** [comment]
@jlhood This was an explicit choice. Makefiles will not work by default in windows and is the reason we won't be adding them into the main `sam init` command. The README that is generated does step you through what was generated, how to build and run tests.

`sam init --location git+ssh://git@github.com/aws-samples/cookiecutter-aws-sam-python.git` might be what you actually want, if you are looking to do something more advanced.
