### ISSUE TITLE
!FindInMap does not work to set Environment Variables

### ISSUE THREAD

**Issue by bnegrao** [awslabs/aws-sam-cli#476]
**Description:**

I am using !FindInMap to set an environment variable value and when I run it with  `sam local start-api` the variable is empty.

**Steps to reproduce the issue:**
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          S3BUCKETURL: !FindInMap: [URLS, S3Bucket, test]              
         

Mappings:
  "URLS" : {
    "S3Bucket" : {
      "sam_local" : "http://sam_local_url",
      "test": "http://test_url",
      "prod" : "http://prod_url"
    }
  }
```

**Observed result:**
Empty string as variable value

**Expected result:**
S3BUCKETURL="http://test_url"

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Ubuntu 18

**Output of `sam --version`**:
SAM CLI, version 0.3.0

**Comment by jfuss** [comment]
We currently do not resolve Intrinsic functions. For Environment Variables, you can use the `--env-vars` instead.

Marking this as a feature-request.

**Comment by walkafwalka** [comment]
@jfuss I noticed this was tagged as stage/waiting-for-release, is this feature supposed to be available in one of the branches right now?

**Comment by jfuss** [comment]
@walkafwalka It is in the develop branch.

**Comment by jfuss** [comment]
Release in [v0.21.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.21.0).

Closing
