### ISSUE TITLE
Debug SAM Local with compiled languages, such as .NET Core?

### ISSUE THREAD

**Issue by fkmare** [awslabs/aws-sam-cli#500]
Is it possible to debug SAM Local with compiled languages, such as .NET Core?

**Comment by sanathkr** [comment]
Unfortunately no, at the moment. I am marking this as a feature request. We are building the first steps in that direction with the excellent Pull Request @austinlparker contributed. If you have expertise on dotnet debugging works, we could use some help :)

**Comment by fkmare** [comment]
Thank you @sanathkr unfortunately I don't have experience with that. Looking forward to it!

**Comment by jfuss** [comment]
Debugging .Net Core is now supported for VSCode in [v0.9.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.9.0). Closing
