### ISSUE TITLE
[Feature Request] generate function events from swagger

### ISSUE THREAD

**Issue by houbie** [awslabs/aws-sam-cli#504]
Currently you have to duplicate your API paths in both the swagger and in the events of the lambda in the SAM template. This could be more DRY by either:
* implicit generation of the lambda events from the swagger paths
* allowing a _catch all_ lambda event like `/*`
I hoped a `/{proxy+}` lambda event in my SAM template would do the trick, but then I get _No function defined for resource method_ in sam local when accessing a path that is defined in the swagger but not in the lambda events

**Comment by sanathkr** [comment]
When you mean implicit generation of events, you mean implicitly add `Event` section to your `AWS::Serverless::Function` resource? This is a good feature request to SAM Repository (https://github.com/awslabs/serverless-application-model). 

For your second question: `/{proxy+}` must work with `sam local start-api` command to catch all your routes. Make sure you have latest version of SAM CLI (>v0.3.0). If you do have latest version, can you post your SAM template snippet so we can examine?

**Comment by houbie** [comment]
With following swagger:
```
swagger: "2.0"
info:
  version: 1.0.0
  title: Notes
  description: Simple note keeping application
host: notes.swagger.io
basePath: /prod
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
   /info:
    get:
      summary: Application info
      operationId: info
      responses:
        "200":
          description: Application info and request/context details
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${APILambda.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
```
and template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS serverless demo application using SAM, API-gateway, Lambda and Dynamo DB

Resources:
  APIGatewayNodejs:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

      DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location: ../swagger.yaml

  APILambdaNodejs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/bundle.js.zip
      Handler: bundle.handler
      Runtime: nodejs8.10
      Events:
        Info:
          Type: Api
          Properties:
            RestApiId: !Ref APIGatewayNodejs
            Path: /info
            Method: ANY
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref APIGatewayNodejs
            Path: /{proxy+}
            Method: GET
```
I can GET http://127.0.0.1:3000/info
When I remove the Info event in the template, the output of Sam local still shows the info endpoint:
```
2018-07-04 09:47:09 Mounting APILambdaNodejs at http://127.0.0.1:3000/{proxy+} [GET]
2018-07-04 09:47:09 Mounting APILambda at http://127.0.0.1:3000/info [GET]
```
but the /info enpoint gives an error: `{"message":"No function defined for resource method"}`

**Comment by jfuss** [comment]
@houbie This is an issue with your template not the CLI. You still have a path in your swagger for `/info` that points to a Lambda Function with the Logical Id of `APILambda`. Since this is not in your template, the CLI can't invoke the function and returns the error you are seeing. 

If you want `{proxy+}` to catch everything, you should be removing the `/info` path from your swagger file.

**Comment by jfuss** [comment]
Closing as there hasn't been a response since July 5th, 2018

**Comment by JoseExposito** [comment]
Any update on this issue? Is it possible to avoid this duplication in the latest versions?
