### ISSUE TITLE
How To Adjust Path?

### ISSUE THREAD

**Issue by JimTheMan** [awslabs/aws-sam-cli#514]
Please complete the documentation in README:

```
Adjust your PATH to include Python scripts installed under User's directory:

# Find your Python User Base path (where Python --user will install packages/scripts)
$ USER_BASE_PATH=$(python -m site --user-base)

# Update your preferred shell configuration
## Standard bash --> ~/.bash_profile
## ZSH           --> ~/.zshrc
## OSX users may need to append 'bin': $USER_BASE_PATH/bin
$ export PATH=$PATH:$USER_BASE_PATH
```

If it is not a simple copy/paste into .bash_profile, please explain what the heck "where Python --user will install packages/scripts" is supposed to mean. thanks.

**Comment by jfuss** [comment]
It means "$ USER_BASE_PATH=$(python -m site --user-base)". That is the line under the comment. 

Do you have an alternative way to phrase this because it is a comment explaining the command right below it?

**Comment by sanathkr** [comment]
#515 will fix this documentation. Meanwhile read https://github.com/kennethreitz/python-guide/blob/master/docs/dev/virtualenvs.rst#L88-L103 for more detailed guide.

**Comment by sanathkr** [comment]
Closing this Issue because there is a PR that will fix it soon.
