### ISSUE TITLE
Add API Gateway Event Input and Output to "app.js" and "app.py"

### ISSUE THREAD

**Issue by danilop** [awslabs/aws-sam-cli#518]
The Node.js and Python hello world examples don't separate clearly what is the syntax used by the API Gateway and what is the basic logic of the example.

I suggest to rename the input "event" as "apiGatewayEvent" and add a link to the Lambda Proxy input/output syntax:

[input format](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format)

[output format](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format)

**Comment by heitorlessa** [comment]
Context: 

**Python**: https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/app.py#L10

**NodeJS**: https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/app.js#L12

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)
