### ISSUE TITLE
Manage `error/exception` for all templates except Go

### ISSUE THREAD

**Issue by danilop** [awslabs/aws-sam-cli#520]
Specifically, in case of error/exception (for example, calling a wrong URL in the template):
- Python/Nodejs needs to return 500 and print error
- Java is returning 400 instead of 500

**Comment by heitorlessa** [comment]
For context: 

**Java**: https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-java/%7B%7Bcookiecutter.project_name%7D%7D/src/main/java/helloworld/App.java#L28

**Python**: https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/app.py#L19

**JS**: https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/app.js#L41

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)
