### ISSUE TITLE
Fix default Python runtime to Python 3.6

### ISSUE THREAD

**Issue by danilop** [awslabs/aws-sam-cli#521]
Currently, if you don't specify a Python version, the old Python 2.7 runtime is selected.

**Comment by heitorlessa** [comment]
For context: https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/template.yaml#L24

**Comment by alexcasalboni** [comment]
This has been fixed/merged already, but I think we should only have `python2.7` and `python3.6` to avoid confusion.

Let's never forget:

> There should be one — and preferably only one — obvious way to do it.
> [[Zen of Python](https://en.wikipedia.org/wiki/Zen_of_Python)]

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)
