### ISSUE TITLE
NodeJs Request Module is not working

### ISSUE THREAD

**Issue by penguinnorth** [awslabs/aws-sam-cli#534]
Hello,

I'm using MAC, SAM(v 0.4.0), NodeJS(v6.14.3), Python(v3.6.0), Request(v2.83.0).
In my code, I have:

const options = {
      url: 'some url string',
      method: 'POST',
      timeout: 5000,
      json: true
    };

request(options, (error, response, body) => {
      console.log('error:', error);
      console.log('statusCode:', response && response.statusCode);
      console.log('body:', body);

      callback(null, 'Finished processing');
});

I keep getting error:
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/node_modules/request/index.js:17:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

{"errorMessage":"Cannot find module 'extend'","errorType":"Error","stackTrace":["Function.Module._load (module.js:417:25)","Module.require (module.js:497:17)","require (internal/module.js:20:19)","Object.<anonymous> (/var/task/node_modules/request/index.js:17:14)","Module._compile (module.js:570:32)","Object.Module._extensions..js (module.js:579:10)","Module.load (module.js:487:32)","tryModuleLoad (module.js:446:12)","Function.Module._load (module.js:438:3)"]}

If I remove the last part 'request(options, (error, response, body)...', there is no errors.
Anybody can tell me what happened? Thanks!

**Comment by penguinnorth** [comment]
Problem resolved.
The issue seems like the docker cannot find the unzip folder.

Thanks for reading.

**Comment by poppahorse** [comment]
@penguinnorth How did you resolve?
