### ISSUE TITLE
Can't find template.yaml or "samples" folder.

### ISSUE THREAD

**Issue by Mohan1996** [awslabs/aws-sam-cli#547]
Following this tutorial, but I can't seem to find a template.yaml file, or the "samples" folder. Has this been moved to a different directory?

https://blog.rowanudell.com/getting-started-with-aws-sam-local/

**Comment by jfuss** [comment]
samples folder has been removed in favor of the `sam init` command. Examples for SAM can be found in SAM's repo: https://github.com/awslabs/serverless-application-model/tree/master/examples

**Comment by Mohan1996** [comment]
Got it, thank you!
