### ISSUE TITLE
Unable to import module error when running "http://127.0.0.1:3000/hello" from tutorial

### ISSUE THREAD

**Issue by Mohan1996** [awslabs/aws-sam-cli#548]
https://imgur.com/a/YZ2sPjW

I tried the URL "http://127.0.0.1:3000/hello" and got a "No data" message on the URL page. This was the error message I got in the terminal. How do I fix this?

**Comment by Mohan1996** [comment]
Wanted to update this, incase anyone else ran into this issue. The README appeared as blank in sublime when I opened it (not sure why), so I didn't know that I had to run NPM install. I randomly opened it again after a couple hears of headaches and reliazed that the README in fact did contain instructions on how to proceed. If anyone else has this issue with "importing module 'app' ", run NPM INSTALL in the directory that contains app.js.

**Comment by devvpm** [comment]
I have this issue while running on python3.7
