### ISSUE TITLE
Log messages are neither printed in the console nor saved into log file

### ISSUE THREAD

**Issue by bigunyak** [awslabs/aws-sam-cli#549]
In SAM v0.4.0 log messages logged with `logging` module (python 3.6) are neither shown in the console nor printed in the log file with the `--log-file` option.
Looks like a regression bug after migrating to python implementation as the same issue was reportedly fixed in #91 and #124 
Trivial code to reproduce the issue is below.
```python
import logging

logging.basicConfig(level=logging.INFO, format='[%(asctime)s] [%(levelname)s] %(message)s')
log = logging.getLogger(__name__)

def handler(event, context):
    log.info("Received S3 event: " + json.dumps(event, indent=2))
    print("TESTTTTTTTTTTTTTTTTTT")
```
Print function works as expected but logging messages are missing.

**Comment by mhart** [comment]
I don't get any output to the logs on a production Lambda with this code – do you?

**Comment by mhart** [comment]
Here's the code I'm testing:
```python
import logging

logging.basicConfig(level=logging.INFO, format='[%(asctime)s] [%(levelname)s] %(message)s')
log = logging.getLogger(__name__)

def lambda_handler(event, context):
    log.info("From log.info")
    context.log("From context.log\n")
    print("From print")
```

And the output:

```
START RequestId: 3b08f65c-89e1-11e8-9e88-514fc42a5b51 Version: $LATEST
From context.log
From print
END RequestId: 3b08f65c-89e1-11e8-9e88-514fc42a5b51
REPORT RequestId: 3b08f65c-89e1-11e8-9e88-514fc42a5b51	Duration: 0.54 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 21 MB	
```

**Comment by jfuss** [comment]
@bigunyak @mhart is correct. What you have does not work in the Lambda Service and therefore will not work locally. By some testing, it doesn't appear that `logging.basicConfig` is respected by the Lambda Runtime. I was able to get this to work:

```
import logging

log = logging.getLogger(__name__)
log.setLevel(logging.INFO)


def lambda_handler(event, context):
    log.info("From log.info")
    context.log("From context.log\n")
    print("From print")
```

So instead of using basicConfig, you should use `addHandler`, `setLevel`, etc on the logger directly.

Closing as this is not specific to the CLI and the CLI matches the Lambda Service.
