### ISSUE TITLE
Invoke Function Without Parameters (skip STDIN)

### ISSUE THREAD

**Issue by adeitcher** [awslabs/aws-sam-cli#556]
**Description:**

It does not seem that there is a way to invoke a function without passing in some kind of event, even if the lambda Handler takes no arguments, as the lack of params defaults to waiting for input from STDIN. No arg handler functions are valid, at least in Golang (haven't looked at other programming languages)

https://docs.aws.amazon.com/lambda/latest/dg/go-programming-model-handler-types.html

**Steps to reproduce the issue:**
1. invoke function normally `sam local invoke MyFunc`

**Observed result:**
1. With no event, function execution waits for input from stdin
2. With a dummy event e.g. `echo '{}' | sam local invoke MyFunc`, function executes immediately despite not taking any argument params `func handler() error`

**Expected result:**
Possibly pass a command line flag like `--no-args` so that the lambda executes immediately rather than waiting for STDIN

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
OS X 10.13.5 High Sierra

**Output of `sam --version`**:
SAM CLI, version 0.3.0

**Comment by tebruno99** [comment]
This actually would be super useful when developing against SQS.

**Comment by akkaash** [comment]
Looking into this.

**Comment by jfuss** [comment]
Closing this as it was released in [0.6.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.0)
