### ISSUE TITLE
Support for CFN intrinsic functions in sam local

### ISSUE THREAD

**Issue by amirkav** [awslabs/aws-sam-cli#573]
Coming here from #194: this is a much-needed feature for sam local to support CFN intrinsic functions. For us, the main use of sam local is to speed up development and testing. This will only be achieved if 'sam local invoke' works with the same template as the main template that will be used to deploy lambda functions to aws. It defeats the purpose if we need to maintain a separate template just for using with sam local.

**Comment by DanielRedOak** [comment]
I think some basic documentation around what works and where would be valuable now that there is some support but not for all. Working off of some SAM templates I was attempting to !Ref resources locally, chasing my tail when it didn't work 😄

**Comment by jfuss** [comment]
Release in [v0.21.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.21.0).

Closing
