### ISSUE TITLE
I can't install aws-sam-cli (sam init helloworld) using python 3.6 and pip3.6 or pip 

### ISSUE THREAD

**Issue by neuberfran** [awslabs/aws-sam-cli#580]
Hi,

**_I tried with python 3.6 but I have new issues:_**

root@neuberfran:/home/neuberfran# pip3.6 install --user aws-sam-cli
Collecting aws-sam-cli
Downloading https://files.pythonhosted.org/packages/5b/af/a26ebaa72183ff2ad1655e89d8477ebf6e92c1f03cf15c97224887d358d8/aws-sam-cli-0.5.0.tar.gz (162kB)
100% |████████████████████████████████| 163kB 1.5MB/s
Collecting six~=1.11.0 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting click~=6.7 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting enum34~=1.1.6 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting Flask~=1.0.2 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting boto3~=1.5 (from aws-sam-cli)
Downloading https://files.pythonhosted.org/packages/d0/10/fa502e2f1e995e007af3ef1c3ab647a5679990c57ad4d168e25279ca7913/boto3-1.7.63-py2.py3-none-any.whl (128kB)
100% |████████████████████████████████| 133kB 1.8MB/s
Collecting PyYAML~=3.12 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Collecting cookiecutter~=1.6.0 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1.6.0-py2.py3-none-any.whl
Collecting aws-sam-translator==1.6.0 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/f6/49/9055710c7c12bf2022661d7402b53047dcd8fe5e5c0b03ee3600993ca66d/aws-sam-translator-1.6.0.tar.gz
Collecting docker>=3.3.0 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/a5/64/8c0a5d22e70257e6b7ef7f14b577f99f0b9b1560c604f87856d0db80d151/docker-3.4.1-py2.py3-none-any.whl
Collecting dateparser~=0.7 (from aws-sam-cli)
Downloading https://files.pythonhosted.org/packages/ac/9e/1aa87c0c59f9731820bfd20a8b148d97b315530c2c92d1fb300328c8c42f/dateparser-0.7.0-py2.py3-none-any.whl (357kB)
100% |████████████████████████████████| 358kB 4.5MB/s
Collecting python-dateutil~=2.6 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting Werkzeug>=0.14 (from Flask~=1.0.2->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting Jinja2>=2.10 (from Flask~=1.0.2->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask~=1.0.2->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz
Collecting botocore<1.11.0,>=1.10.63 (from boto3~=1.5->aws-sam-cli)
Downloading https://files.pythonhosted.org/packages/57/59/a1221949de618cda560017c9db004d88cc51a5956f6a778f42d54cd190d3/botocore-1.10.63-py2.py3-none-any.whl (4.4MB)
100% |████████████████████████████████| 4.4MB 4.1MB/s
Collecting jmespath<1.0.0,>=0.7.1 (from boto3~=1.5->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3~=1.5->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting whichcraft>=0.4.0 (from cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/60/8a/5c52e30e11672f7e3aa61f348ddae443d122bcd96bc8b785ac76dbae944b/whichcraft-0.4.1-py2.py3-none-any.whl
Collecting poyo>=0.1.0 (from cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/ea/6c/62c76c12015f6a1849446fb73da59be1229312c54d6d05068275e52bf29f/poyo-0.4.1-py2.py3-none-any.whl
Collecting requests>=2.18.0 (from cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting future>=0.15.2 (from cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting binaryornot>=0.2.0 (from cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting jinja2-time>=0.1.0 (from cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl
Collecting jsonschema~=2.6 (from aws-sam-translator==1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting docker-pycreds>=0.3.0 (from docker>=3.3.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/ea/bf/7e70aeebc40407fbdb96fa9f79fc8e4722ea889a99378303e3bcc73f4ab5/docker_pycreds-0.3.0-py2.py3-none-any.whl
Collecting websocket-client>=0.32.0 (from docker>=3.3.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl
Collecting regex (from dateparser~=0.7->aws-sam-cli)
Downloading https://files.pythonhosted.org/packages/9f/79/adbe79373ec3c56ae61670bbed30609fe4a9b6af835478fa12bf8795cdec/regex-2018.07.11.tar.gz (628kB)
100% |████████████████████████████████| 634kB 4.9MB/s
Collecting pytz (from dateparser~=0.7->aws-sam-cli)
Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
100% |████████████████████████████████| 512kB 4.5MB/s
Collecting tzlocal (from dateparser~=0.7->aws-sam-cli)
Downloading https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10->Flask~=1.0.2->aws-sam-cli) (0.23)
Collecting docutils>=0.10 (from botocore<1.11.0,>=1.10.63->boto3~=1.5->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting arrow (from jinja2-time>=0.1.0->cookiecutter~=1.6.0->aws-sam-cli)
Building wheels for collected packages: aws-sam-cli, PyYAML, aws-sam-translator, itsdangerous, future, regex, tzlocal
Running setup.py bdist_wheel for aws-sam-cli ... done
Stored in directory: /root/.cache/pip/wheels/bd/5e/5c/101058de2bac26bcaca161b098cc538cd69acbd2916cfe759a
Running setup.py bdist_wheel for PyYAML ... done
Stored in directory: /root/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
Running setup.py bdist_wheel for aws-sam-translator ... done
Stored in directory: /root/.cache/pip/wheels/e9/41/73/71b8e3b2a3c6eeb7c5403ae1df6bf2896e31f2a3b20fad444d
Running setup.py bdist_wheel for itsdangerous ... done
Stored in directory: /root/.cache/pip/wheels/2c/4a/61/5599631c1554768c6290b08c02c72d7317910374ca602ff1e5
Running setup.py bdist_wheel for future ... done
Stored in directory: /root/.cache/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
Running setup.py bdist_wheel for regex ... error
Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-install-hkjl39na/regex/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /tmp/pip-wheel-6lr8a20o --python-tag cp36:
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2018.07.11' to '2018.7.11'
normalized_version,
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
copying regex_3/regex.py -> build/lib.linux-x86_64-3.6
copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.6
copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.6
running build_ext
building '_regex' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/regex_3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
regex_3/_regex.c:46:20: fatal error: Python.h: Arquivo ou diretório não encontrado
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
________________________________________
Failed building wheel for regex
Running setup.py clean for regex
Running setup.py bdist_wheel for tzlocal ... done
Stored in directory: /root/.cache/pip/wheels/15/ae/df/a67bf1ed84e9bf230187d36d8dcfd30072bea0236cb059ed91
Successfully built aws-sam-cli PyYAML aws-sam-translator itsdangerous future tzlocal
Failed to build regex
Installing collected packages: six, click, enum34, Werkzeug, Jinja2, itsdangerous, Flask, docutils, jmespath, python-dateutil, botocore, s3transfer, boto3, PyYAML, whichcraft, poyo, chardet, idna, urllib3, certifi, requests, future, binaryornot, arrow, jinja2-time, cookiecutter, jsonschema, aws-sam-translator, docker-pycreds, websocket-client, docker, regex, pytz, tzlocal, dateparser, aws-sam-cli
The script flask is installed in '/root/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
The script chardetect is installed in '/root/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
The scripts futurize and pasteurize are installed in '/root/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
The script cookiecutter is installed in '/root/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
The script jsonschema is installed in '/root/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Running setup.py install for regex ... error
Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-install-hkjl39na/regex/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-record-tsjrmjoh/install-record.txt --single-version-externally-managed --compile --user --prefix=:
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2018.07.11' to '2018.7.11'
normalized_version,
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
copying regex_3/regex.py -> build/lib.linux-x86_64-3.6
copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.6
copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.6
running build_ext
building '_regex' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/regex_3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
regex_3/_regex.c:46:20: fatal error: Python.h: Arquivo ou diretório não encontrado
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-install-hkjl39na/regex/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-record-tsjrmjoh/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-hkjl39na/regex/
root@neuberfran:/home/neuberfran# sam
O programa 'sam' não está instalado no momento. Você pode instalá-lo digitando:
apt install simon
root@neuberfran:/home/neuberfran# sam --version
O programa 'sam' não está instalado no momento. Você pode instalá-lo digitando:
apt install simon
root@neuberfran:/home/neuberfran# python --version
Python 3.5.3+
root@neuberfran:/home/neuberfran# pip --version
pip 18.0 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
root@neuberfran:/home/neuberfran# pip install --user aws-sam-cli
Collecting aws-sam-cli
Requirement already satisfied: enum34~=1.1.6 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.1.6)
Requirement already satisfied: cookiecutter~=1.6.0 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.6.0)
Requirement already satisfied: aws-sam-translator==1.6.0 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.6.0)
Requirement already satisfied: docker>=3.3.0 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (3.4.1)
Requirement already satisfied: six~=1.11.0 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.11.0)
Collecting dateparser~=0.7 (from aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/ac/9e/1aa87c0c59f9731820bfd20a8b148d97b315530c2c92d1fb300328c8c42f/dateparser-0.7.0-py2.py3-none-any.whl
Requirement already satisfied: Flask~=1.0.2 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.0.2)
Requirement already satisfied: click~=6.7 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (6.7)
Requirement already satisfied: python-dateutil~=2.6 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (2.7.3)
Requirement already satisfied: PyYAML~=3.12 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (3.13)
Requirement already satisfied: boto3~=1.5 in /root/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.7.63)
Requirement already satisfied: jinja2>=2.7 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (2.10)
Requirement already satisfied: whichcraft>=0.4.0 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (0.4.1)
Requirement already satisfied: binaryornot>=0.2.0 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (0.4.4)
Requirement already satisfied: jinja2-time>=0.1.0 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (0.2.0)
Requirement already satisfied: requests>=2.18.0 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (2.19.1)
Requirement already satisfied: future>=0.15.2 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (0.16.0)
Requirement already satisfied: poyo>=0.1.0 in /root/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (0.4.1)
Requirement already satisfied: jsonschema~=2.6 in /root/.local/lib/python3.6/site-packages (from aws-sam-translator==1.6.0->aws-sam-cli) (2.6.0)
Requirement already satisfied: websocket-client>=0.32.0 in /root/.local/lib/python3.6/site-packages (from docker>=3.3.0->aws-sam-cli) (0.48.0)
Requirement already satisfied: docker-pycreds>=0.3.0 in /root/.local/lib/python3.6/site-packages (from docker>=3.3.0->aws-sam-cli) (0.3.0)
Collecting tzlocal (from dateparser~=0.7->aws-sam-cli)
Collecting regex (from dateparser~=0.7->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/9f/79/adbe79373ec3c56ae61670bbed30609fe4a9b6af835478fa12bf8795cdec/regex-2018.07.11.tar.gz
Collecting pytz (from dateparser~=0.7->aws-sam-cli)
Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Requirement already satisfied: Werkzeug>=0.14 in /root/.local/lib/python3.6/site-packages (from Flask~=1.0.2->aws-sam-cli) (0.14.1)
Requirement already satisfied: itsdangerous>=0.24 in /root/.local/lib/python3.6/site-packages (from Flask~=1.0.2->aws-sam-cli) (0.24)
Requirement already satisfied: botocore<1.11.0,>=1.10.63 in /root/.local/lib/python3.6/site-packages (from boto3~=1.5->aws-sam-cli) (1.10.63)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /root/.local/lib/python3.6/site-packages (from boto3~=1.5->aws-sam-cli) (0.1.13)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /root/.local/lib/python3.6/site-packages (from boto3~=1.5->aws-sam-cli) (0.9.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2>=2.7->cookiecutter~=1.6.0->aws-sam-cli) (0.23)
Requirement already satisfied: chardet>=3.0.2 in /root/.local/lib/python3.6/site-packages (from binaryornot>=0.2.0->cookiecutter~=1.6.0->aws-sam-cli) (3.0.4)
Requirement already satisfied: arrow in /root/.local/lib/python3.6/site-packages (from jinja2-time>=0.1.0->cookiecutter~=1.6.0->aws-sam-cli) (0.12.1)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /root/.local/lib/python3.6/site-packages (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in /root/.local/lib/python3.6/site-packages (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /root/.local/lib/python3.6/site-packages (from requests>=2.18.0->cookiecutter~=1.6.0->aws-sam-cli) (2018.4.16)
Requirement already satisfied: docutils>=0.10 in /root/.local/lib/python3.6/site-packages (from botocore<1.11.0,>=1.10.63->boto3~=1.5->aws-sam-cli) (0.14)
Building wheels for collected packages: regex
Running setup.py bdist_wheel for regex ... error
Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-install-6jo0g90q/regex/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /tmp/pip-wheel-riwm722a --python-tag cp36:
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2018.07.11' to '2018.7.11'
normalized_version,
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
copying regex_3/regex.py -> build/lib.linux-x86_64-3.6
copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.6
copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.6
running build_ext
building '_regex' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/regex_3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
regex_3/_regex.c:46:20: fatal error: Python.h: Arquivo ou diretório não encontrado
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
________________________________________
Failed building wheel for regex
Running setup.py clean for regex
Failed to build regex
Installing collected packages: pytz, tzlocal, regex, dateparser, aws-sam-cli
Running setup.py install for regex ... error
Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-install-6jo0g90q/regex/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-record-38oya2ua/install-record.txt --single-version-externally-managed --compile --user --prefix=:
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2018.07.11' to '2018.7.11'
normalized_version,
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
copying regex_3/regex.py -> build/lib.linux-x86_64-3.6
copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.6
copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.6
running build_ext
building '_regex' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/regex_3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
regex_3/_regex.c:46:20: fatal error: Python.h: Arquivo ou diretório não encontrado
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-install-6jo0g90q/regex/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-record-38oya2ua/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-6jo0g90q/regex/
root@neuberfran:/home/neuberfran#

![43217159-65cdf9f0-9030-11e8-8655-3ab458e89cff](https://user-images.githubusercontent.com/38701397/43276465-1eb05d32-90db-11e8-84d7-817a19db598c.png)

**_root@neuberfran:/home/neuberfran# echo $PATH_**
/root/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/bin:/root/go/bin:/bin:root/.local/bin:/bin

![foto01](https://user-images.githubusercontent.com/38701397/43277085-76912fe8-90f6-11e8-8728-ad9c6553b017.png)

![foto02](https://user-images.githubusercontent.com/38701397/43277092-7c9dbafa-90f6-11e8-9586-c61043995abd.png)

**Comment by jfuss** [comment]
This is an issue with your system: 
```
regex_3/_regex.c:46:20: fatal error: Python.h: Arquivo ou diretório não encontrado
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Here is a solution for others: https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit

Closing as this is a system error on your machine.

**Comment by neuberfran** [comment]
Hi,
I need one more help

I can only use sam --version after these two commands below:

export PATH=$PATH:$USER_BASE_PATH/bin
exec "$SHELL"

How to solve this? (pls) 
![tela43](https://user-images.githubusercontent.com/38701397/43485445-c5d4f298-9500-11e8-8b0a-f5aae4e2c286.png)

**Comment by neuberfran** [comment]
new issue: today

![tela100](https://user-images.githubusercontent.com/38701397/43805657-01b05412-9a77-11e8-98e9-2b38a3ff7f8d.png)
