### ISSUE TITLE
Unexisting repository for hello-nodejs template

### ISSUE THREAD

**Issue by alexcasalboni** [awslabs/aws-sam-cli#585]
**Description:**

The repository referenced [here](https://github.com/awslabs/aws-sam-cli/blob/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/package.json#L6) doesn't seem to exist (`https://github.com/aws-samples/cookiecutter-aws-sam-hello-nodej`).

@heitorlessa @sanathkr is it just a broken link or maybe the repo is private?

I noticed because I wanted to improve that template, although now I'm realizing that all the templates are in this repository as well, so I can just update the nodejs template [here](https://github.com/awslabs/aws-sam-cli/tree/6164d6d2e7351a849ad3d79973ac18b8d3d1d371/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello_world).

But still :)

**Observed result:** The package.json file is referencing an unexisting repo.

**Expected result:** The repo should exist / be public.

**Comment by jfuss** [comment]
@alexcasalboni I think we should just remove it (or update it to point to the cli) since that is the example and is within the cli already.

**Comment by alexcasalboni** [comment]
As documented [here](https://docs.npmjs.com/files/package.json#repository), the `repository` field is meant to instruct a computer (i.e. not a human) on "where your code lives".  

Imho, we could just link the SAM CLI repo for all the templates, and then instruct users to customize it once they set up their own repo.

**Comment by DebbieIsMyName** [comment]
Updated with unbroken link.

**Comment by heitorlessa** [comment]
Hey Alex, just seeing this now.

Initial idea was to create a repo for each runtime and move them to foster
enhancements and add integration tests for them alone and make the Sam cli
lean.

While this is not complete I’d vote to remove the link altogether to not
mislead anyone who may want to look up that README

**Comment by jfuss** [comment]
@heitorlessa We already merged the PR that points the package.json to the cli repo. I think having this point to the cli for now is fine since that is where it lives. If we later move these out, we can update it further then.

**Comment by alexcasalboni** [comment]
Sounds good to me :)

**Comment by heitorlessa** [comment]
Agreed ;)
