### ISSUE TITLE
Built in javascript AWS-SDK does not support Amazon Comprehend 'detectSyntax'

### ISSUE THREAD

**Issue by S-Cardenas** [awslabs/aws-sam-cli#588]
The javascript `aws-sdk` that comes built in with aws-sam-cli Runtime `nodejs8.10` does not support Amazon Comprehend `detectSyntax`. In order to get `detectSyntax` to work with aws-sam-cli I had to install the latest version of the javascript `aws-sdk` manually.

Calling `detectSyntax` with the built-in javscript `aws-sdk` yields this result:
```
{"errorMessage":"comprehend.detectSyntax is not a function","errorType":"TypeError","stackTrace":["Promise (/var/task/index.js:101:16)","new Promise (<anonymous>)","comprehendDetectSyntax (/var/task/index.js:93:10)","exports.handler (/var/task/index.js:25:24)","<anonymous>","process._tickDomainCallback (internal/process/next_tick.js:228:7)"]}
```

By installing the latest version of the sdk via `docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs8.10 npm install --save aws-sdk` I am able to successfully call `detectSyntax`.

Is there a way to fix this so that the default sdk can call `detectSyntax`?

**Comment by jfuss** [comment]
@S-Cardenas There may need an update to [docker-lambda](https://github.com/lambci/docker-lambda), though I couldn't find where the sdk is added into the container.

Either way, Lambda does not recommend depending on the [underlying sdks](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html):
```
Control the dependencies in your function's deployment package. The AWS Lambda execution environment contains a number of libraries such the AWS SDK for the Node.js and Python runtimes (a full list can be found here: Lambda Execution Environment and Available Libraries). To enable the latest set of features and security updates, Lambda will periodically update these libraries. These updates may introduce subtle changes to the behavior of your Lambda function. To have full control of the dependencies your function uses, we recommend packaging all your dependencies with your deployment package.
```

My strong recommendation is to package the dependencies you need with your function. 

Closing this as it is not an issue with the cli itself and doesn't follow best practices for lambda, you can cut an issue to docker-lambda if you wish to update the container.
