### ISSUE TITLE
No such option: --debugger-path

### ISSUE THREAD

**Issue by licx** [awslabs/aws-sam-cli#593]
**Description:**

The README mentions a `--debugger-path` argument for sam here:
(Debugging Golang functions) https://github.com/awslabs/aws-sam-cli#debugging-golang-functions

When invoking something like:
`sam local start-api -d 5986 --debugger-path <delve folder path>`

I get
`Error: no such option: --debugger-path`

**Steps to reproduce the issue:**
1. Invoke `sam local start-api -d 5986 --debugger-path bin/dlv`

**Observed result:**
`Error: no such option: --debugger-path`
**Expected result:**
Golang debugging working
**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac OS 10.12
Python 2.7.15
**Output of `sam --version`**:
SAM CLI, version 0.5.0

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
The README you are viewing is develop, while is the most up-to-date but has features that are yet to be released. This is the case for the Golang debugging. You can follow #281 for updates (we will close the issue after it’s released). 

Closing as this is not released yet
