### ISSUE TITLE
Error when using VPC in tempalte

### ISSUE THREAD

**Issue by garypiner** [awslabs/aws-sam-cli#617]
When running a deployment with SAM-CLI and the template specifies to run in a VPC subnet, the following error is received in the stack

The provided execution role does not have permissions to call CreateNetworkInterface on EC2 (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 944fe586-a15b-11e8-a8ae-8975581ab887)

Steps to reproduce the issue:
1. create a template file that uses vpcconfig
      VpcConfig:
        SubnetIds:
          - subnetid
        SecurityGroupIds:
          - sgid
2. sam package --template-file template.yaml --s3-bucket {bucket name} --output-template-file packaged.yaml
3. sam deploy --template-file ./packaged.yaml --stack-name mystack --capabilities CAPABILITY_IAM

sam --version
SAM CLI, version 0.5.0 (OSX and Linux)

Debugs logs provides no useful information

**Comment by jfuss** [comment]
@garypiner Do you have CreateNetworkInterface permissions on the Execution Role? It doesn't look like SAM does anything with the [VPC Config](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/sam_resources.py#L167) other than set the correct value in the CloudFormation Resource. This is out of scope for the CLI. You can create a [Feature Request](https://github.com/awslabs/serverless-application-model/issues) with SAM Translator to add these permissions directly into the Role. I do not know the answer to why this isn't done already, but there could be a good reason to this.

Closing as this is not related to SAM CLI
