### ISSUE TITLE
Typo in blob/develop/docs/installation.rst 

### ISSUE THREAD

**Issue by jmayeux-circle** [awslabs/aws-sam-cli#620]
Under Advanced Installations "git clone git@github.com/awslabs/aws-sam-cli.git" should be "git clone git@github.com:awslabs/aws-sam-cli.git"

**Comment by jfuss** [comment]
@jmayeux-circle I thought we already fixed this once. Regardless, would you be willing to send a PR with the fix?

**Comment by jfuss** [comment]
Closing as this was addressed.
