### ISSUE TITLE
Inconsistent template flag

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-sam-cli#624]
**Description:**
Across SAM CLI, the flag used for specifying the template file is inconsistent. For CloudFormation related commands (deploy/package), --template-file is used, everywhere else --template is used.

**Steps to reproduce the issue:**
1. sam deploy --help
2. sam local invoke --help

**Observed result:**
Both have different template flags

**Expected result:**
Settle on one flag (ideally --template as it's more widely used). --template-file could be aliased for backwards compat.

Amazon Alias: [redacted]@

**Comment by sanathkr** [comment]
deploy/package commands are implemented in AWS CLI. Unfortunately We don't *yet* have control to changing the flag name. We should be able to do that when we move the package & deploy commands into SAM CLI.

I am going to close this issue for now because we can't action on it.
