### ISSUE TITLE
[Python3] The parameter --env-vars does not work

### ISSUE THREAD

**Issue by dadon-david** [awslabs/aws-sam-cli#625]
Hi guys,
I hope you are doing well,

I have an issue with SAM CLI and Python 3, 

#### It seems that the argument `--env-vars` does not work.

Here my handler code:

```
import os
def handler(event, context):
    print(os.environ)
    print(event)
    print(os.environ["TEST_VALUE"])
```

Here the value of my .bashrc:
```
export TEST_VALUE="TEST"
```
And when I type this command:
```
sam local invoke -e <(printf '{"message":"Hey, are you there?" }') --env-vars <(printf {\"TEST_VALUE\":\"$TEST_VALUE\"}) DispatcherFunction
```
I have this response:

```
2018-08-21 16:05:20 Invoking dispatcher.handler (python3.6)
2018-08-21 16:05:20 Starting new HTTP connection (1): 169.254.169.254

Fetching lambci/lambda:python3.6 Docker container image......
2018-08-21 16:05:23 Mounting /Users/d.dadon/Code/python/pagespeed-monitoring/dist as /var/task:ro inside runtime container
START RequestId: 14aac6de-b489-404d-8ee2-2ff5b672a2ae Version: $LATEST
environ({'PATH': '/var/lang/bin:/usr/local/bin:/usr/bin/:/bin', 'HOSTNAME': 'f917ebc40554', 'AWS_SAM_LOCAL': 'true', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '128', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '180', 'AWS_LAMBDA_FUNCTION_HANDLER': 'dispatcher.handler', 'AWS_REGION': 'us-east-1', 'AWS_DEFAULT_REGION': 'us-east-1', 'AWS_ACCESS_KEY_ID': 'defaultkey', 'AWS_SECRET_ACCESS_KEY': 'defaultsecret', 'AWS_LAMBDA_EVENT_BODY': '{"message":"Hey, are you there?" }', 'LD_LIBRARY_PATH': '/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib', 'LANG': 'en_US.UTF-8', 'TZ': ':UTC', 'LAMBDA_TASK_ROOT': '/var/task', 'LAMBDA_RUNTIME_DIR': '/var/runtime', '_AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2', '_AWS_XRAY_DAEMON_PORT': '2000', 'AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2:2000', 'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR', '_X_AMZN_TRACE_ID': 'Parent=11560be54abce8ed', 'AWS_EXECUTION_ENV': 'AWS_Lambda_python3.6', 'PYTHONPATH': '/var/runtime', 'HOME': '/home/sbx_user1051', 'AWS_LAMBDA_LOG_GROUP_NAME': '/aws/lambda/test', 'AWS_LAMBDA_LOG_STREAM_NAME': '2018/8/21/[$LATEST]cbbf349378641594', 'AWS_LAMBDA_FUNCTION_NAME': 'test', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', '_HANDLER': 'dispatcher.handler'})
{'message': 'Hey, are you there?'}
'TEST_VALUE': KeyError
Traceback (most recent call last):
  File "/var/task/dispatcher.py", line 18, in handler
    print(os.environ["TEST_VALUE"])
  File "/var/lang/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TEST_VALUE'

END RequestId: 14aac6de-b489-404d-8ee2-2ff5b672a2ae
REPORT RequestId: 14aac6de-b489-404d-8ee2-2ff5b672a2ae Duration: 12 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 19 MB

{"errorMessage": "'TEST_VALUE'", "errorType": "KeyError", "stackTrace": [["/var/task/dispatcher.py", 18, "handler", "print(os.environ[\"TEST_VALUE\"])"], ["/var/lang/lib/python3.6/os.py", 669, "__getitem__", "raise KeyError(key) from None"]]}
```

Here an excerpt of my `template.yml`

```
    DispatcherFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: dispatcher.handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Schedule
                    Properties:
                        Schedule: rate(1 second)
``` 
**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
- MacOS 10.12.6
- Python 3.6
- Virtualenv with Pipenv

**Output of `sam --version`**:
SAM CLI, version 0.5.0

#### Notes on the issue:

I did the test with "real" path as parameter for `-e` and `--env-vars` argument and I have the same issue.

I am willing to help on this issue, tell me if you have any question about my problem :)

Thank you very much,

**Comment by dadon-david** [comment]
@jfuss : HI ! Thanks for your reactivity :)

So what is the purpose of the `--env-vars` parameter ?

**Comment by jfuss** [comment]
This allows you to set the `env-var`s locally.

Looking at the none local case:
When you deploy those application through CloudFormation, you will set these env vars in some manner through the template (most of the time through parameters in the template). This allows you to control the values of the Env Vars.

We need something similar locally. That is, a way to mutate the Env Vars you define in the template. This is where `--env-var` comes into play. If you don't specify any Env Vars in your template, those will not be in your local container, just like it would not appear in your deployed function.

Does the use and application make sense?

**Comment by dadon-david** [comment]
Okay so I think I get it ! 😃 

I have to first set the value in **Sam**, so with `template.yml`:

```
            Environment:
              Variables:
                TEST_VALUE: "TestValue"
```

Then in **Sam Cli**, I can override the values set in `template.yml` with the `--env-vars` argument.

So for example if my function is named `DispatcherFunction` in `template.yml`, then I can override the env variable with this json as `--env-vars` argument of the `sam local invoke` command ([More about that on the Sam Cli Doc](https://github.com/awslabs/aws-sam-cli/blob/develop/docs/advanced_usage.rst#environment-variable-file)): 

```
{
  "DispatcherFunction": {
    "TEST_VALUE": "NewTestValue"
  }
}
```

So when I launch this command: 

```
sam local invoke -e <(printf '{"message":"Hey, are you there?" }') --env-vars <(printf {\"DispatcherFunction\":{\"TEST_VALUE\":\"NewTestValue\"}}) DispatcherFunction
```

I have that output:
```
{[...],'TEST_VALUE': 'NewTestValue', 'AWS_LAMBDA_EVENT_BODY': '{"message":"Hey, are you there?" },[...]'}
```

Am I right ?

Thank you so much for your help 😄

**Comment by jfuss** [comment]
@dadon-david Yes. And if you did not provide `--env-vars` the value would have been what was defined in the template. In your example that would be `TestValue`. 

Sadly, we do not support intrinsic just yet. So if you were to start Ref-ing Parameters in the template, you will still need to specify the `--env-vars`. 

Going to close this issue out, as things are working as expected. If you need further support, we have a great community going in our slack channel (#samdev).
