### ISSUE TITLE
Raise error when env vars file is in the wrong format

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-sam-cli#626]
**Description:**
Currently, the environment variables file expects the format to be in either:
```json
{
"Parameters": { ... }
}
```

or 

```json
{
"FuncName": {...}
}
```

When an env var file is specified in the wrong format, SAM silently ignores the file.

Ideally, SAM should throw an error to make the user aware that the format is incorrect.

**Observed result:**
Provide a badly formatted env var json file, SAM silently ignores the file

**Expected result:**
Provide a badly formatted env var json file, SAM should error stating the file is in the wrong format

Amazon Alias: [redacted]@

**Comment by sthulb** [comment]
Code responsible: https://github.com/awslabs/aws-sam-cli/blob/9359e4994003cb862561caa811eff366e4c7eedf/samcli/commands/local/lib/local_lambda.py#L144

**Comment by AlJohri** [comment]
👍 I was using a format like `{"myvar": "blahblah"}` before checking the docs and couldn't tell why it wasn't working

**Comment by sanathkr** [comment]
@sthulb  Can you provide a PR to raise an error? This should be pretty simple

**Comment by sthulb** [comment]
I’ve got a PR ready to push. I’ll do it a bit later today.

**Comment by sthulb** [comment]
this was fixed in #675
