### ISSUE TITLE
Sam local doesn't return FunctionError and Payload on Error

### ISSUE THREAD

**Issue by vrealzhou** [awslabs/aws-sam-cli#632]
**Description:**

**Steps to reproduce the issue:**
1. Create any lambda returns error
2. Use sam local start-lambda to start it
3. Invoke the Lambda locally via AWS Golang SDK

**Observed result:**
In the result struct doesn't contains FunctionError and the Payload is empty.

**Expected result:**
From Lambda API document: https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html
The FunctionError field should contains value Handled or Unhandled. And it should returns message in payload.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac OSX 10.13.5

**Output of `sam --version`**:
SAM CLI, version 0.5.0

**Comment by jfuss** [comment]
@vrealzhou This can be expected in some cases (locally). More details can be found in [this comment](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/services/base_local_service.py#L170). Basically, the return values from the docker container come back in sdtout, SAM CLI has to parse out the last line and then interpret whether the return value was an error or not. We only support the best effort in these cases and have tight restrictions here to avoid false positives.

Can you provide the output from the container (the error response is good enough) and the language your function is written in?

**Comment by jfuss** [comment]
Closing due to no response.
