### ISSUE TITLE
Allow environment variables to configure SAM cli flags

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-sam-cli#637]
**Description:**

Common parameters like `--host`, `--port`, `--template[-file]` should be configurable by environment variables to allow common flags to be set in `~/.bashrc` or the likes.

**Observed result:**
Currently, we don't allow this

**Expected result:**
Setting environment variables like: SAM_HOSTNAME or SAM_APIGW_PORT for example would override the requirement for the --host or --port flags

**Comment by jfuss** [comment]
This sounds more like a request for a SAM configuration file. This is much more scalable than using environment variables to accomplish the same thing.

Are you just trying to shorten commands by doing this or attempting to accomplish something else?

Regarding the `--template[-file]`, all commands but package and deploy default to `[default: template.[yaml|yml]]` in the current working directory.

**Comment by sthulb** [comment]
Something else, I wrap sam in a container because python, so I'd like to be able to permanently set the host.

if SAM plans to add a cfg file, that would work.

**Comment by sanathkr** [comment]
We have been wanting to have a cfg file for SAM CLI so these things can be defined in one place. I will keep this issue open as feature request for cfg file

**Comment by sriram-mv** [comment]
`samconfig.toml` supports this today. Closing this issue.
