### ISSUE TITLE
Sam package does not append .zip to uploaded artifact

### ISSUE THREAD

**Issue by adamthomason** [awslabs/aws-sam-cli#639]
**Description:**

I've integrated the sam cli into our automated builds in Jenkins. Everything seemingly works nicely, aside from `sam package --template-file serverless.template --s3-bucket example-bucket --output-template-file serverless-output.yml` does not append '.zip' to the uploaded artifact. I believe this is causing our lambda functions to throw internal server errors. When we 'publish' the project through Visual Studio, a readable filename is created with the .zip extension. 

**Steps to reproduce the issue:**
1. Run `sam package` with appropriate options
2. Observe filename and extension uploaded to s3

**Observed result:**
A zip file with a uuid-like filename without .zip extension

**Expected result:**
A configurable filename uploaded with the .zip extension

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Windows Server 2016 and/or Windows Server 2012 R2

**Output of `sam --version`**:

SAM CLI, version 0.4.0

**Comment by adamthomason** [comment]
Anybody here? Do I need to add more info?

**Comment by lroberts-lly** [comment]
did you ever solve this?  I am having the same issue.

**Comment by PhungXuanAnh** [comment]
I also encountered this issue. And this issue is closed? why?

**Comment by svintit** [comment]
Would love info on this, strange that it hasn't been fixed!
