### ISSUE TITLE
No module named 'lxml.etree'

### ISSUE THREAD

**Issue by AlJohri** [awslabs/aws-sam-cli#645]
I'm getting an `No module named 'lxml.etree'` issue. When built on codebuild vs codepipeline I don't get this issue:

```
2018-09-01 17:05:15 Reading invoke payload from stdin (you can also pass it from file with --event)
2018-09-01 17:05:15 Invoking app.handler.handle (python3.6)
2018-09-01 17:05:15 Starting new HTTP connection (1): 169.254.169.254

Fetching lambci/lambda:python3.6 Docker container image......
2018-09-01 17:05:16 Mounting /Users/johria/Development/politics-explorer/apps/congressional-statements-scraper/build as /var/task:ro inside runtime container
START RequestId: 4388f94f-e7ad-41bb-a8a1-145076c354f6 Version: $LATEST
Unable to import module 'app.handler': No module named 'lxml.etree'
END RequestId: 4388f94f-e7ad-41bb-a8a1-145076c354f6
REPORT RequestId: 4388f94f-e7ad-41bb-a8a1-145076c354f6 Duration: 1398 ms Billed Duration: 1400 ms Memory Size: 128 MB Max Memory Used: 29 MB

{"errorMessage": "Unable to import module 'app.handler'"}
```

I download precompiled binaries for `psycopg2` right now but I have not needed to do it for `lxml`. This looks like a difference between the docker-lambda image vs the real image.

Any ideas?

**Comment by sanathkr** [comment]
Are you saying lxml are available by default in prod? Can you elaborate more about these libraries because we aren't familiar with them.

This is not a SAM CLI issue per-se. So unless we get more details on these libraries we can't do much here.

**Comment by AlJohri** [comment]
> Are you saying lxml are available by default in prod?

I'm saying the underlying libraries for `lxml` are included in prod by default. I believe this would be `libxml2` and `libxslt` although I'm not 100% sure. Basically, running `pip install lxml` links to the underlying libraries automatically on prod whereas it requires providing precompiled binaries locally via sam.

Perhaps an issue for https://github.com/lambci/docker-lambda ?

**Comment by TheSriram** [comment]
do you still face the issue with sam build?

**Comment by jfuss** [comment]
I just tried a simple function that has `psycopg2-binary` and `lxml` as a dependency in the `requirements.txt` file. I was able to import both in the function without the function crashing (complaining about not being importable). I did use `sam build` to build the function. So either docker-lambda solved this or `sam build` make it so you don't need to worry about it. Either way, I can't reproduce this issue. 

Closing this as it seems to be resolved. If not, please cut a new issue.
