### ISSUE TITLE
Proxy resource with a greedy path variable creates incorrect key in pathParameters in event

### ISSUE THREAD

**Issue by nitzien** [awslabs/aws-sam-cli#65]
From API gateway:
```
"pathParameters": {"api": "testapi1"}
```

From SAM local api:
```
"pathParameters": {"api+": "testapi1"}
```

**Comment by PaulMaddox** [comment]
Thanks for reporting this @nitzien.

One of us will take a look at this soon, unless you want to submit a pull request in the meantime?

**Comment by sanathkr** [comment]
This should be fixed in https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0
