### ISSUE TITLE
Deploy functions using pre-created roles

### ISSUE THREAD

**Issue by ndelvalle** [awslabs/aws-sam-cli#656]
I'm trying to deploy my functions to AWS, I'm using an account that does not have create role permissions.

I'm able to create the `packaged-template.yaml` file and upload the functions to s3. Then when trying to deploy them running:

```
aws cloudformation deploy --template-file /Users/ndelvalle/Projects/foo/functions/packaged-template.yaml --stack-name foo --region sa-east-1 --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
```

I got the following output:
```
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
```
Then, when running `aws cloudformation describe-stack-events --stack-name foo`, the error is the following one:

```
ResourceStatusReason": "API: iam:CreateRole User: arn:aws:iam::user/nico is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::role/foo",
```

So my question is, can we pre-create a role in AWS and define it somewhere so sam-cli can use it?

**Output of `sam --version`**:
SAM CLI, version 0.5.0

Note: I tried joining the slack channel several times but my invite never arrived, not sure if [this](https://awssamopensource.splashthat.com) is working.

**Comment by jfuss** [comment]
@ndelvalle You will need to create a User or Role to use when deploying the function. Once it is created, you can set the credentials by using `aws configure`. 

On the slack channel: We are working on making the process faster. Currently, there are some manual steps that need to be taken.

Closing.
