### ISSUE TITLE
AttributeError: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by woph** [awslabs/aws-sam-cli#660]
**Description:**
When trying to execute any SAM commands (e.g. `sam validate` or `sam local start-api`), SAM is quitting my command with:
`File "/Users/<my_fancy_username>/Library/Python/2.7/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.6.0', 'console_scripts', 'sam')()
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samcli/cli/command.py", line 101, in get_command
    mod = importlib.import_module(pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samcli/commands/validate/validate.py", line 17, in <module>
    from .lib.sam_template_validator import SamTemplateValidator
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 8, in <module>
    from samtranslator.translator.translator import Translator
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samtranslator/translator/translator.py", line 11, in <module>
    from samtranslator.plugins.globals.globals_plugin import GlobalsPlugin
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samtranslator/plugins/globals/globals_plugin.py", line 6, in <module>
    from samtranslator.plugins.globals.globals import Globals, InvalidGlobalsSectionException
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samtranslator/plugins/globals/globals.py", line 5, in <module>
    class Globals(object):
  File "/Users/<my_fancy_username>/Library/Python/2.7/lib/python/site-packages/samtranslator/plugins/globals/globals.py", line 31, in Globals
    "DeploymentPreference"
AttributeError: 'str' object has no attribute 'value'`

I was not sure if any of my dependencies is forcing this issue. However, i tried to get my dependencies updated so far.

This also happens if i create a sample app from scratch with:
1. sam init --runtime java (works like a charm)
2. sam validate (fails with above error)
3. sam local start-api (fails with above error)

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
macOS 10.12.6

**Output of `sam --version`**:
`SAM CLI, version 0.6.0`

**Optional Debug logs**:
`pip list` is giving back:
...
aws-sam-cli                            0.6.0
aws-sam-translator                1.6.0
awscli                                       1.16.10
...

I'm using Ptyhon 2.7 with pip 18: 
`pip --version`
pip 18.0 from /Library/Python/2.7/site-packages/pip (python 2.7)

Any help or hints how to solve this issue is highly appreciated :)

**Comment by jfuss** [comment]
@woph What does your template look like? This error you are seeing is coming from the aws-sam-translator package and seems like the value of "DeploymentPreference" is a string which is invalid.

**Comment by woph** [comment]
hi @jfuss ,
the error is caused also by the simple hello world `sam init`. The very same error as of my project.
The template itself looks like this:
[template.txt](https://github.com/awslabs/aws-sam-cli/files/2363545/template.txt)

Thanks for you help
Cheers
Phil

**Comment by jfuss** [comment]
Downloading the template works for me. Which make sense since the template does not define "DeploymentPreference". 

What is the exact command you are running?

**Comment by woph** [comment]
I'm running:
`sam validate` which quits with the exact same message as doing it with `sam local start-api`

**Comment by jfuss** [comment]
Are you only running ‘sam validate’ without specifying the template through ‘-t’? If you are not using ‘-t’, does the current directory have a ‘template.yaml’ file in it? 

There should be no way to get the error you are getting with the template you posted above.

**Comment by woph** [comment]
yes i'm running it within the directory of the template...
also explicitly providing the template does not work. that's why i also thought seeking some help here, since i cannot tell what should be wrong here.

though, i can run `sam package` and `sam deploy` in my project which works before with cloudformation aswell...

**Comment by jfuss** [comment]
Something else is going on here. I tried the same workflow 
* `sam init --runtime java`
* `cd sam-app`
* `sam validate`

But the template is valid.
```
$ sam validate --profile sam-testing
2018-09-08 11:50:25 Found credentials in shared credentials file: ~/.aws/credentials
2018-09-08 11:50:25 Starting new HTTPS connection (1): iam.amazonaws.com
2018-09-08 11:51:40 Starting new HTTPS connection (2): iam.amazonaws.com
/Users/jfuss/sam-app-java/sam-app/template.yaml is a valid SAM Template
```

The error indicates the DeploymentPreference is in the template and has an invalid value (string instead of dict). `sam init`'s template does not have this property though.

**Comment by jfuss** [comment]
I still can't repro this. Given that, I am going to close. If you run into this again, please create a new issue with the exact template that causes the failure so we can investigate further.

**Comment by advissor** [comment]
Maybe someone will run into a similar error
Was doing :
`  [Container] 2019/02/10 04:23:52 Running command aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml`

>  'str' object has no attribute 'get'

` [Container] 2019/02/10 04:23:53 Command did not exit successfully aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
 exit status 255
`
After trying multiples times, it appeared to me that intendant in CodeStar/Cloudformation template was wrong. 

### After fixing intendants in yaml,  template export went through

**Comment by lesfoster** [comment]
I ran into this problem.  I eventually did come to realize the template was invalid, because I had not indented one of the resource's settings enough.  The "Transform" itself was under indented.  The "sam validate" gave me the clue: a "Type" was expected for this value, because it was taken to be another resource.

`AWSTemplateFormatVersion: '2010-09-09'
Description: Starter lambda fn
Resources:
  helloworldpython3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://abucket/aprefix/
      Description: where to store the lambda fn
      Handler: app.lambda_handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 3
    # Transform should align with this comment, not with helloworldpython3 above.
  Transform: AWS::Serverless-2016-10-31`
