### ISSUE TITLE
Request for API Gateway with Custom Domain

### ISSUE THREAD

**Issue by holtc** [awslabs/aws-sam-cli#668]
Would love to see an example similar to that generated by `sam init`, but with the creation of an API Gateway API with a custom domain name.  If this is already doable, how can I update the following to accomplish this?

```
    Api:
      Type: AWS::Serverless::Api
      Properties:
        StageName: prod
        EndpointConfiguration: "EDGE"
        DefinitionBody:
          swagger: "2.0"
          info:
            title: "TestAPI"
            version: "0"
          paths:
            /hello:
              get:
                x-amazon-apigateway-integration:
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations"
                  httpMethod: "POST"
                  responses: {}
                  type: "aws_proxy"
```

**Comment by Haughar** [comment]
@holtc I came across this boilerplate for nodejs which shows how to use custom domains: https://github.com/vernonsoftwaresolutions/aws-serverless-nodejs-boilerplate/blob/74f5856dcecd8678d9f742a8cd774042c3c179af/cloudformation.yaml

There is also a `BasePath` property that you can set on the `AWS::ApiGateway::BasePathMapping` that isn't used in the example linked above

**Comment by jfuss** [comment]
@holtc and @Haughar There is currently an RFC out on the SAM Spec for this support: https://github.com/awslabs/serverless-application-model/issues/783.

This also links to other issues where you can see how to wire up Custom Domains to the AWS::Serverless::Api in the mean time.

Closing as SAM already has issues/RFCs for this and this is for the SAM Spec not the cli.
