### ISSUE TITLE
sam local invoke looking for template.yml

### ISSUE THREAD

**Issue by ehorodyski** [awslabs/aws-sam-cli#678]
**Description:**

When trying to invoke a lambda, I get an error:

```
cd hello_world
sam local invoke -e event.json "HelloWorld"
Error: Template file not found at /{project}/hello_world/template.yml
```

**Steps to reproduce the issue:**
1. Create a new SAM lambda project running Node8.10

**Observed result:**

**Expected result:**

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac

**Output of `sam --version`**:

0.6.0

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by garandam** [comment]
The Template is found within the /{project}/template.yml when you generate it with `$ sam init --runtime nodejs8.10` or did I miss something?

**Comment by nsingh308** [comment]
worked for me too. Thank you

**Comment by aditodkar** [comment]
@ehorodyski I tried what you suggested but it is not working for me. Both template.yaml and hello.json both are in root project folder. I am using this command `sam local invoke HelloLambda3D9C82D6 -e hello.json` but it says file specified not found hello.json
