### ISSUE TITLE
Lambda invokes fail when Logical Ids are invalid (non-alphanumeric)

### ISSUE THREAD

**Issue by nav-agarwal** [awslabs/aws-sam-cli#686]
**Description:**
I have sam_template file with function name as Cloud_Views. This throws 
"error while running samlocal 
local start_lambda command is called"
Error:  

**Steps to reproduce the issue:**
1. Create Sam_template file with one of the funciton name having underscore in it.
2. Run sam local. sam local start-lambda

**Observed result:**
"
2018-10-01 11:43:23 local start_lambda command is called
Error:
"
**Expected result:**
No error should be seen

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Linux samlocal 4.4.0-127-generic #153-Ubuntu 
**Output of `sam --version`**:
SAM CLI, version 0.6.0

**Comment by jfuss** [comment]
@nav-agarwal Logical Ids are defined to be [alphanumeric (A-Za-z0-9)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html). You will need to update the logical Ids in your template to be valid. We should have further validation locally to force this and ensure errors like this do not occur. 

Updating the title and marking as a bug.

**Comment by jfuss** [comment]
@keetonian Do you think this is something SAM Translator should do? That is validate the LogicalIds of SAM resources (maybe all resources)? CFN-Lint might do this as well, so maybe it worth just using that for the validation instead.

Would love to hear your thoughts.

**Comment by andremrezende** [comment]
Hi guys.
Possible it was forgotten. 
Let me know any progress, thanks.

**Comment by keyboardDrummer** [comment]
@jfuss Could you explain why the SAM CLI only allows AlphaNumeric characters in Lambda function identifiers?

**Comment by jfuss** [comment]
@keyboardDrummer Please see my above comment: https://github.com/awslabs/aws-sam-cli/issues/686#issuecomment-426013425

**Comment by jfuss** [comment]
The empty error reported was due to some Pythong2.7 support issues we had but currently do not support Python2.7 anymore. 

Closing as we report this correctly to the console now.
