### ISSUE TITLE
Install docker along with the npm install script

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#69]
Can we install Docker when we do `npm install -g aws-sam-local`? This will lead to an excellent user experience because customers don't have to install Docker as a prerequesite. 

If not, we can at least point them to Docker download page and keep the installation paused, until they install Docker and press skip or continue.

**Comment by gardner** [comment]
It may be difficult to detect non-standard docker installations on various platforms. If one has installed docker manually on a different port/socket or is using `docker-machine` to run on a remote dockerd, but hasn't pulled in the environment variables into their current session, then this feature could result in an unwanted installation of dockerd.

I do like the idea of trying to detect docker and throwing a warning / error.

**Comment by marczis** [comment]
To be honest I would not be that happy with it :)
I assume ppl know how to install docker if they do serverless...

**Comment by sanathkr** [comment]
We decided against this because it not possible to reliably to do it.
