### ISSUE TITLE
API Gateway's remapped headers

### ISSUE THREAD

**Issue by Tanbouz** [awslabs/aws-sam-cli#696]
**Description:**
Under API Gateway's known issues
> [headers may be remapped to x-amzn-Remapped-HEADER when sent to your integration endpoint or sent back by your integration endpoint](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html)

**Observed result:**
sam local start-api doesn't replicate API Gateway's (buggy?) behavior

For my case:
`content-type` and `content-length` were not remapped while `authorization` was remapped to `x-amzn-remapped-authorization` and has caused the deployed frontend application to fail.

**Expected result:**
sam local behaving as the real API Gateway*

**Output of `sam --version`**:
SAM CLI, version 0.6.0

*Note
It seems that it is not publicly known when API Gateway remaps. Complains about the API Gateway service remapping headers [here](https://forums.aws.amazon.com/thread.jspa?threadID=231554) with no clarification under what conditions are the headers remapped.

> following headers **may** be remapped

**Comment by jfuss** [comment]
@Tanbouz Thanks for the issue. SAM CLI cannot confidently remap headers if we do not know under what conditions they are remapped.

I don't quite understand your use-case and how it relates to SAM CLI. You mention that remapping has caused the deployed frontend application to fail but that sounds like it is on the service not SAM CLI. Is the point that, you could have caught this if SAM CLI did the remapping? Just trying to understand the use-case/pain point.

**Comment by Tanbouz** [comment]
Yes, simply an inconvenience that will be only caught later on a deployed API gateway (hopefully staging) or if you happen to know of it beforehand.

The front-end was designed to accept `Authorization` header from `sam local` during development, but it got the remapped header instead when deployed to AWS and failed. I simply had to rename it to something else and it is working fine now.

I was hoping someone here knows the "secret sauce" :smile: behind API gateway remap logic for the sake of improving `sam local`. Otherwise, feel free to close the issue.

**Comment by jfuss** [comment]
SAM CLI is not a replacement to testing your application on AWS. This is due to nuances that SAM CLI can't alway emulate locally. Without clear documentation on how/what is remapped, SAM CLI cannot implement this.

**Comment by ayushnigamsworld** [comment]
Hi, Sorry but I am currently facing the same issue. Has anyone any fix for this yet ?
Authorization Header is being changed to x-amzn-remapped-authorization.
