### ISSUE TITLE
How to make pull request for templates?

### ISSUE THREAD

**Issue by azarboon** [awslabs/aws-sam-cli#698]
Hi,

There is a bug in test cases of default template for Nodejs8.10. I'm wondering how can I make a pull request and suggest an edit? Can you please tell me where are the templates files on git?

**Comment by heitorlessa** [comment]
Hello @azarboon - Thank you for opening up an issue to notify us!

What issue have you found? There was a PR that recently fixed the test case and should be in the next release -- https://github.com/awslabs/aws-sam-cli/pull/662

FWIW, you can find the latest test case for NodeJS here with the test case fixed: https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/tests/unit/test_handler.js

And this is the test case available in the current SAM CLI (0.6) release:

https://github.com/awslabs/aws-sam-cli/blob/master/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/tests/unit/test_handler.js

We're considering moving all default sam init templates to a dedicated repository to make this process easier and with better automated tests.

**Comment by jfuss** [comment]
@azarboon Is the test failure you are experiencing different than what @heitorlessa pointed out?

**Comment by azarboon** [comment]
Currently, init creates a test function against app.lambda_handler function which doesn't exist. It should be app.lambdaHandler. As I can see, the new test case (proposed one?) will fix the problem.

**Comment by jfuss** [comment]
The update from `app.lambda_handler` to `app.lambdaHandler` in the test case has already been merged and waiting for a release. Closing this as it was already been fixed.
