### ISSUE TITLE
Add CLI flag for specifying alternate template

### ISSUE THREAD

**Issue by chantzlarge** [awslabs/aws-sam-cli#701]
**Description:**

I would like to be able to use an options flag in combination with the sam cli commands to specify a template file.

**Steps to reproduce the issue:**

N/a

**Observed result:**

No current options flag available in the CLI so far as I can tell for specifying a template file with a name other than template.yml

**Expected result:**

A CLI option such as, -t <path/to/template>, that can be used with other cli commands. E.g.

sam local start-api -t <path/to/template>

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac

**Output of `sam --version`**:

SAM CLI, version 0.6.0

**Optional Debug logs**:

N/a

**Comment by jfuss** [comment]
This is already available. Commands that take a template have a `-t/--template` option. You can see available options by using the `--help` flag on the commands.

Closing as already supported.

**Comment by chantzlarge** [comment]
👍
