### ISSUE TITLE
sam validate - Missing error message

### ISSUE THREAD

**Issue by RyanKadri** [awslabs/aws-sam-cli#707]
It looks like the current `sam validate` command is not giving back useful error messages for (at least some types of) invalid templates. I am getting error messages that look like:

`Template provided at '/personal/dev/www/flash-card-sw/frontend/template.yaml' was invalid SAM Template.
Error:`

with nothing after the Error:

**Steps to reproduce the issue:**
1. Copy the valid example template from here: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_backend/template.yaml
2. Run sam validate - It should be successful
3. Remove one of the Runtime lines from a Function resource
4. Run sam validate - The validation will fail and you will get a blank error message

**Observed result:**

The blank error shown above.

**Expected result:**

An error explaining that a required field is missing (or generally why the validation failed)

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Ubuntu 18.04

**Output of `sam --version`**:

SAM CLI, version 0.6.0

**Comment by jfuss** [comment]
@RyanKadri By chance have you installed SAM CLI in Py2?

**Comment by RyanKadri** [comment]
Yes. Looks like. Should I have used Python3?

**Comment by jfuss** [comment]
We have an issue with Py2 when printing errors. Py3 does not have this issue.

We do have a PR for this already: #687 

My general suggestion is just to move to Py3 completely but this should be fixed in our next release.

**Comment by RyanKadri** [comment]
Gotcha. Alright. I'll switch over to Python 3. Thanks for your help!

**Comment by jfuss** [comment]
Closing this as we won't be addressing this. Please see [comment for reasoning](https://github.com/awslabs/aws-sam-cli/pull/687#issuecomment-465282787).

If you run into this, please install SAM CLI into a supporting Python3 version or use our [installers](https://aws.amazon.com/serverless/sam/)
