### ISSUE TITLE
sam init --runtime nodejs8.10 needs to create src/index.js

### ISSUE THREAD

**Issue by holtc** [awslabs/aws-sam-cli#723]
**Description:**

`sam init --runtime nodejs8.10` needs to create `src/index.js` in order for the `sam local start-api` command to work out of the box.

**Steps to reproduce the issue:**
1. run `sam init --runtime nodejs8.10`
2. run `sam local start-api`
3. go to `127.0.0.1:3000/hello`

**Observed result:**
You will get the following error:
 ```
Unable to import module 'app': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Expected result:**
Should work fine

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac High Sierra 10.13.6
**Output of `sam --version`**:
SAM CLI, version 0.6.0

**Comment by jfuss** [comment]
@holtc Please follow the README that is generated with `sam init`. You are missing dependencies that you should be installing before you can run `sam local start-api`.

From the README:
```
cd hello_world
npm install
cd ../
```

Closing as not an issue

**Comment by holtc** [comment]
Very weird, I had done that and I still got the error.  I nuked the directory and followed those steps again and it worked.  Thanks!
