### ISSUE TITLE
Debugging go functions doesn't work with the latest GO and Delve

### ISSUE THREAD

**Issue by gaochenyue** [awslabs/aws-sam-cli#724]
**Description:**

**Steps to reproduce the issue:**
1. Install the latest GO (1.11.x) and Devle (v1.1.0)
2. Configure Golang debugging environment by following https://github.com/awslabs/aws-sam-cli/blob/develop/docs/usage.rst#debugging-golang-functions

**Observed result:**
Failed to debug with VS Code
**Expected result:**
Successful debug with VS Code

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac

**Output of `sam --version`**:
SAM CLI, version 0.6.0

**Optional Debug logs**:

`Add --debug flag to command you are running`

Workaround
GO 1.10.x and Delve v1.0.0

**Comment by jfuss** [comment]
@gaochenyue Can you be more specific on the issue? What is the error you are seeing? Can you provide sets to reproduce (commands are very helpful here)? What version of VS Code?

**Comment by jfuss** [comment]
Closing as there has been no response. If you are seeing an issue debugging Go, please create a new issue.
