### ISSUE TITLE
`sam samples` command to download samples

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#73]
After installing SAM CLI, it would be good if there were samples for you to immediately play with.

**Comment by neildf** [comment]
Are the lambda blueprints available through the console consumable by the public through an API? That could be a good starting point for samples.

**Comment by sanathkr** [comment]
Lambda Blueprints are already on Github in the AWS SAM repo - https://github.com/awslabs/serverless-application-model/tree/develop/examples. 

New release adds `sam init` command which serves the same purpose - https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0
