### ISSUE TITLE
[Feature Request] Multi-Value Headers and Query String Parameters

### ISSUE THREAD

**Issue by charsleysa** [awslabs/aws-sam-cli#735]
**Description:**
API Gateway has recently (Oct 4th post in AWS What's New) released support for multi-value headers and query string parameters. It would be awesome if SAM CLI could support this too.

Here's the relevant doc https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#apigateway-multivalue-headers-and-parameters

**Comment by jfuss** [comment]
@charsleysa Thanks for the request. @medinarrior has already got a PR out for it :)

Updating labels.

**Comment by lkonya** [comment]
@jfuss Hi! Any update on this one?

**Comment by jasonrberk** [comment]
Status?  I need query params in my Sam template

**Comment by jfuss** [comment]
Status: Waiting for release

You can install from head (brew install aws-sam-cli --head), build from source, or wait for the next release.

**Comment by jfuss** [comment]
This was released in [v0.18.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.18.0)

Closing
