### ISSUE TITLE
SNS local testing

### ISSUE THREAD

**Issue by j** [awslabs/aws-sam-cli#751]
Is there a way to publish & consume SNS locally?

**Comment by ste00martin** [comment]
yes. but it doesn't work on the latest version (I'm dealing with issues right now with 0.6.2). for 0.3.0 the commands look like this: ```sam local generate-event sns notification --message \"$(cat event.json)\" | sam local invoke MyAwesomeLambda ```

contents of event.json:
```
{
  "foo": "bar"
}
```

**Comment by jfuss** [comment]
@j You can mock out the event with `sam local generate-event` as @ste00martin stated. The bug he is referencing is #755, so you can track the update there (I have a fix out in PR). 

Closing
