### ISSUE TITLE
Updating SAM CLI on AWS Cloud9 - Issue with Loading Remote Functions after upgrade

### ISSUE THREAD

**Issue by judahb** [awslabs/aws-sam-cli#760]
**Description:**

**Steps to reproduce the issue:**
1. Follow Updating SAM CLI on AWS Cloud9 steps
2. Try to load remote functions
3. Fails with "Failed to Load Remote Functions" error on the right side of cloud9

**Observed result:**
"Failed to Load Remote Functions" error on the right side of cloud9
**Expected result:**
Should load remote functions
**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Cloud9
**Output of `sam --version`**:

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
SAM CLI doesn't do anything with "loading remote functions". This seems like a Cloud9 Issue. 

Closing as this is not related to this project.
