### ISSUE TITLE
Issue Importing Swagger Definition and SAM  Cfn template in Cloud9 when importing function

### ISSUE THREAD

**Issue by judahb** [awslabs/aws-sam-cli#761]
**Description:**

**Steps to reproduce the issue:**
1. Import Function from remote in Cloud9
2. Function creates a new yaml template file
3. This template doesnt include the original sam template

**Observed result:**
new template without api gateway implementation which means i need to manually edit file
**Expected result:**
Should be able to test in cloud9 with api gateway and swagger definition without making any changes to sam file.
**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Cloud9
**Output of `sam --version`**:

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
This is out of scope for SAM CLI and sounds like a feature request to Cloud9 instead. SAM CLI does not do any importing of Functions currently and therefore doesn't update the template. Cloud9 maybe able to do this but looks like they don't at the moment. I would reach out to Cloud9 with this as a feature request. 

Closing as it doesn't not relate to SAM CLI.
