### ISSUE TITLE
Better error messages on bad handlers.

### ISSUE THREAD

**Issue by j** [awslabs/aws-sam-cli#765]
If I run my handlers locally and not through docker, I get the error: "Error: Cannot find module 'react-dom'".  But through the CLI, I get "Unable to import module 'dist/handlers': Error".

It'd save a lot of headaches to have the real error messages.

**Comment by jfuss** [comment]
@j Thanks for the report. Sadly this is out of our control. The errors that the CLI outputs are coming from the docker container we use ([docker-lambda](https://github.com/lambci/docker-lambda)) which aims to replicate what the Lambda Service does. The output you are seeing is what will happen in Lambda. You could cut them and issue to see if they are willing to change this locally or even provide a patch but it is out of scope for what SAM CLI can do.

Closing.
