### ISSUE TITLE
property Auth not defined for resource of type AWS::Serverless::Api

### ISSUE THREAD

**Issue by holtc** [awslabs/aws-sam-cli#768]
When running the command `sam local start-api -t template.yaml`, I get the following error:

`Error: [InvalidResourceException('MyApi', 'property Auth not defined for resource of type AWS::Serverless::Api')] ('MyApi', 'property Auth not defined for resource of type AWS::Serverless::Api')`

Is there any way to get this to work locally? I am trying to test Cognito auth locally.  An example of the template file can be found [here](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_cognito_auth/template.yaml).  Thanks!

**Comment by jfuss** [comment]
You are running an old version of the CLI. The update to aws-sam-translator to 1.8 (which supports Auth) happened in SAM CLI [v0.6.2](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.6.2).

You should upgrade your CLI. 

Closing

**Comment by holtc** [comment]
Do I need to use brew to upgrade now?  pip seems to still be installing v0.6.0
