### ISSUE TITLE
Symantec detect sam.exe as SONAR.PSDownloader!g1

### ISSUE THREAD

**Issue by nealyip** [awslabs/aws-sam-cli#769]
**Description:**

Symantec detect sam.exe as SONAR.PSDownloader!g1

**Steps to reproduce the issue:**
1. powershell
2. pip install --user --upgrade aws-sam-cli
3. sam init

**Observed result:**
![sam](https://user-images.githubusercontent.com/6487585/48535630-f24c2a00-e8e6-11e8-8ec7-609a52c72145.png)

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Windows 7 pro
Python 3.7
Symantec Endpoint Protection Version 14(14.2) build 1015 (14.2.1015.0100)

**Comment by TheSriram** [comment]
Hey,

you can download and install SAM for windows via the MSI linked of our release page. It's a signed MSI, so it should alleviate false positives to be picked up by symantec.

Here's the 64 bit MSI from our latest release: [64-bit](https://github.com/awslabs/aws-sam-cli/releases/download/v0.8.1/AWS_SAM_CLI_32_PY3.msi)

**Comment by TheSriram** [comment]
@nealyip Let us know if this resolves it for you, and we can close this issue.

**Comment by TheSriram** [comment]
Do re-open if this didnt solve the issue for you.
