### ISSUE TITLE
Path parameters are automatically decoded (different from AWS behavior)

### ISSUE THREAD

**Issue by gyfis** [awslabs/aws-sam-cli#771]
**Description:**
Path parameters (and possibly query parameters) are automatically URL decoded. This does not happen on AWS.

**Steps to reproduce the issue:**
1. Download `hello_world/app.js` and `template.yaml` from [this gist](https://gist.github.com/gyfis/eb4f8bde54d9ad43ec865be1359bfb87)
2. 
- Start local API (`sam local start-api --template template.yaml`)
- access `127.0.0.1:3000/test/users/3/file/Desktop%2Fphotos%2Fcat.png`
- note the response ([local_response.json in the gist](https://gist.github.com/gyfis/eb4f8bde54d9ad43ec865be1359bfb87#file-local_response-json))
3.
- Deploy to your AWS account (`sam package ...`, `sam deploy ...`)
- access `<AWS-API-Gateway-URL>/test/users/3/file/Desktop%2Fphotos%2Fcat.png`
- note the response ([aws_response.json in the gist](https://gist.github.com/gyfis/eb4f8bde54d9ad43ec865be1359bfb87#file-aws_response-json))

**Observed result:**
Parts of the output (and hence the `event` passed to the `lambdaHandler` itself), namely `path` and `pathParameters`, are different. (local SAM automatically decodes `path` and `pathParameters`)
```
// Local event 
{
...
 "path": "/test/users/3/file/Desktop/photos/cat.png",
...
  "pathParameters": {
      "path": "test/users/3/file/Desktop/photos/cat.png"
  },
...
}

// AWS event
{ 
...
 "path": "/test/users/3/file/Desktop%2Fphotos%2Fcat.png",
...
 "pathParameters": {
    "path": "test/users/3/file/Desktop%2Fphotos%2Fcat.png"
  }
...
}
```

**Expected result:**
The `path` and `pathParameters` parts of the `event` should be the same when using aws-sam-cli locally and for AWS environment.

**Additional details**
I did some light digging, and I got to `Flask.requests` using `werkzeug.Map` for representing the path parameters, and I think that's probably somehow related to the root cause. I also found a [similar issue in the Flask repo](https://github.com/pallets/flask/issues/1336) about query parameters, that was closed without a solution. Because of that, I believe a solution to this could be pretty problematic; I still wanted to submit the issue to be sure I didn't miss anything, e.g. in the configs.

**Output of `sam --version`**:
SAM CLI, version 0.6.1

**Comment by c2tarun** [comment]
@gyfis, Thanks for reporting this issue and sorry for delayed response. For start-api on local we use python-flask. When request reaches lambda through Flask, it gets decoded. Given the design decisions we have made so far there is no easy way to fix this for us. As a workaround you can use `sam local invoke -e event-json-file.json` and that works as expected. I am closing this issue for now, please re-open of you have more questions or concerns.

**Comment by gyfis** [comment]
@c2tarun Thanks for the response!

**Comment by it9gamelog** [comment]
I just hit this bug and it still here.

I'm surprised a major behavior mismatching bug like this got closed without consider being fixed nor documented.
