### ISSUE TITLE
Debug python Intellij

### ISSUE THREAD

**Issue by asyba** [awslabs/aws-sam-cli#777]
Hi, anyone can show or explain me how I can debug python in Intellij? It must be in Intellij and not VSC.
(I already know how to debug with java so I am familiar with the process).

**Comment by kiiadi** [comment]
@asyba we just launched the AWS Toolkit for JetBrains - check it out here https://plugins.jetbrains.com/plugin/11349-aws-toolkit

**Comment by jfuss** [comment]
Closing as @kiiadi response answers the initial question

**Comment by visini** [comment]
As I've had some Python-version related compatibility issues when installing AWS Toolkit for JetBrains (PyCharm in my case), I've written up a blog post with full instructions: https://camillovisini.com/deploy-serverless-python-functions-aws-lambda-pycharm/ Hope this helps someone in the same situation as me!
