### ISSUE TITLE
"sam build" feedback: Auto-detect appropriate binary to build the function

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#783]
Currently, `sam build` defaults to looking for a non-versioned binary of the programming language in your platform. Python for example, uses `python` binary instead of `python2.7` or `python3.6` based on the AWS Lambda runtime.

This might work fine for Python runtime, but we have to explore the feasibility for other programming languages. 

**Verbatim feedback**:
> No matter how it's implemented, my expectation when running `sam build` is that it just works, as long as I have the necessary Python interpreter installed and available in my path. And `python2.7` as well as `python3.6` are available in my path.

**Comment by jfuss** [comment]
`sam build` now looks for the specific python version. Closing
