### ISSUE TITLE
event.requestContext in lambda function running locally missing `requestTime` and `requestTimeEpoch`

### ISSUE THREAD

**Issue by ericallam** [awslabs/aws-sam-cli#793]
**Description:**

When running a lambda behind API Gateway using `sam local start-api`, the event's `requestContext` is missing the `requestTime` and `requestTimeEpoch` attributes. However, generating API Gateway events using `sam local generate-event apigateway aws-proxy` _does_ include those attributes.

**Steps to reproduce the issue:**
1. Start a lambda function locally using `sam local start-api`
2. Make a request to the lambda function through HTTP

**Observed result:**

`event.requestContext.requestTime` and  `event.requestContext.requestTimeEpoch` are null

**Expected result:**

`event.requestContext.requestTime` should be a a date-time string like `"09/Apr/2015:12:34:56 +0000"`

`event.requestContext.requestTimeEpoch` should be the number of milliseconds since the UNIX epoch like `1428582896000`

It would also be great if these values reflected the current time, instead of a hardcoded past value. 

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

macOS version 10.13.6, Docker CE Version 18.06.1-ce-mac73 (26764)

**Output of `sam --version`**:

SAM CLI, version 0.7.0

**Comment by mndeveci** [comment]
This issue should be fixed with following PR; https://github.com/awslabs/aws-sam-cli/pull/2060

**Comment by mndeveci** [comment]
Patched with [v1.1.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v1.1.0)
