### ISSUE TITLE
API gate way still can't load assembly

### ISSUE THREAD

**Issue by feng3245** [awslabs/aws-sam-cli#801]
Issue shown in command line

Command line showing
Unhandled Exception: AWSLambda.Internal.Bootstrap.LambdaValidationException: Unable to load assembly 'MCO.CancellationResolutionLambda.WebAPI'.
   at AWSLambda.Internal.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /opt/workspace/LambdaSandboxCoreCLR-2-1/src/Bootstrap/UserCodeLoader.cs:line 115

File is there
Name spaces are correct

Template file:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 180

Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ../MCO.CancellationResolutionLambda.WebAPI/bin/Release/netcoreapp2.1/publish
            Handler: MCO.CancellationResolutionLambda.WebAPI::Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction::FunctionHandlerAsync
            Runtime: dotnetcore2.1
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ENVIRONMENT: dev
                    SCENARIO: SA_RESOLVER_18_RETRY
                    SNS_ERROR: mco_dev_errors
                    TestFile: DefaultSamEnvSettings.xml
                    LogicTest: true
            MemorySize: 256
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /mco-dev-soldnotcancelled-resolve-SA_RESOLVER_18_RETRY
                        Method: post

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn

Command used
sam local start-api

Does not work still. Needs fix

**Comment by ndobryanskyy** [comment]
@feng3245 Do you have some sample code to try on? It would be nice, if you upload some sample on GitHub, so I could reproduce the issue, thanks

**Comment by ShahSwapnil** [comment]
@feng3245 what was the issue with docker version?

**Comment by feng3245** [comment]
@shahSwapnil the later version of docker doesn't prompt you when docker need access to your harddrive.

**Comment by ndobryanskyy** [comment]
@ShahSwapnil , yes, @feng3245 is right, and it likely caused by permissions problem, if you try to mount any folder from your system to the Docker (e.g. `docker run --rm -it --mount src=~,dst=/sample,type=bind ubuntu` - run from powershell) and then try to access its contents (`/sample` from inside the container) you will see nothing. 

This happens when you've changed your sign in info for Windows also, because Docker knows nothing about your updated creds and fails to gain required permissions.

If the latter is the case, then use _highlighted_ button to reset credentials for Docker.
![image](https://user-images.githubusercontent.com/34073648/50402115-b38a7900-079c-11e9-8c03-08dcf491feb1.png)

And if in this menu you have no shared drives ticked, then go ahead and share the one, you use `sam` on.

@ShahSwapnil BTW your sample code works just fine on my machine, thanks for providing the source to diagnose your problem on - very helpful. If you have any more questions fell free to reach out to me ;)

**Comment by ShahSwapnil** [comment]
@ndobryanskyy, thanks for looking into this. Apparently it's not a security related issue. I followed the steps you mentioned in your last reply. I was able to see the files from inside the container. I also reset the credentials. Afterwards, when I attempted run a docker command it asked me for permissions. this was odd since you guys mentioned it wouldn't ask. 

Before I get to debugging with vs code. 

I started the api in powershell with

- sam local start-api --region us-east-2

Using insomnia i sent a GET request to "http://127.0.0.1:3000/api/values"

that's when I see the error in the screenshot
![image](https://user-images.githubusercontent.com/44791167/50413654-9c6c7b00-07de-11e9-8769-609db66012fa.png)

I also had to update the template.yaml file, the path property under Events. I updated it to 
Path: /{proxy+}. Otherwise I get "Missing Authentication Token" error in insomnia.

**Comment by ShahSwapnil** [comment]
So out of curiosity I created a helloworld project using sam init. I was able to debug that!

**Comment by ndobryanskyy** [comment]
Yeah, @ShahSwapnil now I experience, the same problem, I didn't try to invoke the function, my bad, really 😅
I'll try to debug SAM to know, what is going on, and reach out to you as I have some results or culprits.

**Comment by ShahSwapnil** [comment]
@ndobryanskyy, Ha no worries.  I really appreciate you looking into this.

**Comment by ndobryanskyy** [comment]
@ShahSwapnil from my initial investigation it seems, that something is wrong with dependencies, your Lambda assembly loads _just fine_, and then runner **crashes** on loading the type, you've specified, see the screenshot from attached debugger below.

![image](https://user-images.githubusercontent.com/34073648/50424656-742d5c80-0870-11e9-98db-07d108fbd981.png)

I'm still trying to tweak around and get this working. For this type of projects I've always used `LocalEntryPoint` to test and play around locally TBH. But that is certainly a case that SAM CLI should support also.

@jfuss, @mhart have you guys, ever seen this kind of problem?

**Comment by ShahSwapnil** [comment]
@ndobryanskyy thanks for looking into it. I am trying to determine where that dependencies might be coming from. 

I had used dotnet lambda to create a sample web api project. I haven't done anything else to it.

**Comment by ShahSwapnil** [comment]
@ndobryanskyy any luck?

**Comment by ndobryanskyy** [comment]
@ShahSwapnil, currently I am on my New Year preparation hell-train, so literally, have no spare time, sorry, as Im done with it, I'll get back to the issue immediately 😉

**Comment by ShahSwapnil** [comment]
@ndobryanskyy Ha! No worries. Hope you had a good new years!

**Comment by lngr** [comment]
@ndobryanskyy I'm getting the same error, but based on your screenshot I might have an idea what's causing this.

I have a function that has a simple `APIGatewayProxyRequest` and no inheritance, which works.

```
public class LambdaEntryPoint
{
    ...  
}
```

This handler can also manually load the assembly files, so I'm ruling out docker permission issues.

However, if I add inheritance like this (and overriding `Init()`):
```
public class LambdaEntryPoint : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
{
 ... 
}
```

I'm receiving the error as above:
```
AWSLambda.Internal.Bootstrap.LambdaValidationException: Unable to load type 'Test.Aws.Api.LambdaEntryPoint' from assembly 'Test.Aws'.
```

So I assume it's a dependency of the `APIGatewayProxyFunction`.  One candidate might be any of the `Microsoft.AspNetCore.*` assemblies (which matches your screenshot).

**Those are in the `refs/` subdirectory of of the zip created by `dotnet lambda package`:**

```
$ unzip -l bin/release/netcoreapp2.1/deploy-package.zip  | grep Microsoft.AspNetCore.dll
    22008  05-16-2018 20:18   refs/Microsoft.AspNetCore.dll
```

I see in your screenshot that the `OnAssemblyResolving` function tries to open the dll at the following location:

`Path.Combine({lambdaTaskRoot, $"{assembly.Name}.dll")`, which is of course the wrong location, causing the error.

I've now manually created a .zip file where all the files in `refs/` have been copied to the .zip root, and now it works locally.

**Comment by ndobryanskyy** [comment]
@lngr, that makes sense, thanks for the investigation, I'll check it tonight and share the results

**Comment by ndobryanskyy** [comment]
@lngr, in our case, that is not related to the nested folder structure - all files are directly in the root of the package. I wonder if you could share the `.csproj` of the project, that you successfully ran, so I can examine the packages of it. Maybe that is related to the wrong version of some package in the @ShahSwapnil 's sample project.

**Comment by hudo** [comment]
I have the same problem.  Steps to reproduce:
Created new web app in VS 2017 (aws Lambda Core Web Api template in file/new project)
Executed "sam lambda package" (from AWS .NET global tools)
Added template.yaml and updated .zip/assembly::lambdaEntryPoint locations
Executed "sam local start-api --region us-east-1" in powershell
Opened browsers, tried to hit that API endpoint, and I always get that "unable to load..." error. Btw, developing on Win10. 

So how to even get simplest aspnet core hello-world with SAM running locally?

**Comment by ShahSwapnil** [comment]
@hudo that worked for me as well. Thank you!

**Comment by adfinlay** [comment]
FWIW, I've been battling with `AWSLambda.Internal.Bootstrap.LambdaValidationException: Unable to load type '...' from assembly '...'.` and it seems to be something to do with the underlying docker image that SAM local uses (lambci/docker-lambda), at least in my case. I've found that if I reference `Microsoft.AspNetCore.App` then I get the error, but if I remove that reference and instead explicit add references to the packages I need from that metapackage then it works fine. 

Packages from `Microsoft.AspNetCore.App` is supposed to be available from the Lambda environment, so referencing this package means that deployment packages don't include unnecessary pacakages, however the linking doesn't seem to work within the docker container.

See https://github.com/lambci/docker-lambda/issues/177.
