### ISSUE TITLE
Support building Ruby runtimes through sam build

### ISSUE THREAD

**Issue by metaskills** [awslabs/aws-sam-cli#806]
![image_from_ios](https://user-images.githubusercontent.com/2381/49241730-b9c44a00-f3d6-11e8-88e6-e59adc3aa4b5.jpg)

**Comment by jfuss** [comment]
Quick on the draw @metaskills. Your wishes may come true :)

**Comment by sanathkr** [comment]
Rust is already in a Work-in-Progress PR - https://github.com/awslabs/aws-lambda-builders/pull/43.

Ruby will happen soon. It will happen sooner if you can contribute :)

**Comment by jfuss** [comment]
@metaskills We released invoke ruby runtimes in [0.8.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.8.0). 

I am going to leave this open so we can track build support for Ruby (and will update the title to reflect).

**Comment by TheSriram** [comment]
There is a WIP design doc for Ruby in aws-lambda-builders: https://github.com/awslabs/aws-lambda-builders/pull/49

**Comment by jfuss** [comment]
Ruby builds are now supported in [v0.10.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.10.0)
