### ISSUE TITLE
Design pattern for Selecting Entrypoints, Builders

### ISSUE THREAD

**Issue by sriram-mv** [awslabs/aws-sam-cli#853]
### Describe your idea/feature/enhancement

Currently AWS SAM CLI uses some direct if elif else branches for determining entrypoints and selecting appropriate builders.

https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/docker/lambda_container.py
https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/lib/build/app_builder.py#L48

### Proposal

The proposal is to change this to a pattern of encapsulation within dictionaries, and appropriate handlers defined that would compute the necessary state. This makes the code cleaner and less procedural.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
  - No

**Comment by jfuss** [comment]
I am working on the app_builder part of this now. We have two workflows for go (dep and mod) and will need a way to support that, so starting with getting the 'select a builder' case refactored first.

**Comment by TheSriram** [comment]
This is partially addressed for selecting workflows :)

**Comment by sriram-mv** [comment]
This has been addressed.
