### ISSUE TITLE
go1.x unsupported error

### ISSUE THREAD

**Issue by aidanh010** [awslabs/aws-sam-cli#861]
### Description

The latest version of the runtime installed with `pip3` reports that `go1.x` runtime is not supported.

### Steps to reproduce

Attempt to build the default go hello-world project.

### Observed result

https://gist.github.com/aidanh010/a87abd2d63ce8e42c9649cd6ebc35656

### Expected result

Should build correctly as this is default code and the `go1.x` is listed as supported in readme.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Eduation, build `17134.471`
2. `sam --version`: `SAM CLI, version 0.9.0`

**Comment by aidanh010** [comment]
Figured it out thanks to AWS Developers Slack. Go isn't supported for build only, I wish the error message was clearer.

**Comment by nyx** [comment]
This tripped me up for a bit until I found this issue report. Hope it gets resolved satisfactorily soon.

**Comment by tedder** [comment]
> Figured it out thanks to AWS Developers Slack. Go isn't supported for build only, I wish the error message was clearer.

I was having reading comprehension issues, so rewording: `sam build` does not work for golang, but the rest of the `sam` commands do. Use the `Makefile`'s `make build` command, which runs `go build`.

**Comment by jfuss** [comment]
Releated: dep support: (#888)
