### ISSUE TITLE
Speed up local layer builds when invoking local lambdas

### ISSUE THREAD

**Issue by StefanSmith** [awslabs/aws-sam-cli#863]
### Describe your idea/feature/enhancement

When invoking a local Lambda function that references one or more local layers, SAM CLI builds a custom docker image that overlays the file trees for each layer. This build process runs on every function invocation (in case files have changed) and involves passing docker a tarball containing the Dockerfile and docker context. The docker context contains the file tree for each local layer. This mechanism appears to be required because each layer's file tree can reside in a completely different location on disk but a docker context requires gathering these file trees under a single root.

Currently, the tarball is built with compression turned on and this incurs a significant time delay. As an example, I have a local layer (containing Python dependencies) weighing in at 215 MB (51 MB compressed). Creating the tarball, streaming it to docker and building the docker image currently takes about 27 seconds. Without compression, the same procedure takes less than 4 seconds. I'm doing this on an i7-8650U CPU @ 1.90GHz with 16GB RAM & SSD.

It would be nice to avoid creating the tarball at all if no layer files have changed (of course, Docker's cache will skip `ADD` steps once the build runs but the tarball will always be created first). The only alternative I can think of is for SAM CLI to create a Dockerfile in the parent directory of each layer and sequentially build images, layer upon layer, instead of having a single Dockerfile that adds each layer's file tree. 

### Proposal

Create docker context tarball without compression.

Pull request here: https://github.com/awslabs/aws-sam-cli/pull/862

**Comment by jfuss** [comment]
The initially proposal here was accepted and released (creating docker context tarball without compression).

Closing
