### ISSUE TITLE
Java support for gradle in SAM build

### ISSUE THREAD

**Issue by abrooksv** [awslabs/aws-sam-cli#880]
### Describe your idea/feature/enhancement
SAM build needs support for Java

### Additional Details
Feature request in toolkit: https://github.com/aws/aws-toolkit-jetbrains/issues/712

**Comment by MichaelDz6** [comment]
Why is java8 checkbox checked on the main page if it isn't supported yet?

**Comment by jfuss** [comment]
Scoping this issue to support for gradle. Will create one for maven explicitly.

**Comment by sanathkr** [comment]
Blocked on https://github.com/awslabs/aws-sam-cli/pull/976/files because it refactors lots of the code paths necessary to support Gradle

**Comment by jfuss** [comment]
This was released with [v0.12.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.12.0)

Closing
