### ISSUE TITLE
Metadata of aws-sam-cli not displayed correctly on PyPI

### ISSUE THREAD

**Issue by paoptu023** [awslabs/aws-sam-cli#889]
### Description

Related to https://github.com/awslabs/aws-serverlessrepo-python/issues/21. A customer had been running aws-sam-cli in Python 3.5 for months because he didn't know it's not a supported version, until a new dependency serverlessrepo not supporting 3.5 was added in the recent release. Now he couldn't install aws-sam-cli using `pip` in Python 3.5 anymore. The PyPI home page of [aws-sam-cli](https://pypi.org/project/aws-sam-cli/) doesn't have any Python version info, compared with [serverlessrepo](https://pypi.org/project/serverlessrepo/). It can be confusing to customers when they find out they are running on a not supported Python version.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

OS: Ubuntu 16.04 (LTS)

**Comment by TheSriram** [comment]
Looks like it may be due to rst vs md rendering support on pypi. I created a PR that I'm hoping would address it. 

https://github.com/awslabs/aws-sam-cli/pull/891

**Comment by jfuss** [comment]
Released in [v0.11.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.11.0)

Closing
