### ISSUE TITLE
Support Templates written through CDK through reading Resource Level Metadata

### ISSUE THREAD

**Issue by jfuss** [awslabs/aws-sam-cli#893]
### Describe your idea/feature/enhancement

Currently, AWS SAM CLI only supports templates that are written in CloudFormation (`.json` or `.yaml` files). This leaves out other frameworks like CDK that produce a template. SAM CLI should support these use-cases. 

### Proposal

A design will need to be written for this support. CDK is adding some support to enable the bridging [1] of the tools. The design should capture how we will support templates written through CDK but should keep in mind how we can expand to other frameworks as well (Serverless Framework for example).

[1] https://github.com/awslabs/aws-cdk/pull/1433/

### Additional Details
Other related issues
* https://github.com/awslabs/aws-cdk/issues/716

**Comment by tj** [comment]
Personally I find it pretty elegant that anything that wants to work with SAM can just generate some .json or .yaml

**Comment by eladb** [comment]
@tj 👋

**Comment by jfuss** [comment]
The design and implementation for supporting Resource Level Metadata is done and merged. Only thing left is to release. Updating labels and the issue title to be more accurate (instead of closing and opening another one to track release).

**Comment by jfuss** [comment]
This will also allow people using Amplify to run and test locally with SAM CLI: https://github.com/aws-amplify/amplify-cli/pull/693

**Comment by jfuss** [comment]
Released in [v0.11.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.11.0)

Closing

**Comment by eladb** [comment]
Yey!
