### ISSUE TITLE
setting CodeUri in Globals seems to cause conflict once packaged

### ISSUE THREAD

**Issue by rhbecker** [awslabs/aws-sam-cli#895]
### Description

(I'm sharing this primarily as an FYI -- I'm not too worried about whether it's addressed anytime soon.)

Globally defined `CodeUri` works fine locally, but seemingly conflicts with behavior of `sam package` such that deployed version will not work.

### Steps to reproduce

1. Define `CodeUri` in `Globals` (I used the value `lambda/src`).
2. Do not define `CodeUri` for each function, but do define `Handler` for each function.
3. Note that local invocations run fine.
4. Package, deploy, and test via the API Gateway console. Note errors indicating that handler cannot be found.
5. Replace globally defined `CodeUri` with per function config.
6. Package, deploy, and test via the API Gateway console. Note test success.

### Observed result

See repro step 4 for unexpected observed result and step 6 for post-tweak observed result.

### Expected result

I'm not sure, but maybe it would make sense for the packaging logic to remove the globally defined `CodeUri` value, given that it adds a replacement value once per function? Or if the situation is more complicated than that, at least warn in the docs against defining that as a global, and perhaps have it fail a template validation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 0.10.0

**Comment by jfuss** [comment]
@rhbecker Yes. The ones you linked are for the same thing. Going to close this one in favor of the others.
