### ISSUE TITLE
Sam Package support for AWS::AppSync::FunctionConfiguration

### ISSUE THREAD

**Issue by mkrn** [awslabs/aws-sam-cli#897]
### Describe your idea/feature/enhancement

sam package command should support uploading local files to S3 bucket and replacing with s3 path for following properties of "AWS::AppSync::FunctionConfiguration":

RequestMappingTemplateS3Location
ResponseMappingTemplateS3Location

### Proposal

Add support, especially since  RequestMappingTemplateS3Location, ResponseMappingTemplateS3Location of "AWS::AppSync::Resolver"  are already supported.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
No

**Comment by jfuss** [comment]
Released in v0.18.0. Closing
