### ISSUE TITLE
Node example of specifying the cognito endpoint url?

### ISSUE THREAD

**Issue by ToddHoff** [awslabs/aws-sam-cli#903]
There's a python example, but the there's not a node example. Does anyone have a working example? We really need code examples for supported languages. Thanks.

   self.lambda_client = boto3.client('lambda',
                                  endpoint_url="http://127.0.0.1:3001",
                                  use_ssl=False,
                                  verify=False,
                                  config=Config(signature_version=UNSIGNED,
                                                read_timeout=0,
                                                retries={'max_attempts': 0}))
    self.lambda_client.invoke(FunctionName="HelloWorldFunction")

**Comment by jfuss** [comment]
You should follow the sdk's documentation for this.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/specifying-endpoints.html

**Comment by ToddHoff** [comment]
The difference a saw was how I the endpoint was passed in. So I did:

this.LAMBDA = new AWS.Lambda({ endpoint: 'https://127.0.0.1:3001' });

The result was  the same. There must be some other secret sauce.
