### ISSUE TITLE
Stuck on version 0.7

### ISSUE THREAD

**Issue by asyba** [awslabs/aws-sam-cli#904]
### Description
Hi, I can't update the sam version to v 0.10

### Steps to reproduce

sudo pip install aws-sam-cli
sam --version
SAM CLI, version 0.7.0

1. OS: Ubuntu
2. `sam --version`: 0.7

**Comment by jfuss** [comment]
You might have installed it initially with the ‘—user’ flag (our docs state to use that flag so it’s likely what you did).

**Comment by asyba** [comment]
Don't remember.. so what will be the solution?

**Comment by jfuss** [comment]
It would be to add the ‘—user’ flag.

**Comment by asyba** [comment]
With this was the solution:
pip install --user --upgrade aws-sam-cli

**Comment by TheSriram** [comment]
there are easier installation methods than pip. Pip is an advanced installation method.

Refer: https://aws.amazon.com/serverless/sam/
