### ISSUE TITLE
Support to add SSL Certs to Container so network calls work

### ISSUE THREAD

**Issue by DevOpsChris** [awslabs/aws-sam-cli#917]
I wish sam-cli would add the ability to add SSL certificates that are created for use within a proxy network.  This would enable downloading layers, etc. without tweaking the python code base to `verify = False` requests calls.

### Proposal

1.  Add a volume argument to mount the cert directory in the container to the cert.
-or-
2. Allow post copy of files into the container from aws-sam-cli as a flag.

**Comment by DevOpsChris** [comment]
https://github.com/DevOpsChris/aws-sam-cli/tree/fix_proxy_issues  here's a fix in progress.

**Comment by DevOpsChris** [comment]
Not needed.  Observed you can do this within ENV Variables and have the lambda use the variables within the code to connect to boto3 service calls.

**Comment by DevOpsChris** [comment]
Made a mistake.  I've fixed the layer downloader from behind the proxy with ssl cert.  Here's the fix. #1143

**Comment by jfuss** [comment]
Was released with [v0.16.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.16.0)

Closing

**Comment by ryanpodonnell1** [comment]
This doesn't seem to be picking up the `AWS_CA_BUNDLE` environment variable
