### ISSUE TITLE
Logs fail when using logical ID

### ISSUE THREAD

**Issue by tj** [awslabs/aws-sam-cli#940]
### Description

`sam logs` errors with `The specified log group does not exist.` when a logical id is used, looks like it used the name you pass literally.

### Steps to reproduce

- Deploy a function named `Hello` without a `FunctionName`
- Run `sam logs -tn Hello`

### Observed result

```
$ sam logs -tn QueueCrawls --debug
# notable output:
2019-01-16 11:16:57 Fetching logs from CloudWatch with parameters {'logGroupName': '/aws/lambda/QueueCrawls', 'interleaved': True, 'startTime': 1547636817370}
```

### Expected result

Use the ID generated by SAM, in my case `monitor-QueueCrawls-1FTA2THVAER1U`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: 0.6.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@tj I think this is an issue with the command you are running. You are not passing in the `--stack-name` to the command. We use this value to fetch the CloudFormation generated Id. If you do not pass `--stack-name` then we assume that is the name of the function resource in the Cloud.

**Comment by jfuss** [comment]
Closing as there has been no response.
