### ISSUE TITLE
Function returned an invalid response (must include one of: body, headers or statusCode in the response object).

### ISSUE THREAD

**Issue by luillyfe** [awslabs/aws-sam-cli#964]
### Description

I am trying to test my local function with `sam local start-api` but it appears to make an useless validation to the response. **And since the code above works on perfectly when I submitted to aws lambda, I cannot see the real value of that validation and it does not allow me to test the function in local**

### Steps to reproduce

create your function and return an array, let's say

```js
 index.handler = async () => {
    return [
        {"key":"jsandjsnckads","name":"name1"}, 
        {"key":"asjncjaNCJKndsc","name":"name2"}
    ];
};
```

execute `sam local start-api`
go to  `http://127.0.0.1:3000/users` 

### Observed result

brwoser output
`no data`

console output
```js
 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: [
        {"key":"jsandjsnckads","name":"name1"}, 
        {"key":"asjncjaNCJKndsc","name":"name2"}
    ]
```

### Expected result

browser output

```js
[
        {"key":"jsandjsnckads","name":"name1"}, 
        {"key":"asjncjaNCJKndsc","name":"name2"}
    ]
```

no console output

**Comment by jfuss** [comment]
@luillyfe This is not useless validation. According to API Gateway Docs, the Lambda must return a specific json format. More details can be found [here](https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway/) and [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format).

Closing as the validation matches API Gateways expectations.

**Comment by rsibanez89** [comment]
@luillyfe did you solve this problem?
I'm having the same issue. This is my handler:
`
public APIGatewayProxyResponse Handle() => new APIGatewayProxyResponse
{
    Body = "The lambda function is working!",
    StatusCode = 200,
    Headers = new Dictionary<string, string>
    {
        { "Content-Type", "application/json" },
        { "Access-Control-Allow-Origin", "*" }
    }
};
`

This is the error:
`
2019-05-31 16:00:15 Invalid API Gateway Response Keys: {'multiValueHeaders'} in {'statusCode': 200, 'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'}, 'multiValueHeaders': None, 'body': 'The lambda function is working!', 'isBase64Encoded': False}
2019-05-31 16:00:15 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: {"statusCode":200,"headers":{"Content-Type":"application/json","Access-Control-Allow-Origin":"*"},"multiValueHeaders":null,"body":"The lambda function is working!","isBase64Encoded":false}
2019-05-31 16:00:15 127.0.0.1 - - [31/May/2019 16:00:15] "GET / HTTP/1.1" 502 -
2019-05-31 16:00:15 127.0.0.1 - - [31/May/2019 16:00:15] "GET /favicon.ico HTTP/1.1" 403
`

**Comment by rsibanez89** [comment]
I solved it by downgrading the SAM CLI version to 0.15.0

`sam local start-api` doesn't work on SAM CLI v0.16.1. However, if you deploy it to AWS you won't get the error.

**Comment by luillyfe** [comment]
@rsibanez89 sorry for the late answer. I am glad it is working for you now. The thing to keep in mind here is the **Output Format of a Lambda Function for Proxy Integration** requires that validation but when we are in the console we do not normally (by default) mark the Lambda proxy integration checkbox. That is why it behaves differently from `AWS Console` to `local-api server`. I hope this clarify a little bit this topic.

![Screen Shot 2019-06-07 at 3 09 38 PM](https://user-images.githubusercontent.com/1217199/59130966-8db1f480-8936-11e9-8a2a-5b354e181ae0.png)

**Comment by sukumarbarman** [comment]
Hi rsibanez89,
I am also facing same issue for version 0.19.0.  But I tried to download SAM CLI version to 0.15.0. But did not get link. Can you please provide the link.

Regards,
Sukumar

**Comment by sukumarbarman** [comment]
@luillyfe , 
I did not get  your solution. What changes you did in the following handler:
public APIGatewayProxyResponse Handle() => new APIGatewayProxyResponse
{
    Body = "The lambda function is working!",
    StatusCode = 200,
    Headers = new Dictionary<string, string>
    {
        { "Content-Type", "application/json" },
        { "Access-Control-Allow-Origin", "*" }
    }
};

**Comment by rsibanez89** [comment]
@sukumarbarman These are my steps:
https://github.com/rsibanez89/aws-projects/tree/master/SAMApiGatewayLambda

**Comment by sukumarbarman** [comment]
@rsibanez89  Thanks for your reply.  Tried to install SAM CLI version 0.15.0. But I did not get the link to download. Can you please provide the link.

**Comment by rsibanez89** [comment]
@sukumarbarman Check all the releases here: https://github.com/awslabs/aws-sam-cli/releases

**Comment by ianpogi5** [comment]
> @rsibanez89 sorry for the late answer. I am glad it is working for you now. The thing to keep in mind here is the **Output Format of a Lambda Function for Proxy Integration** requires that validation but when we are in the console we do not normally (by default) mark the Lambda proxy integration checkbox. That is why it behaves differently from `AWS Console` to `local-api server`. I hope this clarify a little bit this topic.
> 
> ![Screen Shot 2019-06-07 at 3 09 38 PM](https://user-images.githubusercontent.com/1217199/59130966-8db1f480-8936-11e9-8a2a-5b354e181ae0.png)

How can we disable response validation in ```sam local start-api```?

**Comment by chunkjs** [comment]
In my case I upgraded to the latest version (0.22), that did the trick 🌬 🏆

**Comment by BJCheng** [comment]
> @rsibanez89 sorry for the late answer. I am glad it is working for you now. The thing to keep in mind here is the **Output Format of a Lambda Function for Proxy Integration** requires that validation but when we are in the console we do not normally (by default) mark the Lambda proxy integration checkbox. That is why it behaves differently from `AWS Console` to `local-api server`. I hope this clarify a little bit this topic.
> 
> ![Screen Shot 2019-06-07 at 3 09 38 PM](https://user-images.githubusercontent.com/1217199/59130966-8db1f480-8936-11e9-8a2a-5b354e181ae0.png)

From the AWS 'Running API Gateway Locally' tutorial it says 'By default, AWS SAM uses Proxy Integration'. Since you already assume our confuse of why AWS Console to local-api server behaves differently, so would you mind share how to uncheck the `Running API Gateway Locally`?
