### ISSUE TITLE
SAM Build support for Go with modules

### ISSUE THREAD

**Issue by jfuss** [awslabs/aws-sam-cli#968]
### Describe your idea/feature/enhancement

Support building go functions that use Go Modules.

**Comment by eikeon** [comment]
I'm assuming this is relevant: awslabs/aws-lambda-builders#64

**Comment by aripalo** [comment]
If I've understood correctly, the lambda builders project now has support for Go modules via this PR https://github.com/awslabs/aws-lambda-builders/pull/65 that is already merged.

There seems to be several different PRs around this project about adding Golang support, but they all seem to be closed. Am I missing something or has the golang build support been left out on purpose or is it still under development?

I'm currently in midst of writing a massive Makefile setup for my projects (they have Go 1.13, Node 10 and Python 3.7 Lambdas) that tackle those sort of "polyglot lambda monorepos" with Lambci Lambda dockers, but I'd rather use just `sam build --use-container`, but so far missing Golang support prevents going down that path. 

Wondering if there's any areas where I could help/contribute regarding the Golang (with Go modules support). I don't want to just shoot in the dark and open a random PR if there's already some active development going on somewhere 🙂

**Comment by jfuss** [comment]
Hey @aripalo. I am not aware of anything in progress for Go Module support within SAM CLI and PRs are always welcome. There is a closed PR in the repo (from me) that tried to get this working some time ago but has feel off my plate for other things. That could be a good place to start.

One thing to note is, `--use-container` is a challenge to support. The main reason for that is Go likes to write to the host (and in this case container). We mount code in a readonly mode (for security reasons so things do not get written back to the host). The initially support we were planning was to disallow `--use-container` (like we do for dotnet for similar reasons). We can tar up the function directory and set that to the container but that is substantially more work. With Go being able to cross compile, most cases will never need a container.

Happy to talk this through further, if you are interested in picking this up.

**Comment by yordis** [comment]
@jfuss any updates on adding support for this?

**Comment by awood45** [comment]
#1731 adds this.

**Comment by aripalo** [comment]
Yes yes! This is great! 🎉 I can finally start to teardown my weird hacks and use SAM CLI with Go! 

![awesome](https://media.tenor.com/images/f4c8059e75d21aa301174d4374ec4680/tenor.gif)
