### ISSUE TITLE
error in 64-bit msi

### ISSUE THREAD

**Issue by Bryan-Enspire** [awslabs/aws-sam-cli#985]
### Description

in sam.cmd, call to SetPythonExe is not made.

### Steps to reproduce

download and run AWS_SAM_CLI_64_PY3.msi, revision {CD191EEB-C1EE-40D5-8E34-EA6A49B55697}

### Observed result

the PythonExe variable remains an empty string

### Expected result

the PythonExe variable should be set to "%~dp0/../runtime/python.exe"

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Win64
2. `sam --version`: SAM CLI, version 0.7.0

**Comment by TheSriram** [comment]
Thanks for this bug report! This will be on the radar on the next thing to fix.

**Comment by TheSriram** [comment]
This should be fixed with the latest version of the SAM CLI release.
